#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Br6.in™
#  File: 0001_initial.py
#  Last Modified: 2024-10-05 01:39:48
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 14:42:34
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@br6.in.
#
#
#

# Generated by Django 5.0.8 on 2024-10-02 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm_core', '0002_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Harmoniq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('optional_instructions', models.TextField()),
                ('mode', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio')], default='audio', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('llm_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llm_core.llmcore')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'verbose_name': 'Harmoniq Agent',
                'verbose_name_plural': 'Harmoniq Agents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization'], name='harmoniq_ha_organiz_a91475_idx'), models.Index(fields=['organization', 'llm_model'], name='harmoniq_ha_organiz_58c5bd_idx'), models.Index(fields=['organization', 'llm_model', 'created_by_user'], name='harmoniq_ha_organiz_9773be_idx'), models.Index(fields=['organization', 'llm_model', 'created_by_user', 'mode'], name='harmoniq_ha_organiz_b877a8_idx')],
            },
        ),
    ]
