# Generated by Django 5.0.8 on 2024-10-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmoniq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harmoniq',
            name='harmoniq_deity',
            field=models.CharField(choices=[('arathreus', 'Arathreus'), ('berathron', 'Berathron'), ('celesthar', 'Celesthar'), ('demorthon', 'Demorthon'), ('eratheris', 'Eratheris')], default='arathreus', max_length=100),
        ),
        migrations.AlterField(
            model_name='harmoniq',
            name='optional_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
