# Generated by Django 5.0.8 on 2024-10-07 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harmoniq', '0002_harmoniq_harmoniq_deity_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='harmoniq',
            name='harmoniq_ha_organiz_b877a8_idx',
        ),
        migrations.RemoveField(
            model_name='harmoniq',
            name='mode',
        ),
    ]
