# Generated by Django 5.0.8 on 2024-10-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmoniq', '0003_remove_harmoniq_harmoniq_ha_organiz_b877a8_idx_and_more'),
        ('leanmod', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harmoniq',
            name='expert_networks',
            field=models.ManyToManyField(blank=True, related_name='harmoniqs', to='leanmod.expertnetwork'),
        ),
    ]
