# Generated by Django 5.0.8 on 2024-10-12 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harmoniq', '0004_harmoniq_expert_networks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harmoniq',
            old_name='expert_networks',
            new_name='consultant_expert_networks',
        ),
    ]
