# Generated by Django 5.0.8 on 2024-12-01 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harmoniq', '0005_rename_expert_networks_harmoniq_consultant_expert_networks'),
        ('organization', '0005_alter_organization_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='harmoniq',
            unique_together={('organization', 'name')},
        ),
    ]
