# Generated by Django 5.0.8 on 2024-10-18 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leanmod', '0002_initial'),
        ('llm_core', '0002_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HadronNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=4000)),
                ('node_description', models.TextField()),
                ('optional_instructions', models.TextField(blank=True, null=True)),
                ('current_state_curl', models.CharField(blank=True, null=True)),
                ('current_state_input_params_description', models.TextField(blank=True, null=True)),
                ('current_state_output_params_description', models.TextField(blank=True, null=True)),
                ('goal_state_curl', models.CharField(blank=True, null=True)),
                ('goal_state_input_params_description', models.TextField(blank=True, null=True)),
                ('goal_state_output_params_description', models.TextField(blank=True, null=True)),
                ('measurements_curl', models.CharField(blank=True, null=True)),
                ('measurements_input_params_description', models.TextField(blank=True, null=True)),
                ('measurements_output_params_description', models.TextField(blank=True, null=True)),
                ('action_set_curl', models.TextField(blank=True, null=True)),
                ('action_set_input_params_description', models.TextField(blank=True, null=True)),
                ('action_set_output_params_description', models.TextField(blank=True, null=True)),
                ('analytic_calculation_curl', models.CharField(blank=True, null=True)),
                ('analytic_calculation_input_params_description', models.TextField(blank=True, null=True)),
                ('analytic_calculation_output_params_description', models.TextField(blank=True, null=True)),
                ('actuation_curl', models.CharField(blank=True, null=True)),
                ('actuation_input_params_description', models.TextField(blank=True, null=True)),
                ('actuation_output_params_description', models.TextField(blank=True, null=True)),
                ('state_action_state_lookback_memory_size', models.IntegerField(default=20)),
                ('publishing_history_lookback_memory_size', models.IntegerField(default=20)),
                ('activation_trigger_endpoint', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('expert_networks', models.ManyToManyField(blank=True, to='leanmod.expertnetwork')),
                ('llm_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='llm_core.llmcore')),
            ],
            options={
                'verbose_name': 'Hadron Node',
                'verbose_name_plural': 'Hadron Nodes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HadronStateActionStateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_state', models.TextField()),
                ('action', models.TextField()),
                ('new_state', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hadron_prime.hadronnode')),
            ],
            options={
                'verbose_name': 'Hadron State-Action-State Log',
                'verbose_name_plural': 'Hadron State-Action-State Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='hadronnode',
            name='state_action_state_history_logs',
            field=models.ManyToManyField(blank=True, to='hadron_prime.hadronstateactionstatelog'),
        ),
        migrations.CreateModel(
            name='HadronSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=4000, unique=True)),
                ('system_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'verbose_name': 'Hadron System',
                'verbose_name_plural': 'Hadron Systems',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='hadronnode',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hadron_prime.hadronsystem'),
        ),
        migrations.CreateModel(
            name='HadronTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=4000)),
                ('topic_description', models.TextField()),
                ('topic_purpose', models.TextField()),
                ('topic_category', models.CharField(choices=[('alerts', 'Alerts'), ('measurements', 'Measurements'), ('states', 'States'), ('actions', 'Actions'), ('commands', 'Commands'), ('info', 'Info')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hadron_prime.hadronsystem')),
            ],
            options={
                'verbose_name': 'Hadron Topic',
                'verbose_name_plural': 'Hadron Topics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='hadronnode',
            name='subscribed_topics',
            field=models.ManyToManyField(blank=True, to='hadron_prime.hadrontopic'),
        ),
        migrations.CreateModel(
            name='HadronTopicMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_node', to='hadron_prime.hadronnode')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hadron_prime.hadrontopic')),
            ],
            options={
                'verbose_name': 'Hadron Topic Message',
                'verbose_name_plural': 'Hadron Topic Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='hadronnode',
            name='publishing_history_logs',
            field=models.ManyToManyField(blank=True, to='hadron_prime.hadrontopicmessage'),
        ),
        migrations.AddIndex(
            model_name='hadronstateactionstatelog',
            index=models.Index(fields=['node', 'action'], name='hadron_prim_node_id_58715a_idx'),
        ),
        migrations.AddIndex(
            model_name='hadronstateactionstatelog',
            index=models.Index(fields=['node', 'created_at'], name='hadron_prim_node_id_ba17c4_idx'),
        ),
        migrations.AddIndex(
            model_name='hadronsystem',
            index=models.Index(fields=['organization', 'system_name'], name='hadron_prim_organiz_643baa_idx'),
        ),
        migrations.AddIndex(
            model_name='hadronsystem',
            index=models.Index(fields=['organization', 'created_by_user'], name='hadron_prim_organiz_fcf14c_idx'),
        ),
        migrations.AddIndex(
            model_name='hadronsystem',
            index=models.Index(fields=['organization', 'created_at'], name='hadron_prim_organiz_e7897d_idx'),
        ),
        migrations.AddIndex(
            model_name='hadronsystem',
            index=models.Index(fields=['organization', 'updated_at'], name='hadron_prim_organiz_f74d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='hadrontopic',
            index=models.Index(fields=['system', 'topic_name'], name='hadron_prim_system__ede7c1_idx'),
        ),
        migrations.AddIndex(
            model_name='hadrontopic',
            index=models.Index(fields=['system', 'created_by_user'], name='hadron_prim_system__21b902_idx'),
        ),
        migrations.AddIndex(
            model_name='hadrontopic',
            index=models.Index(fields=['system', 'created_at'], name='hadron_prim_system__e7d0b4_idx'),
        ),
        migrations.AddIndex(
            model_name='hadrontopic',
            index=models.Index(fields=['system', 'updated_at'], name='hadron_prim_system__898ef3_idx'),
        ),
        migrations.AddIndex(
            model_name='hadrontopicmessage',
            index=models.Index(fields=['topic', 'sender_node'], name='hadron_prim_topic_i_27768f_idx'),
        ),
        migrations.AddIndex(
            model_name='hadrontopicmessage',
            index=models.Index(fields=['topic', 'created_at'], name='hadron_prim_topic_i_5afef8_idx'),
        ),
        migrations.AddIndex(
            model_name='hadronnode',
            index=models.Index(fields=['system', 'node_name'], name='hadron_prim_system__c81f60_idx'),
        ),
        migrations.AddIndex(
            model_name='hadronnode',
            index=models.Index(fields=['system', 'created_by_user'], name='hadron_prim_system__9158b0_idx'),
        ),
        migrations.AddIndex(
            model_name='hadronnode',
            index=models.Index(fields=['system', 'created_at'], name='hadron_prim_system__81ffcf_idx'),
        ),
        migrations.AddIndex(
            model_name='hadronnode',
            index=models.Index(fields=['system', 'updated_at'], name='hadron_prim_system__4e11a9_idx'),
        ),
    ]
