# Generated by Django 5.0.8 on 2024-10-18 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadron_prime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HadronStateErrorActionStateErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_state', models.TextField()),
                ('old_error', models.TextField()),
                ('action', models.TextField()),
                ('new_state', models.TextField()),
                ('new_error', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hadron_prime.hadronnode')),
            ],
            options={
                'verbose_name': 'Hadron State-Error-Action-State-Error Log',
                'verbose_name_plural': 'Hadron State-Error-Action-State-Error Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='hadronnode',
            name='state_action_state_history_logs',
            field=models.ManyToManyField(blank=True, to='hadron_prime.hadronstateerroractionstateerrorlog'),
        ),
        migrations.DeleteModel(
            name='HadronStateActionStateLog',
        ),
        migrations.AddIndex(
            model_name='hadronstateerroractionstateerrorlog',
            index=models.Index(fields=['node', 'action'], name='hadron_prim_node_id_06c80e_idx'),
        ),
        migrations.AddIndex(
            model_name='hadronstateerroractionstateerrorlog',
            index=models.Index(fields=['node', 'created_at'], name='hadron_prim_node_id_4ca026_idx'),
        ),
    ]
