# Generated by Django 5.0.8 on 2024-10-18 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadron_prime', '0002_hadronstateerroractionstateerrorlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HadronNodeExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hadron_prime.hadronnode')),
            ],
            options={
                'verbose_name': 'Hadron Node Execution Log',
                'verbose_name_plural': 'Hadron Node Execution Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['node', 'created_at'], name='hadron_prim_node_id_0d3860_idx')],
            },
        ),
    ]
