# Generated by Django 5.0.8 on 2024-10-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadron_prime', '0003_hadronnodeexecutionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadronnode',
            name='action_set_curl',
            field=models.CharField(blank=True, null=True),
        ),
    ]
