# Generated by Django 5.0.8 on 2024-10-18 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hadron_prime', '0004_alter_hadronnode_action_set_curl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hadronnode',
            old_name='activation_trigger_endpoint',
            new_name='activation_trigger_body',
        ),
    ]
