# Generated by Django 5.0.8 on 2024-10-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadron_prime', '0005_rename_activation_trigger_endpoint_hadronnode_activation_trigger_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='hadronnode',
            name='execution_logs',
            field=models.ManyToManyField(blank=True, to='hadron_prime.hadronnodeexecutionlog'),
        ),
    ]
