# Generated by Django 5.0.8 on 2024-10-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadron_prime', '0006_hadronnode_execution_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hadronnode',
            name='activation_trigger_body',
        ),
        migrations.AddField(
            model_name='hadronnode',
            name='activation_trigger_authentication_key',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='hadronnode',
            name='activation_trigger_hashed_param',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
