# Generated by Django 5.0.8 on 2024-10-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadron_prime', '0007_remove_hadronnode_activation_trigger_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hadronnodeexecutionlog',
            name='execution_status',
            field=models.CharField(choices=[('DEACTIVE', 'DEACTIVE'), ('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='DEACTIVE', max_length=100),
        ),
    ]
