# Generated by Django 5.0.8 on 2024-10-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadron_prime', '0008_hadronnodeexecutionlog_execution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hadronnode',
            name='topic_messages_history_lookback_memory_size',
            field=models.IntegerField(default=20),
        ),
    ]
