# Generated by Django 5.0.8 on 2024-10-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadron_prime', '0009_hadronnode_topic_messages_history_lookback_memory_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadronnode',
            name='topic_messages_history_lookback_memory_size',
            field=models.IntegerField(default=50),
        ),
    ]
