# Generated by Django 5.0.8 on 2024-10-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadron_prime', '0010_alter_hadronnode_topic_messages_history_lookback_memory_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='hadronnode',
            name='error_calculation_curl',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hadronnode',
            name='error_calculation_input_params_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hadronnode',
            name='error_calculation_output_params_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hadrontopic',
            name='topic_category',
            field=models.CharField(choices=[('alerts', 'Alerts'), ('info', 'Info'), ('states', 'States'), ('measurements', 'Measurements'), ('actions', 'Actions'), ('commands', 'Commands')], max_length=100),
        ),
    ]
