# Generated by Django 5.0.8 on 2024-10-22 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadron_prime', '0011_hadronnode_error_calculation_curl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HadronNodeSpeechLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speech_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hadron_prime.hadronnode')),
            ],
            options={
                'verbose_name': 'Hadron Node Speech Log',
                'verbose_name_plural': 'Hadron Node Speech Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='hadronnode',
            name='speech_logs',
            field=models.ManyToManyField(blank=True, to='hadron_prime.hadronnodespeechlog'),
        ),
        migrations.AddIndex(
            model_name='hadronnodespeechlog',
            index=models.Index(fields=['node', 'created_at'], name='hadron_prim_node_id_388bdc_idx'),
        ),
    ]
