# Generated by Django 5.0.8 on 2024-10-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadron_prime', '0012_hadronnodespeechlog_hadronnode_speech_logs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hadronnodespeechlog',
            name='user_query_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
