# Generated by Django 5.0.8 on 2024-11-13 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0007_alter_assistant_context_overflow_strategy'),
        ('hadron_prime', '0013_hadronnodespeechlog_user_query_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HadronNodeAssistantConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hadron_prime_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hadron_prime.hadronnode')),
            ],
            options={
                'verbose_name': 'Hadron Node Assistant Connection',
                'verbose_name_plural': 'Hadron Node Assistant Connections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hadron_prime_node', 'assistant'], name='hadron_prim_hadron__2eda4e_idx'), models.Index(fields=['assistant', 'hadron_prime_node'], name='hadron_prim_assista_04a972_idx')],
                'unique_together': {('hadron_prime_node', 'assistant')},
            },
        ),
    ]
