# Generated by Django 5.0.8 on 2024-12-01 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hadron_prime', '0014_hadronnodeassistantconnection'),
        ('organization', '0005_alter_organization_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hadronnode',
            unique_together={('system', 'node_name')},
        ),
        migrations.AlterUniqueTogether(
            name='hadronsystem',
            unique_together={('organization', 'system_name')},
        ),
    ]
