# Generated by Django 5.0.8 on 2024-12-01 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hadron_prime', '0015_alter_hadronnode_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hadrontopic',
            unique_together={('system', 'topic_name')},
        ),
    ]
