# Generated by Django 5.0.8 on 2024-10-30 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm_core', '0002_initial'),
        ('organization', '0002_organization_description_organization_mission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EllmaScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(max_length=255)),
                ('ellma_script_content', models.TextField(blank=True, null=True)),
                ('ellma_transcribed_file', models.FileField(blank=True, null=True, upload_to='ellma_scripts/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ellma_scripts', to=settings.AUTH_USER_MODEL)),
                ('llm_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ellma_scripts', to='llm_core.llmcore')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ellma_scripts', to='organization.organization')),
            ],
            options={
                'verbose_name': 'eLLMa Script',
                'verbose_name_plural': 'eLLMa Scripts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'llm_model', 'created_by_user'], name='ellma_ellma_organiz_9ca4df_idx'), models.Index(fields=['organization', 'llm_model'], name='ellma_ellma_organiz_2bdaba_idx'), models.Index(fields=['organization'], name='ellma_ellma_organiz_6726f5_idx'), models.Index(fields=['llm_model'], name='ellma_ellma_llm_mod_247b83_idx'), models.Index(fields=['created_by_user'], name='ellma_ellma_created_d37a02_idx'), models.Index(fields=['created_at'], name='ellma_ellma_created_5443f5_idx')],
            },
        ),
    ]
