# Generated by Django 5.0.8 on 2024-10-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ellma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ellmascript',
            name='ellma_transcription_language',
            field=models.CharField(choices=[('python3', 'Python 3'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('java', 'Java'), ('csharp', 'C#'), ('c', 'C'), ('cpp', 'C++'), ('go', 'Go'), ('rust', 'Rust'), ('ruby', 'Ruby'), ('php', 'PHP'), ('swift', 'Swift'), ('kotlin', 'Kotlin'), ('scala', 'Scala'), ('r', 'R'), ('perl', 'Perl'), ('bash', 'Bash'), ('powershell', 'PowerShell')], default='Python 3', max_length=255),
        ),
    ]
