# Generated by Django 5.0.8 on 2024-10-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ellma', '0003_alter_ellmascript_ellma_transcription_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ellmascript',
            name='ellma_transcribed_file',
        ),
        migrations.AddField(
            model_name='ellmascript',
            name='ellma_transcribed_content',
            field=models.FileField(blank=True, null=True, upload_to='ellma_scripts/%Y/%m/%d/'),
        ),
    ]
