# Generated by Django 5.0.8 on 2024-10-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ellma', '0004_remove_ellmascript_ellma_transcribed_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ellmascript',
            name='ellma_transcribed_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
