# Generated by Django 5.0.8 on 2024-10-31 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ellma', '0005_alter_ellmascript_ellma_transcribed_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ellmascript',
            name='ellma_transcription_language',
            field=models.CharField(blank=True, choices=[('python3', 'Python 3'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('java', 'Java'), ('csharp', 'C#'), ('c', 'C'), ('cpp', 'C++'), ('go', 'Go'), ('rust', 'Rust'), ('ruby', 'Ruby'), ('php', 'PHP'), ('swift', 'Swift'), ('kotlin', 'Kotlin'), ('scala', 'Scala'), ('r', 'R'), ('perl', 'Perl'), ('bash', 'Bash'), ('powershell', 'PowerShell')], max_length=255, null=True),
        ),
    ]
