# Generated by Django 5.0.8 on 2024-12-01 22:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ellma', '0007_alter_ellmascript_ellma_transcription_language'),
        ('organization', '0005_alter_organization_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ellmascript',
            unique_together={('organization', 'created_by_user', 'script_name')},
        ),
    ]
