# Generated by Django 5.0.8 on 2024-09-06 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_codebase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codebaserepositorychunk',
            old_name='document_uuid',
            new_name='repository_uuid',
        ),
    ]
