# Generated by Django 5.0.8 on 2024-12-01 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_codebase', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='codebaserepository',
            unique_together={('knowledge_base', 'repository_uri')},
        ),
    ]
