# Generated by Django 5.0.8 on 2024-12-11 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0014_assistant_is_beamguard_active'),
        ('datasource_codebase', '0002_alter_codebaserepository_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='RepositoryProcessingLog',
        ),
        migrations.RemoveIndex(
            model_name='codebaserepositorychunk',
            name='datasource__knowled_994f1d_idx',
        ),
        migrations.RemoveIndex(
            model_name='codebaserepositorychunk',
            name='datasource__knowled_90cdd5_idx',
        ),
        migrations.RemoveIndex(
            model_name='codebaserepositorychunk',
            name='datasource__knowled_f2efe2_idx',
        ),
        migrations.RemoveIndex(
            model_name='coderepositorystorageconnection',
            name='datasource__provide_9c609b_idx',
        ),
        migrations.RemoveIndex(
            model_name='coderepositorystorageconnection',
            name='datasource__provide_734fd7_idx',
        ),
        migrations.RemoveIndex(
            model_name='coderepositorystorageconnection',
            name='datasource__provide_8d750c_idx',
        ),
        migrations.RemoveIndex(
            model_name='coderepositorystorageconnection',
            name='datasource__class_n_bd2ea3_idx',
        ),
        migrations.RenameField(
            model_name='coderepositorystorageconnection',
            old_name='class_name',
            new_name='vector_index_path',
        ),
        migrations.RemoveField(
            model_name='codebaserepository',
            name='knowledge_base_uuid',
        ),
        migrations.RemoveField(
            model_name='codebaserepository',
            name='repository_content_temporary',
        ),
        migrations.RemoveField(
            model_name='codebaserepository',
            name='repository_metadata',
        ),
        migrations.RemoveField(
            model_name='codebaserepositorychunk',
            name='chunk_content',
        ),
        migrations.RemoveField(
            model_name='codebaserepositorychunk',
            name='chunk_metadata',
        ),
        migrations.RemoveField(
            model_name='codebaserepositorychunk',
            name='chunk_number',
        ),
        migrations.RemoveField(
            model_name='codebaserepositorychunk',
            name='chunk_repository_uri',
        ),
        migrations.RemoveField(
            model_name='codebaserepositorychunk',
            name='knowledge_base',
        ),
        migrations.RemoveField(
            model_name='codebaserepositorychunk',
            name='knowledge_base_uuid',
        ),
        migrations.RemoveField(
            model_name='codebaserepositorychunk',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='codebaserepositorychunk',
            name='repository_uuid',
        ),
        migrations.AlterUniqueTogether(
            name='coderepositorystorageconnection',
            unique_together={('name', 'assistant')},
        ),
        migrations.AddField(
            model_name='codebaserepository',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_code_base_repositories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codebaserepository',
            name='n_chunks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codebaserepository',
            name='n_chunks_indexed_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codebaserepositorychunk',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codebaserepositorychunk',
            name='raw_data_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='codebaserepositorychunk',
            name='repository_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasource_codebase.codebaserepository'),
        ),
        migrations.AddField(
            model_name='codebaserepositorychunk',
            name='vector_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coderepositorystorageconnection',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_code_repository_storage_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='codebaserepositorychunk',
            index=models.Index(fields=['repository_item'], name='datasource__reposit_0a13be_idx'),
        ),
        migrations.AddIndex(
            model_name='codebaserepositorychunk',
            index=models.Index(fields=['repository_item', 'created_at'], name='datasource__reposit_668e97_idx'),
        ),
        migrations.AddIndex(
            model_name='codebaserepositorychunk',
            index=models.Index(fields=['repository_item', 'updated_at'], name='datasource__reposit_18ca6a_idx'),
        ),
        migrations.AddIndex(
            model_name='coderepositorystorageconnection',
            index=models.Index(fields=['assistant', 'name'], name='datasource__assista_ce9729_idx'),
        ),
        migrations.AddIndex(
            model_name='coderepositorystorageconnection',
            index=models.Index(fields=['assistant', 'created_at'], name='datasource__assista_a4e9d9_idx'),
        ),
        migrations.AddIndex(
            model_name='coderepositorystorageconnection',
            index=models.Index(fields=['assistant', 'updated_at'], name='datasource__assista_32c323_idx'),
        ),
        migrations.RemoveField(
            model_name='coderepositorystorageconnection',
            name='host_url',
        ),
        migrations.RemoveField(
            model_name='coderepositorystorageconnection',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='coderepositorystorageconnection',
            name='provider_api_key',
        ),
        migrations.RemoveField(
            model_name='coderepositorystorageconnection',
            name='schema_json',
        ),
        migrations.RemoveField(
            model_name='coderepositorystorageconnection',
            name='vectorizer_api_key',
        ),
    ]
