# Generated by Django 5.0.8 on 2024-09-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_codebase', '0002_rename_document_uuid_codebaserepositorychunk_repository_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_full_uri', models.CharField(max_length=1000)),
                ('log_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Repository Processing Log',
                'verbose_name_plural': 'Repository Processing Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['repository_full_uri'], name='datasource__reposit_48adba_idx'), models.Index(fields=['created_at'], name='datasource__created_b65ba2_idx')],
            },
        ),
    ]
