#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Bimod.io™
#  File: 0001_initial.py
#  Last Modified: 2024-10-05 01:39:48
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 14:42:46
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@Bimod.io.
#
#
#

# Generated by Django 5.1.1 on 2024-09-25 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceMLModelConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('model_object_category', models.CharField(choices=[('pth', 'PyTorch Model')], max_length=20)),
                ('directory_full_path', models.CharField(blank=True, max_length=255, null=True)),
                ('directory_schema', models.TextField(blank=True, null=True)),
                ('interpretation_temperature', models.FloatField(default=0.25)),
                ('interpretation_maximum_tokens', models.IntegerField(default=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
            ],
            options={
                'verbose_name': 'Data Source ML Model Connection',
                'verbose_name_plural': 'Data Source ML Model Connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSourceMLModelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_model_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('ml_model_size', models.BigIntegerField(blank=True, null=True)),
                ('interpretation_temperature', models.FloatField(default=0.25)),
                ('full_file_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('file_bytes', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ml_model_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='datasource_ml_models.datasourcemlmodelconnection')),
            ],
            options={
                'verbose_name': 'Data Source ML Model Item',
                'verbose_name_plural': 'Data Source ML Model Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='datasourcemlmodelconnection',
            index=models.Index(fields=['assistant', 'name'], name='datasource__assista_ce9985_idx'),
        ),
        migrations.AddIndex(
            model_name='datasourcemlmodelconnection',
            index=models.Index(fields=['assistant', 'model_object_category'], name='datasource__assista_e1d8ae_idx'),
        ),
        migrations.AddIndex(
            model_name='datasourcemlmodelconnection',
            index=models.Index(fields=['assistant', 'directory_full_path'], name='datasource__assista_ad34b4_idx'),
        ),
        migrations.AddIndex(
            model_name='datasourcemlmodelconnection',
            index=models.Index(fields=['assistant', 'created_at'], name='datasource__assista_4501b0_idx'),
        ),
        migrations.AddIndex(
            model_name='datasourcemlmodelitem',
            index=models.Index(fields=['ml_model_base', 'ml_model_name'], name='datasource__ml_mode_028892_idx'),
        ),
        migrations.AddIndex(
            model_name='datasourcemlmodelitem',
            index=models.Index(fields=['ml_model_base', 'description'], name='datasource__ml_mode_2b05d8_idx'),
        ),
        migrations.AddIndex(
            model_name='datasourcemlmodelitem',
            index=models.Index(fields=['ml_model_base', 'created_at'], name='datasource__ml_mode_2feb8f_idx'),
        ),
        migrations.AddIndex(
            model_name='datasourcemlmodelitem',
            index=models.Index(fields=['ml_model_base', 'updated_at'], name='datasource__ml_mode_b735c7_idx'),
        ),
    ]
