# Generated by Django 5.0.6 on 2024-08-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_ml_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcemlmodelitem',
            name='interpretation_temperature',
            field=models.FloatField(default=0.25),
        ),
    ]
