# Generated by Django 5.0.8 on 2024-12-01 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_ml_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datasourcemlmodelitem',
            unique_together={('ml_model_base', 'ml_model_name')},
        ),
    ]
