# Generated by Django 5.0.8 on 2024-12-01 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0013_alter_assistantoldchatmessagesvectordata_unique_together'),
        ('datasource_ml_models', '0002_alter_datasourcemlmodelitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datasourcemlmodelconnection',
            unique_together={('assistant', 'name')},
        ),
    ]
