# Generated by Django 5.0.8 on 2024-12-21 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_ml_models', '0003_alter_datasourcemlmodelconnection_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcemlmodelitem',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasource_ml_model_items_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
