# Generated by Django 5.1.1 on 2024-09-23 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0003_initial'),
        ('export_assistants', '0001_initial'),
        ('llm_core', '0001_initial'),
        ('llm_transaction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('organization_image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='organization_images/%Y/%m/%d/')),
                ('auto_balance_topup', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_auto_balance_topup', to='llm_transaction.autobalancetopupmodel')),
                ('created_by_user', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organization_created_by_users', to=settings.AUTH_USER_MODEL)),
                ('exported_assistants', models.ManyToManyField(blank=True, related_name='organizations', to='export_assistants.exportassistantapi')),
                ('last_updated_by_user', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organization_last_updated_by_users', to=settings.AUTH_USER_MODEL)),
                ('llm_cores', models.ManyToManyField(related_name='organizations', to='llm_core.llmcore')),
                ('organization_assistants', models.ManyToManyField(blank=True, related_name='organizations', to='assistants.assistant')),
                ('users', models.ManyToManyField(related_name='organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='organizatio_name_2d216c_idx'), models.Index(fields=['email'], name='organizatio_email_8060eb_idx'), models.Index(fields=['phone'], name='organizatio_phone_1ebcb3_idx'), models.Index(fields=['industry'], name='organizatio_industr_ccfa43_idx'), models.Index(fields=['is_active'], name='organizatio_is_acti_51627a_idx'), models.Index(fields=['created_at'], name='organizatio_created_b3d583_idx'), models.Index(fields=['updated_at'], name='organizatio_updated_8d409c_idx'), models.Index(fields=['created_by_user'], name='organizatio_created_18ba4d_idx'), models.Index(fields=['last_updated_by_user'], name='organizatio_last_up_b4c571_idx'), models.Index(fields=['balance'], name='organizatio_balance_a270b5_idx')],
            },
        ),
    ]
