# Generated by Django 5.0.6 on 2024-08-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='organization_images/%Y/%m/%d/keKXvQVgfcH3M6nT'),
        ),
    ]
