# Generated by Django 5.1.1 on 2024-09-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_leanmods', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='exported_leanmods',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='export_leanmods.exportleanmodassistantapi'),
        ),
    ]
