# Generated by Django 5.0.8 on 2024-11-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_description_organization_mission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='balance',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=100),
        ),
    ]
