# Generated by Django 5.0.6 on 2024-06-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='organization_pictures/%Y/%m/%d/weZw1KLRTazXxChl'),
        ),
    ]
