# Generated by Django 5.1.1 on 2024-09-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_orchestrations', '0001_initial'),
        ('organization', '0002_organization_exported_leanmods'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='exported_orchestrations',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='export_orchestrations.exportorchestrationapi'),
        ),
    ]
