# Generated by Django 5.0.6 on 2024-06-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organization_city_organization_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='organization_pictures/%Y/%m/%d/xbTAe1o9RFTUY5gk'),
        ),
    ]
