# Generated by Django 5.0.8 on 2024-09-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_alter_organization_organization_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='organization_images/%Y/%m/%d/PlrFcr7iRnXx7U59'),
        ),
    ]
