# Generated by Django 5.0.6 on 2024-07-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0001_initial'),
        ('organization', '0097_alter_organization_organization_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_assistants',
            field=models.ManyToManyField(related_name='organizations', to='assistants.assistant'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='organization_images/%Y/%m/%d/r22DMZW1KeY1ekSb'),
        ),
    ]
