# Generated by Django 5.0.6 on 2024-07-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0004_alter_llmcore_frequency_penalty_and_more'),
        ('organization', '0109_alter_organization_organization_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='llm_cores',
            field=models.ManyToManyField(related_name='organizations', to='llm_core.llmcore'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='organization_images/%Y/%m/%d/tOOmSAO2l0HPkmd1'),
        ),
    ]
