# Generated by Django 5.0.6 on 2024-07-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0065_alter_assistant_assistant_image'),
        ('organization', '0161_alter_organization_organization_assistants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_assistants',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='assistants.assistant'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='organization_images/%Y/%m/%d/H2MzYB9VdoL9k4xH'),
        ),
    ]
