# Generated by Django 5.0.6 on 2024-07-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_assistants', '0003_exportassistantapi_endpoint_requestlog'),
        ('organization', '0269_alter_organization_organization_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='exported_assistants',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='export_assistants.exportassistantapi'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='organization_images/%Y/%m/%d/jvFV0gIhU8MR6AyE'),
        ),
    ]
