# Generated by Django 5.0.6 on 2024-07-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0270_organization_exported_assistants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='organization_images/%Y/%m/%d/BuPFmRcGcp26dnrn'),
        ),
    ]
