# Generated by Django 5.0.6 on 2024-07-16 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0411_alter_assistant_assistant_image'),
        ('export_assistants', '0005_alter_requestlog_options_and_more'),
        ('llm_core', '0015_alter_llmcore_options_and_more'),
        ('organization', '0507_alter_organization_organization_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='organization_images/%Y/%m/%d/v4SiJ2YYPOF67nxk'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='organizatio_name_2d216c_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['email'], name='organizatio_email_8060eb_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['phone'], name='organizatio_phone_1ebcb3_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['industry'], name='organizatio_industr_ccfa43_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active'], name='organizatio_is_acti_51627a_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['created_at'], name='organizatio_created_b3d583_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['updated_at'], name='organizatio_updated_8d409c_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['created_by_user'], name='organizatio_created_18ba4d_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['last_updated_by_user'], name='organizatio_last_up_b4c571_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['balance'], name='organizatio_balance_a270b5_idx'),
        ),
    ]
