# Generated by Django 5.0.6 on 2024-07-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0529_alter_organization_organization_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='organization_images/%Y/%m/%d/nAUZhKt8JG5waGU3'),
        ),
    ]
