# Generated by Django 5.0.6 on 2024-07-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0567_alter_organization_organization_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='organization_images/%Y/%m/%d/girg3UPxDKDz7usj'),
        ),
    ]
