# Generated by Django 5.0.6 on 2024-07-20 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0027_alter_autobalancetopupmodel_addition_on_balance_threshold_trigger_and_more'),
        ('organization', '0568_alter_organization_organization_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='auto_balance_topup',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_auto_balance_topup', to='llm_transaction.autobalancetopupmodel'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='organization_images/%Y/%m/%d/loJ01u97Ow3xMQQx'),
        ),
    ]
