# Generated by Django 5.0.6 on 2024-08-11 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['created_at'], 'verbose_name': 'Support Ticket', 'verbose_name_plural': 'Support Tickets'},
        ),
        migrations.AlterModelOptions(
            name='supportticketresponse',
            options={'ordering': ['created_at'], 'verbose_name': 'Support Ticket Response', 'verbose_name_plural': 'Support Ticket Responses'},
        ),
    ]
