# Generated by Django 5.0.6 on 2024-08-11 01:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_system', '0002_alter_supportticket_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'created_at'], name='support_sys_status_c19cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'updated_at'], name='support_sys_status_7af653_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'priority'], name='support_sys_status_cd5d28_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='support_sys_status_1fdd1f_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'priority', 'updated_at'], name='support_sys_status_1724fb_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketresponse',
            index=models.Index(fields=['ticket', 'created_at'], name='support_sys_ticket__aa2ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketresponse',
            index=models.Index(fields=['user', 'created_at'], name='support_sys_user_id_7a4fde_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketresponse',
            index=models.Index(fields=['ticket', 'user', 'created_at'], name='support_sys_ticket__443bd6_idx'),
        ),
    ]
