# Generated by Django 5.0.6 on 2024-08-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_system', '0003_supportticket_support_sys_status_c19cc6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(choices=[('recommendation', 'Recommendation'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=50),
        ),
    ]
