# Generated by Django 5.0.8 on 2024-10-22 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm_core', '0002_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BinexusProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=255)),
                ('process_description', models.TextField()),
                ('process_objective', models.TextField(blank=True, null=True)),
                ('process_success_criteria', models.JSONField(default=dict)),
                ('fitness_manager_selectiveness', models.FloatField(default=0.5)),
                ('optimization_generations', models.IntegerField(default=10)),
                ('optimization_population_size', models.IntegerField(default=5)),
                ('optimization_breeding_pool_rate', models.FloatField(default=0.4)),
                ('optimization_mutation_rate_per_individual', models.FloatField(default=0.1)),
                ('optimization_mutation_rate_per_gene', models.FloatField(default=0.1)),
                ('optimization_crossover_rate', models.FloatField(default=0.5)),
                ('self_breeding_possible', models.BooleanField(default=True)),
                ('post_processing_history_average_fitness_per_epoch', models.JSONField(default=list)),
                ('post_processing_history_best_fitness_per_epoch', models.JSONField(default=list)),
                ('post_processing_history_worst_fitness_per_epoch', models.JSONField(default=list)),
                ('post_processing_history_average_of_average_fitnesses', models.FloatField(default=0.0)),
                ('post_processing_history_average_of_best_fitnesses', models.FloatField(default=0.0)),
                ('post_processing_history_average_of_worst_fitnesses', models.FloatField(default=0.0)),
                ('post_processing_history_visual_chart', models.ImageField(blank=True, null=True, upload_to='binexus_process_visual_charts/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('llm_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llm_core.llmcore')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'verbose_name': 'Binexus Process',
                'verbose_name_plural': 'Binexus Processes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BinexusEliteAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_nickname', models.CharField(max_length=255)),
                ('agent_prompt', models.TextField(blank=True, null=True)),
                ('agent_temperature', models.FloatField(default=0.0)),
                ('binexus_fitness_score', models.IntegerField(default=0)),
                ('agent_chromosome_parameters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('binexus_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binexus.binexusprocess')),
            ],
            options={
                'verbose_name': 'Binexus Elite Agent',
                'verbose_name_plural': 'Binexus Elite Agents',
                'ordering': ['-binexus_fitness_score'],
            },
        ),
        migrations.AddIndex(
            model_name='binexusprocess',
            index=models.Index(fields=['organization'], name='binexus_bin_organiz_8ed42e_idx'),
        ),
        migrations.AddIndex(
            model_name='binexusprocess',
            index=models.Index(fields=['organization', 'llm_model'], name='binexus_bin_organiz_7b1af8_idx'),
        ),
        migrations.AddIndex(
            model_name='binexusprocess',
            index=models.Index(fields=['organization', 'llm_model', 'created_by_user'], name='binexus_bin_organiz_62f90e_idx'),
        ),
        migrations.AddIndex(
            model_name='binexusprocess',
            index=models.Index(fields=['organization', 'llm_model', 'created_by_user', 'created_at'], name='binexus_bin_organiz_9d7299_idx'),
        ),
        migrations.AddIndex(
            model_name='binexuseliteagent',
            index=models.Index(fields=['binexus_fitness_score'], name='binexus_fitness_score_idx'),
        ),
        migrations.AddIndex(
            model_name='binexuseliteagent',
            index=models.Index(fields=['created_at'], name='created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='binexuseliteagent',
            index=models.Index(fields=['updated_at'], name='updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='binexuseliteagent',
            index=models.Index(fields=['binexus_process'], name='binexus_process_idx'),
        ),
        migrations.AddIndex(
            model_name='binexuseliteagent',
            index=models.Index(fields=['agent_nickname'], name='agent_nickname_idx'),
        ),
        migrations.AddIndex(
            model_name='binexuseliteagent',
            index=models.Index(fields=['agent_temperature'], name='agent_temperature_idx'),
        ),
        migrations.AddIndex(
            model_name='binexuseliteagent',
            index=models.Index(fields=['created_at', 'updated_at'], name='created_at_updated_at_idx'),
        ),
    ]
