# Generated by Django 5.0.8 on 2024-10-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binexus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binexusprocess',
            name='process_success_criteria',
            field=models.TextField(blank=True, null=True),
        ),
    ]
