# Generated by Django 5.0.8 on 2024-10-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binexus', '0002_alter_binexusprocess_process_success_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='binexuseliteagent',
            name='assignment_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
