# Generated by Django 5.0.8 on 2024-10-23 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binexus', '0003_binexuseliteagent_assignment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binexuseliteagent',
            name='assignment_content',
        ),
    ]
