# Generated by Django 5.0.8 on 2024-10-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binexus', '0004_remove_binexuseliteagent_assignment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binexusprocess',
            name='post_processing_history_average_fitness_per_epoch',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='binexusprocess',
            name='post_processing_history_average_of_average_fitnesses',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='binexusprocess',
            name='post_processing_history_average_of_best_fitnesses',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='binexusprocess',
            name='post_processing_history_average_of_worst_fitnesses',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='binexusprocess',
            name='post_processing_history_best_fitness_per_epoch',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='binexusprocess',
            name='post_processing_history_worst_fitness_per_epoch',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
