# Generated by Django 5.0.8 on 2024-10-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binexus', '0005_alter_binexusprocess_post_processing_history_average_fitness_per_epoch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='binexusprocess',
            name='additional_genes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
