# Generated by Django 5.0.8 on 2024-12-01 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binexus', '0006_binexusprocess_additional_genes'),
        ('organization', '0005_alter_organization_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='binexusprocess',
            unique_together={('organization', 'process_name')},
        ),
    ]
