#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Bimod.io™
#  File: 0001_initial.py
#  Last Modified: 2024-10-05 01:39:47
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 14:42:39
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@Bimod.io.
#
#
#

# Generated by Django 5.0.8 on 2024-09-30 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('serialized_data', models.TextField()),
                ('encryption_password', models.CharField(max_length=255)),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Backup',
                'verbose_name_plural': 'Data Backups',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['responsible_user'], name='data_backup_respons_98090d_idx'), models.Index(fields=['backup_name'], name='data_backup_backup__dec489_idx'), models.Index(fields=['created_at'], name='data_backup_created_311c48_idx'), models.Index(fields=['responsible_user', 'backup_name', 'created_at'], name='data_backup_respons_301974_idx'), models.Index(fields=['responsible_user', 'created_at'], name='data_backup_respons_4e6852_idx'), models.Index(fields=['backup_name', 'created_at'], name='data_backup_backup__c15545_idx')],
            },
        ),
    ]
