#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Br6.in™
#  File: 0002_alter_databackup_serialized_data.py
#  Last Modified: 2024-10-05 01:39:47
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 14:42:39
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@br6.in.
#
#
#

# Generated by Django 5.0.8 on 2024-09-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_backups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databackup',
            name='serialized_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
