# Generated by Django 5.0.8 on 2024-09-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_backups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databackup',
            name='serialized_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
