#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Jupi.tr™
#  File: 0003_databackup_organization_and_more.py
#  Last Modified: 2024-09-30 16:47:04
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 01:36:37
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@jupi.tr.
#

# Generated by Django 5.0.8 on 2024-09-30 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_backups', '0002_alter_databackup_serialized_data'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='databackup',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddIndex(
            model_name='databackup',
            index=models.Index(fields=['organization'], name='data_backup_organiz_9f4a33_idx'),
        ),
        migrations.AddIndex(
            model_name='databackup',
            index=models.Index(fields=['organization', 'responsible_user'], name='data_backup_organiz_0c4e04_idx'),
        ),
        migrations.AddIndex(
            model_name='databackup',
            index=models.Index(fields=['organization', 'backup_name'], name='data_backup_organiz_53ec54_idx'),
        ),
        migrations.AddIndex(
            model_name='databackup',
            index=models.Index(fields=['organization', 'responsible_user', 'created_at'], name='data_backup_organiz_0b5233_idx'),
        ),
        migrations.AddIndex(
            model_name='databackup',
            index=models.Index(fields=['organization', 'backup_name', 'created_at'], name='data_backup_organiz_f002ba_idx'),
        ),
        migrations.AddIndex(
            model_name='databackup',
            index=models.Index(fields=['organization', 'responsible_user', 'backup_name', 'created_at'], name='data_backup_organiz_838cef_idx'),
        ),
    ]
