# Generated by Django 5.0.8 on 2024-09-30 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_backups', '0002_alter_databackup_serialized_data'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='databackup',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddIndex(
            model_name='databackup',
            index=models.Index(fields=['organization'], name='data_backup_organiz_9f4a33_idx'),
        ),
        migrations.AddIndex(
            model_name='databackup',
            index=models.Index(fields=['organization', 'responsible_user'], name='data_backup_organiz_0c4e04_idx'),
        ),
        migrations.AddIndex(
            model_name='databackup',
            index=models.Index(fields=['organization', 'backup_name'], name='data_backup_organiz_53ec54_idx'),
        ),
        migrations.AddIndex(
            model_name='databackup',
            index=models.Index(fields=['organization', 'responsible_user', 'created_at'], name='data_backup_organiz_0b5233_idx'),
        ),
        migrations.AddIndex(
            model_name='databackup',
            index=models.Index(fields=['organization', 'backup_name', 'created_at'], name='data_backup_organiz_f002ba_idx'),
        ),
        migrations.AddIndex(
            model_name='databackup',
            index=models.Index(fields=['organization', 'responsible_user', 'backup_name', 'created_at'], name='data_backup_organiz_838cef_idx'),
        ),
    ]
