# Generated by Django 5.0.8 on 2024-09-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_backups', '0003_databackup_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databackup',
            name='backup_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
