#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Jupi.tr™
#  File: 0005_databackup_backup_type_and_more.py
#  Last Modified: 2024-09-30 16:47:04
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 01:36:37
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@jupi.tr.
#

# Generated by Django 5.0.8 on 2024-09-30 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_backups', '0004_databackup_backup_uuid'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='databackup',
            name='backup_type',
            field=models.CharField(blank=True, choices=[('assistants', 'Assistants'), ('llm_models', 'LLM Models'), ('ner_instances', 'NER Instances'), ('custom_functions', 'Custom Functions'), ('custom_apis', 'Custom APIs'), ('custom_scripts', 'Custom Scripts')], max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='databackup',
            index=models.Index(fields=['backup_type'], name='data_backup_backup__12414b_idx'),
        ),
        migrations.AddIndex(
            model_name='databackup',
            index=models.Index(fields=['organization', 'backup_type'], name='data_backup_organiz_598778_idx'),
        ),
        migrations.AddIndex(
            model_name='databackup',
            index=models.Index(fields=['organization', 'created_at'], name='data_backup_organiz_2874e2_idx'),
        ),
        migrations.AddIndex(
            model_name='databackup',
            index=models.Index(fields=['responsible_user', 'backup_type', 'created_at'], name='data_backup_respons_23bb9e_idx'),
        ),
        migrations.AddIndex(
            model_name='databackup',
            index=models.Index(fields=['organization', 'responsible_user', 'backup_type', 'created_at'], name='data_backup_organiz_4394f9_idx'),
        ),
        migrations.AddIndex(
            model_name='databackup',
            index=models.Index(fields=['organization', 'backup_name', 'backup_type', 'created_at'], name='data_backup_organiz_fcb8c9_idx'),
        ),
        migrations.AddIndex(
            model_name='databackup',
            index=models.Index(fields=['organization', 'responsible_user', 'backup_name', 'backup_type', 'created_at'], name='data_backup_organiz_78ecf2_idx'),
        ),
    ]
