# Generated by Django 5.0.8 on 2024-12-01 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_backups', '0006_alter_databackup_responsible_user'),
        ('organization', '0005_alter_organization_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='databackup',
            unique_together={('organization', 'backup_name', 'backup_type', 'created_at')},
        ),
    ]
