# Generated by Django 5.0.8 on 2024-10-01 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0003_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGeneratorConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('provider', models.CharField(choices=[('lumo-ai', 'Lumo AI')], max_length=255)),
                ('provider_api_key', models.CharField(max_length=100000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'verbose_name': 'Video Generator Connection',
                'verbose_name_plural': 'Video Generator Connections',
                'db_table': 'video_generator_connections',
                'indexes': [models.Index(fields=['organization'], name='video_gener_organiz_ce8595_idx'), models.Index(fields=['organization', 'assistant'], name='video_gener_organiz_1a3a44_idx'), models.Index(fields=['organization', 'assistant', 'created_by_user'], name='video_gener_organiz_c3ffdf_idx')],
            },
        ),
    ]
