# Generated by Django 5.0.8 on 2024-10-01 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_generations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='videogeneratorconnection',
            new_name='video_gener_organiz_c6643a_idx',
            old_name='video_gener_organiz_ce8595_idx',
        ),
        migrations.RenameIndex(
            model_name='videogeneratorconnection',
            new_name='video_gener_organiz_3a84ab_idx',
            old_name='video_gener_organiz_1a3a44_idx',
        ),
        migrations.RenameIndex(
            model_name='videogeneratorconnection',
            new_name='video_gener_organiz_c534d4_idx',
            old_name='video_gener_organiz_c3ffdf_idx',
        ),
        migrations.AlterModelTable(
            name='videogeneratorconnection',
            table=None,
        ),
    ]
