#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Jupi.tr™
#  File: 0002_rename_video_gener_organiz_ce8595_idx_video_gener_organiz_c6643a_idx_and_more.py
#  Last Modified: 2024-10-01 22:54:15
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 01:36:43
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@jupi.tr.
#

# Generated by Django 5.0.8 on 2024-10-01 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_generations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='videogeneratorconnection',
            new_name='video_gener_organiz_c6643a_idx',
            old_name='video_gener_organiz_ce8595_idx',
        ),
        migrations.RenameIndex(
            model_name='videogeneratorconnection',
            new_name='video_gener_organiz_3a84ab_idx',
            old_name='video_gener_organiz_1a3a44_idx',
        ),
        migrations.RenameIndex(
            model_name='videogeneratorconnection',
            new_name='video_gener_organiz_c534d4_idx',
            old_name='video_gener_organiz_c3ffdf_idx',
        ),
        migrations.AlterModelTable(
            name='videogeneratorconnection',
            table=None,
        ),
    ]
