#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Bimod.io™
#  File: 0003_generatedvideo.py
#  Last Modified: 2024-10-05 01:39:48
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 14:42:46
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@Bimod.io.
#
#
#

# Generated by Django 5.0.8 on 2024-10-02 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0003_initial'),
        ('multimodal_chat', '0001_initial'),
        ('organization', '0001_initial'),
        ('video_generations', '0002_rename_video_gener_organiz_ce8595_idx_video_gener_organiz_c6643a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_videos', to='assistants.assistant')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_videos', to=settings.AUTH_USER_MODEL)),
                ('multimodal_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_videos', to='multimodal_chat.multimodalchat')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_videos', to='organization.organization')),
            ],
        ),
    ]
