# Generated by Django 5.0.8 on 2024-10-02 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimodal_chat', '0001_initial'),
        ('video_generations', '0003_generatedvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedvideo',
            name='multimodal_chat_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_videos', to='multimodal_chat.multimodalchatmessage'),
        ),
    ]
