# Generated by Django 5.0.8 on 2024-10-02 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_generations', '0004_generatedvideo_multimodal_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedvideo',
            name='multimodal_chat_message',
        ),
    ]
