#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Br6.in™
#  File: 0005_remove_generatedvideo_multimodal_chat_message.py
#  Last Modified: 2024-10-05 01:39:48
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 14:42:46
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@br6.in.
#
#
#

# Generated by Django 5.0.8 on 2024-10-02 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_generations', '0004_generatedvideo_multimodal_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedvideo',
            name='multimodal_chat_message',
        ),
    ]
