#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Jupi.tr™
#  File: 0006_alter_generatedvideo_options_and_more.py
#  Last Modified: 2024-10-01 22:54:15
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 01:36:43
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@jupi.tr.
#

# Generated by Django 5.0.8 on 2024-10-02 00:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0003_initial'),
        ('multimodal_chat', '0001_initial'),
        ('organization', '0001_initial'),
        ('video_generations', '0005_remove_generatedvideo_multimodal_chat_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatedvideo',
            options={'verbose_name': 'Generated Video', 'verbose_name_plural': 'Generated Videos'},
        ),
        migrations.AddIndex(
            model_name='generatedvideo',
            index=models.Index(fields=['organization'], name='video_gener_organiz_d51391_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedvideo',
            index=models.Index(fields=['organization', 'assistant'], name='video_gener_organiz_9258c6_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedvideo',
            index=models.Index(fields=['organization', 'assistant', 'created_by_user'], name='video_gener_organiz_6ef14a_idx'),
        ),
    ]
