# Generated by Django 5.0.8 on 2024-10-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_generations', '0006_alter_generatedvideo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogeneratorconnection',
            name='provider',
            field=models.CharField(choices=[('luma-ai', 'Luma AI')], max_length=255),
        ),
    ]
