#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Bimod.io™
#  File: 0007_alter_videogeneratorconnection_provider.py
#  Last Modified: 2024-10-05 01:39:48
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 14:42:46
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@Bimod.io.
#
#
#

# Generated by Django 5.0.8 on 2024-10-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_generations', '0006_alter_generatedvideo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogeneratorconnection',
            name='provider',
            field=models.CharField(choices=[('luma-ai', 'Luma AI')], max_length=255),
        ),
    ]
