# Generated by Django 5.0.8 on 2024-12-01 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0013_alter_assistantoldchatmessagesvectordata_unique_together'),
        ('multimodal_chat', '0005_remove_multimodalchat_context_memory_connection'),
        ('organization', '0006_alter_organization_name'),
        ('video_generations', '0007_alter_videogeneratorconnection_provider'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='generatedvideo',
            unique_together={('organization', 'assistant', 'multimodal_chat', 'video_url')},
        ),
    ]
