# Generated by Django 5.0.8 on 2024-12-01 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0013_alter_assistantoldchatmessagesvectordata_unique_together'),
        ('video_generations', '0008_alter_generatedvideo_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videogeneratorconnection',
            unique_together={('assistant', 'name')},
        ),
    ]
