# Generated by Django 5.0.8 on 2024-10-25 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0004_assistant_multi_step_reasoning_capability_choice'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField()),
                ('project_department', models.TextField()),
                ('project_description', models.TextField()),
                ('project_status', models.CharField(blank=True, max_length=1000, null=True)),
                ('project_priority', models.CharField(blank=True, max_length=1000, null=True)),
                ('project_risk_level', models.CharField(blank=True, max_length=1000, null=True)),
                ('project_goals', models.TextField(blank=True, null=True)),
                ('project_constraints', models.TextField(blank=True, null=True)),
                ('project_stakeholders', models.TextField(blank=True, null=True)),
                ('project_start_date', models.DateField(blank=True, null=True)),
                ('project_end_date', models.DateField(blank=True, null=True)),
                ('project_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistants', models.ManyToManyField(blank=True, related_name='project_items', to='assistants.assistant')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_project_items', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'verbose_name': 'Project Item',
                'verbose_name_plural': 'Project Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTeamItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=1000)),
                ('team_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_project_teams', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_teams', to='projects.projectitem')),
                ('team_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_project_teams', to=settings.AUTH_USER_MODEL)),
                ('team_members', models.ManyToManyField(blank=True, related_name='project_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Team Item',
                'verbose_name_plural': 'Project Team Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='projectitem',
            index=models.Index(fields=['organization', 'project_name', 'project_department'], name='projects_pr_organiz_ddb6e1_idx'),
        ),
        migrations.AddIndex(
            model_name='projectitem',
            index=models.Index(fields=['organization', 'project_name'], name='projects_pr_organiz_6cad68_idx'),
        ),
        migrations.AddIndex(
            model_name='projectitem',
            index=models.Index(fields=['organization'], name='projects_pr_organiz_acc332_idx'),
        ),
        migrations.AddIndex(
            model_name='projectitem',
            index=models.Index(fields=['project_name'], name='projects_pr_project_ce0cf1_idx'),
        ),
        migrations.AddIndex(
            model_name='projectitem',
            index=models.Index(fields=['project_department'], name='projects_pr_project_500d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectitem',
            index=models.Index(fields=['created_at'], name='projects_pr_created_4d2970_idx'),
        ),
        migrations.AddIndex(
            model_name='projectitem',
            index=models.Index(fields=['updated_at'], name='projects_pr_updated_4668b7_idx'),
        ),
        migrations.AddIndex(
            model_name='projectitem',
            index=models.Index(fields=['project_status'], name='projects_pr_project_28dd6e_idx'),
        ),
        migrations.AddIndex(
            model_name='projectitem',
            index=models.Index(fields=['project_priority'], name='projects_pr_project_aa0bb2_idx'),
        ),
        migrations.AddIndex(
            model_name='projectitem',
            index=models.Index(fields=['project_risk_level'], name='projects_pr_project_53454d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectitem',
            index=models.Index(fields=['project_start_date'], name='projects_pr_project_674ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='projectitem',
            index=models.Index(fields=['project_end_date'], name='projects_pr_project_9bdd65_idx'),
        ),
        migrations.AddIndex(
            model_name='projectitem',
            index=models.Index(fields=['project_budget'], name='projects_pr_project_68b4a2_idx'),
        ),
        migrations.AddIndex(
            model_name='projectitem',
            index=models.Index(fields=['created_by_user'], name='projects_pr_created_bbf8d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectitem',
            unique_together={('organization', 'project_name', 'project_department')},
        ),
        migrations.AddIndex(
            model_name='projectteamitem',
            index=models.Index(fields=['project', 'team_name'], name='projects_pr_project_f8af26_idx'),
        ),
        migrations.AddIndex(
            model_name='projectteamitem',
            index=models.Index(fields=['project'], name='projects_pr_project_7274ac_idx'),
        ),
        migrations.AddIndex(
            model_name='projectteamitem',
            index=models.Index(fields=['team_name'], name='projects_pr_team_na_addec1_idx'),
        ),
        migrations.AddIndex(
            model_name='projectteamitem',
            index=models.Index(fields=['created_at'], name='projects_pr_created_b06d73_idx'),
        ),
        migrations.AddIndex(
            model_name='projectteamitem',
            index=models.Index(fields=['updated_at'], name='projects_pr_updated_9990ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectteamitem',
            unique_together={('project', 'team_name')},
        ),
    ]
