# Generated by Django 5.0.8 on 2024-10-25 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectitem',
            name='assistants',
        ),
    ]
