# Generated by Django 5.1 on 2024-08-30 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finetuning', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finetunedmodelconnection',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['organization'], name='finetuning__organiz_78573d_idx'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['nickname'], name='finetuning__nicknam_dcf492_idx'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['model_name'], name='finetuning__model_n_c04b21_idx'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['created_at'], name='finetuning__created_8451f8_idx'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['organization', 'nickname'], name='finetuning__organiz_bda71c_idx'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['organization', 'model_name'], name='finetuning__organiz_dfaee8_idx'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['organization', 'created_at'], name='finetuning__organiz_b3073c_idx'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['nickname', 'model_name'], name='finetuning__nicknam_b749f4_idx'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['nickname', 'created_at'], name='finetuning__nicknam_63e490_idx'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['model_name', 'created_at'], name='finetuning__model_n_652f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['organization', 'nickname', 'model_name'], name='finetuning__organiz_468d57_idx'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['organization', 'nickname', 'created_at'], name='finetuning__organiz_3f7097_idx'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['organization', 'model_name', 'created_at'], name='finetuning__organiz_63569e_idx'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['nickname', 'model_name', 'created_at'], name='finetuning__nicknam_65713c_idx'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['organization', 'nickname', 'model_name', 'created_at'], name='finetuning__organiz_bd1dbd_idx'),
        ),
    ]
