#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Jupi.tr™
#  File: 0002_initial.py
#  Last Modified: 2024-09-25 17:51:06
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 01:36:35
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@jupi.tr.
#

# Generated by Django 5.1.1 on 2024-09-25 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finetuning', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finetunedmodelconnection',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['organization'], name='finetuning__organiz_78573d_idx'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['nickname'], name='finetuning__nicknam_dcf492_idx'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['model_name'], name='finetuning__model_n_c04b21_idx'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['created_at'], name='finetuning__created_8451f8_idx'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['organization', 'nickname'], name='finetuning__organiz_bda71c_idx'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['organization', 'model_name'], name='finetuning__organiz_dfaee8_idx'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['organization', 'created_at'], name='finetuning__organiz_b3073c_idx'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['nickname', 'model_name'], name='finetuning__nicknam_b749f4_idx'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['nickname', 'created_at'], name='finetuning__nicknam_63e490_idx'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['model_name', 'created_at'], name='finetuning__model_n_652f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['organization', 'nickname', 'model_name'], name='finetuning__organiz_468d57_idx'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['organization', 'nickname', 'created_at'], name='finetuning__organiz_3f7097_idx'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['organization', 'model_name', 'created_at'], name='finetuning__organiz_63569e_idx'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['nickname', 'model_name', 'created_at'], name='finetuning__nicknam_65713c_idx'),
        ),
        migrations.AddIndex(
            model_name='finetunedmodelconnection',
            index=models.Index(fields=['organization', 'nickname', 'model_name', 'created_at'], name='finetuning__organiz_bd1dbd_idx'),
        ),
    ]
