# Generated by Django 5.0.8 on 2024-12-01 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finetuning', '0002_initial'),
        ('organization', '0005_alter_organization_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='finetunedmodelconnection',
            unique_together={('organization', 'nickname')},
        ),
    ]
