# Generated by Django 5.0.8 on 2024-12-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finetuning', '0003_alter_finetunedmodelconnection_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finetunedmodelconnection',
            name='model_type',
            field=models.CharField(choices=[('o1', 'O1'), ('o1-mini', 'O1-Mini')], max_length=255),
        ),
    ]
