# Generated by Django 5.0.8 on 2024-12-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finetuning', '0004_alter_finetunedmodelconnection_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finetunedmodelconnection',
            name='model_type',
            field=models.CharField(choices=[('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4o', 'GPT-4o'), ('gpt-4', 'GPT-4')], max_length=255),
        ),
    ]
