#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Br6.in™
#  File: 0001_initial.py
#  Last Modified: 2024-10-05 01:39:48
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 14:42:43
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@br6.in.
#
#
#

# Generated by Django 5.1.1 on 2024-09-25 20:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoBalanceTopUpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_balance_threshold_trigger', models.BooleanField(default=False)),
                ('on_interval_by_days_trigger', models.BooleanField(default=False)),
                ('balance_lower_trigger_threshold_value', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('addition_on_balance_threshold_trigger', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('regular_by_days_interval', models.IntegerField(blank=True, null=True)),
                ('addition_on_interval_by_days_trigger', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('date_of_last_auto_top_up', models.DateTimeField(blank=True, null=True)),
                ('calendar_month_total_auto_addition_value', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('monthly_hard_limit_auto_addition_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auto Balance Top Up',
                'verbose_name_plural': 'Auto Balance Top Ups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding_engine', models.CharField(choices=[('cl100k_base', 'cl100k_base'), ('p50k_base', 'p50k_base'), ('r50k_base', 'r50k_base')], default='cl100k_base', max_length=100)),
                ('transaction_context_content', models.TextField(blank=True, default='')),
                ('number_of_tokens', models.IntegerField(blank=True, null=True)),
                ('llm_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('internal_service_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('tax_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('total_billable_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('transaction_type', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], default='system', max_length=100)),
                ('transaction_source', models.CharField(choices=[('app', 'Application'), ('api', 'API'), ('generation', 'Generation'), ('sql-read', 'SQL Read'), ('sql-write', 'SQL Write'), ('store-memory', 'Store Memory'), ('interpret-code', 'Interpret Code'), ('download-file', 'Download File'), ('file-system-commands', 'File System Commands'), ('knowledge-base-search', 'Knowledge Base Search'), ('retrieve-memory', 'Retrieve Memory'), ('ml-model-prediction', 'ML Model Prediction'), ('internal-function-execution', 'Internal Function Execution'), ('external-function-execution', 'External Function Execution'), ('interpret-file', 'Interpret File'), ('interpret-image', 'Interpret Image')], default='application', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_tool_cost', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationBalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Organization Balance Snapshot',
                'verbose_name_plural': 'Organization Balance Snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('auto-top-up', 'Auto Top-Up'), ('top-up', 'Top-Up'), ('gift-credits', 'Gift Credits'), ('transferred-credits', 'Transferred Credits')], default='top-up', max_length=50)),
                ('amount_added', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_method', models.CharField(choices=[('credit-card', 'Credit Card'), ('internal-transfer', 'Internal Transfer')], default='credit-card', max_length=50)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('invoice_number', models.CharField(blank=True, max_length=2000, null=True)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='invoice_barcodes/%Y/%m/%d/')),
                ('transaction_paper', models.FileField(blank=True, null=True, upload_to='transaction_papers/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Transaction Invoice',
                'verbose_name_plural': 'Transaction Invoices',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
