# Generated by Django 5.0.6 on 2024-06-29 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm_core', '0002_remove_llmcore_audience_remove_llmcore_tone'),
        ('organization', '0022_alter_organization_organization_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_tokens', models.IntegerField()),
                ('llm_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('internal_service_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='llm_core.llmcore')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
