# Generated by Django 5.0.6 on 2024-06-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmtransaction',
            name='transaction_context_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
