# Generated by Django 5.1 on 2024-08-30 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0004_initial'),
        ('llm_core', '0002_initial'),
        ('llm_transaction', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='autobalancetopupmodel',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_balance_top_ups', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='llmtransaction',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='llm_core.llmcore'),
        ),
        migrations.AddField(
            model_name='llmtransaction',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='llmtransaction',
            name='responsible_assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='assistants.assistant'),
        ),
        migrations.AddField(
            model_name='llmtransaction',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationbalancesnapshot',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_snapshots', to='organization.organization'),
        ),
        migrations.AddIndex(
            model_name='llmtransaction',
            index=models.Index(fields=['organization'], name='llm_transac_organiz_91ae95_idx'),
        ),
        migrations.AddIndex(
            model_name='llmtransaction',
            index=models.Index(fields=['model'], name='llm_transac_model_i_68ce56_idx'),
        ),
        migrations.AddIndex(
            model_name='llmtransaction',
            index=models.Index(fields=['created_at'], name='llm_transac_created_c54e57_idx'),
        ),
        migrations.AddIndex(
            model_name='llmtransaction',
            index=models.Index(fields=['organization', 'model', 'created_at'], name='llm_transac_organiz_4e9289_idx'),
        ),
        migrations.AddIndex(
            model_name='llmtransaction',
            index=models.Index(fields=['organization', 'created_at'], name='llm_transac_organiz_09595b_idx'),
        ),
        migrations.AddIndex(
            model_name='llmtransaction',
            index=models.Index(fields=['model', 'created_at'], name='llm_transac_model_i_e9b932_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationbalancesnapshot',
            index=models.Index(fields=['organization'], name='llm_transac_organiz_a78817_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationbalancesnapshot',
            index=models.Index(fields=['created_at'], name='llm_transac_created_c08d59_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationbalancesnapshot',
            index=models.Index(fields=['organization', 'created_at'], name='llm_transac_organiz_1fa0e8_idx'),
        ),
    ]
