#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Jupi.tr™
#  File: 0003_alter_transactioninvoice_payment_method.py
#  Last Modified: 2024-09-29 16:16:40
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 01:36:41
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@jupi.tr.
#

# Generated by Django 5.0.8 on 2024-09-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioninvoice',
            name='payment_method',
            field=models.CharField(choices=[('credit-card', 'Credit Card'), ('internal-transfer', 'Internal Transfer'), ('direct-sales', 'Direct Sales')], default='credit-card', max_length=50),
        ),
    ]
