# Generated by Django 5.1.1 on 2024-09-24 22:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0002_initial'),
        ('organization', '0003_organization_exported_orchestrations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('auto-top-up', 'Auto Top-Up'), ('top-up', 'Top-Up'), ('gift-credits', 'Gift Credits'), ('transferred-credits', 'Transferred Credits')], default='top-up', max_length=50)),
                ('amount_added', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_method', models.CharField(choices=[('credit-card', 'Credit Card')], default='credit-card', max_length=50)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='invoice_barcodes/%Y/%m/%d/')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_invoices', to='organization.organization')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Invoice',
                'verbose_name_plural': 'Transaction Invoices',
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['organization'], name='llm_transac_organiz_1f5ba6_idx'), models.Index(fields=['responsible_user'], name='llm_transac_respons_b34134_idx'), models.Index(fields=['transaction_date'], name='llm_transac_transac_b759a7_idx'), models.Index(fields=['organization', 'transaction_date'], name='llm_transac_organiz_fb3d71_idx'), models.Index(fields=['organization', 'responsible_user', 'transaction_date'], name='llm_transac_organiz_ca2f95_idx')],
            },
        ),
    ]
