# Generated by Django 5.0.6 on 2024-06-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0002_llmtransaction_transaction_context_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmtransaction',
            name='encoding_engine',
            field=models.CharField(choices=[('cl100k_base', 'cl100k_base'), ('p50k_base', 'p50k_base'), ('r50k_base', 'r50k_base')], default='cl100k_base', max_length=100),
        ),
        migrations.AlterField(
            model_name='llmtransaction',
            name='transaction_context_content',
            field=models.TextField(),
        ),
    ]
