# Generated by Django 5.0.8 on 2024-09-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioninvoice',
            name='payment_method',
            field=models.CharField(choices=[('credit-card', 'Credit Card'), ('internal-transfer', 'Internal Transfer'), ('direct-sales', 'Direct Sales')], default='credit-card', max_length=50),
        ),
    ]
