# Generated by Django 5.1.1 on 2024-09-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0003_transactioninvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioninvoice',
            name='payment_method',
            field=models.CharField(choices=[('credit-card', 'Credit Card'), ('internal-transfer', 'Internal Transfer')], default='credit-card', max_length=50),
        ),
    ]
