# Generated by Django 5.0.6 on 2024-06-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0003_llmtransaction_encoding_engine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmtransaction',
            name='transaction_context_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
