# Generated by Django 5.0.8 on 2024-09-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0004_alter_transactioninvoice_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioninvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
