# Generated by Django 5.0.6 on 2024-06-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0004_alter_llmtransaction_transaction_context_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmtransaction',
            name='internal_service_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='llmtransaction',
            name='llm_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='llmtransaction',
            name='number_of_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='llmtransaction',
            name='tax_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='llmtransaction',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
