#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Jupi.tr™
#  File: 0005_alter_llmtransaction_transaction_source.py
#  Last Modified: 2024-10-01 22:54:15
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 01:36:41
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@jupi.tr.
#

# Generated by Django 5.0.8 on 2024-10-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0004_alter_llmtransaction_transaction_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmtransaction',
            name='transaction_source',
            field=models.CharField(choices=[('app', 'Application'), ('api', 'API'), ('generation', 'Generation'), ('sql-read', 'SQL Read'), ('sql-write', 'SQL Write'), ('store-memory', 'Store Memory'), ('interpret-code', 'Interpret Code'), ('upload-file', 'Upload File'), ('download-file', 'Download File'), ('file-system-commands', 'File System Commands'), ('knowledge-base-search', 'Knowledge Base Search'), ('code-base-search', 'Code Base Search'), ('retrieve-memory', 'Retrieve Memory'), ('ml-model-prediction', 'ML Model Prediction'), ('browsing', 'Browsing'), ('internal-function-execution', 'Internal Function Execution'), ('external-function-execution', 'External Function Execution'), ('internal-api-execution', 'Internal API Execution'), ('external-api-execution', 'External API Execution'), ('internal-script-retrieval', 'Internal Script Retrieval'), ('external-script-retrieval', 'External Script Retrieval'), ('interpret-file', 'Interpret File'), ('interpret-image', 'Interpret Image'), ('scheduled-job-execution', 'Scheduled Job Execution'), ('trigger-job-execution', 'Trigger Job Execution'), ('generate-image', 'Generate Image'), ('modify-image', 'Modify Image'), ('variate-image', 'Variate Image'), ('audio-processing-stt', 'Audio Processing STT'), ('audio-processing-tts', 'Audio Processing TTS'), ('brainstorming', 'Brainstorming'), ('generate-video', 'Generate Video')], default='application', max_length=100),
        ),
    ]
