# Generated by Django 5.0.6 on 2024-06-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0005_alter_llmtransaction_internal_service_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmtransaction',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
