# Generated by Django 5.0.8 on 2024-09-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0005_alter_transactioninvoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioninvoice',
            name='transaction_paper',
            field=models.FileField(blank=True, null=True, upload_to='transaction_papers/%Y/%m/%d/'),
        ),
    ]
