# Generated by Django 5.0.6 on 2024-06-29 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0006_alter_llmtransaction_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmtransaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
