# Generated by Django 5.0.6 on 2024-06-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0008_alter_llmtransaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmtransaction',
            name='total_billable_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
