# Generated by Django 5.0.6 on 2024-07-08 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0174_alter_assistant_assistant_image'),
        ('llm_core', '0013_alter_llmcore_organization'),
        ('llm_transaction', '0013_llmtransaction_responsible_assistant'),
        ('organization', '0271_alter_organization_organization_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmtransaction',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='llm_core.llmcore'),
        ),
        migrations.AlterField(
            model_name='llmtransaction',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='llmtransaction',
            name='responsible_assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='assistants.assistant'),
        ),
        migrations.AlterField(
            model_name='llmtransaction',
            name='responsible_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
