# Generated by Django 5.0.8 on 2024-10-31 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0014_alter_llmtransaction_transaction_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmtransaction',
            name='transaction_source',
            field=models.CharField(choices=[('app', 'Application'), ('api', 'API'), ('generation', 'Generation'), ('sql-read', 'SQL Read'), ('sql-write', 'SQL Write'), ('nosql-read', 'NoSQL Read'), ('nosql-write', 'NoSQL Write'), ('store-memory', 'Store Memory'), ('interpret-code', 'Interpret Code'), ('reasoning', 'Reasoning'), ('upload-file', 'Upload File'), ('download-file', 'Download File'), ('file-system-commands', 'File System Commands'), ('knowledge-base-search', 'Knowledge Base Search'), ('code-base-search', 'Code Base Search'), ('retrieve-memory', 'Retrieve Memory'), ('ml-model-prediction', 'ML Model Prediction'), ('browsing', 'Browsing'), ('internal-function-execution', 'Internal Function Execution'), ('external-function-execution', 'External Function Execution'), ('internal-api-execution', 'Internal API Execution'), ('external-api-execution', 'External API Execution'), ('internal-script-retrieval', 'Internal Script Retrieval'), ('external-script-retrieval', 'External Script Retrieval'), ('interpret-file', 'Interpret File'), ('interpret-image', 'Interpret Image'), ('scheduled-job-execution', 'Scheduled Job Execution'), ('trigger-job-execution', 'Trigger Job Execution'), ('generate-image', 'Generate Image'), ('modify-image', 'Modify Image'), ('variate-image', 'Variate Image'), ('audio-processing-stt', 'Audio Processing STT'), ('audio-processing-tts', 'Audio Processing TTS'), ('brainstorming', 'Brainstorming'), ('generate-video', 'Generate Video'), ('ellma-scripting', 'Ellma Scripting'), ('drafting', 'Drafting'), ('hadron-prime', 'Hadron Prime'), ('smart-contract-creation', 'Smart Contract Creation'), ('binexus', 'Binexus'), ('metakanban', 'MetaKanban'), ('meeting-transcription', 'Meeting Transcription'), ('metatempo', 'MetaTempo')], default='application', max_length=100),
        ),
    ]
