# Generated by Django 5.0.6 on 2024-07-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0015_alter_llmtransaction_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmtransaction',
            name='transaction_source',
            field=models.CharField(choices=[('app', 'Application'), ('api', 'API')], default='application', max_length=100),
        ),
        migrations.AddField(
            model_name='llmtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], default='system', max_length=100),
        ),
    ]
