# Generated by Django 5.0.6 on 2024-07-12 00:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0254_alter_assistant_assistant_image'),
        ('llm_core', '0013_alter_llmcore_organization'),
        ('llm_transaction', '0016_llmtransaction_transaction_source_and_more'),
        ('organization', '0351_alter_organization_organization_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='llmtransaction',
            index=models.Index(fields=['created_at'], name='llm_transac_created_c54e57_idx'),
        ),
        migrations.AddIndex(
            model_name='llmtransaction',
            index=models.Index(fields=['organization'], name='llm_transac_organiz_91ae95_idx'),
        ),
        migrations.AddIndex(
            model_name='llmtransaction',
            index=models.Index(fields=['model'], name='llm_transac_model_i_68ce56_idx'),
        ),
        migrations.AddIndex(
            model_name='llmtransaction',
            index=models.Index(fields=['responsible_user'], name='llm_transac_respons_8b9a19_idx'),
        ),
    ]
