# Generated by Django 5.0.6 on 2024-07-12 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0017_llmtransaction_llm_transac_created_c54e57_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='llmtransaction',
            name='llm_transac_respons_8b9a19_idx',
        ),
    ]
