# Generated by Django 5.0.6 on 2024-07-12 00:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0256_alter_assistant_assistant_image'),
        ('llm_core', '0013_alter_llmcore_organization'),
        ('llm_transaction', '0018_remove_llmtransaction_llm_transac_respons_8b9a19_idx'),
        ('organization', '0353_alter_organization_organization_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='llmtransaction',
            index=models.Index(fields=['organization', 'model', 'created_at'], name='llm_transac_organiz_4e9289_idx'),
        ),
    ]
