# Generated by Django 5.0.8 on 2024-12-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0019_alter_llmtransaction_transaction_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('developer', 'Developer')], default='developer', max_length=100),
        ),
    ]
