# Generated by Django 5.0.6 on 2024-07-12 00:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0257_alter_assistant_assistant_image'),
        ('llm_core', '0013_alter_llmcore_organization'),
        ('llm_transaction', '0019_llmtransaction_llm_transac_organiz_4e9289_idx'),
        ('organization', '0354_alter_organization_organization_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='llmtransaction',
            index=models.Index(fields=['organization', 'created_at'], name='llm_transac_organiz_09595b_idx'),
        ),
        migrations.AddIndex(
            model_name='llmtransaction',
            index=models.Index(fields=['model', 'created_at'], name='llm_transac_model_i_e9b932_idx'),
        ),
    ]
