# Generated by Django 5.0.6 on 2024-07-12 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0020_llmtransaction_llm_transac_organiz_09595b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmtransaction',
            name='transaction_context_content',
        ),
    ]
