# Generated by Django 5.0.8 on 2024-12-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0020_alter_llmtransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], default='system', max_length=100),
        ),
    ]
