# Generated by Django 5.0.8 on 2024-12-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0021_alter_llmtransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autobalancetopupmodel',
            name='calendar_month_total_auto_addition_value',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
    ]
