# Generated by Django 5.0.6 on 2024-07-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0021_remove_llmtransaction_transaction_context_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmtransaction',
            name='transaction_context_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
