# Generated by Django 5.0.6 on 2024-07-19 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0023_alter_llmtransaction_responsible_user'),
        ('organization', '0562_alter_organization_organization_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoBalanceTopUpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_balance_threshold_trigger', models.BooleanField(default=False)),
                ('on_interval_by_days_trigger', models.BooleanField(default=False)),
                ('balance_lower_trigger_threshold_value', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('addition_on_balance_threshold_trigger', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('regular_by_days_interval', models.IntegerField(blank=True, null=True)),
                ('addition_on_interval_by_days_trigger', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('monthly_hard_limit_auto_addition_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_balance_top_ups', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Auto Balance Top Up',
                'verbose_name_plural': 'Auto Balance Top Ups',
                'ordering': ['-created_at'],
            },
        ),
    ]
