# Generated by Django 5.0.6 on 2024-07-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0024_autobalancetopupmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobalancetopupmodel',
            name='date_of_last_auto_top_up',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
