# Generated by Django 5.0.6 on 2024-07-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0025_autobalancetopupmodel_date_of_last_auto_top_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobalancetopupmodel',
            name='calendar_month_total_auto_addition_value',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
