# Generated by Django 5.0.6 on 2024-07-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0026_autobalancetopupmodel_calendar_month_total_auto_addition_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autobalancetopupmodel',
            name='addition_on_balance_threshold_trigger',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='autobalancetopupmodel',
            name='addition_on_interval_by_days_trigger',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='autobalancetopupmodel',
            name='balance_lower_trigger_threshold_value',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='autobalancetopupmodel',
            name='calendar_month_total_auto_addition_value',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='autobalancetopupmodel',
            name='monthly_hard_limit_auto_addition_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
