# Generated by Django 5.0.6 on 2024-07-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0027_alter_autobalancetopupmodel_addition_on_balance_threshold_trigger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmtransaction',
            name='is_tool_cost',
            field=models.BooleanField(default=False),
        ),
    ]
