# Generated by Django 5.0.6 on 2024-07-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0028_llmtransaction_is_tool_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmtransaction',
            name='transaction_source',
            field=models.CharField(choices=[('app', 'Application'), ('api', 'API'), ('generation', 'Generation'), ('sql-read', 'SQL Read'), ('sql-write', 'SQL Write'), ('store-memory', 'Store Memory'), ('interpret-code', 'Interpret Code'), ('download-file', 'Download File'), ('file-system-commands', 'File System Commands'), ('knowledge-base-search', 'Knowledge Base Search'), ('retrieve-memory', 'Retrieve Memory'), ('ml-model-prediction', 'ML Model Prediction'), ('internal-function-execution', 'Internal Function Execution'), ('external-function-execution', 'External Function Execution'), ('interpret-file', 'Interpret File'), ('interpret-image', 'Interpret Image')], default='application', max_length=100),
        ),
    ]
