# Generated by Django 5.0.6 on 2024-07-31 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0029_alter_llmtransaction_transaction_source'),
        ('organization', '0692_alter_organization_organization_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationBalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_snapshots', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Organization Balance Snapshot',
                'verbose_name_plural': 'Organization Balance Snapshots',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization'], name='llm_transac_organiz_a78817_idx'), models.Index(fields=['created_at'], name='llm_transac_created_c08d59_idx'), models.Index(fields=['organization', 'created_at'], name='llm_transac_organiz_1fa0e8_idx')],
            },
        ),
    ]
