# Generated by Django 5.1.1 on 2024-09-15 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('instructions', models.TextField(blank=True, default='')),
                ('response_template', models.TextField(blank=True, default='')),
                ('audience', models.CharField(max_length=1000)),
                ('tone', models.CharField(max_length=1000)),
                ('response_language', models.CharField(choices=[('auto', 'Auto (Detect)'), ('sq', 'Albanian'), ('ar', 'Arabic'), ('bs', 'Bosnian'), ('bg', 'Bulgarian'), ('zh', 'Chinese'), ('hr', 'Croatian'), ('cs', 'Czech'), ('da', 'Danish'), ('nl', 'Dutch'), ('en', 'English'), ('et', 'Estonian'), ('fi', 'Finnish'), ('fi', 'Finnish'), ('fr', 'French'), ('de', 'German'), ('el', 'Greek'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hu', 'Hungarian'), ('is', 'Icelandic'), ('id', 'Indonesian'), ('ga', 'Irish'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('lv', 'Latvian'), ('lt', 'Lithuanian'), ('mk', 'Macedonian'), ('ms', 'Malay'), ('no', 'Norwegian'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sr', 'Serbian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('es', 'Spanish'), ('sv', 'Swedish'), ('th', 'Thai'), ('tr', 'Turkish'), ('uk', 'Ukrainian'), ('cy', 'Welsh')], default='auto', max_length=10)),
                ('max_retry_count', models.IntegerField(default=3)),
                ('tool_max_attempts_per_instance', models.IntegerField(default=3)),
                ('tool_max_chains', models.IntegerField(default=3)),
                ('glossary', models.JSONField(blank=True, default=dict)),
                ('time_awareness', models.BooleanField(default=True)),
                ('place_awareness', models.BooleanField(default=True)),
                ('assistant_image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/')),
                ('context_overflow_strategy', models.CharField(choices=[('stop', 'Stop Conversation'), ('forget', 'Forget Oldest Messages'), ('vectorize', 'Vectorize Oldest Messages')], default='forget', max_length=100)),
                ('max_context_messages', models.IntegerField(default=25)),
                ('vectorizer_name', models.CharField(blank=True, choices=[('text2vec-openai', 'Text2Vec (OpenAI)')], default='text2vec-openai', max_length=100, null=True)),
                ('vectorizer_api_key', models.CharField(blank=True, max_length=1000, null=True)),
                ('document_base_directory', models.CharField(blank=True, max_length=1000, null=True)),
                ('storages_base_directory', models.CharField(blank=True, max_length=1000, null=True)),
                ('ml_models_base_directory', models.CharField(blank=True, max_length=1000, null=True)),
                ('image_generation_capability', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants_created_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assistant',
                'verbose_name_plural': 'Assistants',
                'ordering': ['-created_at'],
            },
        ),
    ]
