#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Br6.in™
#  File: 0002_initial.py
#  Last Modified: 2024-10-05 01:39:47
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 14:42:38
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@br6.in.
#
#
#

# Generated by Django 5.1.1 on 2024-09-25 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0001_initial'),
        ('data_security', '0001_initial'),
        ('llm_core', '0001_initial'),
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='llm_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='llm_core.llmcore'),
        ),
        migrations.AddField(
            model_name='assistant',
            name='memories',
            field=models.ManyToManyField(blank=True, related_name='assistants', to='memories.assistantmemory'),
        ),
        migrations.AddField(
            model_name='assistant',
            name='ner_integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistants', to='data_security.nerintegration'),
        ),
    ]
