# Generated by Django 5.0.6 on 2024-07-02 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistant',
            options={'ordering': ['-created_at'], 'verbose_name': 'Assistant', 'verbose_name_plural': 'Assistants'},
        ),
    ]
