# Generated by Django 5.1.1 on 2024-09-15 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0001_initial'),
        ('mm_functions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='custom_function_references',
            field=models.ManyToManyField(blank=True, related_name='assistants', to='mm_functions.customfunctionreference'),
        ),
        migrations.AddField(
            model_name='assistant',
            name='last_updated_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants_updated_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
