# Generated by Django 5.1 on 2024-08-30 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0002_initial'),
        ('llm_core', '0001_initial'),
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='llm_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='llm_core.llmcore'),
        ),
        migrations.AddField(
            model_name='assistant',
            name='memories',
            field=models.ManyToManyField(blank=True, related_name='assistants', to='memories.assistantmemory'),
        ),
    ]
