# Generated by Django 5.1.1 on 2024-09-23 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0002_initial'),
        ('data_security', '0001_initial'),
        ('llm_core', '0001_initial'),
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='llm_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='llm_core.llmcore'),
        ),
        migrations.AddField(
            model_name='assistant',
            name='memories',
            field=models.ManyToManyField(blank=True, related_name='assistants', to='memories.assistantmemory'),
        ),
        migrations.AddField(
            model_name='assistant',
            name='ner_integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistants', to='data_security.nerintegration'),
        ),
    ]
