# Generated by Django 5.0.6 on 2024-07-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0002_alter_assistant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='audience',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='tone',
            field=models.CharField(max_length=1000),
        ),
    ]
