# Generated by Django 5.0.6 on 2024-08-02 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0003_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='organization.organization'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'llm_model', 'name'], name='assistants__organiz_30796f_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'llm_model', 'created_by_user'], name='assistants__organiz_533523_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'llm_model', 'last_updated_by_user'], name='assistants__organiz_7124d9_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'llm_model', 'created_at'], name='assistants__organiz_51ca67_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'llm_model', 'updated_at'], name='assistants__organiz_2f102d_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'llm_model', 'name', 'created_at'], name='assistants__organiz_0873c7_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'llm_model', 'name', 'updated_at'], name='assistants__organiz_e8c98d_idx'),
        ),
    ]
