# Generated by Django 5.0.8 on 2024-10-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='multi_step_reasoning_capability_choice',
            field=models.CharField(choices=[('none', 'None'), ('cost-effective', 'Cost Effective'), ('high-performance', 'High Performance')], default='none', max_length=100),
        ),
    ]
