# Generated by Django 5.0.6 on 2024-07-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0003_alter_assistant_audience_alter_assistant_tone'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='organization_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/mK19aLtcfyRehR5M'),
        ),
    ]
