# Generated by Django 5.1.1 on 2024-09-23 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0003_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='organization.organization'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization'], name='assistants__organiz_c2cd72_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['llm_model'], name='assistants__llm_mod_0450af_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['name'], name='assistants__name_157a60_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['response_language'], name='assistants__respons_ae4cac_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['created_by_user'], name='assistants__created_450a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['last_updated_by_user'], name='assistants__last_up_4b3e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['created_at'], name='assistants__created_0635c9_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['updated_at'], name='assistants__updated_60710a_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['context_overflow_strategy'], name='assistants__context_bb81e7_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['vectorizer_name'], name='assistants__vectori_220cee_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'llm_model'], name='assistants__organiz_c36bfa_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'name'], name='assistants__organiz_fe5fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'created_by_user'], name='assistants__organiz_6d8dee_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'last_updated_by_user'], name='assistants__organiz_0d9288_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'created_at'], name='assistants__organiz_5d0f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'updated_at'], name='assistants__organiz_4d6539_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['llm_model', 'name'], name='assistants__llm_mod_87cbc9_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['llm_model', 'created_by_user'], name='assistants__llm_mod_c7d3cb_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['llm_model', 'last_updated_by_user'], name='assistants__llm_mod_331c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['llm_model', 'created_at'], name='assistants__llm_mod_97ae17_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['llm_model', 'updated_at'], name='assistants__llm_mod_e6664e_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['created_by_user', 'created_at'], name='assistants__created_a5cd84_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['created_by_user', 'updated_at'], name='assistants__created_8ebcd0_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['last_updated_by_user', 'created_at'], name='assistants__last_up_36a7b7_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['last_updated_by_user', 'updated_at'], name='assistants__last_up_53e0c7_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'llm_model', 'name'], name='assistants__organiz_30796f_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'llm_model', 'created_by_user'], name='assistants__organiz_533523_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'llm_model', 'last_updated_by_user'], name='assistants__organiz_7124d9_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'llm_model', 'created_at'], name='assistants__organiz_51ca67_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'llm_model', 'updated_at'], name='assistants__organiz_2f102d_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'name', 'created_at'], name='assistants__organiz_4b8d21_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'name', 'updated_at'], name='assistants__organiz_d4583f_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'created_by_user', 'created_at'], name='assistants__organiz_43aefc_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'created_by_user', 'updated_at'], name='assistants__organiz_12cc32_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'last_updated_by_user', 'created_at'], name='assistants__organiz_535e70_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'last_updated_by_user', 'updated_at'], name='assistants__organiz_3bdf59_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['llm_model', 'name', 'created_at'], name='assistants__llm_mod_c92db5_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['llm_model', 'name', 'updated_at'], name='assistants__llm_mod_8f108b_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['llm_model', 'created_by_user', 'created_at'], name='assistants__llm_mod_3c8e25_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['llm_model', 'created_by_user', 'updated_at'], name='assistants__llm_mod_04a3c0_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['llm_model', 'last_updated_by_user', 'created_at'], name='assistants__llm_mod_e662b4_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['llm_model', 'last_updated_by_user', 'updated_at'], name='assistants__llm_mod_5f75d2_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['created_by_user', 'created_at', 'updated_at'], name='assistants__created_183f00_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['last_updated_by_user', 'created_at', 'updated_at'], name='assistants__last_up_1de473_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'llm_model', 'name', 'created_at'], name='assistants__organiz_0873c7_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'llm_model', 'name', 'updated_at'], name='assistants__organiz_e8c98d_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'llm_model', 'created_by_user', 'created_at'], name='assistants__organiz_01ec8e_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'llm_model', 'created_by_user', 'updated_at'], name='assistants__organiz_129130_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'llm_model', 'last_updated_by_user', 'created_at'], name='assistants__organiz_090b8d_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'llm_model', 'last_updated_by_user', 'updated_at'], name='assistants__organiz_a60ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'name', 'created_at', 'updated_at'], name='assistants__organiz_df848a_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'created_by_user', 'created_at', 'updated_at'], name='assistants__organiz_bd4ac3_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'last_updated_by_user', 'created_at', 'updated_at'], name='assistants__organiz_942025_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['llm_model', 'name', 'created_at', 'updated_at'], name='assistants__llm_mod_f0933c_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['llm_model', 'created_by_user', 'created_at', 'updated_at'], name='assistants__llm_mod_304356_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['llm_model', 'last_updated_by_user', 'created_at', 'updated_at'], name='assistants__llm_mod_958cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'context_overflow_strategy'], name='assistants__organiz_49c758_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'vectorizer_name'], name='assistants__organiz_9c1e13_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['llm_model', 'context_overflow_strategy'], name='assistants__llm_mod_846f30_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['llm_model', 'vectorizer_name'], name='assistants__llm_mod_b4b3af_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'llm_model', 'context_overflow_strategy'], name='assistants__organiz_c7b65b_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'llm_model', 'vectorizer_name'], name='assistants__organiz_3cbeb4_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['created_by_user', 'context_overflow_strategy'], name='assistants__created_402b39_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['created_by_user', 'vectorizer_name'], name='assistants__created_cc235a_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['last_updated_by_user', 'context_overflow_strategy'], name='assistants__last_up_557851_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['last_updated_by_user', 'vectorizer_name'], name='assistants__last_up_925b3e_idx'),
        ),
    ]
