# Generated by Django 5.0.6 on 2024-07-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0004_assistant_organization_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistant',
            name='organization_image',
        ),
        migrations.AddField(
            model_name='assistant',
            name='assistant_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/530YZWtufQmfpVhD'),
        ),
    ]
