# Generated by Django 5.0.8 on 2024-10-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0005_assistant_project_items'),
        ('projects', '0002_remove_projectitem_assistants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='project_items',
            field=models.ManyToManyField(blank=True, related_name='assistants', to='projects.projectitem'),
        ),
    ]
