# Generated by Django 5.0.8 on 2024-11-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0006_alter_assistant_project_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='context_overflow_strategy',
            field=models.CharField(choices=[('stop', 'Stop Conversation'), ('forget', 'Forget Oldest Messages')], default='forget', max_length=100),
        ),
    ]
