# Generated by Django 5.0.8 on 2024-11-17 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0007_alter_assistant_context_overflow_strategy'),
        ('multimodal_chat', '0004_alter_multimodalchat_chat_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantOldChatMessagesVectorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('raw_data_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('vector_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant_chat_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_chat_message_vector_data', to='multimodal_chat.multimodalchatmessage')),
            ],
            options={
                'verbose_name': 'Assistant Old Chat Messages Vector Data',
                'verbose_name_plural': 'Assistant Old Chat Messages Vector Datas',
                'indexes': [models.Index(fields=['assistant_chat_message'], name='assistants__assista_025f99_idx'), models.Index(fields=['created_at'], name='assistants__created_ca545e_idx'), models.Index(fields=['updated_at'], name='assistants__updated_d43658_idx')],
            },
        ),
    ]
