# Generated by Django 5.0.8 on 2024-11-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0008_assistantoldchatmessagesvectordata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='context_overflow_strategy',
            field=models.CharField(choices=[('stop', 'Stop Conversation'), ('forget', 'Forget Oldest Messages'), ('vectorize', 'Vectorize Oldest Messages')], default='forget', max_length=100),
        ),
    ]
