# Generated by Django 5.0.8 on 2024-11-17 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0009_alter_assistant_context_overflow_strategy'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assistant',
            name='assistants__vectori_220cee_idx',
        ),
        migrations.RemoveIndex(
            model_name='assistant',
            name='assistants__organiz_9c1e13_idx',
        ),
        migrations.RemoveIndex(
            model_name='assistant',
            name='assistants__llm_mod_b4b3af_idx',
        ),
        migrations.RemoveIndex(
            model_name='assistant',
            name='assistants__organiz_3cbeb4_idx',
        ),
        migrations.RemoveIndex(
            model_name='assistant',
            name='assistants__created_cc235a_idx',
        ),
        migrations.RemoveIndex(
            model_name='assistant',
            name='assistants__last_up_925b3e_idx',
        ),
        migrations.RemoveField(
            model_name='assistant',
            name='vectorizer_api_key',
        ),
        migrations.RemoveField(
            model_name='assistant',
            name='vectorizer_name',
        ),
    ]
