# Generated by Django 5.0.8 on 2024-12-01 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0011_remove_assistant_assistants__context_bb81e7_idx_and_more'),
        ('organization', '0005_alter_organization_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assistant',
            unique_together={('organization', 'name')},
        ),
    ]
