# Generated by Django 5.0.8 on 2024-12-01 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0012_alter_assistant_unique_together'),
        ('multimodal_chat', '0005_remove_multimodalchat_context_memory_connection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assistantoldchatmessagesvectordata',
            unique_together={('assistant_chat_message',)},
        ),
    ]
