# Generated by Django 5.0.8 on 2024-09-05 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0013_alter_assistant_assistant_image'),
        ('data_security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='ner_integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistants', to='data_security.nerintegration'),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='assistant_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/fYijUSrnLs5g6yEv'),
        ),
    ]
