# Generated by Django 5.0.8 on 2024-12-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0013_alter_assistantoldchatmessagesvectordata_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='is_beamguard_active',
            field=models.BooleanField(default=True),
        ),
    ]
