# Generated by Django 5.0.8 on 2024-09-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0014_assistant_ner_integration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='assistant_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/iG6R7tRAmB9lwuSf'),
        ),
    ]
