# Generated by Django 5.0.8 on 2024-09-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0017_alter_assistant_assistant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='assistant_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/Simi68jNUS9qprA8'),
        ),
    ]
