# Generated by Django 5.0.6 on 2024-08-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0029_alter_assistant_assistant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='assistant_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/x9bOJvY1jLznlmcw'),
        ),
    ]
