# Generated by Django 5.0.6 on 2024-07-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0071_alter_assistant_assistant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='response_templates',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='assistant_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/nJzKwnlWYw1O3sNV'),
        ),
    ]
