# Generated by Django 5.0.6 on 2024-07-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0072_assistant_response_templates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='assistant_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/Rs9u6Humx7LAnc5b'),
        ),
    ]
