# Generated by Django 5.0.6 on 2024-07-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0073_alter_assistant_assistant_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistant',
            old_name='response_templates',
            new_name='response_template',
        ),
        migrations.AlterField(
            model_name='assistant',
            name='assistant_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/ErnUF9D1iLnSQuZL'),
        ),
    ]
