# Generated by Django 5.0.6 on 2024-07-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0117_alter_assistant_assistant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='assistant_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/w8NcmM32ZvyB95QR'),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='response_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('nl', 'Dutch'), ('ru', 'Russian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('zh', 'Chinese'), ('ar', 'Arabic'), ('tr', 'Turkish'), ('pl', 'Polish'), ('sv', 'Swedish'), ('da', 'Danish'), ('fi', 'Finnish'), ('no', 'Norwegian'), ('he', 'Hebrew'), ('id', 'Indonesian'), ('ms', 'Malay'), ('th', 'Thai'), ('hi', 'Hindi'), ('hu', 'Hungarian'), ('cs', 'Czech'), ('sk', 'Slovak'), ('uk', 'Ukrainian'), ('ro', 'Romanian'), ('bg', 'Bulgarian'), ('el', 'Greek'), ('fi', 'Finnish'), ('et', 'Estonian'), ('lv', 'Latvian'), ('lt', 'Lithuanian'), ('hr', 'Croatian'), ('sr', 'Serbian'), ('sl', 'Slovenian'), ('mk', 'Macedonian'), ('sq', 'Albanian'), ('bs', 'Bosnian'), ('is', 'Icelandic'), ('cy', 'Welsh'), ('ga', 'Irish'), ('auto', 'Auto')], default='auto', max_length=10),
        ),
    ]
