# Generated by Django 5.0.6 on 2024-07-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0126_alter_assistant_assistant_image'),
        ('memories', '0003_alter_assistantmemory_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='memories',
            field=models.ManyToManyField(blank=True, related_name='assistants', to='memories.assistantmemory'),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='assistant_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/0NWHXbKDmGl6KX2a'),
        ),
    ]
