# Generated by Django 5.0.6 on 2024-07-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0150_assistant_place_awareness_assistant_time_awareness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='assistant_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/s5YJYImDWMGeYMqq'),
        ),
    ]
