# Generated by Django 5.0.6 on 2024-07-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0223_alter_assistant_assistant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='tool_max_attempts_per_instance',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='assistant',
            name='tool_max_chains',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='assistant_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/inTyUl9GGx5fqf3j'),
        ),
    ]
