# Generated by Django 5.0.6 on 2024-07-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0224_assistant_tool_max_attempts_per_instance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='assistant_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/C8d8H6dSb2UrUh1D'),
        ),
    ]
