# Generated by Django 5.0.6 on 2024-07-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0274_alter_assistant_assistant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='context_overflow_strategy',
            field=models.CharField(choices=[('stop', 'Stop Conversation'), ('forget', 'Forget Oldest Messages'), ('summarize', 'Summarize Oldest Messages'), ('vectorize', 'Vectorize Oldest Messages')], default='forget', max_length=100),
        ),
        migrations.AddField(
            model_name='assistant',
            name='max_context_messages',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='assistant',
            name='summarization_batch_size',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='assistant',
            name='vectorizer_name',
            field=models.CharField(choices=[('text2vec-openai', 'Text2Vec (OpenAI)')], default='text2vec-openai', max_length=100),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='assistant_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/ha94F6seFr98cvep'),
        ),
    ]
