# Generated by Django 5.0.6 on 2024-07-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0277_alter_assistant_assistant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='assistant_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/2AEgL6qBThEYWLnF'),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='summarization_batch_size',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='vectorizer_name',
            field=models.CharField(blank=True, choices=[('text2vec-openai', 'Text2Vec (OpenAI)')], default='text2vec-openai', max_length=100, null=True),
        ),
    ]
