# Generated by Django 5.0.6 on 2024-07-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0278_alter_assistant_assistant_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistant',
            name='summarization_batch_size',
        ),
        migrations.AlterField(
            model_name='assistant',
            name='assistant_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/R9G6Rhx6hsjOINyq'),
        ),
    ]
