# Generated by Django 5.0.6 on 2024-07-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0280_alter_assistant_assistant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='vectorizer_api_key',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='assistant_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/HNZIMY1RFsmkdQYP'),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='context_overflow_strategy',
            field=models.CharField(choices=[('stop', 'Stop Conversation'), ('forget', 'Forget Oldest Messages'), ('vectorize', 'Vectorize Oldest Messages')], default='forget', max_length=100),
        ),
    ]
