# Generated by Django 5.0.6 on 2024-07-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0281_assistant_vectorizer_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='assistant_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/Rn3D2HnkojZnLYIn'),
        ),
    ]
