# Generated by Django 5.0.6 on 2024-07-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0335_assistant_document_base_directory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='assistant_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/NkNBmB8nYnTflITn'),
        ),
    ]
