# Generated by Django 5.0.6 on 2024-07-16 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0399_alter_assistant_assistant_image'),
        ('llm_core', '0014_alter_llmcore_model_name'),
        ('memories', '0003_alter_assistantmemory_assistant'),
        ('organization', '0497_alter_organization_organization_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='assistant_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/3N9Avw4L7lqEedqA'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'llm_model', 'name'], name='assistants__organiz_30796f_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'llm_model', 'created_by_user'], name='assistants__organiz_533523_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'llm_model', 'last_updated_by_user'], name='assistants__organiz_7124d9_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'llm_model', 'created_at'], name='assistants__organiz_51ca67_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'llm_model', 'updated_at'], name='assistants__organiz_2f102d_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'llm_model', 'name', 'created_at'], name='assistants__organiz_0873c7_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['organization', 'llm_model', 'name', 'updated_at'], name='assistants__organiz_e8c98d_idx'),
        ),
    ]
