# Generated by Django 5.0.6 on 2024-07-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0462_alter_assistant_assistant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='assistant_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/dqkgwVJn43BMMX27'),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='glossary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
