# Generated by Django 5.0.6 on 2024-07-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0475_alter_assistant_assistant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='ml_models_base_directory',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='assistant_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/0OqZ8nei8MZ1jSHo'),
        ),
    ]
