# Generated by Django 5.0.6 on 2024-07-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0500_alter_assistant_assistant_image'),
        ('mm_functions', '0006_customfunction_created_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='custom_function_references',
            field=models.ManyToManyField(blank=True, related_name='assistants', to='mm_functions.customfunctionreference'),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='assistant_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/CI00rMwjXhgrScMe'),
        ),
    ]
