# Generated by Django 5.0.6 on 2024-07-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0501_assistant_custom_function_references_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='assistant_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/vXGnCuIxJ9jPAI1A'),
        ),
    ]
