# Generated by Django 5.0.6 on 2024-07-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0505_alter_assistant_assistant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='assistant_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/EzYbl1Tb5I1EBh9G'),
        ),
    ]
