# Generated by Django 5.0.6 on 2024-07-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0527_alter_assistant_assistant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='assistant_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/TZKZ7RJ2Rr2W9c10'),
        ),
    ]
