# Generated by Django 5.0.6 on 2024-07-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0564_alter_assistant_assistant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='image_generation_capability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='assistant_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/kJ7N3PBEoDdsP9yh'),
        ),
    ]
