# Generated by Django 5.0.6 on 2024-07-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0565_assistant_image_generation_capability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='assistant_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='assistant_images/%Y/%m/%d/Xbc3j1GQ2GfRda96'),
        ),
    ]
