# Generated by Django 5.1 on 2024-08-30 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0004_initial'),
        ('multimodal_chat', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StarredMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant')], default='USER', max_length=10)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('message_image_urls', models.JSONField(blank=True, null=True)),
                ('message_file_urls', models.JSONField(blank=True, null=True)),
                ('starred_at', models.DateTimeField(auto_now_add=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimodal_chat.multimodalchat')),
                ('chat_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimodal_chat.multimodalchatmessage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Starred Message',
                'verbose_name_plural': 'Starred Messages',
                'ordering': ['-starred_at'],
                'indexes': [models.Index(fields=['user', 'organization', 'assistant', 'chat', 'chat_message'], name='starred_mes_user_id_c990f6_idx'), models.Index(fields=['user', 'organization', 'assistant', 'chat', 'starred_at'], name='starred_mes_user_id_6d522d_idx'), models.Index(fields=['user', 'organization', 'assistant', 'chat', 'sender_type'], name='starred_mes_user_id_3cf879_idx'), models.Index(fields=['user', 'organization', 'assistant', 'chat', 'sender_type', 'starred_at'], name='starred_mes_user_id_12657a_idx'), models.Index(fields=['user', 'organization', 'assistant', 'chat', 'sender_type', 'chat_message'], name='starred_mes_user_id_f233b1_idx'), models.Index(fields=['user', 'organization', 'assistant', 'chat', 'chat_message', 'starred_at'], name='starred_mes_user_id_67bf31_idx'), models.Index(fields=['user', 'organization', 'assistant', 'chat', 'chat_message', 'sender_type'], name='starred_mes_user_id_6149c7_idx'), models.Index(fields=['user', 'organization', 'assistant', 'chat', 'chat_message', 'sender_type', 'starred_at'], name='starred_mes_user_id_7fda96_idx')],
            },
        ),
    ]
