# Generated by Django 5.0.6 on 2024-07-08 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0135_alter_assistant_assistant_image'),
        ('multimodal_chat', '0014_rename_messages_multimodalchat_chat_messages'),
        ('organization', '0232_alter_organization_organization_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StarredMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starred_at', models.DateTimeField(auto_now_add=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimodal_chat.multimodalchat')),
                ('chat_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimodal_chat.multimodalchatmessage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Starred Message',
                'verbose_name_plural': 'Starred Messages',
            },
        ),
    ]
