# Generated by Django 5.0.8 on 2024-12-01 22:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimodal_chat', '0005_remove_multimodalchat_context_memory_connection'),
        ('starred_messages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='starredmessage',
            unique_together={('user', 'chat_message')},
        ),
    ]
