# Generated by Django 5.0.6 on 2024-07-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starred_messages', '0002_starredmessage_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='starredmessage',
            name='sender_type',
            field=models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant')], default='USER', max_length=10),
        ),
    ]
