# Generated by Django 5.0.6 on 2024-07-16 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0412_alter_assistant_assistant_image'),
        ('multimodal_chat', '0024_multimodalchat_multimodal__organiz_6d4d01_idx_and_more'),
        ('organization', '0509_alter_organization_organization_image'),
        ('starred_messages', '0003_starredmessage_sender_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='starredmessage',
            options={'ordering': ['-starred_at'], 'verbose_name': 'Starred Message', 'verbose_name_plural': 'Starred Messages'},
        ),
        migrations.AddIndex(
            model_name='starredmessage',
            index=models.Index(fields=['user', 'organization', 'assistant', 'chat', 'chat_message'], name='starred_mes_user_id_c990f6_idx'),
        ),
        migrations.AddIndex(
            model_name='starredmessage',
            index=models.Index(fields=['user', 'organization', 'assistant', 'chat', 'starred_at'], name='starred_mes_user_id_6d522d_idx'),
        ),
        migrations.AddIndex(
            model_name='starredmessage',
            index=models.Index(fields=['user', 'organization', 'assistant', 'chat', 'sender_type'], name='starred_mes_user_id_3cf879_idx'),
        ),
        migrations.AddIndex(
            model_name='starredmessage',
            index=models.Index(fields=['user', 'organization', 'assistant', 'chat', 'sender_type', 'starred_at'], name='starred_mes_user_id_12657a_idx'),
        ),
        migrations.AddIndex(
            model_name='starredmessage',
            index=models.Index(fields=['user', 'organization', 'assistant', 'chat', 'sender_type', 'chat_message'], name='starred_mes_user_id_f233b1_idx'),
        ),
        migrations.AddIndex(
            model_name='starredmessage',
            index=models.Index(fields=['user', 'organization', 'assistant', 'chat', 'chat_message', 'starred_at'], name='starred_mes_user_id_67bf31_idx'),
        ),
        migrations.AddIndex(
            model_name='starredmessage',
            index=models.Index(fields=['user', 'organization', 'assistant', 'chat', 'chat_message', 'sender_type'], name='starred_mes_user_id_6149c7_idx'),
        ),
        migrations.AddIndex(
            model_name='starredmessage',
            index=models.Index(fields=['user', 'organization', 'assistant', 'chat', 'chat_message', 'sender_type', 'starred_at'], name='starred_mes_user_id_7fda96_idx'),
        ),
    ]
