# Generated by Django 5.0.6 on 2024-07-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starred_messages', '0004_alter_starredmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='starredmessage',
            name='message_file_urls',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='starredmessage',
            name='message_image_urls',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
