# Generated by Django 5.1.1 on 2024-09-19 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm_core', '0002_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeanAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True, default='')),
                ('time_awareness', models.BooleanField(default=True)),
                ('place_awareness', models.BooleanField(default=True)),
                ('lean_assistant_image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='lean_assistant_images/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lean_assistants_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lean_assistants_updated_by_user', to=settings.AUTH_USER_MODEL)),
                ('llm_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lean_assistants', to='llm_core.llmcore')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lean_assistants', to='organization.organization')),
            ],
            options={
                'verbose_name': 'LeanAssistant',
                'verbose_name_plural': 'LeanAssistants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization'], name='leanmod_lea_organiz_4e25d8_idx'), models.Index(fields=['llm_model'], name='leanmod_lea_llm_mod_e9b65d_idx'), models.Index(fields=['name'], name='leanmod_lea_name_a02533_idx'), models.Index(fields=['created_by_user'], name='leanmod_lea_created_14d7e8_idx'), models.Index(fields=['last_updated_by_user'], name='leanmod_lea_last_up_c45996_idx'), models.Index(fields=['created_at'], name='leanmod_lea_created_1df6f5_idx'), models.Index(fields=['updated_at'], name='leanmod_lea_updated_ad0af9_idx'), models.Index(fields=['organization', 'llm_model'], name='leanmod_lea_organiz_6d83b3_idx'), models.Index(fields=['organization', 'name'], name='leanmod_lea_organiz_6931e8_idx'), models.Index(fields=['organization', 'created_by_user'], name='leanmod_lea_organiz_44919f_idx'), models.Index(fields=['organization', 'last_updated_by_user'], name='leanmod_lea_organiz_f8989b_idx'), models.Index(fields=['organization', 'created_at'], name='leanmod_lea_organiz_0fa6a6_idx'), models.Index(fields=['organization', 'updated_at'], name='leanmod_lea_organiz_997980_idx'), models.Index(fields=['llm_model', 'name'], name='leanmod_lea_llm_mod_7b9364_idx'), models.Index(fields=['llm_model', 'created_by_user'], name='leanmod_lea_llm_mod_e476e2_idx'), models.Index(fields=['llm_model', 'last_updated_by_user'], name='leanmod_lea_llm_mod_f3e856_idx'), models.Index(fields=['llm_model', 'created_at'], name='leanmod_lea_llm_mod_23abea_idx'), models.Index(fields=['llm_model', 'updated_at'], name='leanmod_lea_llm_mod_da9b22_idx'), models.Index(fields=['created_by_user', 'created_at'], name='leanmod_lea_created_c599f3_idx'), models.Index(fields=['created_by_user', 'updated_at'], name='leanmod_lea_created_43342d_idx'), models.Index(fields=['last_updated_by_user', 'created_at'], name='leanmod_lea_last_up_377e91_idx'), models.Index(fields=['last_updated_by_user', 'updated_at'], name='leanmod_lea_last_up_a40c25_idx'), models.Index(fields=['organization', 'llm_model', 'name'], name='leanmod_lea_organiz_accb7f_idx'), models.Index(fields=['organization', 'llm_model', 'created_by_user'], name='leanmod_lea_organiz_038ce1_idx'), models.Index(fields=['organization', 'llm_model', 'last_updated_by_user'], name='leanmod_lea_organiz_55d9ba_idx'), models.Index(fields=['organization', 'llm_model', 'created_at'], name='leanmod_lea_organiz_623193_idx'), models.Index(fields=['organization', 'llm_model', 'updated_at'], name='leanmod_lea_organiz_51c69f_idx'), models.Index(fields=['organization', 'name', 'created_at'], name='leanmod_lea_organiz_ff26a2_idx'), models.Index(fields=['organization', 'name', 'updated_at'], name='leanmod_lea_organiz_030496_idx'), models.Index(fields=['organization', 'created_by_user', 'created_at'], name='leanmod_lea_organiz_4aaae4_idx'), models.Index(fields=['organization', 'created_by_user', 'updated_at'], name='leanmod_lea_organiz_4d58e0_idx'), models.Index(fields=['organization', 'last_updated_by_user', 'created_at'], name='leanmod_lea_organiz_aee24f_idx'), models.Index(fields=['organization', 'last_updated_by_user', 'updated_at'], name='leanmod_lea_organiz_abac1d_idx'), models.Index(fields=['llm_model', 'name', 'created_at'], name='leanmod_lea_llm_mod_ab7077_idx'), models.Index(fields=['llm_model', 'name', 'updated_at'], name='leanmod_lea_llm_mod_6478af_idx'), models.Index(fields=['llm_model', 'created_by_user', 'created_at'], name='leanmod_lea_llm_mod_b81a57_idx'), models.Index(fields=['llm_model', 'created_by_user', 'updated_at'], name='leanmod_lea_llm_mod_50148c_idx'), models.Index(fields=['llm_model', 'last_updated_by_user', 'created_at'], name='leanmod_lea_llm_mod_854f8b_idx'), models.Index(fields=['llm_model', 'last_updated_by_user', 'updated_at'], name='leanmod_lea_llm_mod_41833f_idx'), models.Index(fields=['created_by_user', 'created_at', 'updated_at'], name='leanmod_lea_created_024575_idx'), models.Index(fields=['last_updated_by_user', 'created_at', 'updated_at'], name='leanmod_lea_last_up_37af2c_idx'), models.Index(fields=['organization', 'llm_model', 'name', 'created_at'], name='leanmod_lea_organiz_84b773_idx'), models.Index(fields=['organization', 'llm_model', 'name', 'updated_at'], name='leanmod_lea_organiz_ed36d8_idx'), models.Index(fields=['organization', 'llm_model', 'created_by_user', 'created_at'], name='leanmod_lea_organiz_e88afe_idx'), models.Index(fields=['organization', 'llm_model', 'created_by_user', 'updated_at'], name='leanmod_lea_organiz_706be7_idx'), models.Index(fields=['organization', 'llm_model', 'last_updated_by_user', 'created_at'], name='leanmod_lea_organiz_16dc3b_idx'), models.Index(fields=['organization', 'llm_model', 'last_updated_by_user', 'updated_at'], name='leanmod_lea_organiz_c02991_idx'), models.Index(fields=['organization', 'name', 'created_at', 'updated_at'], name='leanmod_lea_organiz_db440d_idx'), models.Index(fields=['organization', 'created_by_user', 'created_at', 'updated_at'], name='leanmod_lea_organiz_950361_idx'), models.Index(fields=['organization', 'last_updated_by_user', 'created_at', 'updated_at'], name='leanmod_lea_organiz_98cad7_idx'), models.Index(fields=['llm_model', 'name', 'created_at', 'updated_at'], name='leanmod_lea_llm_mod_fbb5a3_idx'), models.Index(fields=['llm_model', 'created_by_user', 'created_at', 'updated_at'], name='leanmod_lea_llm_mod_9e25cd_idx'), models.Index(fields=['llm_model', 'last_updated_by_user', 'created_at', 'updated_at'], name='leanmod_lea_llm_mod_326e91_idx')],
            },
        ),
    ]
