# Generated by Django 5.1.1 on 2024-09-25 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertNetworkAssistantReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_instructions', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expert Network Assistant Reference',
                'verbose_name_plural': 'Expert Network Assistant References',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeanAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True, default='')),
                ('lean_assistant_image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='lean_assistant_images/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lean Assistant',
                'verbose_name_plural': 'Lean Assistants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpertNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_networks_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_networks_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expert Network',
                'verbose_name_plural': 'Expert Networks',
                'ordering': ['-created_at'],
            },
        ),
    ]
