# Generated by Django 5.1.1 on 2024-09-19 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leanmod', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leanassistant',
            name='place_awareness',
        ),
        migrations.RemoveField(
            model_name='leanassistant',
            name='time_awareness',
        ),
    ]
