# Generated by Django 5.1.1 on 2024-09-23 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0004_initial'),
        ('leanmod', '0001_initial'),
        ('llm_core', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expertnetwork',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_networks', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='expertnetworkassistantreference',
            name='assistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant'),
        ),
        migrations.AddField(
            model_name='expertnetworkassistantreference',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_network_assistant_references_created_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expertnetworkassistantreference',
            name='last_updated_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_network_assistant_references_updated_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expertnetworkassistantreference',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leanmod.expertnetwork'),
        ),
        migrations.AddField(
            model_name='expertnetwork',
            name='assistant_references',
            field=models.ManyToManyField(related_name='networks', to='leanmod.expertnetworkassistantreference'),
        ),
        migrations.AddField(
            model_name='leanassistant',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lean_assistants_created_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leanassistant',
            name='expert_networks',
            field=models.ManyToManyField(blank=True, related_name='lean_assistants', to='leanmod.expertnetwork'),
        ),
        migrations.AddField(
            model_name='leanassistant',
            name='last_updated_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lean_assistants_updated_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leanassistant',
            name='llm_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lean_assistants', to='llm_core.llmcore'),
        ),
        migrations.AddField(
            model_name='leanassistant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lean_assistants', to='organization.organization'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network'], name='leanmod_exp_network_b302fd_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['assistant'], name='leanmod_exp_assista_0c5e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['context_instructions'], name='leanmod_exp_context_902a5e_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['created_by_user'], name='leanmod_exp_created_9959b1_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['last_updated_by_user'], name='leanmod_exp_last_up_1d3eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['created_at'], name='leanmod_exp_created_27fe7e_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['updated_at'], name='leanmod_exp_updated_6ef62f_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'assistant'], name='leanmod_exp_network_3cfcab_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'context_instructions'], name='leanmod_exp_network_c3c884_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'created_by_user'], name='leanmod_exp_network_b349f6_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'last_updated_by_user'], name='leanmod_exp_network_ca0db7_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'created_at'], name='leanmod_exp_network_b667dc_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'updated_at'], name='leanmod_exp_network_f5c6a5_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['assistant', 'context_instructions'], name='leanmod_exp_assista_1705bf_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['assistant', 'created_by_user'], name='leanmod_exp_assista_7535bb_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['assistant', 'last_updated_by_user'], name='leanmod_exp_assista_476367_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['assistant', 'created_at'], name='leanmod_exp_assista_ab3cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['assistant', 'updated_at'], name='leanmod_exp_assista_f2ed61_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['created_by_user', 'created_at'], name='leanmod_exp_created_572b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['created_by_user', 'updated_at'], name='leanmod_exp_created_ccf2d0_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['last_updated_by_user', 'created_at'], name='leanmod_exp_last_up_dd7788_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['last_updated_by_user', 'updated_at'], name='leanmod_exp_last_up_3254a4_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'assistant', 'context_instructions'], name='leanmod_exp_network_33e724_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'assistant', 'created_by_user'], name='leanmod_exp_network_a99b87_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'assistant', 'last_updated_by_user'], name='leanmod_exp_network_1d4a77_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'assistant', 'created_at'], name='leanmod_exp_network_4f9209_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'assistant', 'updated_at'], name='leanmod_exp_network_a3de6c_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'context_instructions', 'created_at'], name='leanmod_exp_network_33111b_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'context_instructions', 'updated_at'], name='leanmod_exp_network_959a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'created_by_user', 'created_at'], name='leanmod_exp_network_2b1cff_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'created_by_user', 'updated_at'], name='leanmod_exp_network_c7da1b_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'last_updated_by_user', 'created_at'], name='leanmod_exp_network_634183_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'last_updated_by_user', 'updated_at'], name='leanmod_exp_network_e91fa5_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['assistant', 'context_instructions', 'created_at'], name='leanmod_exp_assista_0cba44_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['assistant', 'context_instructions', 'updated_at'], name='leanmod_exp_assista_6a7eba_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['assistant', 'created_by_user', 'created_at'], name='leanmod_exp_assista_29c1a9_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['assistant', 'created_by_user', 'updated_at'], name='leanmod_exp_assista_bf9080_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['assistant', 'last_updated_by_user', 'created_at'], name='leanmod_exp_assista_fd7d28_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['assistant', 'last_updated_by_user', 'updated_at'], name='leanmod_exp_assista_e27b48_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['created_by_user', 'created_at', 'updated_at'], name='leanmod_exp_created_063c44_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['last_updated_by_user', 'created_at', 'updated_at'], name='leanmod_exp_last_up_f84bda_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['name'], name='leanmod_exp_name_d0a12b_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['created_by_user'], name='leanmod_exp_created_f08db6_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['last_updated_by_user'], name='leanmod_exp_last_up_be9d40_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['created_at'], name='leanmod_exp_created_546904_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['updated_at'], name='leanmod_exp_updated_e50b28_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['name', 'created_at'], name='leanmod_exp_name_675094_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['name', 'updated_at'], name='leanmod_exp_name_b4c49a_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['created_by_user', 'created_at'], name='leanmod_exp_created_9b607d_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['created_by_user', 'updated_at'], name='leanmod_exp_created_846bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['last_updated_by_user', 'created_at'], name='leanmod_exp_last_up_cec75e_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['last_updated_by_user', 'updated_at'], name='leanmod_exp_last_up_fe3b66_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['name', 'created_by_user', 'created_at'], name='leanmod_exp_name_3be2b0_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['name', 'created_by_user', 'updated_at'], name='leanmod_exp_name_bbb555_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['name', 'last_updated_by_user', 'created_at'], name='leanmod_exp_name_eb0f61_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['name', 'last_updated_by_user', 'updated_at'], name='leanmod_exp_name_789afc_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['created_by_user', 'created_at', 'updated_at'], name='leanmod_exp_created_28d3f2_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['last_updated_by_user', 'created_at', 'updated_at'], name='leanmod_exp_last_up_384067_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['name', 'created_by_user', 'created_at', 'updated_at'], name='leanmod_exp_name_8f9b78_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['name', 'last_updated_by_user', 'created_at', 'updated_at'], name='leanmod_exp_name_d08d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['organization'], name='leanmod_lea_organiz_4e25d8_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['llm_model'], name='leanmod_lea_llm_mod_e9b65d_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['name'], name='leanmod_lea_name_a02533_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['created_by_user'], name='leanmod_lea_created_14d7e8_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['last_updated_by_user'], name='leanmod_lea_last_up_c45996_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['created_at'], name='leanmod_lea_created_1df6f5_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['updated_at'], name='leanmod_lea_updated_ad0af9_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['organization', 'llm_model'], name='leanmod_lea_organiz_6d83b3_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['organization', 'name'], name='leanmod_lea_organiz_6931e8_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['organization', 'created_by_user'], name='leanmod_lea_organiz_44919f_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['organization', 'last_updated_by_user'], name='leanmod_lea_organiz_f8989b_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['organization', 'created_at'], name='leanmod_lea_organiz_0fa6a6_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['organization', 'updated_at'], name='leanmod_lea_organiz_997980_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['llm_model', 'name'], name='leanmod_lea_llm_mod_7b9364_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['llm_model', 'created_by_user'], name='leanmod_lea_llm_mod_e476e2_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['llm_model', 'last_updated_by_user'], name='leanmod_lea_llm_mod_f3e856_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['llm_model', 'created_at'], name='leanmod_lea_llm_mod_23abea_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['llm_model', 'updated_at'], name='leanmod_lea_llm_mod_da9b22_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['created_by_user', 'created_at'], name='leanmod_lea_created_c599f3_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['created_by_user', 'updated_at'], name='leanmod_lea_created_43342d_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['last_updated_by_user', 'created_at'], name='leanmod_lea_last_up_377e91_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['last_updated_by_user', 'updated_at'], name='leanmod_lea_last_up_a40c25_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['organization', 'llm_model', 'name'], name='leanmod_lea_organiz_accb7f_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['organization', 'llm_model', 'created_by_user'], name='leanmod_lea_organiz_038ce1_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['organization', 'llm_model', 'last_updated_by_user'], name='leanmod_lea_organiz_55d9ba_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['organization', 'llm_model', 'created_at'], name='leanmod_lea_organiz_623193_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['organization', 'llm_model', 'updated_at'], name='leanmod_lea_organiz_51c69f_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['organization', 'name', 'created_at'], name='leanmod_lea_organiz_ff26a2_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['organization', 'name', 'updated_at'], name='leanmod_lea_organiz_030496_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['organization', 'created_by_user', 'created_at'], name='leanmod_lea_organiz_4aaae4_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['organization', 'created_by_user', 'updated_at'], name='leanmod_lea_organiz_4d58e0_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['organization', 'last_updated_by_user', 'created_at'], name='leanmod_lea_organiz_aee24f_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['organization', 'last_updated_by_user', 'updated_at'], name='leanmod_lea_organiz_abac1d_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['llm_model', 'name', 'created_at'], name='leanmod_lea_llm_mod_ab7077_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['llm_model', 'name', 'updated_at'], name='leanmod_lea_llm_mod_6478af_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['llm_model', 'created_by_user', 'created_at'], name='leanmod_lea_llm_mod_b81a57_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['llm_model', 'created_by_user', 'updated_at'], name='leanmod_lea_llm_mod_50148c_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['llm_model', 'last_updated_by_user', 'created_at'], name='leanmod_lea_llm_mod_854f8b_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['llm_model', 'last_updated_by_user', 'updated_at'], name='leanmod_lea_llm_mod_41833f_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['created_by_user', 'created_at', 'updated_at'], name='leanmod_lea_created_024575_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['last_updated_by_user', 'created_at', 'updated_at'], name='leanmod_lea_last_up_37af2c_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['organization', 'llm_model', 'name', 'created_at'], name='leanmod_lea_organiz_84b773_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['organization', 'llm_model', 'name', 'updated_at'], name='leanmod_lea_organiz_ed36d8_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['organization', 'llm_model', 'created_by_user', 'created_at'], name='leanmod_lea_organiz_e88afe_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['organization', 'llm_model', 'created_by_user', 'updated_at'], name='leanmod_lea_organiz_706be7_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['organization', 'llm_model', 'last_updated_by_user', 'created_at'], name='leanmod_lea_organiz_16dc3b_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['organization', 'llm_model', 'last_updated_by_user', 'updated_at'], name='leanmod_lea_organiz_c02991_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['organization', 'name', 'created_at', 'updated_at'], name='leanmod_lea_organiz_db440d_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['organization', 'created_by_user', 'created_at', 'updated_at'], name='leanmod_lea_organiz_950361_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['organization', 'last_updated_by_user', 'created_at', 'updated_at'], name='leanmod_lea_organiz_98cad7_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['llm_model', 'name', 'created_at', 'updated_at'], name='leanmod_lea_llm_mod_fbb5a3_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['llm_model', 'created_by_user', 'created_at', 'updated_at'], name='leanmod_lea_llm_mod_9e25cd_idx'),
        ),
        migrations.AddIndex(
            model_name='leanassistant',
            index=models.Index(fields=['llm_model', 'last_updated_by_user', 'created_at', 'updated_at'], name='leanmod_lea_llm_mod_326e91_idx'),
        ),
    ]
