# Generated by Django 5.0.8 on 2024-11-17 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leanmod', '0002_initial'),
        ('multimodal_chat', '0005_remove_multimodalchat_context_memory_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='leanassistant',
            name='context_overflow_strategy',
            field=models.CharField(choices=[('stop', 'Stop Conversation'), ('forget', 'Forget Oldest Messages'), ('vectorize', 'Vectorize Oldest Messages')], default='forget', max_length=100),
        ),
        migrations.CreateModel(
            name='LeanModOldChatMessagesVectorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('raw_data_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('vector_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leanmod_chat_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leanmod_chat_message_vector_data', to='multimodal_chat.multimodalleanchatmessage')),
            ],
            options={
                'verbose_name': 'LeanMod Old Chat Messages Vector Data',
                'verbose_name_plural': 'LeanMod Old Chat Messages Vector Datas',
                'indexes': [models.Index(fields=['leanmod_chat_message'], name='leanmod_lea_leanmod_dda0b6_idx'), models.Index(fields=['created_at'], name='leanmod_lea_created_db6ca7_idx'), models.Index(fields=['updated_at'], name='leanmod_lea_updated_a22bab_idx')],
            },
        ),
    ]
