# Generated by Django 5.1.1 on 2024-09-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leanmod', '0003_expertnetwork_expertnetworkassistantreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leanassistant',
            name='expert_networks',
            field=models.ManyToManyField(related_name='lean_assistants', to='leanmod.expertnetwork'),
        ),
    ]
