# Generated by Django 5.0.8 on 2024-11-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leanmod', '0003_leanassistant_context_overflow_strategy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leanassistant',
            name='max_context_messages',
            field=models.IntegerField(default=25),
        ),
    ]
