# Generated by Django 5.1.1 on 2024-09-19 02:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0004_initial'),
        ('leanmod', '0004_leanassistant_expert_networks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertnetwork',
            options={'ordering': ['-created_at'], 'verbose_name': 'ExpertNetwork', 'verbose_name_plural': 'ExpertNetworks'},
        ),
        migrations.AlterModelOptions(
            name='expertnetworkassistantreference',
            options={'ordering': ['-created_at'], 'verbose_name': 'ExpertNetworkAssistantReference', 'verbose_name_plural': 'ExpertNetworkAssistantReferences'},
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['name'], name='leanmod_exp_name_d0a12b_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['created_by_user'], name='leanmod_exp_created_f08db6_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['last_updated_by_user'], name='leanmod_exp_last_up_be9d40_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['created_at'], name='leanmod_exp_created_546904_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['updated_at'], name='leanmod_exp_updated_e50b28_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['name', 'created_at'], name='leanmod_exp_name_675094_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['name', 'updated_at'], name='leanmod_exp_name_b4c49a_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['created_by_user', 'created_at'], name='leanmod_exp_created_9b607d_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['created_by_user', 'updated_at'], name='leanmod_exp_created_846bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['last_updated_by_user', 'created_at'], name='leanmod_exp_last_up_cec75e_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['last_updated_by_user', 'updated_at'], name='leanmod_exp_last_up_fe3b66_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['name', 'created_by_user', 'created_at'], name='leanmod_exp_name_3be2b0_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['name', 'created_by_user', 'updated_at'], name='leanmod_exp_name_bbb555_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['name', 'last_updated_by_user', 'created_at'], name='leanmod_exp_name_eb0f61_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['name', 'last_updated_by_user', 'updated_at'], name='leanmod_exp_name_789afc_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['created_by_user', 'created_at', 'updated_at'], name='leanmod_exp_created_28d3f2_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['last_updated_by_user', 'created_at', 'updated_at'], name='leanmod_exp_last_up_384067_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['name', 'created_by_user', 'created_at', 'updated_at'], name='leanmod_exp_name_8f9b78_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetwork',
            index=models.Index(fields=['name', 'last_updated_by_user', 'created_at', 'updated_at'], name='leanmod_exp_name_d08d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network'], name='leanmod_exp_network_b302fd_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['assistant'], name='leanmod_exp_assista_0c5e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['context_instructions'], name='leanmod_exp_context_902a5e_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['created_by_user'], name='leanmod_exp_created_9959b1_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['last_updated_by_user'], name='leanmod_exp_last_up_1d3eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['created_at'], name='leanmod_exp_created_27fe7e_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['updated_at'], name='leanmod_exp_updated_6ef62f_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'assistant'], name='leanmod_exp_network_3cfcab_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'context_instructions'], name='leanmod_exp_network_c3c884_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'created_by_user'], name='leanmod_exp_network_b349f6_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'last_updated_by_user'], name='leanmod_exp_network_ca0db7_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'created_at'], name='leanmod_exp_network_b667dc_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'updated_at'], name='leanmod_exp_network_f5c6a5_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['assistant', 'context_instructions'], name='leanmod_exp_assista_1705bf_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['assistant', 'created_by_user'], name='leanmod_exp_assista_7535bb_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['assistant', 'last_updated_by_user'], name='leanmod_exp_assista_476367_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['assistant', 'created_at'], name='leanmod_exp_assista_ab3cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['assistant', 'updated_at'], name='leanmod_exp_assista_f2ed61_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['created_by_user', 'created_at'], name='leanmod_exp_created_572b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['created_by_user', 'updated_at'], name='leanmod_exp_created_ccf2d0_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['last_updated_by_user', 'created_at'], name='leanmod_exp_last_up_dd7788_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['last_updated_by_user', 'updated_at'], name='leanmod_exp_last_up_3254a4_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'assistant', 'context_instructions'], name='leanmod_exp_network_33e724_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'assistant', 'created_by_user'], name='leanmod_exp_network_a99b87_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'assistant', 'last_updated_by_user'], name='leanmod_exp_network_1d4a77_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'assistant', 'created_at'], name='leanmod_exp_network_4f9209_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'assistant', 'updated_at'], name='leanmod_exp_network_a3de6c_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'context_instructions', 'created_at'], name='leanmod_exp_network_33111b_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'context_instructions', 'updated_at'], name='leanmod_exp_network_959a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'created_by_user', 'created_at'], name='leanmod_exp_network_2b1cff_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'created_by_user', 'updated_at'], name='leanmod_exp_network_c7da1b_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'last_updated_by_user', 'created_at'], name='leanmod_exp_network_634183_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['network', 'last_updated_by_user', 'updated_at'], name='leanmod_exp_network_e91fa5_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['assistant', 'context_instructions', 'created_at'], name='leanmod_exp_assista_0cba44_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['assistant', 'context_instructions', 'updated_at'], name='leanmod_exp_assista_6a7eba_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['assistant', 'created_by_user', 'created_at'], name='leanmod_exp_assista_29c1a9_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['assistant', 'created_by_user', 'updated_at'], name='leanmod_exp_assista_bf9080_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['assistant', 'last_updated_by_user', 'created_at'], name='leanmod_exp_assista_fd7d28_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['assistant', 'last_updated_by_user', 'updated_at'], name='leanmod_exp_assista_e27b48_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['created_by_user', 'created_at', 'updated_at'], name='leanmod_exp_created_063c44_idx'),
        ),
        migrations.AddIndex(
            model_name='expertnetworkassistantreference',
            index=models.Index(fields=['last_updated_by_user', 'created_at', 'updated_at'], name='leanmod_exp_last_up_f84bda_idx'),
        ),
    ]
