# Generated by Django 5.0.8 on 2024-11-25 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leanmod', '0004_leanassistant_max_context_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertnetworkassistantreference',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_references', to='leanmod.expertnetwork'),
        ),
    ]
