# Generated by Django 5.0.8 on 2024-12-01 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leanmod', '0005_alter_expertnetworkassistantreference_network'),
        ('organization', '0005_alter_organization_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expertnetwork',
            unique_together={('organization', 'name')},
        ),
    ]
