# Generated by Django 5.1.1 on 2024-09-19 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leanmod', '0005_alter_expertnetwork_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertnetwork',
            options={'ordering': ['-created_at'], 'verbose_name': 'Expert Network', 'verbose_name_plural': 'Expert Networks'},
        ),
        migrations.AlterModelOptions(
            name='expertnetworkassistantreference',
            options={'ordering': ['-created_at'], 'verbose_name': 'Expert Network Assistant Reference', 'verbose_name_plural': 'Expert Network Assistant References'},
        ),
        migrations.AlterModelOptions(
            name='leanassistant',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lean Assistant', 'verbose_name_plural': 'Lean Assistants'},
        ),
    ]
