# Generated by Django 5.0.8 on 2024-12-01 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0013_alter_assistantoldchatmessagesvectordata_unique_together'),
        ('leanmod', '0006_alter_expertnetwork_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expertnetworkassistantreference',
            unique_together={('network', 'assistant')},
        ),
    ]
