# Generated by Django 5.1.1 on 2024-09-21 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leanmod', '0006_alter_expertnetwork_options_and_more'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertnetwork',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_networks', to='organization.organization'),
        ),
    ]
