# Generated by Django 5.1.1 on 2024-09-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leanmod', '0007_expertnetwork_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leanassistant',
            name='expert_networks',
            field=models.ManyToManyField(blank=True, related_name='lean_assistants', to='leanmod.expertnetwork'),
        ),
    ]
