# Generated by Django 5.0.8 on 2024-12-01 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leanmod', '0007_alter_expertnetworkassistantreference_unique_together'),
        ('organization', '0005_alter_organization_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leanassistant',
            unique_together={('organization', 'name')},
        ),
    ]
