# Generated by Django 5.1.1 on 2024-09-24 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leanmod', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportLeanmodAssistantAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('request_limit_per_hour', models.IntegerField(default=1000)),
                ('is_online', models.BooleanField(default=True)),
                ('custom_api_key', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('endpoint', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_lean_assistants_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('lean_assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leanmod.leanassistant')),
            ],
            options={
                'verbose_name': 'Export LeanMod Assistant API',
                'verbose_name_plural': 'Export LeanMod Assistant APIs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeanmodRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('export_lean_assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='export_leanmods.exportleanmodassistantapi')),
            ],
            options={
                'verbose_name': 'Request LeanMod Log',
                'verbose_name_plural': 'Request LeanMod Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='exportleanmodassistantapi',
            index=models.Index(fields=['lean_assistant'], name='export_lean_lean_as_42d9ff_idx'),
        ),
        migrations.AddIndex(
            model_name='exportleanmodassistantapi',
            index=models.Index(fields=['created_by_user'], name='export_lean_created_c22b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='exportleanmodassistantapi',
            index=models.Index(fields=['created_at'], name='export_lean_created_ca2aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='exportleanmodassistantapi',
            index=models.Index(fields=['updated_at'], name='export_lean_updated_52f736_idx'),
        ),
        migrations.AddIndex(
            model_name='exportleanmodassistantapi',
            index=models.Index(fields=['lean_assistant', 'created_at'], name='export_lean_lean_as_67e33a_idx'),
        ),
        migrations.AddIndex(
            model_name='exportleanmodassistantapi',
            index=models.Index(fields=['lean_assistant', 'updated_at'], name='export_lean_lean_as_c4561c_idx'),
        ),
        migrations.AddIndex(
            model_name='exportleanmodassistantapi',
            index=models.Index(fields=['lean_assistant', 'created_by_user'], name='export_lean_lean_as_ac8842_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodrequestlog',
            index=models.Index(fields=['export_lean_assistant'], name='export_lean_export__19e9cf_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodrequestlog',
            index=models.Index(fields=['timestamp'], name='export_lean_timesta_6dddae_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodrequestlog',
            index=models.Index(fields=['export_lean_assistant', 'timestamp'], name='export_lean_export__b79862_idx'),
        ),
    ]
