# Generated by Django 5.1.1 on 2024-09-25 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('export_leanmods', '0001_initial'),
        ('leanmod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportleanmodassistantapi',
            name='lean_assistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exported_leanmods', to='leanmod.leanassistant'),
        ),
    ]
