#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Jupi.tr™
#  File: 0002_initial.py
#  Last Modified: 2024-09-25 17:51:06
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 01:36:39
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@jupi.tr.
#

# Generated by Django 5.1.1 on 2024-09-25 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('export_leanmods', '0001_initial'),
        ('leanmod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportleanmodassistantapi',
            name='lean_assistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exported_leanmods', to='leanmod.leanassistant'),
        ),
    ]
