#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Bimod.io™
#  File: 0003_initial.py
#  Last Modified: 2024-10-05 01:39:48
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 14:42:42
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@Bimod.io.
#
#
#

# Generated by Django 5.1.1 on 2024-09-25 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('export_leanmods', '0002_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportleanmodassistantapi',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exported_leanmods', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='leanmodrequestlog',
            name='export_lean_assistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='export_leanmods.exportleanmodassistantapi'),
        ),
        migrations.AddIndex(
            model_name='exportleanmodassistantapi',
            index=models.Index(fields=['lean_assistant'], name='export_lean_lean_as_42d9ff_idx'),
        ),
        migrations.AddIndex(
            model_name='exportleanmodassistantapi',
            index=models.Index(fields=['created_by_user'], name='export_lean_created_c22b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='exportleanmodassistantapi',
            index=models.Index(fields=['created_at'], name='export_lean_created_ca2aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='exportleanmodassistantapi',
            index=models.Index(fields=['updated_at'], name='export_lean_updated_52f736_idx'),
        ),
        migrations.AddIndex(
            model_name='exportleanmodassistantapi',
            index=models.Index(fields=['lean_assistant', 'created_at'], name='export_lean_lean_as_67e33a_idx'),
        ),
        migrations.AddIndex(
            model_name='exportleanmodassistantapi',
            index=models.Index(fields=['lean_assistant', 'updated_at'], name='export_lean_lean_as_c4561c_idx'),
        ),
        migrations.AddIndex(
            model_name='exportleanmodassistantapi',
            index=models.Index(fields=['lean_assistant', 'created_by_user'], name='export_lean_lean_as_ac8842_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodrequestlog',
            index=models.Index(fields=['export_lean_assistant'], name='export_lean_export__19e9cf_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodrequestlog',
            index=models.Index(fields=['timestamp'], name='export_lean_timesta_6dddae_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodrequestlog',
            index=models.Index(fields=['export_lean_assistant', 'timestamp'], name='export_lean_export__b79862_idx'),
        ),
    ]
