# Generated by Django 5.0.8 on 2024-12-01 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export_leanmods', '0003_initial'),
        ('leanmod', '0005_alter_expertnetworkassistantreference_network'),
        ('organization', '0005_alter_organization_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exportleanmodassistantapi',
            unique_together={('organization', 'lean_assistant', 'is_public')},
        ),
    ]
