
GRANT ALL PRIVILEGES ON DATABASE bimod_dev TO admin_dev;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO admin_dev;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO admin_dev;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO admin_dev;
ALTER USER admin_dev WITH SUPERUSER;
ALTER USER admin_dev WITH CREATEDB CREATEROLE;


GRANT ALL PRIVILEGES ON DATABASE bimod_prod TO admin_prod;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO admin_prod;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO admin_prod;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO admin_prod;
ALTER USER admin_prod WITH SUPERUSER;
ALTER USER admin_prod WITH CREATEDB CREATEROLE;
