#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Jupi.tr™
#  File: 0001_initial.py
#  Last Modified: 2024-09-25 17:51:06
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 01:36:42
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@jupi.tr.
#

# Generated by Django 5.1.1 on 2024-09-25 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0003_initial'),
        ('datasource_knowledge_base', '0001_initial'),
        ('leanmod', '0002_initial'),
        ('llm_transaction', '0002_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultimodalChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('chat_source', models.CharField(choices=[('app', 'Application'), ('api', 'API'), ('scheduled', 'Scheduled'), ('orchestration', 'Orchestration')], default='app', max_length=100)),
                ('assistant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_chats', to='assistants.assistant')),
                ('context_memory_connection', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_chat', to='datasource_knowledge_base.contexthistoryknowledgebaseconnection')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_chats_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('transactions', models.ManyToManyField(blank=True, related_name='multimodal_chats', to='llm_transaction.llmtransaction')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Multimodal Chat',
                'verbose_name_plural': 'Multimodal Chats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MultimodalChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'System'), ('TOOL', 'Tool')], max_length=10)),
                ('message_text_content', models.TextField()),
                ('message_json_content', models.JSONField(blank=True, default=dict, null=True)),
                ('message_image_contents', models.JSONField(blank=True, default=list, null=True)),
                ('message_file_contents', models.JSONField(blank=True, default=list, null=True)),
                ('message_audio', models.URLField(blank=True, max_length=10000, null=True)),
                ('starred', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('multimodal_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='multimodal_chat.multimodalchat')),
            ],
            options={
                'verbose_name': 'Multimodal Chat Message',
                'verbose_name_plural': 'Multimodal Chat Messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MultimodalLeanChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('chat_source', models.CharField(choices=[('app', 'Application'), ('api', 'API'), ('scheduled', 'Scheduled'), ('orchestration', 'Orchestration')], default='app', max_length=100)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_lean_chats_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('lean_assistant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_lean_chats', to='leanmod.leanassistant')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('transactions', models.ManyToManyField(blank=True, related_name='multimodal_lean_chats', to='llm_transaction.llmtransaction')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_lean_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Multimodal Lean Chat',
                'verbose_name_plural': 'Multimodal Lean Chats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MultimodalLeanChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'System'), ('TOOL', 'Tool')], max_length=10)),
                ('message_text_content', models.TextField()),
                ('message_json_content', models.JSONField(blank=True, default=dict, null=True)),
                ('message_image_contents', models.JSONField(blank=True, default=list, null=True)),
                ('message_file_contents', models.JSONField(blank=True, default=list, null=True)),
                ('message_audio', models.URLField(blank=True, max_length=10000, null=True)),
                ('starred', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('multimodal_lean_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lean_chat_messages', to='multimodal_chat.multimodalleanchat')),
            ],
            options={
                'verbose_name': 'Multimodal Lean Chat Message',
                'verbose_name_plural': 'Multimodal Lean Chat Messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatCreationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'verbose_name': 'Chat Creation Log',
                'verbose_name_plural': 'Chat Creation Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='multimodal__created_140f3d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessageCreationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'verbose_name': 'Chat Message Creation Log',
                'verbose_name_plural': 'Chat Message Creation Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='multimodal__created_43fdc7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id'], name='multimodal__id_ec6086_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization'], name='multimodal__organiz_c3c643_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant'], name='multimodal__assista_993c1a_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user'], name='multimodal__user_id_b5c7cb_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['chat_source'], name='multimodal__chat_so_fdba6a_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['is_archived'], name='multimodal__is_arch_be8c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['created_by_user'], name='multimodal__created_ffb632_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['created_at'], name='multimodal__created_ded54c_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['updated_at'], name='multimodal__updated_5cf47f_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization'], name='multimodal__id_1fa05b_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'assistant'], name='multimodal__id_7e2adf_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'user'], name='multimodal__id_4a3985_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'chat_source'], name='multimodal__id_ccd222_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'is_archived'], name='multimodal__id_a3b260_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'created_by_user'], name='multimodal__id_2fdae5_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'created_at'], name='multimodal__id_08626d_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'updated_at'], name='multimodal__id_9f39f2_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant'], name='multimodal__organiz_bf89f3_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'user'], name='multimodal__organiz_eb44e6_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'chat_source'], name='multimodal__organiz_bcb000_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'is_archived'], name='multimodal__organiz_a52ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'created_by_user'], name='multimodal__organiz_7f49d3_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'created_at'], name='multimodal__organiz_b032b1_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'updated_at'], name='multimodal__organiz_ba7e39_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'user'], name='multimodal__assista_fdfdba_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'chat_source'], name='multimodal__assista_d66098_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'is_archived'], name='multimodal__assista_308a32_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'created_by_user'], name='multimodal__assista_3515d3_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'created_at'], name='multimodal__assista_f8f884_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'updated_at'], name='multimodal__assista_676aab_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'chat_source'], name='multimodal__user_id_a97779_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'is_archived'], name='multimodal__user_id_ac6275_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'created_by_user'], name='multimodal__user_id_4db902_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'created_at'], name='multimodal__user_id_8a4f03_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'updated_at'], name='multimodal__user_id_f4ce11_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['chat_source', 'is_archived'], name='multimodal__chat_so_4f4145_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['chat_source', 'created_by_user'], name='multimodal__chat_so_1c191f_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['chat_source', 'created_at'], name='multimodal__chat_so_356e51_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['chat_source', 'updated_at'], name='multimodal__chat_so_3c0d6b_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['is_archived', 'created_by_user'], name='multimodal__is_arch_e49044_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['is_archived', 'created_at'], name='multimodal__is_arch_97c06e_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['is_archived', 'updated_at'], name='multimodal__is_arch_f82fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['created_by_user', 'created_at'], name='multimodal__created_1f58ca_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['created_by_user', 'updated_at'], name='multimodal__created_a5140d_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['created_at', 'updated_at'], name='multimodal__created_7fbb16_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization', 'assistant'], name='multimodal__id_e4c8df_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization', 'user'], name='multimodal__id_a721a0_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization', 'chat_source'], name='multimodal__id_f567f3_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization', 'is_archived'], name='multimodal__id_34b810_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization', 'created_by_user'], name='multimodal__id_406b27_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization', 'created_at'], name='multimodal__id_e40511_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization', 'updated_at'], name='multimodal__id_91cd35_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'assistant', 'user'], name='multimodal__id_534688_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'assistant', 'chat_source'], name='multimodal__id_d5fe33_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'assistant', 'is_archived'], name='multimodal__id_db4a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'assistant', 'created_by_user'], name='multimodal__id_375428_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'assistant', 'created_at'], name='multimodal__id_131e44_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'assistant', 'updated_at'], name='multimodal__id_0b7097_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'user', 'chat_source'], name='multimodal__id_e6a7ac_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'user', 'is_archived'], name='multimodal__id_f57dc9_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'user', 'created_by_user'], name='multimodal__id_f8308e_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'user', 'created_at'], name='multimodal__id_9153a3_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'user', 'updated_at'], name='multimodal__id_7cb42e_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'chat_source', 'is_archived'], name='multimodal__id_b1fdd9_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'chat_source', 'created_by_user'], name='multimodal__id_855604_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'chat_source', 'created_at'], name='multimodal__id_061f0a_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'chat_source', 'updated_at'], name='multimodal__id_6ed76b_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'is_archived', 'created_by_user'], name='multimodal__id_cd016b_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'is_archived', 'created_at'], name='multimodal__id_53b4cb_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'is_archived', 'updated_at'], name='multimodal__id_b04803_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'created_by_user', 'created_at'], name='multimodal__id_f07662_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'created_by_user', 'updated_at'], name='multimodal__id_5a8092_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'created_at', 'updated_at'], name='multimodal__id_d211a2_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'user'], name='multimodal__organiz_6d4d01_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'chat_source'], name='multimodal__organiz_281fdd_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'is_archived'], name='multimodal__organiz_e06ddb_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'created_by_user'], name='multimodal__organiz_5876e1_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'created_at'], name='multimodal__organiz_54e4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'updated_at'], name='multimodal__organiz_3605c9_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'user', 'chat_source'], name='multimodal__organiz_0f852a_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'user', 'is_archived'], name='multimodal__organiz_da9053_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'user', 'created_by_user'], name='multimodal__organiz_890196_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'user', 'created_at'], name='multimodal__organiz_1fdcaf_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'user', 'updated_at'], name='multimodal__organiz_5dfa09_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'chat_source', 'is_archived'], name='multimodal__organiz_ce86c8_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'chat_source', 'created_by_user'], name='multimodal__organiz_7f3b56_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'chat_source', 'created_at'], name='multimodal__organiz_8b11e2_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'chat_source', 'updated_at'], name='multimodal__organiz_6ba636_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'is_archived', 'created_by_user'], name='multimodal__organiz_855d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'is_archived', 'created_at'], name='multimodal__organiz_9a9318_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'is_archived', 'updated_at'], name='multimodal__organiz_fd76df_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'created_by_user', 'created_at'], name='multimodal__organiz_8d57c8_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'created_by_user', 'updated_at'], name='multimodal__organiz_26c1c5_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'created_at', 'updated_at'], name='multimodal__organiz_34a498_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'user', 'chat_source'], name='multimodal__assista_33fa4f_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'user', 'is_archived'], name='multimodal__assista_cea523_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'user', 'created_by_user'], name='multimodal__assista_d7582e_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'user', 'created_at'], name='multimodal__assista_38ccf8_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'user', 'updated_at'], name='multimodal__assista_1cdf03_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'chat_source', 'is_archived'], name='multimodal__assista_668945_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'chat_source', 'created_by_user'], name='multimodal__assista_e64e0c_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'chat_source', 'created_at'], name='multimodal__assista_3afece_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'chat_source', 'updated_at'], name='multimodal__assista_9b3bc5_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'is_archived', 'created_by_user'], name='multimodal__assista_726b0a_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'is_archived', 'created_at'], name='multimodal__assista_674606_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'is_archived', 'updated_at'], name='multimodal__assista_d88ace_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'created_by_user', 'created_at'], name='multimodal__assista_ede89b_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'created_by_user', 'updated_at'], name='multimodal__assista_052d4e_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'created_at', 'updated_at'], name='multimodal__assista_f26514_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'chat_source', 'is_archived'], name='multimodal__user_id_7b7c08_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'chat_source', 'created_by_user'], name='multimodal__user_id_a34a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'chat_source', 'created_at'], name='multimodal__user_id_ef9648_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'chat_source', 'updated_at'], name='multimodal__user_id_758ea6_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'is_archived', 'created_by_user'], name='multimodal__user_id_99df4f_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'is_archived', 'created_at'], name='multimodal__user_id_5d07bd_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'is_archived', 'updated_at'], name='multimodal__user_id_64d8e8_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'created_by_user', 'created_at'], name='multimodal__user_id_585d02_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'created_by_user', 'updated_at'], name='multimodal__user_id_dc6685_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'created_at', 'updated_at'], name='multimodal__user_id_11ef5d_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['chat_source', 'is_archived', 'created_by_user'], name='multimodal__chat_so_815197_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['chat_source', 'is_archived', 'created_at'], name='multimodal__chat_so_e84314_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['chat_source', 'is_archived', 'updated_at'], name='multimodal__chat_so_7072b2_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['chat_source', 'created_by_user', 'created_at'], name='multimodal__chat_so_7e8977_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['chat_source', 'created_by_user', 'updated_at'], name='multimodal__chat_so_12fbf7_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['chat_source', 'created_at', 'updated_at'], name='multimodal__chat_so_ff7428_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['is_archived', 'created_by_user', 'created_at'], name='multimodal__is_arch_0731bf_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['is_archived', 'created_by_user', 'updated_at'], name='multimodal__is_arch_d49c74_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['is_archived', 'created_at', 'updated_at'], name='multimodal__is_arch_6856cf_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['created_by_user', 'created_at', 'updated_at'], name='multimodal__created_6512d9_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization', 'assistant', 'user'], name='multimodal__id_34323e_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization', 'assistant', 'chat_source'], name='multimodal__id_1dc7c9_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization', 'assistant', 'is_archived'], name='multimodal__id_73a738_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization', 'assistant', 'created_by_user'], name='multimodal__id_8c7861_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization', 'assistant', 'created_at'], name='multimodal__id_b2dbfe_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization', 'assistant', 'updated_at'], name='multimodal__id_43a793_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization', 'user', 'chat_source'], name='multimodal__id_b587f4_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization', 'user', 'is_archived'], name='multimodal__id_c88353_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization', 'user', 'created_by_user'], name='multimodal__id_986807_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization', 'user', 'created_at'], name='multimodal__id_d9e28f_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization', 'user', 'updated_at'], name='multimodal__id_b52821_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization', 'chat_source', 'is_archived'], name='multimodal__id_d84ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization', 'chat_source', 'created_by_user'], name='multimodal__id_38bb54_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization', 'chat_source', 'created_at'], name='multimodal__id_ec3321_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization', 'chat_source', 'updated_at'], name='multimodal__id_ebecb8_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization', 'is_archived', 'created_by_user'], name='multimodal__id_f732f5_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization', 'is_archived', 'created_at'], name='multimodal__id_52b9c4_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization', 'is_archived', 'updated_at'], name='multimodal__id_bd60ed_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization', 'created_by_user', 'created_at'], name='multimodal__id_acd877_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization', 'created_by_user', 'updated_at'], name='multimodal__id_ba0c48_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'organization', 'created_at', 'updated_at'], name='multimodal__id_005a36_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'assistant', 'user', 'chat_source'], name='multimodal__id_d99e69_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'assistant', 'user', 'is_archived'], name='multimodal__id_89cca5_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'assistant', 'user', 'created_by_user'], name='multimodal__id_f89b81_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'assistant', 'user', 'created_at'], name='multimodal__id_bd4f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'assistant', 'user', 'updated_at'], name='multimodal__id_fc9a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'assistant', 'chat_source', 'is_archived'], name='multimodal__id_a0c2f7_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'assistant', 'chat_source', 'created_by_user'], name='multimodal__id_b53dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'assistant', 'chat_source', 'created_at'], name='multimodal__id_07b9cb_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'assistant', 'chat_source', 'updated_at'], name='multimodal__id_e58b58_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'assistant', 'is_archived', 'created_by_user'], name='multimodal__id_5a38c2_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'assistant', 'is_archived', 'created_at'], name='multimodal__id_5c4f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'assistant', 'is_archived', 'updated_at'], name='multimodal__id_cfeb88_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'assistant', 'created_by_user', 'created_at'], name='multimodal__id_2699b6_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'assistant', 'created_by_user', 'updated_at'], name='multimodal__id_291b09_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'assistant', 'created_at', 'updated_at'], name='multimodal__id_08984f_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'user', 'chat_source', 'is_archived'], name='multimodal__id_9eafa0_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'user', 'chat_source', 'created_by_user'], name='multimodal__id_d2f372_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'user', 'chat_source', 'created_at'], name='multimodal__id_7f21c4_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'user', 'chat_source', 'updated_at'], name='multimodal__id_960ed4_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'user', 'is_archived', 'created_by_user'], name='multimodal__id_e3fecd_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'user', 'is_archived', 'created_at'], name='multimodal__id_26a61c_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'user', 'is_archived', 'updated_at'], name='multimodal__id_215b75_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'user', 'created_by_user', 'created_at'], name='multimodal__id_95e296_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'user', 'created_by_user', 'updated_at'], name='multimodal__id_5dec38_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'user', 'created_at', 'updated_at'], name='multimodal__id_3c3048_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'chat_source', 'is_archived', 'created_by_user'], name='multimodal__id_0e88d9_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'chat_source', 'is_archived', 'created_at'], name='multimodal__id_2161b5_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'chat_source', 'is_archived', 'updated_at'], name='multimodal__id_103e5f_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'chat_source', 'created_by_user', 'created_at'], name='multimodal__id_a1a139_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'chat_source', 'created_by_user', 'updated_at'], name='multimodal__id_024feb_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'chat_source', 'created_at', 'updated_at'], name='multimodal__id_cc314c_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'is_archived', 'created_by_user', 'created_at'], name='multimodal__id_d8cd6d_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'is_archived', 'created_by_user', 'updated_at'], name='multimodal__id_974dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'is_archived', 'created_at', 'updated_at'], name='multimodal__id_e6ff28_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['id', 'created_by_user', 'created_at', 'updated_at'], name='multimodal__id_bb17f0_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'user', 'chat_source'], name='multimodal__organiz_4cec7b_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'user', 'is_archived'], name='multimodal__organiz_c4d353_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'user', 'created_by_user'], name='multimodal__organiz_7285c0_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'user', 'created_at'], name='multimodal__organiz_3e65bf_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'user', 'updated_at'], name='multimodal__organiz_5906b9_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'chat_source', 'is_archived'], name='multimodal__organiz_1d835a_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'chat_source', 'created_by_user'], name='multimodal__organiz_4c0892_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'chat_source', 'created_at'], name='multimodal__organiz_97f6c0_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'chat_source', 'updated_at'], name='multimodal__organiz_287ef0_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'is_archived', 'created_by_user'], name='multimodal__organiz_276b9e_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'is_archived', 'created_at'], name='multimodal__organiz_4cd663_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'is_archived', 'updated_at'], name='multimodal__organiz_236457_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'created_by_user', 'created_at'], name='multimodal__organiz_dd64f7_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'created_by_user', 'updated_at'], name='multimodal__organiz_b5e73a_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'created_at', 'updated_at'], name='multimodal__organiz_635d82_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'user', 'chat_source', 'is_archived'], name='multimodal__organiz_fcbaa8_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'user', 'chat_source', 'created_by_user'], name='multimodal__organiz_5ef964_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'user', 'chat_source', 'created_at'], name='multimodal__organiz_bf6fab_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'user', 'chat_source', 'updated_at'], name='multimodal__organiz_54bedb_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'user', 'is_archived', 'created_by_user'], name='multimodal__organiz_7869d8_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'user', 'is_archived', 'created_at'], name='multimodal__organiz_6af325_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'user', 'is_archived', 'updated_at'], name='multimodal__organiz_5a2725_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'user', 'created_by_user', 'created_at'], name='multimodal__organiz_51021c_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'user', 'created_by_user', 'updated_at'], name='multimodal__organiz_b6a077_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'user', 'created_at', 'updated_at'], name='multimodal__organiz_93f5e5_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'chat_source', 'is_archived', 'created_by_user'], name='multimodal__organiz_7cd371_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'chat_source', 'is_archived', 'created_at'], name='multimodal__organiz_d7e63d_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'chat_source', 'is_archived', 'updated_at'], name='multimodal__organiz_0c18df_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'chat_source', 'created_by_user', 'created_at'], name='multimodal__organiz_8576f3_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'chat_source', 'created_by_user', 'updated_at'], name='multimodal__organiz_9bdcff_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'chat_source', 'created_at', 'updated_at'], name='multimodal__organiz_661181_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'is_archived', 'created_by_user', 'created_at'], name='multimodal__organiz_339472_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'is_archived', 'created_by_user', 'updated_at'], name='multimodal__organiz_9495a8_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'is_archived', 'created_at', 'updated_at'], name='multimodal__organiz_da2c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'created_by_user', 'created_at', 'updated_at'], name='multimodal__organiz_519d86_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'user', 'chat_source', 'is_archived'], name='multimodal__assista_425b28_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'user', 'chat_source', 'created_by_user'], name='multimodal__assista_109d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'user', 'chat_source', 'created_at'], name='multimodal__assista_050451_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'user', 'chat_source', 'updated_at'], name='multimodal__assista_0c612d_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'user', 'is_archived', 'created_by_user'], name='multimodal__assista_fe7152_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'user', 'is_archived', 'created_at'], name='multimodal__assista_a7138d_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'user', 'is_archived', 'updated_at'], name='multimodal__assista_c409c2_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'user', 'created_by_user', 'created_at'], name='multimodal__assista_39fc11_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'user', 'created_by_user', 'updated_at'], name='multimodal__assista_b3db59_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'user', 'created_at', 'updated_at'], name='multimodal__assista_80ed4c_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'chat_source', 'is_archived', 'created_by_user'], name='multimodal__assista_455695_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'chat_source', 'is_archived', 'created_at'], name='multimodal__assista_892745_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'chat_source', 'is_archived', 'updated_at'], name='multimodal__assista_3bcd73_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'chat_source', 'created_by_user', 'created_at'], name='multimodal__assista_0994ea_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'chat_source', 'created_by_user', 'updated_at'], name='multimodal__assista_16293d_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'chat_source', 'created_at', 'updated_at'], name='multimodal__assista_4d01e0_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'is_archived', 'created_by_user', 'created_at'], name='multimodal__assista_70625c_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'is_archived', 'created_by_user', 'updated_at'], name='multimodal__assista_612069_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'is_archived', 'created_at', 'updated_at'], name='multimodal__assista_f73334_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'created_by_user', 'created_at', 'updated_at'], name='multimodal__assista_8724a4_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'chat_source', 'is_archived', 'created_by_user'], name='multimodal__user_id_5dc1e8_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'chat_source', 'is_archived', 'created_at'], name='multimodal__user_id_986bf3_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'chat_source', 'is_archived', 'updated_at'], name='multimodal__user_id_87ae51_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'chat_source', 'created_by_user', 'created_at'], name='multimodal__user_id_760bf4_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'chat_source', 'created_by_user', 'updated_at'], name='multimodal__user_id_e251f1_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'chat_source', 'created_at', 'updated_at'], name='multimodal__user_id_4c0d5f_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'is_archived', 'created_by_user', 'created_at'], name='multimodal__user_id_b7bb8f_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'is_archived', 'created_by_user', 'updated_at'], name='multimodal__user_id_ddff97_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'is_archived', 'created_at', 'updated_at'], name='multimodal__user_id_e22feb_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'created_by_user', 'created_at', 'updated_at'], name='multimodal__user_id_5f4a74_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['chat_source', 'is_archived', 'created_by_user', 'created_at'], name='multimodal__chat_so_1e6c4c_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['chat_source', 'is_archived', 'created_by_user', 'updated_at'], name='multimodal__chat_so_d121a4_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['chat_source', 'is_archived', 'created_at', 'updated_at'], name='multimodal__chat_so_4e0a83_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['chat_source', 'created_by_user', 'created_at', 'updated_at'], name='multimodal__chat_so_f514bf_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['is_archived', 'created_by_user', 'created_at', 'updated_at'], name='multimodal__is_arch_582183_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchatmessage',
            index=models.Index(fields=['multimodal_chat'], name='multimodal__multimo_b4eaed_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchatmessage',
            index=models.Index(fields=['sender_type'], name='multimodal__sender__f379dd_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchatmessage',
            index=models.Index(fields=['starred'], name='multimodal__starred_c52e99_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchatmessage',
            index=models.Index(fields=['sent_at'], name='multimodal__sent_at_351755_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchatmessage',
            index=models.Index(fields=['multimodal_chat', 'sender_type'], name='multimodal__multimo_5883a1_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchatmessage',
            index=models.Index(fields=['multimodal_chat', 'starred'], name='multimodal__multimo_f9b9e2_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchatmessage',
            index=models.Index(fields=['multimodal_chat', 'sent_at'], name='multimodal__multimo_b4e72a_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchatmessage',
            index=models.Index(fields=['sender_type', 'starred'], name='multimodal__sender__1ccead_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchatmessage',
            index=models.Index(fields=['sender_type', 'sent_at'], name='multimodal__sender__4fcbea_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchatmessage',
            index=models.Index(fields=['starred', 'sent_at'], name='multimodal__starred_fe9ee9_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchatmessage',
            index=models.Index(fields=['multimodal_chat', 'sender_type', 'starred'], name='multimodal__multimo_a73ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchatmessage',
            index=models.Index(fields=['multimodal_chat', 'sender_type', 'sent_at'], name='multimodal__multimo_7e8fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchatmessage',
            index=models.Index(fields=['multimodal_chat', 'starred', 'sent_at'], name='multimodal__multimo_8c2c37_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchatmessage',
            index=models.Index(fields=['sender_type', 'starred', 'sent_at'], name='multimodal__sender__193c7a_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchatmessage',
            index=models.Index(fields=['multimodal_chat', 'sender_type', 'starred', 'sent_at'], name='multimodal__multimo_96b0a4_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['id'], name='multimodal__id_2eec9c_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization'], name='multimodal__organiz_54ab17_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant'], name='multimodal__lean_as_fb302f_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user'], name='multimodal__user_id_a7823f_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['chat_source'], name='multimodal__chat_so_ac25d0_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['is_archived'], name='multimodal__is_arch_7d7bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['created_by_user'], name='multimodal__created_1e448b_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['created_at'], name='multimodal__created_53af47_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['updated_at'], name='multimodal__updated_f1f74e_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['id', 'organization'], name='multimodal__id_bf107a_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['id', 'lean_assistant'], name='multimodal__id_68f502_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['id', 'user'], name='multimodal__id_825eaf_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['id', 'chat_source'], name='multimodal__id_0e5fa5_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['id', 'is_archived'], name='multimodal__id_684394_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['id', 'created_by_user'], name='multimodal__id_418c44_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['id', 'created_at'], name='multimodal__id_48ee93_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['id', 'updated_at'], name='multimodal__id_b723ce_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'lean_assistant'], name='multimodal__organiz_3bb0ac_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'user'], name='multimodal__organiz_511863_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'chat_source'], name='multimodal__organiz_396d49_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'is_archived'], name='multimodal__organiz_07cfa5_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'created_by_user'], name='multimodal__organiz_f77ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'created_at'], name='multimodal__organiz_03feb7_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'updated_at'], name='multimodal__organiz_ddbc45_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'user'], name='multimodal__lean_as_7a2b50_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'chat_source'], name='multimodal__lean_as_91cf97_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'is_archived'], name='multimodal__lean_as_136186_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'created_by_user'], name='multimodal__lean_as_a530cb_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'created_at'], name='multimodal__lean_as_004ee3_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'updated_at'], name='multimodal__lean_as_ad9554_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'chat_source'], name='multimodal__user_id_47f17e_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'is_archived'], name='multimodal__user_id_6e6060_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'created_by_user'], name='multimodal__user_id_b68509_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'created_at'], name='multimodal__user_id_57c149_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'updated_at'], name='multimodal__user_id_e8341a_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['chat_source', 'is_archived'], name='multimodal__chat_so_bb6a97_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['chat_source', 'created_by_user'], name='multimodal__chat_so_41b1b0_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['chat_source', 'created_at'], name='multimodal__chat_so_6f2fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['chat_source', 'updated_at'], name='multimodal__chat_so_f3aaa3_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['is_archived', 'created_by_user'], name='multimodal__is_arch_6a3b11_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['is_archived', 'created_at'], name='multimodal__is_arch_fff4f7_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['is_archived', 'updated_at'], name='multimodal__is_arch_58e4db_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['created_by_user', 'created_at'], name='multimodal__created_3d5a04_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['created_by_user', 'updated_at'], name='multimodal__created_cfb9b1_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['created_at', 'updated_at'], name='multimodal__created_217eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'lean_assistant', 'user'], name='multimodal__organiz_de4787_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'lean_assistant', 'chat_source'], name='multimodal__organiz_3761bb_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'lean_assistant', 'is_archived'], name='multimodal__organiz_6727ea_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'lean_assistant', 'created_by_user'], name='multimodal__organiz_43b946_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'lean_assistant', 'created_at'], name='multimodal__organiz_6dd001_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'lean_assistant', 'updated_at'], name='multimodal__organiz_9e7e71_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'user', 'chat_source'], name='multimodal__organiz_da9ed8_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'user', 'is_archived'], name='multimodal__organiz_5b20ec_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'user', 'created_by_user'], name='multimodal__organiz_8b6de3_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'user', 'created_at'], name='multimodal__organiz_de949b_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'user', 'updated_at'], name='multimodal__organiz_6d346d_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'chat_source', 'is_archived'], name='multimodal__organiz_636420_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'chat_source', 'created_by_user'], name='multimodal__organiz_36317a_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'chat_source', 'created_at'], name='multimodal__organiz_9601b5_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'chat_source', 'updated_at'], name='multimodal__organiz_20f41c_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'is_archived', 'created_by_user'], name='multimodal__organiz_1e033d_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'is_archived', 'created_at'], name='multimodal__organiz_c78038_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'is_archived', 'updated_at'], name='multimodal__organiz_5ee61d_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'created_by_user', 'created_at'], name='multimodal__organiz_2e755f_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'created_by_user', 'updated_at'], name='multimodal__organiz_1db7bb_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'created_at', 'updated_at'], name='multimodal__organiz_e2b9b6_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'user', 'chat_source'], name='multimodal__lean_as_8563b1_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'user', 'is_archived'], name='multimodal__lean_as_4abd12_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'user', 'created_by_user'], name='multimodal__lean_as_b68055_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'user', 'created_at'], name='multimodal__lean_as_4e6e09_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'user', 'updated_at'], name='multimodal__lean_as_48afb7_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'chat_source', 'is_archived'], name='multimodal__lean_as_177f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'chat_source', 'created_by_user'], name='multimodal__lean_as_fe0da0_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'chat_source', 'created_at'], name='multimodal__lean_as_235a22_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'chat_source', 'updated_at'], name='multimodal__lean_as_40b63b_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'is_archived', 'created_by_user'], name='multimodal__lean_as_d844b9_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'is_archived', 'created_at'], name='multimodal__lean_as_5625f1_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'is_archived', 'updated_at'], name='multimodal__lean_as_393e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'created_by_user', 'created_at'], name='multimodal__lean_as_443ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'created_by_user', 'updated_at'], name='multimodal__lean_as_36e7cd_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'created_at', 'updated_at'], name='multimodal__lean_as_a25e44_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'chat_source', 'is_archived'], name='multimodal__user_id_d86581_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'chat_source', 'created_by_user'], name='multimodal__user_id_d504a1_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'chat_source', 'created_at'], name='multimodal__user_id_86ddd8_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'chat_source', 'updated_at'], name='multimodal__user_id_f55a37_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'is_archived', 'created_by_user'], name='multimodal__user_id_222a6a_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'is_archived', 'created_at'], name='multimodal__user_id_ef3e09_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'is_archived', 'updated_at'], name='multimodal__user_id_8dcb00_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'created_by_user', 'created_at'], name='multimodal__user_id_df9a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'created_by_user', 'updated_at'], name='multimodal__user_id_9133e7_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'created_at', 'updated_at'], name='multimodal__user_id_343bba_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['chat_source', 'is_archived', 'created_by_user'], name='multimodal__chat_so_1c61c5_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['chat_source', 'is_archived', 'created_at'], name='multimodal__chat_so_d14952_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['chat_source', 'is_archived', 'updated_at'], name='multimodal__chat_so_15b77c_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['chat_source', 'created_by_user', 'created_at'], name='multimodal__chat_so_791654_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['chat_source', 'created_by_user', 'updated_at'], name='multimodal__chat_so_2d39a0_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['chat_source', 'created_at', 'updated_at'], name='multimodal__chat_so_4b3a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['multimodal_lean_chat'], name='multimodal__multimo_ef00eb_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['sender_type'], name='multimodal__sender__ae7854_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['starred'], name='multimodal__starred_db655c_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['sent_at'], name='multimodal__sent_at_67c3bd_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['multimodal_lean_chat', 'sender_type'], name='multimodal__multimo_36c795_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['multimodal_lean_chat', 'starred'], name='multimodal__multimo_5d20ac_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['multimodal_lean_chat', 'sent_at'], name='multimodal__multimo_a38e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['sender_type', 'starred'], name='multimodal__sender__d6f8e1_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['sender_type', 'sent_at'], name='multimodal__sender__37e50b_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['starred', 'sent_at'], name='multimodal__starred_da29a8_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['multimodal_lean_chat', 'sender_type', 'starred'], name='multimodal__multimo_6a0138_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['multimodal_lean_chat', 'sender_type', 'sent_at'], name='multimodal__multimo_08b0d1_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['multimodal_lean_chat', 'starred', 'sent_at'], name='multimodal__multimo_8b4bba_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['sender_type', 'starred', 'sent_at'], name='multimodal__sender__44e09e_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['multimodal_lean_chat', 'sender_type', 'starred', 'sent_at'], name='multimodal__multimo_92422b_idx'),
        ),
    ]
