# Generated by Django 5.1.1 on 2024-09-15 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0004_initial'),
        ('datasource_knowledge_base', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultimodalChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'System'), ('TOOL', 'Tool')], max_length=10)),
                ('message_text_content', models.TextField()),
                ('message_json_content', models.JSONField(blank=True, default=dict, null=True)),
                ('message_image_contents', models.JSONField(blank=True, default=list, null=True)),
                ('message_file_contents', models.JSONField(blank=True, default=list, null=True)),
                ('message_audio', models.URLField(blank=True, max_length=10000, null=True)),
                ('starred', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Multimodal Chat Message',
                'verbose_name_plural': 'Multimodal Chat Messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatCreationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'verbose_name': 'Chat Creation Log',
                'verbose_name_plural': 'Chat Creation Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessageCreationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'verbose_name': 'Chat Message Creation Log',
                'verbose_name_plural': 'Chat Message Creation Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MultimodalChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('chat_source', models.CharField(choices=[('app', 'Application'), ('api', 'API'), ('scheduled', 'Scheduled'), ('orchestration', 'Orchestration')], default='app', max_length=100)),
                ('assistant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_chats', to='assistants.assistant')),
                ('context_memory_connection', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_chat', to='datasource_knowledge_base.contexthistoryknowledgebaseconnection')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_chats_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'verbose_name': 'Multimodal Chat',
                'verbose_name_plural': 'Multimodal Chats',
                'ordering': ['-created_at'],
            },
        ),
    ]
