# Generated by Django 5.0.6 on 2024-07-02 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimodal_chat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultimodalChat',
        ),
    ]
