# Generated by Django 5.0.6 on 2024-08-02 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm_transaction', '0002_initial'),
        ('multimodal_chat', '0001_initial'),
        ('starred_messages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='multimodalchat',
            name='starred_messages',
            field=models.ManyToManyField(blank=True, related_name='multimodal_chats', to='starred_messages.starredmessage'),
        ),
        migrations.AddField(
            model_name='multimodalchat',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='multimodal_chats', to='llm_transaction.llmtransaction'),
        ),
        migrations.AddField(
            model_name='multimodalchat',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multimodalchatmessage',
            name='multimodal_chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_chat', to='multimodal_chat.multimodalchat'),
        ),
        migrations.AddField(
            model_name='multimodalchat',
            name='chat_messages',
            field=models.ManyToManyField(blank=True, related_name='multimodal_chats', to='multimodal_chat.multimodalchatmessage'),
        ),
        migrations.AddIndex(
            model_name='chatcreationlog',
            index=models.Index(fields=['created_at'], name='multimodal__created_140f3d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessagecreationlog',
            index=models.Index(fields=['created_at'], name='multimodal__created_43fdc7_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchatmessage',
            index=models.Index(fields=['multimodal_chat', 'sender_type'], name='multimodal__multimo_5883a1_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchatmessage',
            index=models.Index(fields=['multimodal_chat', 'sent_at'], name='multimodal__multimo_b4e72a_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchatmessage',
            index=models.Index(fields=['multimodal_chat', 'sender_type', 'sent_at'], name='multimodal__multimo_7e8fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchatmessage',
            index=models.Index(fields=['multimodal_chat', 'sender_type', 'starred'], name='multimodal__multimo_a73ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchatmessage',
            index=models.Index(fields=['multimodal_chat', 'starred'], name='multimodal__multimo_f9b9e2_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchatmessage',
            index=models.Index(fields=['multimodal_chat', 'starred', 'sent_at'], name='multimodal__multimo_8c2c37_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'user'], name='multimodal__organiz_6d4d01_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'user', 'created_at'], name='multimodal__organiz_3e65bf_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'user', 'updated_at'], name='multimodal__organiz_5906b9_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'created_at'], name='multimodal__organiz_54e4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'updated_at'], name='multimodal__organiz_3605c9_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'created_at'], name='multimodal__organiz_b032b1_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'updated_at'], name='multimodal__organiz_ba7e39_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'created_at'], name='multimodal__assista_f8f884_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'updated_at'], name='multimodal__assista_676aab_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'created_at'], name='multimodal__user_id_8a4f03_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'updated_at'], name='multimodal__user_id_f4ce11_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['chat_source'], name='multimodal__chat_so_fdba6a_idx'),
        ),
    ]
