# Generated by Django 5.0.8 on 2024-10-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimodal_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimodalchat',
            name='chat_source',
            field=models.CharField(choices=[('app', 'Application'), ('api', 'API'), ('scheduled', 'Scheduled'), ('orchestration', 'Orchestration'), ('drafting', 'Drafting')], default='app', max_length=100),
        ),
        migrations.AlterField(
            model_name='multimodalleanchat',
            name='chat_source',
            field=models.CharField(choices=[('app', 'Application'), ('api', 'API'), ('scheduled', 'Scheduled'), ('orchestration', 'Orchestration'), ('drafting', 'Drafting')], default='app', max_length=100),
        ),
    ]
