# Generated by Django 5.1.1 on 2024-09-21 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leanmod', '0008_alter_leanassistant_expert_networks'),
        ('llm_transaction', '0002_initial'),
        ('multimodal_chat', '0002_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultimodalLeanChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('chat_source', models.CharField(choices=[('app', 'Application'), ('api', 'API'), ('scheduled', 'Scheduled'), ('orchestration', 'Orchestration')], default='app', max_length=100)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_lean_chats_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('lean_assistant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_lean_chats', to='leanmod.leanassistant')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('transactions', models.ManyToManyField(blank=True, related_name='multimodal_lean_chats', to='llm_transaction.llmtransaction')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_lean_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Multimodal Lean Chat',
                'verbose_name_plural': 'Multimodal Lean Chats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MultimodalLeanChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'System'), ('TOOL', 'Tool')], max_length=10)),
                ('message_text_content', models.TextField()),
                ('message_json_content', models.JSONField(blank=True, default=dict, null=True)),
                ('message_image_contents', models.JSONField(blank=True, default=list, null=True)),
                ('message_file_contents', models.JSONField(blank=True, default=list, null=True)),
                ('message_audio', models.URLField(blank=True, max_length=10000, null=True)),
                ('starred', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('multimodal_lean_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lean_messages_chat', to='multimodal_chat.multimodalleanchat')),
            ],
            options={
                'verbose_name': 'Multimodal Lean Chat Message',
                'verbose_name_plural': 'Multimodal Lean Chat Messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='multimodalleanchat',
            name='lean_chat_messages',
            field=models.ManyToManyField(blank=True, related_name='multimodal_lean_chats', to='multimodal_chat.multimodalleanchatmessage'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['multimodal_lean_chat'], name='multimodal__multimo_ef00eb_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['sender_type'], name='multimodal__sender__ae7854_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['starred'], name='multimodal__starred_db655c_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['sent_at'], name='multimodal__sent_at_67c3bd_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['multimodal_lean_chat', 'sender_type'], name='multimodal__multimo_36c795_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['multimodal_lean_chat', 'starred'], name='multimodal__multimo_5d20ac_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['multimodal_lean_chat', 'sent_at'], name='multimodal__multimo_a38e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['sender_type', 'starred'], name='multimodal__sender__d6f8e1_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['sender_type', 'sent_at'], name='multimodal__sender__37e50b_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['starred', 'sent_at'], name='multimodal__starred_da29a8_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['multimodal_lean_chat', 'sender_type', 'starred'], name='multimodal__multimo_6a0138_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['multimodal_lean_chat', 'sender_type', 'sent_at'], name='multimodal__multimo_08b0d1_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['multimodal_lean_chat', 'starred', 'sent_at'], name='multimodal__multimo_8b4bba_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['sender_type', 'starred', 'sent_at'], name='multimodal__sender__44e09e_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchatmessage',
            index=models.Index(fields=['multimodal_lean_chat', 'sender_type', 'starred', 'sent_at'], name='multimodal__multimo_92422b_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['id'], name='multimodal__id_2eec9c_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization'], name='multimodal__organiz_54ab17_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant'], name='multimodal__lean_as_fb302f_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user'], name='multimodal__user_id_a7823f_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['chat_source'], name='multimodal__chat_so_ac25d0_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['is_archived'], name='multimodal__is_arch_7d7bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['created_by_user'], name='multimodal__created_1e448b_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['created_at'], name='multimodal__created_53af47_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['updated_at'], name='multimodal__updated_f1f74e_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['id', 'organization'], name='multimodal__id_bf107a_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['id', 'lean_assistant'], name='multimodal__id_68f502_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['id', 'user'], name='multimodal__id_825eaf_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['id', 'chat_source'], name='multimodal__id_0e5fa5_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['id', 'is_archived'], name='multimodal__id_684394_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['id', 'created_by_user'], name='multimodal__id_418c44_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['id', 'created_at'], name='multimodal__id_48ee93_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['id', 'updated_at'], name='multimodal__id_b723ce_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'lean_assistant'], name='multimodal__organiz_3bb0ac_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'user'], name='multimodal__organiz_511863_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'chat_source'], name='multimodal__organiz_396d49_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'is_archived'], name='multimodal__organiz_07cfa5_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'created_by_user'], name='multimodal__organiz_f77ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'created_at'], name='multimodal__organiz_03feb7_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'updated_at'], name='multimodal__organiz_ddbc45_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'user'], name='multimodal__lean_as_7a2b50_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'chat_source'], name='multimodal__lean_as_91cf97_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'is_archived'], name='multimodal__lean_as_136186_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'created_by_user'], name='multimodal__lean_as_a530cb_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'created_at'], name='multimodal__lean_as_004ee3_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'updated_at'], name='multimodal__lean_as_ad9554_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'chat_source'], name='multimodal__user_id_47f17e_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'is_archived'], name='multimodal__user_id_6e6060_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'created_by_user'], name='multimodal__user_id_b68509_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'created_at'], name='multimodal__user_id_57c149_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'updated_at'], name='multimodal__user_id_e8341a_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['chat_source', 'is_archived'], name='multimodal__chat_so_bb6a97_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['chat_source', 'created_by_user'], name='multimodal__chat_so_41b1b0_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['chat_source', 'created_at'], name='multimodal__chat_so_6f2fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['chat_source', 'updated_at'], name='multimodal__chat_so_f3aaa3_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['is_archived', 'created_by_user'], name='multimodal__is_arch_6a3b11_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['is_archived', 'created_at'], name='multimodal__is_arch_fff4f7_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['is_archived', 'updated_at'], name='multimodal__is_arch_58e4db_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['created_by_user', 'created_at'], name='multimodal__created_3d5a04_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['created_by_user', 'updated_at'], name='multimodal__created_cfb9b1_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['created_at', 'updated_at'], name='multimodal__created_217eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'lean_assistant', 'user'], name='multimodal__organiz_de4787_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'lean_assistant', 'chat_source'], name='multimodal__organiz_3761bb_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'lean_assistant', 'is_archived'], name='multimodal__organiz_6727ea_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'lean_assistant', 'created_by_user'], name='multimodal__organiz_43b946_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'lean_assistant', 'created_at'], name='multimodal__organiz_6dd001_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'lean_assistant', 'updated_at'], name='multimodal__organiz_9e7e71_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'user', 'chat_source'], name='multimodal__organiz_da9ed8_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'user', 'is_archived'], name='multimodal__organiz_5b20ec_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'user', 'created_by_user'], name='multimodal__organiz_8b6de3_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'user', 'created_at'], name='multimodal__organiz_de949b_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'user', 'updated_at'], name='multimodal__organiz_6d346d_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'chat_source', 'is_archived'], name='multimodal__organiz_636420_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'chat_source', 'created_by_user'], name='multimodal__organiz_36317a_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'chat_source', 'created_at'], name='multimodal__organiz_9601b5_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'chat_source', 'updated_at'], name='multimodal__organiz_20f41c_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'is_archived', 'created_by_user'], name='multimodal__organiz_1e033d_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'is_archived', 'created_at'], name='multimodal__organiz_c78038_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'is_archived', 'updated_at'], name='multimodal__organiz_5ee61d_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'created_by_user', 'created_at'], name='multimodal__organiz_2e755f_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'created_by_user', 'updated_at'], name='multimodal__organiz_1db7bb_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['organization', 'created_at', 'updated_at'], name='multimodal__organiz_e2b9b6_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'user', 'chat_source'], name='multimodal__lean_as_8563b1_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'user', 'is_archived'], name='multimodal__lean_as_4abd12_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'user', 'created_by_user'], name='multimodal__lean_as_b68055_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'user', 'created_at'], name='multimodal__lean_as_4e6e09_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'user', 'updated_at'], name='multimodal__lean_as_48afb7_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'chat_source', 'is_archived'], name='multimodal__lean_as_177f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'chat_source', 'created_by_user'], name='multimodal__lean_as_fe0da0_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'chat_source', 'created_at'], name='multimodal__lean_as_235a22_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'chat_source', 'updated_at'], name='multimodal__lean_as_40b63b_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'is_archived', 'created_by_user'], name='multimodal__lean_as_d844b9_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'is_archived', 'created_at'], name='multimodal__lean_as_5625f1_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'is_archived', 'updated_at'], name='multimodal__lean_as_393e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'created_by_user', 'created_at'], name='multimodal__lean_as_443ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'created_by_user', 'updated_at'], name='multimodal__lean_as_36e7cd_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['lean_assistant', 'created_at', 'updated_at'], name='multimodal__lean_as_a25e44_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'chat_source', 'is_archived'], name='multimodal__user_id_d86581_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'chat_source', 'created_by_user'], name='multimodal__user_id_d504a1_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'chat_source', 'created_at'], name='multimodal__user_id_86ddd8_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'chat_source', 'updated_at'], name='multimodal__user_id_f55a37_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'is_archived', 'created_by_user'], name='multimodal__user_id_222a6a_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'is_archived', 'created_at'], name='multimodal__user_id_ef3e09_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'is_archived', 'updated_at'], name='multimodal__user_id_8dcb00_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'created_by_user', 'created_at'], name='multimodal__user_id_df9a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'created_by_user', 'updated_at'], name='multimodal__user_id_9133e7_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['user', 'created_at', 'updated_at'], name='multimodal__user_id_343bba_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['chat_source', 'is_archived', 'created_by_user'], name='multimodal__chat_so_1c61c5_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['chat_source', 'is_archived', 'created_at'], name='multimodal__chat_so_d14952_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['chat_source', 'is_archived', 'updated_at'], name='multimodal__chat_so_15b77c_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['chat_source', 'created_by_user', 'created_at'], name='multimodal__chat_so_791654_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['chat_source', 'created_by_user', 'updated_at'], name='multimodal__chat_so_2d39a0_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanchat',
            index=models.Index(fields=['chat_source', 'created_at', 'updated_at'], name='multimodal__chat_so_4b3a3c_idx'),
        ),
    ]
