# Generated by Django 5.0.6 on 2024-07-03 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm_transaction', '0010_llmtransaction_responsible_user'),
        ('multimodal_chat', '0002_delete_multimodalchat'),
        ('organization', '0114_alter_organization_organization_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultimodalChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_chats_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='MultimodalChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'System')], max_length=10)),
                ('message_text_content', models.TextField()),
                ('message_json_content', models.JSONField(default=dict)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('multimodal_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_chat', to='multimodal_chat.multimodalchat')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_transaction', to='llm_transaction.llmtransaction')),
            ],
            options={
                'verbose_name': 'Multimodal Chat Message',
                'verbose_name_plural': 'Multimodal Chat Messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='multimodalchat',
            name='messages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_chat_messages', to='multimodal_chat.multimodalchatmessage'),
        ),
    ]
