# Generated by Django 5.0.6 on 2024-07-03 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0018_alter_assistant_assistant_image'),
        ('multimodal_chat', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='multimodalchat',
            name='assistant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_chats', to='assistants.assistant'),
        ),
        migrations.AddField(
            model_name='multimodalchat',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
