# Generated by Django 5.0.8 on 2024-11-17 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimodal_chat', '0004_alter_multimodalchat_chat_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimodalchat',
            name='context_memory_connection',
        ),
    ]
