# Generated by Django 5.0.6 on 2024-07-03 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0010_llmtransaction_responsible_user'),
        ('multimodal_chat', '0004_multimodalchat_assistant_multimodalchat_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multimodalchat',
            options={'ordering': ['-created_at'], 'verbose_name': 'Multimodal Chat', 'verbose_name_plural': 'Multimodal Chats'},
        ),
        migrations.AddField(
            model_name='multimodalchat',
            name='transactions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_chat_transactions', to='llm_transaction.llmtransaction'),
        ),
    ]
