# Generated by Django 5.0.8 on 2024-12-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimodal_chat', '0005_remove_multimodalchat_context_memory_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimodalleanchatmessage',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
