# Generated by Django 5.0.6 on 2024-07-03 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimodal_chat', '0005_alter_multimodalchat_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimodalchat',
            name='transactions',
        ),
    ]
