# Generated by Django 5.0.8 on 2024-12-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimodal_chat', '0006_multimodalleanchatmessage_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimodalchatmessage',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
