# Generated by Django 5.0.6 on 2024-07-03 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0010_llmtransaction_responsible_user'),
        ('multimodal_chat', '0007_multimodalchat_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimodalchat',
            name='messages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_chat_messages', to='multimodal_chat.multimodalchatmessage'),
        ),
        migrations.AlterField(
            model_name='multimodalchat',
            name='transactions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_chat_transactions', to='llm_transaction.llmtransaction'),
        ),
    ]
