# Generated by Django 5.0.6 on 2024-07-03 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0010_llmtransaction_responsible_user'),
        ('multimodal_chat', '0008_alter_multimodalchat_messages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimodalchatmessage',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_transaction', to='llm_transaction.llmtransaction'),
        ),
    ]
