# Generated by Django 5.0.6 on 2024-07-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimodal_chat', '0009_alter_multimodalchatmessage_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimodalchatmessage',
            name='message_json_content',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
