# Generated by Django 5.0.8 on 2024-12-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimodal_chat', '0009_remove_multimodalleanchat_multimodal__id_bf107a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimodalchatmessage',
            name='sender_type',
            field=models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('DEVELOPER', 'Developer'), ('TOOL', 'Tool')], max_length=10),
        ),
        migrations.AlterField(
            model_name='multimodalleanchatmessage',
            name='sender_type',
            field=models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('DEVELOPER', 'Developer'), ('TOOL', 'Tool')], max_length=10),
        ),
    ]
