# Generated by Django 5.0.6 on 2024-07-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0010_llmtransaction_responsible_user'),
        ('multimodal_chat', '0010_alter_multimodalchatmessage_message_json_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimodalchat',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='multimodalchat',
            name='transactions',
        ),
        migrations.AddField(
            model_name='multimodalchat',
            name='messages',
            field=models.ManyToManyField(related_name='multimodal_chats', to='multimodal_chat.multimodalchatmessage'),
        ),
        migrations.AddField(
            model_name='multimodalchat',
            name='transactions',
            field=models.ManyToManyField(related_name='multimodal_chats', to='llm_transaction.llmtransaction'),
        ),
    ]
