# Generated by Django 5.0.8 on 2024-12-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimodal_chat', '0010_alter_multimodalchatmessage_sender_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimodalchatmessage',
            name='sender_type',
            field=models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'System'), ('TOOL', 'Tool')], max_length=10),
        ),
        migrations.AlterField(
            model_name='multimodalleanchatmessage',
            name='sender_type',
            field=models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'System'), ('TOOL', 'Tool')], max_length=10),
        ),
    ]
