# Generated by Django 5.0.6 on 2024-07-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0010_llmtransaction_responsible_user'),
        ('multimodal_chat', '0012_alter_multimodalchat_messages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimodalchat',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='multimodal_chats', to='multimodal_chat.multimodalchatmessage'),
        ),
        migrations.AlterField(
            model_name='multimodalchat',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='multimodal_chats', to='llm_transaction.llmtransaction'),
        ),
    ]
