# Generated by Django 5.0.6 on 2024-07-04 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimodal_chat', '0013_alter_multimodalchat_messages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multimodalchat',
            old_name='messages',
            new_name='chat_messages',
        ),
    ]
