# Generated by Django 5.0.6 on 2024-07-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimodal_chat', '0014_rename_messages_multimodalchat_chat_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimodalchatmessage',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
