# Generated by Django 5.0.6 on 2024-07-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimodal_chat', '0015_multimodalchatmessage_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimodalchat',
            name='chat_source',
            field=models.CharField(choices=[('app', 'Application'), ('api', 'API')], default='app', max_length=100),
        ),
    ]
