# Generated by Django 5.0.6 on 2024-07-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0015_alter_llmtransaction_model_and_more'),
        ('multimodal_chat', '0016_multimodalchat_chat_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimodalchatmessage',
            name='transaction',
        ),
        migrations.AddField(
            model_name='multimodalchatmessage',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='messages_chat', to='llm_transaction.llmtransaction'),
        ),
    ]
