# Generated by Django 5.0.6 on 2024-07-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0015_alter_llmtransaction_model_and_more'),
        ('multimodal_chat', '0017_remove_multimodalchatmessage_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimodalchatmessage',
            name='transactions',
            field=models.ManyToManyField(blank=True, null=True, related_name='messages_chat', to='llm_transaction.llmtransaction'),
        ),
    ]
