# Generated by Django 5.0.6 on 2024-07-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimodal_chat', '0018_alter_multimodalchatmessage_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimodalchatmessage',
            name='transactions',
        ),
    ]
