# Generated by Django 5.0.6 on 2024-07-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimodal_chat', '0019_remove_multimodalchatmessage_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimodalchatmessage',
            name='sender_type',
            field=models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'System'), ('TOOL', 'Tool')], max_length=10),
        ),
    ]
