# Generated by Django 5.0.6 on 2024-07-15 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimodal_chat', '0021_multimodalchat_context_memory_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimodalchat',
            name='context_memory_connection',
        ),
    ]
