# Generated by Django 5.0.6 on 2024-07-15 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_knowledge_base', '0013_remove_contexthistoryknowledgebaseconnection_host_url_and_more'),
        ('multimodal_chat', '0022_remove_multimodalchat_context_memory_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimodalchat',
            name='context_memory_connection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_chat', to='datasource_knowledge_base.contexthistoryknowledgebaseconnection'),
        ),
    ]
