# Generated by Django 5.0.6 on 2024-07-16 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0410_alter_assistant_assistant_image'),
        ('datasource_knowledge_base', '0016_alter_contexthistoryknowledgebaseconnection_unique_together_and_more'),
        ('llm_transaction', '0022_llmtransaction_transaction_context_content'),
        ('multimodal_chat', '0023_multimodalchat_context_memory_connection'),
        ('organization', '0507_alter_organization_organization_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'user'], name='multimodal__organiz_6d4d01_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'user', 'created_at'], name='multimodal__organiz_3e65bf_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'user', 'updated_at'], name='multimodal__organiz_5906b9_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'created_at'], name='multimodal__organiz_54e4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'assistant', 'updated_at'], name='multimodal__organiz_3605c9_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'created_at'], name='multimodal__organiz_b032b1_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['organization', 'updated_at'], name='multimodal__organiz_ba7e39_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'created_at'], name='multimodal__assista_f8f884_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['assistant', 'updated_at'], name='multimodal__assista_676aab_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'created_at'], name='multimodal__user_id_8a4f03_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['user', 'updated_at'], name='multimodal__user_id_f4ce11_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchat',
            index=models.Index(fields=['chat_source'], name='multimodal__chat_so_fdba6a_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchatmessage',
            index=models.Index(fields=['multimodal_chat', 'sender_type'], name='multimodal__multimo_5883a1_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchatmessage',
            index=models.Index(fields=['multimodal_chat', 'sent_at'], name='multimodal__multimo_b4e72a_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchatmessage',
            index=models.Index(fields=['multimodal_chat', 'sender_type', 'sent_at'], name='multimodal__multimo_7e8fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchatmessage',
            index=models.Index(fields=['multimodal_chat', 'sender_type', 'starred'], name='multimodal__multimo_a73ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchatmessage',
            index=models.Index(fields=['multimodal_chat', 'starred'], name='multimodal__multimo_f9b9e2_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalchatmessage',
            index=models.Index(fields=['multimodal_chat', 'starred', 'sent_at'], name='multimodal__multimo_8c2c37_idx'),
        ),
    ]
