# Generated by Django 5.0.6 on 2024-07-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimodal_chat', '0024_multimodalchat_multimodal__organiz_6d4d01_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimodalchatmessage',
            name='message_file_content',
            field=models.FileField(blank=True, null=True, upload_to='multimodal_chat_files/%YYYY/%mm/%dd/%HH/%MM/%SS/'),
        ),
        migrations.AddField(
            model_name='multimodalchatmessage',
            name='message_image_content',
            field=models.ImageField(blank=True, null=True, upload_to='multimodal_chat_images/%YYYY/%mm/%dd/%HH/%MM/%SS/'),
        ),
    ]
