# Generated by Django 5.0.6 on 2024-07-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimodal_chat', '0025_multimodalchatmessage_message_file_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimodalchatmessage',
            name='message_image_content',
        ),
        migrations.AddField(
            model_name='multimodalchatmessage',
            name='message_image_contents',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='multimodalchatmessage',
            name='message_file_content',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
