# Generated by Django 5.0.6 on 2024-07-18 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimodal_chat', '0026_remove_multimodalchatmessage_message_image_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multimodalchatmessage',
            old_name='message_file_content',
            new_name='message_file_contents',
        ),
    ]
