# Generated by Django 5.0.6 on 2024-07-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimodal_chat', '0027_rename_message_file_content_multimodalchatmessage_message_file_contents'),
        ('starred_messages', '0004_alter_starredmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimodalchat',
            name='starred_messages',
            field=models.ManyToManyField(blank=True, related_name='multimodal_chats', to='starred_messages.starredmessage'),
        ),
    ]
