# Generated by Django 5.0.6 on 2024-07-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimodal_chat', '0028_multimodalchat_starred_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimodalchat',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
