# Generated by Django 5.0.6 on 2024-07-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimodal_chat', '0029_multimodalchat_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimodalchat',
            name='chat_source',
            field=models.CharField(choices=[('app', 'Application'), ('api', 'API'), ('scheduled', 'Scheduled')], default='app', max_length=100),
        ),
    ]
