# Generated by Django 5.0.6 on 2024-07-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimodal_chat', '0030_alter_multimodalchat_chat_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatCreationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
