# Generated by Django 5.0.6 on 2024-07-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimodal_chat', '0031_chatcreationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageCreationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chat Message Creation Log',
                'verbose_name_plural': 'Chat Message Creation Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='chatcreationlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Chat Creation Log', 'verbose_name_plural': 'Chat Creation Logs'},
        ),
        migrations.AddIndex(
            model_name='chatcreationlog',
            index=models.Index(fields=['created_at'], name='multimodal__created_140f3d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessagecreationlog',
            index=models.Index(fields=['created_at'], name='multimodal__created_43fdc7_idx'),
        ),
    ]
