# Generated by Django 5.0.6 on 2024-07-31 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimodal_chat', '0032_chatmessagecreationlog_alter_chatcreationlog_options_and_more'),
        ('organization', '0695_alter_organization_organization_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatcreationlog',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='chatmessagecreationlog',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
    ]
