# Generated by Django 5.0.8 on 2024-11-05 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantIntegrationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=1000)),
                ('category_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assistant Integration Category',
                'verbose_name_plural': 'Assistant Integration Categories',
                'indexes': [models.Index(fields=['category_name'], name='integration_categor_b28dfc_idx')],
                'unique_together': {('category_name',)},
            },
        ),
        migrations.CreateModel(
            name='AssistantIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.JSONField(blank=True, null=True)),
                ('integration_name', models.CharField(max_length=1000)),
                ('integration_description', models.TextField(blank=True, null=True)),
                ('integration_instructions', models.TextField(blank=True, null=True)),
                ('integration_audience', models.CharField(blank=True, max_length=1000, null=True)),
                ('integration_tone', models.CharField(blank=True, max_length=1000, null=True)),
                ('integration_assistant_image_url', models.URLField(blank=True, null=True)),
                ('integration_multi_step_reasoning', models.BooleanField(default=False)),
                ('integration_response_template', models.TextField(blank=True, null=True)),
                ('integration_glossary', models.TextField(blank=True, null=True)),
                ('integration_time_awareness', models.BooleanField(default=True)),
                ('integration_location_awareness', models.BooleanField(default=True)),
                ('integration_max_retries', models.IntegerField(default=5)),
                ('integration_max_tool_retries', models.IntegerField(default=5)),
                ('integration_max_tool_pipelines', models.IntegerField(default=5)),
                ('integration_max_message_memory', models.IntegerField(default=5)),
                ('integration_image_generation_capability', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.assistantintegrationcategory')),
            ],
            options={
                'verbose_name': 'Assistant Integration',
                'verbose_name_plural': 'Assistant Integrations',
                'ordering': ['-integration_name'],
                'indexes': [models.Index(fields=['integration_name'], name='integration_integra_ed76c7_idx'), models.Index(fields=['integration_name', 'integration_category'], name='integration_integra_83ec71_idx'), models.Index(fields=['integration_name', 'integration_category', 'integration_audience'], name='integration_integra_d7c46c_idx'), models.Index(fields=['integration_name', 'integration_category', 'integration_tone'], name='integration_integra_d1a3f8_idx'), models.Index(fields=['integration_name', 'integration_category', 'integration_multi_step_reasoning'], name='integration_integra_8d2227_idx'), models.Index(fields=['integration_name', 'integration_category', 'integration_time_awareness'], name='integration_integra_8762bb_idx'), models.Index(fields=['integration_name', 'integration_category', 'integration_location_awareness'], name='integration_integra_ea3222_idx'), models.Index(fields=['integration_name', 'integration_category', 'integration_max_retries'], name='integration_integra_c8a0ab_idx'), models.Index(fields=['integration_name', 'integration_category', 'integration_max_tool_retries'], name='integration_integra_e6c312_idx')],
            },
        ),
    ]
