# Generated by Django 5.0.8 on 2024-11-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantintegrationcategory',
            name='category_slug',
            field=models.SlugField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
