# Generated by Django 5.0.8 on 2024-11-05 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_security', '0002_initial'),
        ('integrations', '0002_assistantintegrationcategory_category_slug'),
        ('mm_apis', '0001_initial'),
        ('mm_functions', '0001_initial'),
        ('mm_scripts', '0001_initial'),
        ('projects', '0002_remove_projectitem_assistants'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantintegration',
            name='integration_context_overflow_strategy',
            field=models.CharField(default='forget', max_length=1000),
        ),
        migrations.AddField(
            model_name='assistantintegration',
            name='integration_custom_apis',
            field=models.ManyToManyField(blank=True, to='mm_apis.customapi'),
        ),
        migrations.AddField(
            model_name='assistantintegration',
            name='integration_custom_functions',
            field=models.ManyToManyField(blank=True, to='mm_functions.customfunction'),
        ),
        migrations.AddField(
            model_name='assistantintegration',
            name='integration_custom_scripts',
            field=models.ManyToManyField(blank=True, to='mm_scripts.customscript'),
        ),
        migrations.AddField(
            model_name='assistantintegration',
            name='integration_response_language',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='assistantintegration',
            name='ner_integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_integrations', to='data_security.nerintegration'),
        ),
        migrations.AddField(
            model_name='assistantintegration',
            name='project_items',
            field=models.ManyToManyField(blank=True, related_name='assistant_integrations', to='projects.projectitem'),
        ),
    ]
