# Generated by Django 5.0.8 on 2024-11-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_assistantintegration_integration_context_overflow_strategy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantintegrationcategory',
            name='category_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
