# Generated by Django 5.0.8 on 2024-11-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_assistantintegrationcategory_category_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantintegrationcategory',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
