# Generated by Django 5.0.8 on 2024-11-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_assistantintegrationcategory_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantintegration',
            name='integration_assistant_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='integration_assistant_images/%Y/%m/%d/'),
        ),
    ]
