# Generated by Django 5.0.8 on 2024-11-06 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_alter_assistantintegration_integration_assistant_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistantintegration',
            old_name='integration_assistant_image_url',
            new_name='integration_assistant_image',
        ),
    ]
