# Generated by Django 5.0.8 on 2024-11-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_rename_integration_assistant_image_url_assistantintegration_integration_assistant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantintegration',
            name='integration_response_template',
            field=models.TextField(default=''),
        ),
    ]
