# Generated by Django 5.0.8 on 2024-11-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_alter_assistantintegration_integration_response_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantintegration',
            name='integration_response_language',
            field=models.CharField(default='auto', max_length=1000),
        ),
    ]
