# Generated by Django 5.0.8 on 2024-11-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_alter_assistantintegration_integration_response_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantintegration',
            name='integration_glossary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
