# Generated by Django 5.0.8 on 2024-11-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_alter_assistantintegration_integration_glossary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantintegration',
            name='integration_multi_step_reasoning',
            field=models.BooleanField(default='high-performance'),
        ),
    ]
