# Generated by Django 5.0.8 on 2024-11-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0011_alter_assistantintegration_integration_multi_step_reasoning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantintegration',
            name='integration_multi_step_reasoning',
            field=models.CharField(default='high-performance'),
        ),
    ]
