# Generated by Django 5.0.8 on 2024-11-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_alter_assistantintegration_integration_context_overflow_strategy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantintegration',
            name='integration_max_message_memory',
            field=models.IntegerField(default=25),
        ),
    ]
