# Generated by Django 5.0.8 on 2024-12-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_alter_assistantintegration_integration_max_message_memory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assistantintegrationcategory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='assistantintegrationcategory',
            name='category_name',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
