# Generated by Django 5.0.8 on 2024-12-01 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0015_alter_assistantintegrationcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assistantintegration',
            unique_together={('integration_category', 'integration_name')},
        ),
    ]
