# Generated by Django 5.0.8 on 2024-10-28 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metakanban', '0021_alter_metakanbanboard_connection_api_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTempoConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tracking_active', models.BooleanField(default=True)),
                ('optional_context_instructions', models.TextField(blank=True, null=True)),
                ('overall_log_intervals', models.CharField(choices=[('daily', 'Daily'), ('bi-daily', 'Bi-Daily'), ('weekly', 'Weekly'), ('bi-weekly', 'Bi-Weekly'), ('monthly', 'Monthly')], default='daily', max_length=1000)),
                ('member_log_intervals', models.CharField(choices=[('times_12_per_hour', '12 Times Per Hour'), ('times_6_per_hour', '6 Times Per Hour'), ('times_4_per_hour', '4 Times Per Hour'), ('times_3_per_hour', '3 Times Per Hour'), ('times_2_per_hour', '2 Times Per Hour'), ('hourly', 'Hourly'), ('every_2_hours', 'Every 2 Hours'), ('every_4_hours', 'Every 4 Hours')], default='times_6_per_hour', max_length=1000)),
                ('tracked_weekdays', models.JSONField(blank=True, null=True)),
                ('tracking_start_time', models.TimeField(blank=True, null=True)),
                ('tracking_end_time', models.TimeField(blank=True, null=True)),
                ('connection_api_key', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metakanban.metakanbanboard')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metatempo_board_connections_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MetaTempo Board Connection',
                'verbose_name_plural': 'MetaTempo Board Connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetaTempoMemberLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot_image', models.ImageField(blank=True, null=True, upload_to='metatempo/member_logs/%Y/%m/%d/')),
                ('is_log_retrieval_successful', models.BooleanField(default=False)),
                ('activity_summary', models.TextField(blank=True, null=True)),
                ('activity_tags', models.JSONField(blank=True, null=True)),
                ('work_intensity', models.IntegerField(blank=True, null=True)),
                ('application_usage_stats', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metatempo_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metatempo.metatempoconnection')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MetaTempo Member Log',
                'verbose_name_plural': 'MetaTempo Member Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MetaTempoMemberLogDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_activity_summary', models.TextField(blank=True, null=True)),
                ('key_tasks', models.JSONField(blank=True, null=True)),
                ('overall_work_intensity', models.IntegerField(blank=True, null=True)),
                ('application_usage_stats', models.JSONField(blank=True, null=True)),
                ('datestamp', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logs', models.ManyToManyField(blank=True, to='metatempo.metatempomemberlog')),
                ('metatempo_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metatempo.metatempoconnection')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MetaTempo Member Log Daily',
                'verbose_name_plural': 'MetaTempo Member Log Dailies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetaTempoProjectOverallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_activity_summary', models.TextField(blank=True, null=True)),
                ('overall_key_insights', models.JSONField(blank=True, null=True)),
                ('overall_work_intensity', models.IntegerField(blank=True, null=True)),
                ('overall_application_usage_stats', models.JSONField(blank=True, null=True)),
                ('datestamp', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metatempo_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metatempo.metatempoconnection')),
            ],
            options={
                'verbose_name': 'MetaTempo Project Overall Log',
                'verbose_name_plural': 'MetaTempo Project Overall Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='metatempoconnection',
            index=models.Index(fields=['board', 'is_tracking_active'], name='metatempo_m_board_i_5bf5f0_idx'),
        ),
        migrations.AddIndex(
            model_name='metatempoconnection',
            index=models.Index(fields=['connection_api_key'], name='metatempo_m_connect_2cd7c1_idx'),
        ),
        migrations.AddIndex(
            model_name='metatempoconnection',
            index=models.Index(fields=['created_by_user'], name='metatempo_m_created_44e914_idx'),
        ),
        migrations.AddIndex(
            model_name='metatempoconnection',
            index=models.Index(fields=['created_at'], name='metatempo_m_created_d77f19_idx'),
        ),
        migrations.AddIndex(
            model_name='metatempoconnection',
            index=models.Index(fields=['updated_at'], name='metatempo_m_updated_fe1adf_idx'),
        ),
        migrations.AddIndex(
            model_name='metatempomemberlog',
            index=models.Index(fields=['metatempo_connection', 'user'], name='metatempo_m_metatem_1ed39c_idx'),
        ),
        migrations.AddIndex(
            model_name='metatempomemberlog',
            index=models.Index(fields=['timestamp'], name='metatempo_m_timesta_2c7b49_idx'),
        ),
        migrations.AddIndex(
            model_name='metatempomemberlog',
            index=models.Index(fields=['work_intensity'], name='metatempo_m_work_in_9327dd_idx'),
        ),
        migrations.AddIndex(
            model_name='metatempomemberlogdaily',
            index=models.Index(fields=['metatempo_connection', 'user'], name='metatempo_m_metatem_4c8106_idx'),
        ),
        migrations.AddIndex(
            model_name='metatempomemberlogdaily',
            index=models.Index(fields=['datestamp'], name='metatempo_m_datesta_28f96d_idx'),
        ),
        migrations.AddIndex(
            model_name='metatempomemberlogdaily',
            index=models.Index(fields=['overall_work_intensity'], name='metatempo_m_overall_fe7181_idx'),
        ),
        migrations.AddIndex(
            model_name='metatempoprojectoveralllog',
            index=models.Index(fields=['metatempo_connection'], name='metatempo_m_metatem_0e2e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='metatempoprojectoveralllog',
            index=models.Index(fields=['datestamp'], name='metatempo_m_datesta_77c565_idx'),
        ),
        migrations.AddIndex(
            model_name='metatempoprojectoveralllog',
            index=models.Index(fields=['overall_work_intensity'], name='metatempo_m_overall_f41c8e_idx'),
        ),
    ]
