# Generated by Django 5.0.8 on 2024-10-29 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metatempo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metatempomemberlog',
            name='is_log_retrieval_successful',
        ),
    ]
