# Generated by Django 5.0.8 on 2024-10-29 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metakanban', '0021_alter_metakanbanboard_connection_api_key'),
        ('metatempo', '0002_remove_metatempomemberlog_is_log_retrieval_successful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatempoconnection',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metakanban.metakanbanboard', unique=True),
        ),
    ]
