# Generated by Django 5.0.8 on 2024-10-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatempo', '0004_alter_metatempoconnection_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatempomemberlog',
            name='identifier_uuid',
            field=models.UUIDField(null=True, blank=True, editable=False, unique=True),
        ),
    ]
