# Generated by Django 5.0.8 on 2024-10-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatempo', '0005_metatempomemberlog_identifier_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatempomemberlog',
            name='identifier_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
