# Generated by Django 5.0.8 on 2024-10-30 03:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatempo', '0006_alter_metatempomemberlog_identifier_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatempomemberlog',
            name='identifier_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
