# Generated by Django 5.0.8 on 2024-10-30 04:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatempo', '0008_alter_metatempomemberlog_identifier_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='metatempomemberlog',
            index=models.Index(fields=['identifier_uuid'], name='metatempo_m_identif_48043c_idx'),
        ),
    ]
