# Generated by Django 5.0.8 on 2024-10-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatempo', '0009_metatempomemberlog_metatempo_m_identif_48043c_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatempomemberlog',
            name='identifier_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
