# Generated by Django 5.0.8 on 2024-10-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatempo', '0010_alter_metatempomemberlog_identifier_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatempomemberlog',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
