# Generated by Django 5.0.8 on 2024-11-13 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0007_alter_assistant_context_overflow_strategy'),
        ('metatempo', '0011_alter_metatempomemberlog_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTempoAssistantConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('metatempo_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metatempo.metatempoconnection')),
            ],
            options={
                'verbose_name': 'Meta Tempo Assistant Connection',
                'verbose_name_plural': 'Meta Tempo Assistant Connections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['metatempo_instance', 'assistant'], name='metatempo_m_metatem_b29c06_idx'), models.Index(fields=['assistant', 'metatempo_instance'], name='metatempo_m_assista_6a7e0f_idx')],
                'unique_together': {('metatempo_instance', 'assistant')},
            },
        ),
    ]
