# Generated by Django 5.0.8 on 2024-12-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_base_category', models.CharField(choices=[('software_and_it', 'Software and IT'), ('legal_and_law', 'Legal and Law'), ('healthcare_and_medicine', 'Healthcare and Medicine'), ('finance_and_business', 'Finance and Business'), ('education_and_training', 'Education and Training'), ('science_and_engineering', 'Science and Engineering'), ('history_and_culture', 'History and Culture'), ('sports_and_entertainment', 'Sports and Entertainment'), ('military_and_defense', 'Military and Defense'), ('transport_and_logistics', 'Transport and Logistics'), ('agriculture_and_food', 'Agriculture and Food'), ('media_and_communication', 'Media and Communication'), ('space_and_astronomy', 'Space and Astronomy'), ('ethics_and_philosophy', 'Ethics and Philosophy'), ('miscellaneous', 'Miscellaneous')], default='miscellaneous', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('knowledge_base_image', models.ImageField(blank=True, null=True, upload_to='integration_knowledge_base_images/%Y/%m/%d/')),
                ('knowledge_base_download_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Knowledge Base Integration',
                'verbose_name_plural': 'Knowledge Base Integrations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['knowledge_base_category'], name='knowledge_b_knowled_281fab_idx'), models.Index(fields=['created_at'], name='knowledge_b_created_f55147_idx'), models.Index(fields=['updated_at'], name='knowledge_b_updated_ffdd7a_idx')],
            },
        ),
    ]
