# Generated by Django 5.0.8 on 2024-11-02 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0006_alter_assistant_project_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormicaGoogleAppsConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_api_key', models.CharField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formica_assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formica Google Apps Connection',
                'verbose_name_plural': 'Formica Google Apps Connections',
                'indexes': [models.Index(fields=['formica_assistant'], name='formica_for_formica_c40318_idx'), models.Index(fields=['owner_user'], name='formica_for_owner_u_7fca2a_idx'), models.Index(fields=['formica_assistant', 'owner_user'], name='formica_for_formica_2ad8fd_idx')],
                'unique_together': {('formica_assistant', 'owner_user')},
            },
        ),
    ]
