#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Br6.in™
#  File: 0001_initial.py
#  Last Modified: 2024-10-05 01:39:48
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 14:42:34
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@br6.in.
#

# Generated by Django 5.1.1 on 2024-09-25 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('authentication_type', models.CharField(choices=[('None', 'None'), ('Bearer', 'Bearer')], default='None', max_length=5000)),
                ('authentication_token', models.CharField(blank=True, default='', max_length=5000)),
                ('base_url', models.CharField(default='', max_length=5000)),
                ('endpoints', models.JSONField(blank=True, default=dict)),
                ('api_picture', models.ImageField(blank=True, null=True, upload_to='custom_apis/%YYYY/%mm/%dd/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom API',
                'verbose_name_plural': 'Custom APIs',
            },
        ),
        migrations.CreateModel(
            name='CustomAPIReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_source', models.CharField(blank=True, default='internal', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('custom_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_api_references', to='mm_apis.customapi')),
            ],
            options={
                'verbose_name': 'Custom API Reference',
                'verbose_name_plural': 'Custom API References',
            },
        ),
        migrations.AddIndex(
            model_name='customapi',
            index=models.Index(fields=['name'], name='mm_apis_cus_name_d4c7e1_idx'),
        ),
        migrations.AddIndex(
            model_name='customapi',
            index=models.Index(fields=['created_by_user'], name='mm_apis_cus_created_3ff351_idx'),
        ),
        migrations.AddIndex(
            model_name='customapi',
            index=models.Index(fields=['created_at'], name='mm_apis_cus_created_4f56e7_idx'),
        ),
        migrations.AddIndex(
            model_name='customapi',
            index=models.Index(fields=['updated_at'], name='mm_apis_cus_updated_2deaa5_idx'),
        ),
        migrations.AddIndex(
            model_name='customapi',
            index=models.Index(fields=['is_public'], name='mm_apis_cus_is_publ_628496_idx'),
        ),
        migrations.AddIndex(
            model_name='customapi',
            index=models.Index(fields=['is_featured'], name='mm_apis_cus_is_feat_948542_idx'),
        ),
        migrations.AddIndex(
            model_name='customapi',
            index=models.Index(fields=['name', 'is_public'], name='mm_apis_cus_name_5ec089_idx'),
        ),
        migrations.AddIndex(
            model_name='customapi',
            index=models.Index(fields=['name', 'is_featured'], name='mm_apis_cus_name_f34245_idx'),
        ),
        migrations.AddIndex(
            model_name='customapireference',
            index=models.Index(fields=['custom_api', 'assistant'], name='mm_apis_cus_custom__18b236_idx'),
        ),
        migrations.AddIndex(
            model_name='customapireference',
            index=models.Index(fields=['assistant', 'custom_api', 'created_by_user'], name='mm_apis_cus_assista_e39dc4_idx'),
        ),
        migrations.AddIndex(
            model_name='customapireference',
            index=models.Index(fields=['created_at'], name='mm_apis_cus_created_7136fc_idx'),
        ),
        migrations.AddIndex(
            model_name='customapireference',
            index=models.Index(fields=['assistant'], name='mm_apis_cus_assista_c7319c_idx'),
        ),
        migrations.AddIndex(
            model_name='customapireference',
            index=models.Index(fields=['custom_api'], name='mm_apis_cus_custom__32ed7c_idx'),
        ),
        migrations.AddIndex(
            model_name='customapireference',
            index=models.Index(fields=['created_by_user'], name='mm_apis_cus_created_7b7f66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customapireference',
            unique_together={('custom_api', 'assistant')},
        ),
    ]
