# Generated by Django 5.0.6 on 2024-07-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customapi',
            name='authentication_type',
            field=models.CharField(choices=[('None', 'None'), ('Bearer', 'Bearer')], default='None', max_length=5000),
        ),
    ]
