# Generated by Django 5.0.6 on 2024-07-26 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm_apis', '0002_alter_customapi_authentication_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customapi',
            old_name='authentication_details',
            new_name='authentication_token',
        ),
    ]
