# Generated by Django 5.0.6 on 2024-07-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_apis', '0003_rename_authentication_details_customapi_authentication_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customapi',
            name='authentication_token',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
