# Generated by Django 5.0.6 on 2024-07-26 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm_apis', '0004_alter_customapi_authentication_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customapi',
            name='body_param_names',
        ),
        migrations.RemoveField(
            model_name='customapi',
            name='http_methods',
        ),
        migrations.RemoveField(
            model_name='customapi',
            name='path_param_names',
        ),
        migrations.RemoveField(
            model_name='customapi',
            name='query_param_names',
        ),
    ]
