# Generated by Django 5.0.6 on 2024-07-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_apis', '0005_remove_customapi_body_param_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customapi',
            name='authentication_token',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
