# Generated by Django 5.0.6 on 2024-07-20 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0482_alter_assistant_assistant_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeRepositoryConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_clone_url', models.CharField(max_length=5000)),
                ('git_username', models.CharField(max_length=1000)),
                ('git_password', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('class_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('vectorizer', models.CharField(blank=True, choices=[('text2vec-openai', 'Text2Vec (OpenAI)')], default='text2vec-openai', max_length=100, null=True)),
                ('vectorizer_api_key', models.CharField(blank=True, max_length=1000, null=True)),
                ('embedding_chunk_size', models.IntegerField(default=1024)),
                ('embedding_chunk_overlap', models.IntegerField(default=256)),
                ('schema_json', models.TextField(blank=True, null=True)),
                ('search_instance_retrieval_limit', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
            ],
            options={
                'verbose_name': 'Code Repository Connection',
                'verbose_name_plural': 'Code Repository Connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeRepositoryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file_name', models.CharField(max_length=1000)),
                ('document_description', models.TextField()),
                ('document_metadata', models.JSONField()),
                ('document_uri', models.CharField(blank=True, max_length=1000, null=True)),
                ('code_repo_uuid', models.CharField(blank=True, max_length=1000, null=True)),
                ('document_content_temporary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_repository_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource_code_repository.coderepositoryconnection')),
            ],
            options={
                'verbose_name': 'Code Repository File',
                'verbose_name_plural': 'Code Repository Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='coderepositoryconnection',
            name='code_repository_files',
            field=models.ManyToManyField(blank=True, related_name='code_repository', to='datasource_code_repository.coderepositoryfile'),
        ),
        migrations.CreateModel(
            name='CodeRepositoryFileChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_number', models.IntegerField()),
                ('chunk_content', models.TextField()),
                ('chunk_metadata', models.TextField()),
                ('chunk_document_uri', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_base_uuid', models.CharField(blank=True, max_length=1000, null=True)),
                ('document_uuid', models.CharField(blank=True, max_length=1000, null=True)),
                ('code_repository_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource_code_repository.coderepositoryconnection')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='datasource_code_repository.coderepositoryfile')),
            ],
            options={
                'verbose_name': 'Code Repository File Chunk',
                'verbose_name_plural': 'Code Repository File Chunks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='coderepositoryfile',
            name='document_chunks',
            field=models.ManyToManyField(blank=True, related_name='files', to='datasource_code_repository.coderepositoryfilechunk'),
        ),
        migrations.AddIndex(
            model_name='coderepositoryconnection',
            index=models.Index(fields=['assistant', 'name'], name='datasource__assista_4ccb93_idx'),
        ),
        migrations.AddIndex(
            model_name='coderepositoryconnection',
            index=models.Index(fields=['assistant', 'created_at'], name='datasource__assista_a59b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='coderepositoryconnection',
            index=models.Index(fields=['assistant', 'updated_at'], name='datasource__assista_f51973_idx'),
        ),
        migrations.AddIndex(
            model_name='coderepositoryconnection',
            index=models.Index(fields=['class_name'], name='datasource__class_n_45bcd3_idx'),
        ),
        migrations.AddIndex(
            model_name='coderepositoryconnection',
            index=models.Index(fields=['vectorizer'], name='datasource__vectori_254978_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coderepositoryconnection',
            unique_together={('assistant', 'name')},
        ),
        migrations.AddIndex(
            model_name='coderepositoryfilechunk',
            index=models.Index(fields=['code_repository_connection', 'file', 'chunk_number'], name='datasource__code_re_2d8525_idx'),
        ),
        migrations.AddIndex(
            model_name='coderepositoryfilechunk',
            index=models.Index(fields=['code_repository_connection', 'file', 'created_at'], name='datasource__code_re_11cb83_idx'),
        ),
        migrations.AddIndex(
            model_name='coderepositoryfilechunk',
            index=models.Index(fields=['code_repository_connection', 'file', 'updated_at'], name='datasource__code_re_b550ea_idx'),
        ),
        migrations.AddIndex(
            model_name='coderepositoryfile',
            index=models.Index(fields=['code_repository_connection', 'document_file_name'], name='datasource__code_re_a7097e_idx'),
        ),
        migrations.AddIndex(
            model_name='coderepositoryfile',
            index=models.Index(fields=['code_repository_connection', 'created_at'], name='datasource__code_re_440a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='coderepositoryfile',
            index=models.Index(fields=['code_repository_connection', 'updated_at'], name='datasource__code_re_47b97b_idx'),
        ),
    ]
