# Generated by Django 5.0.6 on 2024-07-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_code_repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coderepositoryconnection',
            name='host_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='coderepositoryconnection',
            name='provider',
            field=models.CharField(choices=[('weaviate', 'Weaviate')], default='weaviate', max_length=100),
        ),
        migrations.AddField(
            model_name='coderepositoryconnection',
            name='provider_api_key',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
