# Generated by Django 5.1.1 on 2024-09-23 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('packages', models.JSONField(blank=True, default=list)),
                ('input_fields', models.JSONField(blank=True, default=list)),
                ('output_fields', models.JSONField(blank=True, default=list)),
                ('code_text', models.TextField(blank=True, default='')),
                ('secrets', models.JSONField(blank=True, default=dict)),
                ('function_picture', models.ImageField(blank=True, null=True, upload_to='custom_functions/%YYYY/%mm/%dd/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Function',
                'verbose_name_plural': 'Custom Functions',
            },
        ),
        migrations.CreateModel(
            name='CustomFunctionReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_source', models.CharField(blank=True, default='internal', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('custom_function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm_functions.customfunction')),
            ],
            options={
                'verbose_name': 'Custom Function Reference',
                'verbose_name_plural': 'Custom Function References',
            },
        ),
        migrations.AddField(
            model_name='customfunction',
            name='custom_function_references',
            field=models.ManyToManyField(blank=True, to='mm_functions.customfunctionreference'),
        ),
        migrations.AddIndex(
            model_name='customfunctionreference',
            index=models.Index(fields=['custom_function', 'assistant'], name='mm_function_custom__8dd53c_idx'),
        ),
        migrations.AddIndex(
            model_name='customfunctionreference',
            index=models.Index(fields=['assistant', 'custom_function', 'created_by_user'], name='mm_function_assista_3ced42_idx'),
        ),
        migrations.AddIndex(
            model_name='customfunctionreference',
            index=models.Index(fields=['created_at'], name='mm_function_created_7bc495_idx'),
        ),
        migrations.AddIndex(
            model_name='customfunctionreference',
            index=models.Index(fields=['assistant'], name='mm_function_assista_057527_idx'),
        ),
        migrations.AddIndex(
            model_name='customfunctionreference',
            index=models.Index(fields=['custom_function'], name='mm_function_custom__5a5ccd_idx'),
        ),
        migrations.AddIndex(
            model_name='customfunctionreference',
            index=models.Index(fields=['created_by_user'], name='mm_function_created_d67115_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customfunctionreference',
            unique_together={('custom_function', 'assistant')},
        ),
        migrations.AddIndex(
            model_name='customfunction',
            index=models.Index(fields=['name'], name='mm_function_name_1f02c1_idx'),
        ),
        migrations.AddIndex(
            model_name='customfunction',
            index=models.Index(fields=['created_by_user'], name='mm_function_created_93c202_idx'),
        ),
        migrations.AddIndex(
            model_name='customfunction',
            index=models.Index(fields=['created_at'], name='mm_function_created_2a486c_idx'),
        ),
        migrations.AddIndex(
            model_name='customfunction',
            index=models.Index(fields=['updated_at'], name='mm_function_updated_16e748_idx'),
        ),
        migrations.AddIndex(
            model_name='customfunction',
            index=models.Index(fields=['is_public'], name='mm_function_is_publ_b31b28_idx'),
        ),
        migrations.AddIndex(
            model_name='customfunction',
            index=models.Index(fields=['is_featured'], name='mm_function_is_feat_610cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='customfunction',
            index=models.Index(fields=['name', 'is_public'], name='mm_function_name_25affd_idx'),
        ),
    ]
