# Generated by Django 5.0.6 on 2024-07-23 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0488_alter_assistant_assistant_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CustomFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_from_store', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('input_fields', models.JSONField(blank=True, default=dict)),
                ('output_fields', models.JSONField(blank=True, default=dict)),
                ('code_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
                ('store_function_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mm_functions.storefunction')),
            ],
            options={
                'verbose_name': 'Custom Function',
                'verbose_name_plural': 'Custom Functions',
            },
        ),
    ]
