# Generated by Django 5.0.6 on 2024-07-23 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0489_alter_assistant_assistant_image'),
        ('mm_functions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfunction',
            name='store_function_id',
        ),
        migrations.RenameField(
            model_name='customfunction',
            old_name='is_from_store',
            new_name='is_store_function',
        ),
        migrations.RemoveField(
            model_name='customfunction',
            name='assistant',
        ),
        migrations.CreateModel(
            name='CustomFunctionReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('custom_function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm_functions.customfunction')),
            ],
        ),
        migrations.AddField(
            model_name='customfunction',
            name='references',
            field=models.ManyToManyField(through='mm_functions.CustomFunctionReference', to='assistants.assistant'),
        ),
        migrations.DeleteModel(
            name='StoreFunction',
        ),
    ]
