# Generated by Django 5.0.6 on 2024-07-23 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0495_alter_assistant_assistant_image'),
        ('mm_functions', '0002_remove_customfunction_store_function_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfunctionreference',
            options={'verbose_name': 'Custom Function Reference', 'verbose_name_plural': 'Custom Function References'},
        ),
        migrations.RenameField(
            model_name='customfunction',
            old_name='is_store_function',
            new_name='is_public',
        ),
        migrations.RemoveField(
            model_name='customfunction',
            name='references',
        ),
        migrations.AddField(
            model_name='customfunction',
            name='custom_function_references',
            field=models.ManyToManyField(blank=True, to='mm_functions.customfunctionreference'),
        ),
        migrations.AddField(
            model_name='customfunction',
            name='packages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='customfunction',
            index=models.Index(fields=['name'], name='mm_function_name_1f02c1_idx'),
        ),
        migrations.AddIndex(
            model_name='customfunction',
            index=models.Index(fields=['created_at'], name='mm_function_created_2a486c_idx'),
        ),
        migrations.AddIndex(
            model_name='customfunction',
            index=models.Index(fields=['updated_at'], name='mm_function_updated_16e748_idx'),
        ),
        migrations.AddIndex(
            model_name='customfunction',
            index=models.Index(fields=['is_public'], name='mm_function_is_publ_b31b28_idx'),
        ),
        migrations.AddIndex(
            model_name='customfunction',
            index=models.Index(fields=['name', 'is_public'], name='mm_function_name_25affd_idx'),
        ),
        migrations.AddIndex(
            model_name='customfunctionreference',
            index=models.Index(fields=['custom_function', 'assistant'], name='mm_function_custom__8dd53c_idx'),
        ),
        migrations.AddIndex(
            model_name='customfunctionreference',
            index=models.Index(fields=['assistant', 'custom_function', 'created_by_user'], name='mm_function_assista_3ced42_idx'),
        ),
        migrations.AddIndex(
            model_name='customfunctionreference',
            index=models.Index(fields=['created_at'], name='mm_function_created_7bc495_idx'),
        ),
        migrations.AddIndex(
            model_name='customfunctionreference',
            index=models.Index(fields=['assistant'], name='mm_function_assista_057527_idx'),
        ),
        migrations.AddIndex(
            model_name='customfunctionreference',
            index=models.Index(fields=['custom_function'], name='mm_function_custom__5a5ccd_idx'),
        ),
        migrations.AddIndex(
            model_name='customfunctionreference',
            index=models.Index(fields=['created_by_user'], name='mm_function_created_d67115_idx'),
        ),
    ]
