# Generated by Django 5.0.6 on 2024-07-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_functions', '0003_alter_customfunctionreference_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfunction',
            name='input_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='customfunction',
            name='output_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
