# Generated by Django 5.0.6 on 2024-07-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_functions', '0004_alter_customfunction_input_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfunction',
            name='function_picture',
            field=models.ImageField(blank=True, null=True, upload_to='custom_functions/%YYYY/%mm/%dd/'),
        ),
    ]
