# Generated by Django 5.0.6 on 2024-07-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_functions', '0006_customfunction_created_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfunctionreference',
            name='function_source',
            field=models.CharField(blank=True, default='custom', max_length=255),
        ),
    ]
