# Generated by Django 5.0.6 on 2024-07-24 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_functions', '0007_customfunctionreference_function_source'),
        ('organization', '0600_alter_organization_organization_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customfunction',
            name='created_by_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.organization'),
        ),
        migrations.AddIndex(
            model_name='customfunction',
            index=models.Index(fields=['created_by_user'], name='mm_function_created_93c202_idx'),
        ),
        migrations.AddIndex(
            model_name='customfunction',
            index=models.Index(fields=['created_by_organization'], name='mm_function_created_b69827_idx'),
        ),
    ]
