# Generated by Django 5.0.6 on 2024-07-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm_functions', '0008_customfunction_created_by_organization_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customfunction',
            name='mm_function_created_b69827_idx',
        ),
        migrations.RemoveField(
            model_name='customfunction',
            name='created_by_organization',
        ),
    ]
