# Generated by Django 5.0.6 on 2024-07-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_functions', '0009_remove_customfunction_mm_function_created_b69827_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfunction',
            name='categories',
            field=models.JSONField(blank=True, default=['miscellaneous']),
        ),
    ]
