# Generated by Django 5.0.6 on 2024-07-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_functions', '0010_customfunction_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfunction',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
