# Generated by Django 5.0.6 on 2024-07-26 00:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0513_alter_assistant_assistant_image'),
        ('mm_functions', '0011_alter_customfunction_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customfunction',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customfunctionreference',
            name='function_source',
            field=models.CharField(blank=True, default='internal', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='customfunctionreference',
            unique_together={('custom_function', 'assistant')},
        ),
        migrations.AddIndex(
            model_name='customfunction',
            index=models.Index(fields=['is_featured'], name='mm_function_is_feat_610cc1_idx'),
        ),
    ]
