# Generated by Django 5.0.6 on 2024-07-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_functions', '0012_customfunction_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfunction',
            name='secrets',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
