# Generated by Django 5.0.8 on 2024-12-14 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SinapteraConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active_on_assistants', models.BooleanField(default=False)),
                ('is_active_on_leanmods', models.BooleanField(default=False)),
                ('is_active_on_orchestrators', models.BooleanField(default=False)),
                ('is_active_on_voidforgers', models.BooleanField(default=False)),
                ('rubric_weight_comprehensiveness', models.IntegerField(default=10)),
                ('rubric_weight_accuracy', models.IntegerField(default=9)),
                ('rubric_weight_relevancy', models.IntegerField(default=8)),
                ('rubric_weight_cohesiveness', models.IntegerField(default=8)),
                ('rubric_weight_diligence', models.IntegerField(default=6)),
                ('rubric_weight_grammar', models.IntegerField(default=4)),
                ('rubric_weight_naturalness', models.IntegerField(default=2)),
                ('branching_factor', models.IntegerField(default=4)),
                ('branch_keeping_factor', models.IntegerField(default=2)),
                ('evaluation_depth_factor', models.IntegerField(default=4)),
                ('additional_rubric_criteria', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sinaptera_configuration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sinaptera Configuration',
                'verbose_name_plural': 'Sinaptera Configurations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='sinaptera_s_created_6f3f1f_idx'), models.Index(fields=['updated_at'], name='sinaptera_s_updated_82f8fd_idx')],
            },
        ),
    ]
