# Generated by Django 5.0.8 on 2024-12-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinaptera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinapteraconfiguration',
            name='nitro_boost',
            field=models.BooleanField(default=False),
        ),
    ]
