# Generated by Django 5.1.1 on 2024-09-23 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0004_initial'),
        ('llm_core', '0002_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('instructions', models.TextField(blank=True, default='')),
                ('workflow_step_guide', models.TextField(blank=True, default='')),
                ('maximum_assistant_limits', models.IntegerField(default=10)),
                ('response_template', models.TextField(blank=True, default='')),
                ('audience', models.CharField(max_length=1000)),
                ('tone', models.CharField(max_length=1000)),
                ('response_language', models.CharField(choices=[('auto', 'Auto (Detect)'), ('sq', 'Albanian'), ('ar', 'Arabic'), ('bs', 'Bosnian'), ('bg', 'Bulgarian'), ('zh', 'Chinese'), ('hr', 'Croatian'), ('cs', 'Czech'), ('da', 'Danish'), ('nl', 'Dutch'), ('en', 'English'), ('et', 'Estonian'), ('fi', 'Finnish'), ('fi', 'Finnish'), ('fr', 'French'), ('de', 'German'), ('el', 'Greek'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hu', 'Hungarian'), ('is', 'Icelandic'), ('id', 'Indonesian'), ('ga', 'Irish'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('lv', 'Latvian'), ('lt', 'Lithuanian'), ('mk', 'Macedonian'), ('ms', 'Malay'), ('no', 'Norwegian'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sr', 'Serbian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('es', 'Spanish'), ('sv', 'Swedish'), ('th', 'Thai'), ('tr', 'Turkish'), ('uk', 'Ukrainian'), ('cy', 'Welsh')], default='auto', max_length=10)),
                ('maestro_image', models.ImageField(blank=True, max_length=5000, null=True, upload_to='maestro_images/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maestros_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maestros_last_updated_by_user', to=settings.AUTH_USER_MODEL)),
                ('llm_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maestros', to='llm_core.llmcore')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maestros', to='organization.organization')),
                ('workers', models.ManyToManyField(blank=True, related_name='maestros', to='assistants.assistant')),
            ],
            options={
                'verbose_name': 'Maestro',
                'verbose_name_plural': 'Maestros',
            },
        ),
        migrations.CreateModel(
            name='OrchestrationQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orchestration_queries_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orchestration_queries_last_updated_by_user', to=settings.AUTH_USER_MODEL)),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='orchestrations.maestro')),
            ],
            options={
                'verbose_name': 'Orchestration Query',
                'verbose_name_plural': 'Orchestration Queries',
            },
        ),
        migrations.CreateModel(
            name='OrchestrationQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('user', 'User'), ('info', 'Info'), ('error', 'Error'), ('worker_request', 'Worker Request'), ('worker_response', 'Worker Response'), ('maestro_answer', 'Maestro Answer')], default='info', max_length=100)),
                ('log_text_content', models.TextField()),
                ('log_image_contents', models.JSONField(blank=True, default=list, null=True)),
                ('log_file_contents', models.JSONField(blank=True, default=list, null=True)),
                ('log_audio_contents', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assistants.assistant')),
                ('orchestration_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='orchestrations.orchestrationquery')),
            ],
            options={
                'verbose_name': 'Orchestration Query Log',
                'verbose_name_plural': 'Orchestration Query Logs',
            },
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['organization'], name='orchestrati_organiz_a77bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['llm_model'], name='orchestrati_llm_mod_9e315d_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['name'], name='orchestrati_name_dc7565_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['response_language'], name='orchestrati_respons_a7ff6e_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['created_by_user'], name='orchestrati_created_72306e_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['last_updated_by_user'], name='orchestrati_last_up_fd5844_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['created_at'], name='orchestrati_created_151342_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['updated_at'], name='orchestrati_updated_34abf2_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['organization', 'llm_model'], name='orchestrati_organiz_236117_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['organization', 'name'], name='orchestrati_organiz_51dc96_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['organization', 'created_by_user'], name='orchestrati_organiz_0c2892_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['organization', 'last_updated_by_user'], name='orchestrati_organiz_791a90_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['organization', 'created_at'], name='orchestrati_organiz_4c6453_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['organization', 'updated_at'], name='orchestrati_organiz_3b2585_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['llm_model', 'name'], name='orchestrati_llm_mod_981b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['llm_model', 'created_by_user'], name='orchestrati_llm_mod_cb9bb1_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['llm_model', 'last_updated_by_user'], name='orchestrati_llm_mod_bfccb6_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['llm_model', 'created_at'], name='orchestrati_llm_mod_7ea904_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['llm_model', 'updated_at'], name='orchestrati_llm_mod_ab94c8_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['created_by_user', 'created_at'], name='orchestrati_created_7f50bf_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['created_by_user', 'updated_at'], name='orchestrati_created_e7c3ba_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['last_updated_by_user', 'created_at'], name='orchestrati_last_up_b352a0_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['last_updated_by_user', 'updated_at'], name='orchestrati_last_up_520390_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['organization', 'llm_model', 'name'], name='orchestrati_organiz_e082da_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['organization', 'llm_model', 'created_by_user'], name='orchestrati_organiz_d78c02_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['organization', 'llm_model', 'last_updated_by_user'], name='orchestrati_organiz_1e905b_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['organization', 'llm_model', 'created_at'], name='orchestrati_organiz_f5f102_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['organization', 'llm_model', 'updated_at'], name='orchestrati_organiz_4388f2_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['organization', 'name', 'created_at'], name='orchestrati_organiz_f261c6_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['organization', 'name', 'updated_at'], name='orchestrati_organiz_988369_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['organization', 'created_by_user', 'created_at'], name='orchestrati_organiz_72aebe_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['organization', 'created_by_user', 'updated_at'], name='orchestrati_organiz_9932a1_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['organization', 'last_updated_by_user', 'created_at'], name='orchestrati_organiz_95b41c_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['organization', 'last_updated_by_user', 'updated_at'], name='orchestrati_organiz_ec2a89_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['llm_model', 'name', 'created_at'], name='orchestrati_llm_mod_3db4a1_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['llm_model', 'name', 'updated_at'], name='orchestrati_llm_mod_35b545_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['llm_model', 'created_by_user', 'created_at'], name='orchestrati_llm_mod_06b5c9_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['llm_model', 'created_by_user', 'updated_at'], name='orchestrati_llm_mod_1c5fd4_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['llm_model', 'last_updated_by_user', 'created_at'], name='orchestrati_llm_mod_192dfe_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['llm_model', 'last_updated_by_user', 'updated_at'], name='orchestrati_llm_mod_638fce_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['created_by_user', 'created_at', 'updated_at'], name='orchestrati_created_7085ea_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['last_updated_by_user', 'created_at', 'updated_at'], name='orchestrati_last_up_ca583d_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['organization', 'llm_model', 'name', 'created_at'], name='orchestrati_organiz_d34d16_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['organization', 'llm_model', 'name', 'updated_at'], name='orchestrati_organiz_c92c90_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['organization', 'llm_model', 'created_by_user', 'created_at'], name='orchestrati_organiz_26bf6b_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['organization', 'llm_model', 'created_by_user', 'updated_at'], name='orchestrati_organiz_30c485_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['organization', 'llm_model', 'last_updated_by_user', 'created_at'], name='orchestrati_organiz_0eae9c_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['organization', 'llm_model', 'last_updated_by_user', 'updated_at'], name='orchestrati_organiz_9f6ab4_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['organization', 'name', 'created_at', 'updated_at'], name='orchestrati_organiz_2aa491_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['organization', 'created_by_user', 'created_at', 'updated_at'], name='orchestrati_organiz_643c30_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['organization', 'last_updated_by_user', 'created_at', 'updated_at'], name='orchestrati_organiz_03875a_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['llm_model', 'name', 'created_at', 'updated_at'], name='orchestrati_llm_mod_3bbd58_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['llm_model', 'created_by_user', 'created_at', 'updated_at'], name='orchestrati_llm_mod_610b81_idx'),
        ),
        migrations.AddIndex(
            model_name='maestro',
            index=models.Index(fields=['llm_model', 'last_updated_by_user', 'created_at', 'updated_at'], name='orchestrati_llm_mod_b8090b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='maestro',
            unique_together={('organization', 'llm_model', 'name')},
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['maestro'], name='orchestrati_maestro_43839d_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['query_text'], name='orchestrati_query_t_71ac33_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['created_by_user'], name='orchestrati_created_36b425_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['last_updated_by_user'], name='orchestrati_last_up_893e28_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['created_at'], name='orchestrati_created_a4a5f6_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['updated_at'], name='orchestrati_updated_3285bc_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['maestro', 'query_text'], name='orchestrati_maestro_59ea81_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['maestro', 'created_by_user'], name='orchestrati_maestro_9732bf_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['maestro', 'last_updated_by_user'], name='orchestrati_maestro_5aa9b8_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['maestro', 'created_at'], name='orchestrati_maestro_c33f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['maestro', 'updated_at'], name='orchestrati_maestro_473a47_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['query_text', 'created_at'], name='orchestrati_query_t_774686_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['query_text', 'updated_at'], name='orchestrati_query_t_957cdd_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['created_by_user', 'created_at'], name='orchestrati_created_55ebae_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['created_by_user', 'updated_at'], name='orchestrati_created_b9ae07_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['last_updated_by_user', 'created_at'], name='orchestrati_last_up_94c4e3_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['last_updated_by_user', 'updated_at'], name='orchestrati_last_up_e1e8bd_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['maestro', 'query_text', 'created_at'], name='orchestrati_maestro_a41df7_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['maestro', 'query_text', 'updated_at'], name='orchestrati_maestro_007eba_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['maestro', 'created_by_user', 'created_at'], name='orchestrati_maestro_088901_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['maestro', 'created_by_user', 'updated_at'], name='orchestrati_maestro_68f1f3_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['maestro', 'last_updated_by_user', 'created_at'], name='orchestrati_maestro_ad49d0_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['maestro', 'last_updated_by_user', 'updated_at'], name='orchestrati_maestro_1227cf_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['query_text', 'created_at', 'updated_at'], name='orchestrati_query_t_1f3431_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['created_by_user', 'created_at', 'updated_at'], name='orchestrati_created_7f7e31_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['last_updated_by_user', 'created_at', 'updated_at'], name='orchestrati_last_up_9c94e8_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['maestro', 'query_text', 'created_at', 'updated_at'], name='orchestrati_maestro_e08d07_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['maestro', 'created_by_user', 'created_at', 'updated_at'], name='orchestrati_maestro_4a7e72_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquery',
            index=models.Index(fields=['maestro', 'last_updated_by_user', 'created_at', 'updated_at'], name='orchestrati_maestro_b2ae7d_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquerylog',
            index=models.Index(fields=['orchestration_query'], name='orchestrati_orchest_841848_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquerylog',
            index=models.Index(fields=['created_at'], name='orchestrati_created_14b08d_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationquerylog',
            index=models.Index(fields=['orchestration_query', 'created_at'], name='orchestrati_orchest_077914_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orchestrationquerylog',
            unique_together={('orchestration_query', 'created_at')},
        ),
    ]
