# Generated by Django 5.0.8 on 2024-11-13 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0007_alter_assistant_context_overflow_strategy'),
        ('orchestrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrchestrationReactantAssistantConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('orchestration_maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrations.maestro')),
            ],
            options={
                'verbose_name': 'Orchestration Reactant Assistant Connection',
                'verbose_name_plural': 'Orchestration Reactant Assistant Connections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['orchestration_maestro', 'assistant'], name='orchestrati_orchest_cca370_idx'), models.Index(fields=['assistant', 'orchestration_maestro'], name='orchestrati_assista_955afa_idx')],
                'unique_together': {('orchestration_maestro', 'assistant')},
            },
        ),
    ]
