# Generated by Django 5.1 on 2024-08-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestro',
            name='maestro_image',
            field=models.ImageField(blank=True, max_length=5000, null=True, upload_to='maestro_images/%Y/%m/%d/p9pK1AEsLaVtdbB9'),
        ),
    ]
