# Generated by Django 5.0.8 on 2024-12-01 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrations', '0002_orchestrationreactantassistantconnection'),
        ('organization', '0005_alter_organization_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='maestro',
            unique_together={('organization', 'name')},
        ),
    ]
