# Generated by Django 5.0.8 on 2024-12-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrations', '0003_alter_maestro_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchestrationquerylog',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
