# Generated by Django 5.1 on 2024-08-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrations', '0004_alter_maestro_maestro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestro',
            name='maestro_image',
            field=models.ImageField(blank=True, max_length=5000, null=True, upload_to='maestro_images/%Y/%m/%d/BRNG6QitNZrJjNBP'),
        ),
    ]
