# Generated by Django 5.0.8 on 2024-12-15 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrations', '0005_remove_maestro_orchestrati_organiz_e082da_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orchestrationquery',
            name='orchestrati_query_t_774686_idx',
        ),
        migrations.RemoveIndex(
            model_name='orchestrationquery',
            name='orchestrati_query_t_957cdd_idx',
        ),
        migrations.RemoveIndex(
            model_name='orchestrationquery',
            name='orchestrati_created_55ebae_idx',
        ),
        migrations.RemoveIndex(
            model_name='orchestrationquery',
            name='orchestrati_created_b9ae07_idx',
        ),
        migrations.RemoveIndex(
            model_name='orchestrationquery',
            name='orchestrati_last_up_94c4e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='orchestrationquery',
            name='orchestrati_last_up_e1e8bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='orchestrationquery',
            name='orchestrati_maestro_a41df7_idx',
        ),
        migrations.RemoveIndex(
            model_name='orchestrationquery',
            name='orchestrati_maestro_007eba_idx',
        ),
        migrations.RemoveIndex(
            model_name='orchestrationquery',
            name='orchestrati_maestro_088901_idx',
        ),
        migrations.RemoveIndex(
            model_name='orchestrationquery',
            name='orchestrati_maestro_68f1f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='orchestrationquery',
            name='orchestrati_maestro_ad49d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='orchestrationquery',
            name='orchestrati_maestro_1227cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='orchestrationquery',
            name='orchestrati_query_t_1f3431_idx',
        ),
        migrations.RemoveIndex(
            model_name='orchestrationquery',
            name='orchestrati_created_7f7e31_idx',
        ),
        migrations.RemoveIndex(
            model_name='orchestrationquery',
            name='orchestrati_last_up_9c94e8_idx',
        ),
        migrations.RemoveIndex(
            model_name='orchestrationquery',
            name='orchestrati_maestro_e08d07_idx',
        ),
        migrations.RemoveIndex(
            model_name='orchestrationquery',
            name='orchestrati_maestro_4a7e72_idx',
        ),
        migrations.RemoveIndex(
            model_name='orchestrationquery',
            name='orchestrati_maestro_b2ae7d_idx',
        ),
    ]
