# Generated by Django 5.0.8 on 2024-09-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrations', '0017_alter_maestro_maestro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestro',
            name='maestro_image',
            field=models.ImageField(blank=True, max_length=5000, null=True, upload_to='maestro_images/%Y/%m/%d/DQeS27A0X9JTQ5eU'),
        ),
    ]
