# Generated by Django 5.0.6 on 2024-06-29 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0008_alter_organization_organization_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('provider', models.CharField(choices=[('OA', 'OpenAI-GPT')], max_length=2)),
                ('api_key', models.CharField(max_length=8192)),
                ('model_name', models.CharField(choices=[('gpt-4o', 'gpt-4o'), ('gpt-4-turbo', 'gpt-4-turbo'), ('gpt-4', 'gpt-4'), ('gpt-3.5-turbo-16k', 'gpt-3.5-turbo-16k'), ('gpt-3.5-turbo-0125', 'gpt-3.5-turbo-0125'), ('gpt-3.5-turbo', 'gpt-3.5-turbo')], max_length=255)),
                ('temperature', models.FloatField(default=0.5)),
                ('maximum_tokens', models.IntegerField(default=4094)),
                ('stop_sequences', models.TextField(blank=True, default='')),
                ('tone', models.CharField(max_length=255)),
                ('audience', models.CharField(max_length=255)),
                ('top_p', models.FloatField(default=1.0)),
                ('frequency_penalty', models.FloatField(default=0.0)),
                ('presence_penalty', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_core_created_by_users', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_core_last_updated_by_users', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'verbose_name': 'LLM Core',
                'verbose_name_plural': 'LLM Cores',
            },
        ),
    ]
