# Generated by Django 5.1.1 on 2024-09-15 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('provider', models.CharField(choices=[('OA', 'OpenAI-GPT')], max_length=2)),
                ('api_key', models.CharField(max_length=8192)),
                ('model_name', models.CharField(max_length=1000)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('maximum_tokens', models.IntegerField(default=4094)),
                ('stop_sequences', models.TextField(blank=True, default='')),
                ('top_p', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('frequency_penalty', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('presence_penalty', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_core_created_by_users', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_core_last_updated_by_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM Core',
                'verbose_name_plural': 'LLM Cores',
                'ordering': ['-created_at'],
            },
        ),
    ]
