# Generated by Django 5.0.6 on 2024-06-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmcore',
            name='audience',
        ),
        migrations.RemoveField(
            model_name='llmcore',
            name='tone',
        ),
    ]
