#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Jupi.tr™
#  File: 0002_initial.py
#  Last Modified: 2024-09-25 17:51:06
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 01:36:32
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@jupi.tr.
#

# Generated by Django 5.1.1 on 2024-09-25 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm_core', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcore',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_cores', to='organization.organization'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['nickname'], name='llm_core_ll_nicknam_1fadd5_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['provider'], name='llm_core_ll_provide_ec2ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['model_name'], name='llm_core_ll_model_n_978cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['created_at'], name='llm_core_ll_created_05a363_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['updated_at'], name='llm_core_ll_updated_d52279_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['organization'], name='llm_core_ll_organiz_66f211_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['created_by_user'], name='llm_core_ll_created_db0636_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['last_updated_by_user'], name='llm_core_ll_last_up_983282_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['organization', 'nickname'], name='llm_core_ll_organiz_03ffba_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['organization', 'provider'], name='llm_core_ll_organiz_e3331e_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['organization', 'model_name'], name='llm_core_ll_organiz_b9b2fe_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['organization', 'created_at'], name='llm_core_ll_organiz_b67d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['organization', 'updated_at'], name='llm_core_ll_organiz_f8b980_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['organization', 'created_by_user'], name='llm_core_ll_organiz_908ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['organization', 'last_updated_by_user'], name='llm_core_ll_organiz_50db47_idx'),
        ),
    ]
