# Generated by Django 5.0.8 on 2024-11-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmcore',
            name='model_name',
            field=models.CharField(default='gpt-4', max_length=1000),
        ),
    ]
