# Generated by Django 5.0.6 on 2024-06-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0002_remove_llmcore_audience_remove_llmcore_tone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmcore',
            name='model_name',
            field=models.CharField(choices=[('gpt-4o', 'gpt-4o'), ('gpt-4-turbo', 'gpt-4-turbo'), ('gpt-4', 'gpt-4'), ('gpt-3.5-turbo-16k', 'gpt-3.5-turbo-16k'), ('gpt-3.5-turbo', 'gpt-3.5-turbo')], max_length=255),
        ),
    ]
