# Generated by Django 5.1 on 2024-08-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmcore',
            name='model_name',
            field=models.CharField(max_length=1000),
        ),
    ]
