# Generated by Django 5.0.6 on 2024-06-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0003_alter_llmcore_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmcore',
            name='frequency_penalty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='llmcore',
            name='presence_penalty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='llmcore',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='llmcore',
            name='top_p',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
