# Generated by Django 5.0.8 on 2024-12-01 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0004_alter_llmcore_model_name'),
        ('organization', '0005_alter_organization_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='llmcore',
            unique_together={('organization', 'nickname')},
        ),
    ]
