# Generated by Django 5.0.8 on 2024-12-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0005_alter_llmcore_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmcore',
            name='model_name',
            field=models.CharField(default='O1', max_length=1000),
        ),
    ]
