# Generated by Django 5.0.8 on 2024-12-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0006_alter_llmcore_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmcore',
            name='model_name',
            field=models.CharField(default='gpt-4o', max_length=1000),
        ),
    ]
