# Generated by Django 5.0.6 on 2024-07-03 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0006_alter_llmcore_organization'),
        ('organization', '0142_alter_organization_organization_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmcore',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
    ]
