# Generated by Django 5.0.8 on 2024-12-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0007_alter_llmcore_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmcore',
            name='model_name',
            field=models.CharField(default='o1-preview', max_length=1000),
        ),
    ]
