# Generated by Django 5.0.8 on 2025-01-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0008_alter_llmcore_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmcore',
            name='model_name',
            field=models.CharField(default='o1', max_length=1000),
        ),
    ]
