# Generated by Django 5.0.6 on 2024-07-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0008_alter_llmcore_organization'),
        ('organization', '0144_alter_organization_organization_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmcore',
            name='organization',
        ),
        migrations.AddField(
            model_name='llmcore',
            name='llm_organizations',
            field=models.ManyToManyField(related_name='organizations_llm_cores_set', to='organization.organization'),
        ),
    ]
