# Generated by Django 5.0.6 on 2024-07-03 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0009_remove_llmcore_organization_and_more'),
        ('organization', '0149_alter_organization_organization_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmcore',
            name='llm_organizations',
        ),
        migrations.AddField(
            model_name='llmcore',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_cores_created_by_organization', to='organization.organization'),
        ),
    ]
