# Generated by Django 5.0.6 on 2024-07-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0010_remove_llmcore_llm_organizations_and_more'),
        ('organization', '0151_alter_organization_organization_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmcore',
            name='organization',
        ),
        migrations.AddField(
            model_name='llmcore',
            name='llm_core_organizations',
            field=models.ManyToManyField(related_name='llm_cores_organization', to='organization.organization'),
        ),
    ]
