# Generated by Django 5.0.6 on 2024-07-03 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0012_remove_llmcore_llm_core_organizations_and_more'),
        ('organization', '0161_alter_organization_organization_assistants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmcore',
            name='organization',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='llm_cores_organization', to='organization.organization'),
        ),
    ]
