# Generated by Django 5.0.6 on 2024-07-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0013_alter_llmcore_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmcore',
            name='model_name',
            field=models.CharField(choices=[('gpt-4o', 'gpt-4o'), ('gpt-4-turbo', 'gpt-4-turbo'), ('gpt-4', 'gpt-4')], max_length=255),
        ),
    ]
