# Generated by Django 5.0.6 on 2024-07-16 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_core', '0014_alter_llmcore_model_name'),
        ('organization', '0504_alter_organization_organization_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llmcore',
            options={'ordering': ['-created_at'], 'verbose_name': 'LLM Core', 'verbose_name_plural': 'LLM Cores'},
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['nickname'], name='llm_core_ll_nicknam_1fadd5_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['provider'], name='llm_core_ll_provide_ec2ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['model_name'], name='llm_core_ll_model_n_978cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['created_at'], name='llm_core_ll_created_05a363_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['updated_at'], name='llm_core_ll_updated_d52279_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['organization'], name='llm_core_ll_organiz_66f211_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['created_by_user'], name='llm_core_ll_created_db0636_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['last_updated_by_user'], name='llm_core_ll_last_up_983282_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['organization', 'nickname'], name='llm_core_ll_organiz_03ffba_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['organization', 'provider'], name='llm_core_ll_organiz_e3331e_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['organization', 'model_name'], name='llm_core_ll_organiz_b9b2fe_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['organization', 'created_at'], name='llm_core_ll_organiz_b67d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['organization', 'updated_at'], name='llm_core_ll_organiz_f8b980_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['organization', 'created_by_user'], name='llm_core_ll_organiz_908ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcore',
            index=models.Index(fields=['organization', 'last_updated_by_user'], name='llm_core_ll_organiz_50db47_idx'),
        ),
    ]
