# Generated by Django 5.0.6 on 2024-07-09 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SQLDatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbms_type', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('database_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('schema_name', models.CharField(default='public', max_length=255)),
                ('schema_data_json', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomSQLQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('sql_query', models.TextField()),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='datasource_sql.sqldatabaseconnection')),
            ],
        ),
    ]
