#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Bimod.io™
#  File: 0001_initial.py
#  Last Modified: 2024-10-05 01:39:48
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 14:42:41
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@Bimod.io.
#
#
#

# Generated by Django 5.1.1 on 2024-09-25 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLDatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbms_type', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('database_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('one_time_sql_retrieval_instance_limit', models.IntegerField(default=100)),
                ('one_time_sql_retrieval_token_limit', models.IntegerField(default=10000)),
                ('is_read_only', models.BooleanField(default=True)),
                ('schema_data_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sql_database_connections', to='assistants.assistant')),
                ('created_by_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sql_database_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SQL Database Connection',
                'verbose_name_plural': 'SQL Database Connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomSQLQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('sql_query', models.TextField()),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_queries', to='datasource_sql.sqldatabaseconnection')),
            ],
            options={
                'verbose_name': 'Custom SQL Query',
                'verbose_name_plural': 'Custom SQL Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sqldatabaseconnection',
            index=models.Index(fields=['assistant', 'dbms_type', 'name'], name='datasource__assista_18c818_idx'),
        ),
        migrations.AddIndex(
            model_name='sqldatabaseconnection',
            index=models.Index(fields=['assistant', 'dbms_type', 'created_at'], name='datasource__assista_a10fc4_idx'),
        ),
        migrations.AddIndex(
            model_name='sqldatabaseconnection',
            index=models.Index(fields=['assistant', 'dbms_type', 'updated_at'], name='datasource__assista_184042_idx'),
        ),
        migrations.AddIndex(
            model_name='sqldatabaseconnection',
            index=models.Index(fields=['assistant', 'dbms_type', 'name', 'created_at'], name='datasource__assista_e5ca35_idx'),
        ),
        migrations.AddIndex(
            model_name='sqldatabaseconnection',
            index=models.Index(fields=['assistant', 'dbms_type', 'name', 'updated_at'], name='datasource__assista_3fb424_idx'),
        ),
        migrations.AddIndex(
            model_name='customsqlquery',
            index=models.Index(fields=['database_connection', 'name'], name='datasource__databas_5dddf7_idx'),
        ),
        migrations.AddIndex(
            model_name='customsqlquery',
            index=models.Index(fields=['database_connection', 'created_at'], name='datasource__databas_5fb66a_idx'),
        ),
        migrations.AddIndex(
            model_name='customsqlquery',
            index=models.Index(fields=['database_connection', 'updated_at'], name='datasource__databas_0c10b4_idx'),
        ),
        migrations.AddIndex(
            model_name='customsqlquery',
            index=models.Index(fields=['database_connection', 'name', 'created_at'], name='datasource__databas_efe9e7_idx'),
        ),
        migrations.AddIndex(
            model_name='customsqlquery',
            index=models.Index(fields=['database_connection', 'name', 'updated_at'], name='datasource__databas_d02b8c_idx'),
        ),
    ]
