# Generated by Django 5.0.8 on 2024-12-01 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0013_alter_assistantoldchatmessagesvectordata_unique_together'),
        ('datasource_sql', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sqldatabaseconnection',
            unique_together={('assistant', 'host', 'port', 'database_name')},
        ),
    ]
