# Generated by Django 5.0.6 on 2024-07-09 21:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0205_alter_assistant_assistant_image'),
        ('datasource_sql', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sqldatabaseconnection',
            name='assistant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sql_database_connections', to='assistants.assistant'),
        ),
        migrations.AddField(
            model_name='sqldatabaseconnection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sqldatabaseconnection',
            name='created_by_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sql_database_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sqldatabaseconnection',
            name='custom_queries',
            field=models.ManyToManyField(blank=True, to='datasource_sql.customsqlquery'),
        ),
        migrations.AddField(
            model_name='sqldatabaseconnection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
