# Generated by Django 5.0.8 on 2024-12-01 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_sql', '0002_alter_sqldatabaseconnection_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customsqlquery',
            unique_together={('database_connection', 'name')},
        ),
    ]
