# Generated by Django 5.0.6 on 2024-07-09 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_sql', '0002_sqldatabaseconnection_assistant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customsqlquery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Custom SQL Query', 'verbose_name_plural': 'Custom SQL Queries'},
        ),
        migrations.AlterModelOptions(
            name='sqldatabaseconnection',
            options={'ordering': ['-created_at'], 'verbose_name': 'SQL Database Connection', 'verbose_name_plural': 'SQL Database Connections'},
        ),
    ]
