# Generated by Django 5.0.8 on 2024-12-04 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_sql', '0003_alter_customsqlquery_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLSchemaChunkVectorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('raw_data_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('vector_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sql_database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource_sql.sqldatabaseconnection')),
            ],
            options={
                'verbose_name': 'SQL Schema Chunk Vector Data',
                'verbose_name_plural': 'SQL Schema Chunk Vector Data',
                'indexes': [models.Index(fields=['sql_database'], name='datasource__sql_dat_ff567c_idx'), models.Index(fields=['created_at'], name='datasource__created_5f3a02_idx'), models.Index(fields=['updated_at'], name='datasource__updated_156229_idx')],
            },
        ),
    ]
