# Generated by Django 5.0.6 on 2024-07-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_sql', '0003_alter_customsqlquery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqldatabaseconnection',
            name='is_read_only',
            field=models.BooleanField(default=True),
        ),
    ]
