# Generated by Django 5.0.8 on 2024-12-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_sql', '0004_sqlschemachunkvectordata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqldatabaseconnection',
            name='dbms_type',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('oracle', 'Oracle'), ('mariaDB', 'MariaDB')], max_length=50),
        ),
    ]
