# Generated by Django 5.0.6 on 2024-07-09 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_sql', '0004_sqldatabaseconnection_is_read_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqldatabaseconnection',
            name='schema_name',
        ),
    ]
