# Generated by Django 5.0.6 on 2024-07-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_sql', '0005_remove_sqldatabaseconnection_schema_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqldatabaseconnection',
            name='one_time_sql_retrieval_instance_limit',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='sqldatabaseconnection',
            name='one_time_sql_retrieval_token_limit',
            field=models.IntegerField(default=5000),
        ),
    ]
