# Generated by Django 5.0.8 on 2024-12-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_sql', '0005_alter_sqldatabaseconnection_dbms_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqldatabaseconnection',
            name='dbms_type',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('mssql', 'Microsoft SQL Server'), ('oracle', 'Oracle'), ('mariaDB', 'MariaDB')], max_length=50),
        ),
    ]
