# Generated by Django 5.0.6 on 2024-07-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_sql', '0006_sqldatabaseconnection_one_time_sql_retrieval_instance_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqldatabaseconnection',
            name='one_time_sql_retrieval_instance_limit',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='sqldatabaseconnection',
            name='one_time_sql_retrieval_token_limit',
            field=models.IntegerField(default=10000),
        ),
    ]
