# Generated by Django 5.0.8 on 2024-12-18 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0014_assistant_is_beamguard_active'),
        ('datasource_sql', '0006_alter_sqldatabaseconnection_dbms_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sqldatabaseconnection',
            unique_together={('assistant', 'database_name')},
        ),
    ]
