# Generated by Django 5.0.6 on 2024-07-16 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0405_alter_assistant_assistant_image'),
        ('datasource_sql', '0007_alter_sqldatabaseconnection_one_time_sql_retrieval_instance_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customsqlquery',
            index=models.Index(fields=['database_connection', 'name'], name='datasource__databas_5dddf7_idx'),
        ),
        migrations.AddIndex(
            model_name='customsqlquery',
            index=models.Index(fields=['database_connection', 'created_at'], name='datasource__databas_5fb66a_idx'),
        ),
        migrations.AddIndex(
            model_name='customsqlquery',
            index=models.Index(fields=['database_connection', 'updated_at'], name='datasource__databas_0c10b4_idx'),
        ),
        migrations.AddIndex(
            model_name='customsqlquery',
            index=models.Index(fields=['database_connection', 'name', 'created_at'], name='datasource__databas_efe9e7_idx'),
        ),
        migrations.AddIndex(
            model_name='customsqlquery',
            index=models.Index(fields=['database_connection', 'name', 'updated_at'], name='datasource__databas_d02b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='sqldatabaseconnection',
            index=models.Index(fields=['assistant', 'dbms_type', 'name'], name='datasource__assista_18c818_idx'),
        ),
        migrations.AddIndex(
            model_name='sqldatabaseconnection',
            index=models.Index(fields=['assistant', 'dbms_type', 'created_at'], name='datasource__assista_a10fc4_idx'),
        ),
        migrations.AddIndex(
            model_name='sqldatabaseconnection',
            index=models.Index(fields=['assistant', 'dbms_type', 'updated_at'], name='datasource__assista_184042_idx'),
        ),
        migrations.AddIndex(
            model_name='sqldatabaseconnection',
            index=models.Index(fields=['assistant', 'dbms_type', 'name', 'created_at'], name='datasource__assista_e5ca35_idx'),
        ),
        migrations.AddIndex(
            model_name='sqldatabaseconnection',
            index=models.Index(fields=['assistant', 'dbms_type', 'name', 'updated_at'], name='datasource__assista_3fb424_idx'),
        ),
    ]
