# Generated by Django 5.0.6 on 2024-08-02 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextHistoryMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_base_memory_uuid', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Context History Memory',
                'verbose_name_plural': 'Context History Memories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContextHistoryMemoryChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_number', models.IntegerField()),
                ('chunk_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_base_memory_uuid', models.CharField(blank=True, max_length=1000, null=True)),
                ('chunk_uuid', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Context History Memory Chunk',
                'verbose_name_plural': 'Context History Memory Chunks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentKnowledgeBaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('weaviate', 'Weaviate')], max_length=100)),
                ('host_url', models.CharField(max_length=1000)),
                ('provider_api_key', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(max_length=1000)),
                ('class_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField()),
                ('vectorizer', models.CharField(blank=True, choices=[('text2vec-openai', 'Text2Vec (OpenAI)')], default='text2vec-openai', max_length=100, null=True)),
                ('vectorizer_api_key', models.CharField(blank=True, max_length=1000, null=True)),
                ('embedding_chunk_size', models.IntegerField(default=1024)),
                ('embedding_chunk_overlap', models.IntegerField(default=256)),
                ('schema_json', models.TextField(blank=True, null=True)),
                ('search_instance_retrieval_limit', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Knowledge Base Connection',
                'verbose_name_plural': 'Document Knowledge Base Connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_full_uri', models.CharField(max_length=1000)),
                ('log_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document Processing Log',
                'verbose_name_plural': 'Document Processing Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML'), ('csv', 'CSV'), ('docx', 'DOCX'), ('ipynb', 'IPYNB'), ('json', 'JSON'), ('xml', 'XML'), ('txt', 'TXT'), ('md', 'MD'), ('rtf', 'RTF'), ('odt', 'ODT'), ('pptx', 'POWERPOINT'), ('xlsx', 'XLSX')], max_length=100)),
                ('document_file_name', models.CharField(max_length=1000)),
                ('document_description', models.TextField()),
                ('document_metadata', models.JSONField()),
                ('document_uri', models.CharField(blank=True, max_length=1000, null=True)),
                ('knowledge_base_uuid', models.CharField(blank=True, max_length=1000, null=True)),
                ('document_content_temporary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Knowledge Base Document',
                'verbose_name_plural': 'Knowledge Base Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseDocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_document_type', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('html', 'HTML'), ('csv', 'CSV'), ('docx', 'DOCX'), ('ipynb', 'IPYNB'), ('json', 'JSON'), ('xml', 'XML'), ('txt', 'TXT'), ('md', 'MD'), ('rtf', 'RTF'), ('odt', 'ODT'), ('pptx', 'POWERPOINT'), ('xlsx', 'XLSX')], max_length=100, null=True)),
                ('chunk_number', models.IntegerField()),
                ('chunk_content', models.TextField()),
                ('chunk_metadata', models.TextField()),
                ('chunk_document_uri', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_base_uuid', models.CharField(blank=True, max_length=1000, null=True)),
                ('document_uuid', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Knowledge Base Document Chunk',
                'verbose_name_plural': 'Knowledge Base Document Chunks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContextHistoryKnowledgeBaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('vectorizer', models.CharField(choices=[('text2vec-openai', 'Text2Vec (OpenAI)')], default='text2vec-openai', max_length=100)),
                ('vectorizer_api_key', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
            ],
            options={
                'verbose_name': 'Context History Knowledge Base Connection',
                'verbose_name_plural': 'Context History Knowledge Base Connections',
                'ordering': ['-created_at'],
            },
        ),
    ]
