# Generated by Django 5.1.1 on 2024-09-15 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0004_initial'),
        ('datasource_knowledge_base', '0001_initial'),
        ('multimodal_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contexthistoryknowledgebaseconnection',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='multimodal_chat.multimodalchat'),
        ),
        migrations.AddField(
            model_name='contexthistorymemory',
            name='context_history_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='datasource_knowledge_base.contexthistoryknowledgebaseconnection'),
        ),
        migrations.AddField(
            model_name='contexthistoryknowledgebaseconnection',
            name='context_history_memories',
            field=models.ManyToManyField(blank=True, related_name='knowledge_bases', to='datasource_knowledge_base.contexthistorymemory'),
        ),
        migrations.AddField(
            model_name='contexthistorymemorychunk',
            name='context_history_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource_knowledge_base.contexthistoryknowledgebaseconnection'),
        ),
        migrations.AddField(
            model_name='contexthistorymemorychunk',
            name='memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='datasource_knowledge_base.contexthistorymemory'),
        ),
        migrations.AddField(
            model_name='contexthistorymemory',
            name='memory_chunks',
            field=models.ManyToManyField(blank=True, related_name='memories', to='datasource_knowledge_base.contexthistorymemorychunk'),
        ),
        migrations.AddField(
            model_name='documentknowledgebaseconnection',
            name='assistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant'),
        ),
        migrations.AddIndex(
            model_name='documentprocessinglog',
            index=models.Index(fields=['document_full_uri'], name='datasource__documen_a82e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentprocessinglog',
            index=models.Index(fields=['created_at'], name='datasource__created_65dbc8_idx'),
        ),
        migrations.AddField(
            model_name='knowledgebasedocument',
            name='knowledge_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='datasource_knowledge_base.documentknowledgebaseconnection'),
        ),
        migrations.AddField(
            model_name='documentknowledgebaseconnection',
            name='knowledge_base_documents',
            field=models.ManyToManyField(blank=True, related_name='knowledge_bases', to='datasource_knowledge_base.knowledgebasedocument'),
        ),
        migrations.AddField(
            model_name='knowledgebasedocumentchunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='datasource_knowledge_base.knowledgebasedocument'),
        ),
        migrations.AddField(
            model_name='knowledgebasedocumentchunk',
            name='knowledge_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource_knowledge_base.documentknowledgebaseconnection'),
        ),
        migrations.AddField(
            model_name='knowledgebasedocument',
            name='document_chunks',
            field=models.ManyToManyField(blank=True, related_name='documents', to='datasource_knowledge_base.knowledgebasedocumentchunk'),
        ),
        migrations.AddIndex(
            model_name='contexthistoryknowledgebaseconnection',
            index=models.Index(fields=['assistant', 'chat'], name='datasource__assista_1b62e2_idx'),
        ),
        migrations.AddIndex(
            model_name='contexthistoryknowledgebaseconnection',
            index=models.Index(fields=['created_at'], name='datasource__created_66b5c9_idx'),
        ),
        migrations.AddIndex(
            model_name='contexthistoryknowledgebaseconnection',
            index=models.Index(fields=['updated_at'], name='datasource__updated_d5c2ae_idx'),
        ),
        migrations.AddIndex(
            model_name='contexthistoryknowledgebaseconnection',
            index=models.Index(fields=['class_name'], name='datasource__class_n_14893e_idx'),
        ),
        migrations.AddIndex(
            model_name='contexthistoryknowledgebaseconnection',
            index=models.Index(fields=['vectorizer'], name='datasource__vectori_aa6f31_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contexthistoryknowledgebaseconnection',
            unique_together={('assistant', 'chat')},
        ),
        migrations.AddIndex(
            model_name='contexthistorymemorychunk',
            index=models.Index(fields=['context_history_base', 'memory', 'chunk_number'], name='datasource__context_29106b_idx'),
        ),
        migrations.AddIndex(
            model_name='contexthistorymemorychunk',
            index=models.Index(fields=['context_history_base', 'memory', 'created_at'], name='datasource__context_6cf0ca_idx'),
        ),
        migrations.AddIndex(
            model_name='contexthistorymemorychunk',
            index=models.Index(fields=['context_history_base', 'memory', 'updated_at'], name='datasource__context_6ff907_idx'),
        ),
        migrations.AddIndex(
            model_name='contexthistorymemory',
            index=models.Index(fields=['context_history_base', 'memory_name'], name='datasource__context_22dcff_idx'),
        ),
        migrations.AddIndex(
            model_name='contexthistorymemory',
            index=models.Index(fields=['context_history_base', 'created_at'], name='datasource__context_50cdb2_idx'),
        ),
        migrations.AddIndex(
            model_name='contexthistorymemory',
            index=models.Index(fields=['context_history_base', 'updated_at'], name='datasource__context_64d621_idx'),
        ),
        migrations.AddIndex(
            model_name='documentknowledgebaseconnection',
            index=models.Index(fields=['provider', 'assistant', 'name'], name='datasource__provide_4ae798_idx'),
        ),
        migrations.AddIndex(
            model_name='documentknowledgebaseconnection',
            index=models.Index(fields=['provider', 'assistant', 'created_at'], name='datasource__provide_6893cf_idx'),
        ),
        migrations.AddIndex(
            model_name='documentknowledgebaseconnection',
            index=models.Index(fields=['provider', 'assistant', 'updated_at'], name='datasource__provide_e4d4ed_idx'),
        ),
        migrations.AddIndex(
            model_name='documentknowledgebaseconnection',
            index=models.Index(fields=['class_name'], name='datasource__class_n_580d70_idx'),
        ),
        migrations.AddIndex(
            model_name='documentknowledgebaseconnection',
            index=models.Index(fields=['vectorizer'], name='datasource__vectori_d8a1e6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentknowledgebaseconnection',
            unique_together={('host_url', 'assistant')},
        ),
        migrations.AddIndex(
            model_name='knowledgebasedocumentchunk',
            index=models.Index(fields=['knowledge_base', 'document', 'chunk_number'], name='datasource__knowled_678ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebasedocumentchunk',
            index=models.Index(fields=['knowledge_base', 'document', 'created_at'], name='datasource__knowled_6bfa01_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebasedocumentchunk',
            index=models.Index(fields=['knowledge_base', 'document', 'updated_at'], name='datasource__knowled_e0c1cd_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebasedocument',
            index=models.Index(fields=['knowledge_base', 'document_file_name'], name='datasource__knowled_b150d7_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebasedocument',
            index=models.Index(fields=['knowledge_base', 'created_at'], name='datasource__knowled_9e6066_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebasedocument',
            index=models.Index(fields=['knowledge_base', 'updated_at'], name='datasource__knowled_a6d8d5_idx'),
        ),
    ]
