# Generated by Django 5.0.6 on 2024-07-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentknowledgebaseconnection',
            name='class_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
