# Generated by Django 5.0.8 on 2024-11-17 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_knowledge_base', '0002_initial'),
        ('multimodal_chat', '0005_remove_multimodalchat_context_memory_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contexthistorymemory',
            name='context_history_base',
        ),
        migrations.RemoveField(
            model_name='contexthistorymemorychunk',
            name='context_history_base',
        ),
        migrations.RemoveField(
            model_name='contexthistorymemorychunk',
            name='memory',
        ),
        migrations.DeleteModel(
            name='ContextHistoryKnowledgeBaseConnection',
        ),
        migrations.DeleteModel(
            name='ContextHistoryMemory',
        ),
        migrations.DeleteModel(
            name='ContextHistoryMemoryChunk',
        ),
    ]
