# Generated by Django 5.0.6 on 2024-07-13 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0302_alter_assistant_assistant_image'),
        ('datasource_knowledge_base', '0002_alter_documentknowledgebaseconnection_class_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentknowledgebaseconnection',
            unique_together={('host_url', 'assistant')},
        ),
    ]
