# Generated by Django 5.0.8 on 2024-12-11 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0014_assistant_is_beamguard_active'),
        ('datasource_knowledge_base', '0003_remove_contexthistorymemory_context_history_base_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunkVectorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_document_type', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('html', 'HTML'), ('csv', 'CSV'), ('docx', 'DOCX'), ('ipynb', 'IPYNB'), ('json', 'JSON'), ('xml', 'XML'), ('txt', 'TXT'), ('md', 'MD'), ('rtf', 'RTF'), ('odt', 'ODT'), ('pptx', 'POWERPOINT'), ('xlsx', 'XLSX')], max_length=100, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('raw_data_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('vector_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Knowledge Base Document Chunk',
                'verbose_name_plural': 'Knowledge Base Document Chunks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='DocumentProcessingLog',
        ),
        migrations.RemoveField(
            model_name='knowledgebasedocumentchunk',
            name='document',
        ),
        migrations.RemoveField(
            model_name='knowledgebasedocumentchunk',
            name='knowledge_base',
        ),
        migrations.RemoveIndex(
            model_name='documentknowledgebaseconnection',
            name='datasource__provide_4ae798_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentknowledgebaseconnection',
            name='datasource__provide_6893cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentknowledgebaseconnection',
            name='datasource__provide_e4d4ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentknowledgebaseconnection',
            name='datasource__class_n_580d70_idx',
        ),
        migrations.RenameField(
            model_name='documentknowledgebaseconnection',
            old_name='class_name',
            new_name='vector_index_path',
        ),
        migrations.AlterUniqueTogether(
            name='documentknowledgebaseconnection',
            unique_together={('name', 'assistant')},
        ),
        migrations.RemoveField(
            model_name='knowledgebasedocument',
            name='document_content_temporary',
        ),
        migrations.RemoveField(
            model_name='knowledgebasedocument',
            name='document_uri',
        ),
        migrations.RemoveField(
            model_name='knowledgebasedocument',
            name='knowledge_base_uuid',
        ),
        migrations.AddField(
            model_name='knowledgebasedocument',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_knowledge_base_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgebasedocument',
            name='n_chunks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knowledgebasedocument',
            name='n_chunks_indexed_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='documentknowledgebaseconnection',
            index=models.Index(fields=['assistant', 'name'], name='datasource__assista_e7edd3_idx'),
        ),
        migrations.AddIndex(
            model_name='documentknowledgebaseconnection',
            index=models.Index(fields=['assistant', 'created_at'], name='datasource__assista_4863d1_idx'),
        ),
        migrations.AddIndex(
            model_name='documentknowledgebaseconnection',
            index=models.Index(fields=['assistant', 'updated_at'], name='datasource__assista_563a86_idx'),
        ),
        migrations.AddField(
            model_name='documentchunkvectordata',
            name='knowledge_base_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_chunks', to='datasource_knowledge_base.knowledgebasedocument'),
        ),
        migrations.DeleteModel(
            name='KnowledgeBaseDocumentChunk',
        ),
        migrations.RemoveField(
            model_name='documentknowledgebaseconnection',
            name='host_url',
        ),
        migrations.RemoveField(
            model_name='documentknowledgebaseconnection',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='documentknowledgebaseconnection',
            name='provider_api_key',
        ),
        migrations.RemoveField(
            model_name='documentknowledgebaseconnection',
            name='schema_json',
        ),
        migrations.RemoveField(
            model_name='documentknowledgebaseconnection',
            name='vectorizer_api_key',
        ),
        migrations.AddIndex(
            model_name='documentchunkvectordata',
            index=models.Index(fields=['knowledge_base_document'], name='datasource__knowled_02c9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunkvectordata',
            index=models.Index(fields=['knowledge_base_document', 'created_at'], name='datasource__knowled_d55c68_idx'),
        ),
    ]
