# Generated by Django 5.0.6 on 2024-07-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_knowledge_base', '0003_alter_documentknowledgebaseconnection_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebasedocument',
            name='document_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML'), ('csv', 'CSV'), ('docx', 'DOCX'), ('ipynb', 'IPYNB'), ('json', 'JSON'), ('xml', 'XML'), ('txt', 'TXT'), ('md', 'MD'), ('rtf', 'RTF'), ('odt', 'ODT'), ('pptx', 'POWERPOINT'), ('xlsx', 'XLSX')], max_length=100),
        ),
        migrations.AlterField(
            model_name='knowledgebasedocumentchunk',
            name='chunk_document_type',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('html', 'HTML'), ('csv', 'CSV'), ('docx', 'DOCX'), ('ipynb', 'IPYNB'), ('json', 'JSON'), ('xml', 'XML'), ('txt', 'TXT'), ('md', 'MD'), ('rtf', 'RTF'), ('odt', 'ODT'), ('pptx', 'POWERPOINT'), ('xlsx', 'XLSX')], max_length=100, null=True),
        ),
    ]
