# Generated by Django 5.0.6 on 2024-07-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_knowledge_base', '0004_alter_knowledgebasedocument_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasedocument',
            name='document_uri',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='knowledgebasedocument',
            name='knowledge_base_uuid',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='knowledgebasedocumentchunk',
            name='chunk_document_uri',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
