# Generated by Django 5.0.8 on 2024-12-11 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_knowledge_base', '0004_documentchunkvectordata_delete_documentprocessinglog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentknowledgebaseconnection',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_knowledge_base_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgebasedocument',
            name='document_uri',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgebasedocument',
            name='document_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgebasedocument',
            name='document_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
