# Generated by Django 5.0.6 on 2024-07-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_knowledge_base', '0005_knowledgebasedocument_document_uri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasedocumentchunk',
            name='knowledge_base_uuid',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
