# Generated by Django 5.0.8 on 2024-12-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_knowledge_base', '0005_documentknowledgebaseconnection_created_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasedocument',
            name='document_raw_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
