# Generated by Django 5.0.6 on 2024-07-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_knowledge_base', '0006_knowledgebasedocumentchunk_knowledge_base_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasedocumentchunk',
            name='document_uuid',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
