# Generated by Django 5.0.8 on 2024-12-11 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_knowledge_base', '0006_knowledgebasedocument_document_raw_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgebasedocument',
            name='document_raw_data',
        ),
    ]
