# Generated by Django 5.0.6 on 2024-07-13 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0339_alter_assistant_assistant_image'),
        ('datasource_knowledge_base', '0007_knowledgebasedocumentchunk_document_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextHistoryKnowledgeBaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vectorizer', models.CharField(choices=[('text2vec-openai', 'Text2Vec (OpenAI)')], default='text2vec-openai', max_length=100)),
                ('vectorizer_api_key', models.CharField(blank=True, max_length=1000, null=True)),
                ('embedding_chunk_size', models.IntegerField(default=1024)),
                ('embedding_chunk_overlap', models.IntegerField(default=256)),
                ('schema_json', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
            ],
            options={
                'verbose_name': 'Context History Knowledge Base Connection',
                'verbose_name_plural': 'Context History Knowledge Base Connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContextHistoryMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_text', models.TextField()),
                ('knowledge_base_memory_uuid', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context_history_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='datasource_knowledge_base.contexthistoryknowledgebaseconnection')),
            ],
            options={
                'verbose_name': 'Context History Memory',
                'verbose_name_plural': 'Context History Memories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contexthistoryknowledgebaseconnection',
            name='context_history_memories',
            field=models.ManyToManyField(blank=True, related_name='knowledge_bases', to='datasource_knowledge_base.contexthistorymemory'),
        ),
    ]
