# Generated by Django 5.0.6 on 2024-07-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_knowledge_base', '0008_contexthistoryknowledgebaseconnection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_full_uri', models.CharField(max_length=1000)),
                ('log_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document Processing Log',
                'verbose_name_plural': 'Document Processing Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
