# Generated by Django 5.0.6 on 2024-07-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_knowledge_base', '0009_documentprocessinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentknowledgebaseconnection',
            name='search_instance_retrieval_limit',
            field=models.IntegerField(default=10),
        ),
    ]
