# Generated by Django 5.0.6 on 2024-07-15 20:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_knowledge_base', '0010_documentknowledgebaseconnection_search_instance_retrieval_limit'),
        ('multimodal_chat', '0020_alter_multimodalchatmessage_sender_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contexthistoryknowledgebaseconnection',
            name='embedding_chunk_overlap',
        ),
        migrations.RemoveField(
            model_name='contexthistoryknowledgebaseconnection',
            name='embedding_chunk_size',
        ),
        migrations.RemoveField(
            model_name='contexthistoryknowledgebaseconnection',
            name='schema_json',
        ),
        migrations.RemoveField(
            model_name='contexthistorymemory',
            name='content_text',
        ),
        migrations.AddField(
            model_name='contexthistoryknowledgebaseconnection',
            name='chat',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='multimodal_chat.multimodalchat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contexthistoryknowledgebaseconnection',
            name='class_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contexthistoryknowledgebaseconnection',
            name='host_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contexthistoryknowledgebaseconnection',
            name='provider',
            field=models.CharField(choices=[('weaviate', 'Weaviate')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contexthistoryknowledgebaseconnection',
            name='provider_api_key',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contexthistorymemory',
            name='document_uri',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='ContextHistoryMemoryChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_number', models.IntegerField()),
                ('chunk_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_base_memory_uuid', models.CharField(blank=True, max_length=1000, null=True)),
                ('memory_uuid', models.CharField(blank=True, max_length=1000, null=True)),
                ('context_history_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource_knowledge_base.contexthistoryknowledgebaseconnection')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='datasource_knowledge_base.contexthistorymemory')),
            ],
            options={
                'verbose_name': 'Context History Memory Chunk',
                'verbose_name_plural': 'Context History Memory Chunks',
                'ordering': ['-created_at'],
            },
        ),
    ]
