# Generated by Django 5.0.6 on 2024-07-15 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0365_alter_assistant_assistant_image'),
        ('datasource_knowledge_base', '0011_remove_contexthistoryknowledgebaseconnection_embedding_chunk_overlap_and_more'),
        ('multimodal_chat', '0020_alter_multimodalchatmessage_sender_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contexthistoryknowledgebaseconnection',
            name='assistant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant'),
        ),
        migrations.AlterField(
            model_name='contexthistoryknowledgebaseconnection',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='multimodal_chat.multimodalchat'),
        ),
    ]
