# Generated by Django 5.0.6 on 2024-07-15 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_knowledge_base', '0012_alter_contexthistoryknowledgebaseconnection_assistant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contexthistoryknowledgebaseconnection',
            name='host_url',
        ),
        migrations.RemoveField(
            model_name='contexthistoryknowledgebaseconnection',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='contexthistoryknowledgebaseconnection',
            name='provider_api_key',
        ),
    ]
