# Generated by Django 5.0.6 on 2024-07-15 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_knowledge_base', '0013_remove_contexthistoryknowledgebaseconnection_host_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contexthistorymemory',
            old_name='document_uri',
            new_name='memory_name',
        ),
        migrations.RenameField(
            model_name='contexthistorymemorychunk',
            old_name='memory_uuid',
            new_name='chunk_uuid',
        ),
    ]
