# Generated by Django 5.0.6 on 2024-07-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_knowledge_base', '0014_rename_document_uri_contexthistorymemory_memory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contexthistorymemory',
            name='memory_chunks',
            field=models.ManyToManyField(blank=True, related_name='memories', to='datasource_knowledge_base.contexthistorymemorychunk'),
        ),
    ]
