# Generated by Django 5.0.8 on 2024-11-25 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0005_alter_organization_phone'),
        ('voidforger', '0019_alter_voidforgeractionmemoryvectordata_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportVoidForgerAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('request_limit_per_hour', models.IntegerField(default=1000)),
                ('is_online', models.BooleanField(default=True)),
                ('custom_api_key', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('endpoint', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_voidforgers_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exported_voidforgers', to='organization.organization')),
                ('voidforger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exported_voidforgers', to='voidforger.voidforger')),
            ],
            options={
                'verbose_name': 'Export VoidForger API',
                'verbose_name_plural': 'Export VoidForger APIs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoidForgerRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('export_voidforger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='export_voidforger.exportvoidforgerapi')),
            ],
            options={
                'verbose_name': 'Request VoidForger Log',
                'verbose_name_plural': 'Request VoidForger Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='exportvoidforgerapi',
            index=models.Index(fields=['voidforger'], name='export_void_voidfor_b227ed_idx'),
        ),
        migrations.AddIndex(
            model_name='exportvoidforgerapi',
            index=models.Index(fields=['created_by_user'], name='export_void_created_f1a70a_idx'),
        ),
        migrations.AddIndex(
            model_name='exportvoidforgerapi',
            index=models.Index(fields=['created_at'], name='export_void_created_2fd4d1_idx'),
        ),
        migrations.AddIndex(
            model_name='exportvoidforgerapi',
            index=models.Index(fields=['updated_at'], name='export_void_updated_e6bd90_idx'),
        ),
        migrations.AddIndex(
            model_name='exportvoidforgerapi',
            index=models.Index(fields=['voidforger', 'created_at'], name='export_void_voidfor_276b9a_idx'),
        ),
        migrations.AddIndex(
            model_name='exportvoidforgerapi',
            index=models.Index(fields=['voidforger', 'updated_at'], name='export_void_voidfor_4fc0c9_idx'),
        ),
        migrations.AddIndex(
            model_name='exportvoidforgerapi',
            index=models.Index(fields=['voidforger', 'created_by_user'], name='export_void_voidfor_5b6783_idx'),
        ),
        migrations.AddIndex(
            model_name='voidforgerrequestlog',
            index=models.Index(fields=['export_voidforger'], name='export_void_export__e28200_idx'),
        ),
        migrations.AddIndex(
            model_name='voidforgerrequestlog',
            index=models.Index(fields=['timestamp'], name='export_void_timesta_c66ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='voidforgerrequestlog',
            index=models.Index(fields=['export_voidforger', 'timestamp'], name='export_void_export__7337d0_idx'),
        ),
    ]
