# Generated by Django 5.0.8 on 2024-12-01 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export_voidforger', '0001_initial'),
        ('organization', '0005_alter_organization_phone'),
        ('voidforger', '0019_alter_voidforgeractionmemoryvectordata_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exportvoidforgerapi',
            unique_together={('organization', 'voidforger', 'is_public')},
        ),
    ]
