# Generated by Django 5.0.8 on 2024-11-15 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm_core', '0002_initial'),
        ('organization', '0003_alter_organization_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoidForger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_instructions', models.TextField(blank=True, null=True)),
                ('tone', models.CharField(default='Professional and Assertive', max_length=100)),
                ('response_language', models.CharField(choices=[('auto', 'Auto (Detect)'), ('sq', 'Albanian'), ('ar', 'Arabic'), ('bs', 'Bosnian'), ('bg', 'Bulgarian'), ('zh', 'Chinese'), ('hr', 'Croatian'), ('cs', 'Czech'), ('da', 'Danish'), ('nl', 'Dutch'), ('en', 'English'), ('et', 'Estonian'), ('fi', 'Finnish'), ('fi', 'Finnish'), ('fr', 'French'), ('de', 'German'), ('el', 'Greek'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hu', 'Hungarian'), ('is', 'Icelandic'), ('id', 'Indonesian'), ('ga', 'Irish'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('lv', 'Latvian'), ('lt', 'Lithuanian'), ('mk', 'Macedonian'), ('ms', 'Malay'), ('no', 'Norwegian'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sr', 'Serbian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('es', 'Spanish'), ('sv', 'Swedish'), ('th', 'Thai'), ('tr', 'Turkish'), ('uk', 'Ukrainian'), ('cy', 'Welsh')], default='auto', max_length=100)),
                ('runtime_status', models.CharField(choices=[('paused', 'Paused'), ('active', 'Active'), ('working', 'Working')], default='paused', max_length=100)),
                ('auto_run_max_lifetime_cycles', models.IntegerField(default=1000)),
                ('auto_run_trigger_interval_minutes', models.IntegerField(default=15)),
                ('short_term_memory_max_messages', models.IntegerField(default=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('llm_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='llm_core.llmcore')),
                ('organizations', models.ManyToManyField(blank=True, to='organization.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VoidForger',
                'verbose_name_plural': 'VoidForgers',
                'indexes': [models.Index(fields=['user'], name='voidforger__user_id_888b2c_idx'), models.Index(fields=['user', 'runtime_status'], name='voidforger__user_id_e3d485_idx'), models.Index(fields=['user', 'runtime_status', 'created_at'], name='voidforger__user_id_805943_idx'), models.Index(fields=['user', 'runtime_status', 'updated_at'], name='voidforger__user_id_75df48_idx'), models.Index(fields=['user', 'runtime_status', 'created_at', 'updated_at'], name='voidforger__user_id_3215b3_idx'), models.Index(fields=['user', 'runtime_status', 'created_at', 'updated_at', 'llm_model'], name='voidforger__user_id_15e88c_idx')],
            },
        ),
    ]
