# Generated by Django 5.0.8 on 2024-11-15 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voidforger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoidForgerToggleAutoExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('activated', 'Activated'), ('paused', 'Paused'), ('end_of_life', 'End of Life')], max_length=20)),
                ('metadata', models.JSONField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('responsible_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('voidforger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voidforger.voidforger')),
            ],
            options={
                'verbose_name': 'VoidForger Toggle Auto Execution Log',
                'verbose_name_plural': 'VoidForger Toggle Auto Execution Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['voidforger', 'action_type'], name='voidforger__voidfor_55f6f7_idx'), models.Index(fields=['voidforger', 'timestamp'], name='voidforger__voidfor_a4b88f_idx'), models.Index(fields=['voidforger', 'action_type', 'timestamp'], name='voidforger__voidfor_275f2f_idx')],
            },
        ),
    ]
