# Generated by Django 5.0.8 on 2024-11-15 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voidforger', '0002_voidforgertoggleautoexecutionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='voidforger',
            name='maximum_actions_per_cycle',
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name='VoidForgerActionMemoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('natural_language_response', 'Natural Language Response'), ('tool_order', 'Tool Order')], max_length=255)),
                ('action_order_raw_text', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('voidforger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voidforger.voidforger')),
            ],
            options={
                'verbose_name': 'VoidForger Action Memory Log',
                'verbose_name_plural': 'VoidForger Action Memory Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['voidforger', 'action_type'], name='voidforger__voidfor_6ca582_idx'), models.Index(fields=['voidforger', 'timestamp'], name='voidforger__voidfor_8e38ec_idx'), models.Index(fields=['voidforger', 'action_type', 'timestamp'], name='voidforger__voidfor_850222_idx')],
            },
        ),
    ]
