# Generated by Django 5.0.8 on 2024-11-15 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_transaction', '0018_alter_llmtransaction_transaction_source'),
        ('voidforger', '0003_voidforger_maximum_actions_per_cycle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultimodalVoidForgerChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_voidforger_chats_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('transactions', models.ManyToManyField(blank=True, related_name='multimodal_voidforger_chats', to='llm_transaction.llmtransaction')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_voidforger_chats', to=settings.AUTH_USER_MODEL)),
                ('voidforger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_chats', to='voidforger.voidforger')),
            ],
            options={
                'verbose_name': 'Multimodal VoidForger Chat',
                'verbose_name_plural': 'Multimodal VoidForger Chats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MultimodalVoidForgerChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'System'), ('TOOL', 'Tool')], max_length=100)),
                ('message_text_content', models.TextField()),
                ('message_json_content', models.JSONField(blank=True, default=dict, null=True)),
                ('message_image_contents', models.JSONField(blank=True, default=list, null=True)),
                ('message_file_contents', models.JSONField(blank=True, default=list, null=True)),
                ('message_audio', models.URLField(blank=True, max_length=10000, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('multimodal_voidforger_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voidforger_chat_messages', to='voidforger.multimodalvoidforgerchat')),
            ],
            options={
                'verbose_name': 'Multimodal VoidForger Chat Message',
                'verbose_name_plural': 'Multimodal VoidForger Chat Messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='multimodalvoidforgerchat',
            index=models.Index(fields=['voidforger'], name='voidforger__voidfor_a7055e_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalvoidforgerchat',
            index=models.Index(fields=['user'], name='voidforger__user_id_60531b_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalvoidforgerchat',
            index=models.Index(fields=['created_by_user'], name='voidforger__created_d05f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalvoidforgerchat',
            index=models.Index(fields=['created_at'], name='voidforger__created_a2f27c_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalvoidforgerchat',
            index=models.Index(fields=['updated_at'], name='voidforger__updated_8d7c2f_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalvoidforgerchat',
            index=models.Index(fields=['voidforger', 'user'], name='voidforger__voidfor_4a1bc5_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalvoidforgerchat',
            index=models.Index(fields=['voidforger', 'created_by_user'], name='voidforger__voidfor_374085_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalvoidforgerchat',
            index=models.Index(fields=['voidforger', 'created_at'], name='voidforger__voidfor_0c0edf_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalvoidforgerchat',
            index=models.Index(fields=['voidforger', 'updated_at'], name='voidforger__voidfor_e83aee_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalvoidforgerchatmessage',
            index=models.Index(fields=['multimodal_voidforger_chat'], name='voidforger__multimo_81e13f_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalvoidforgerchatmessage',
            index=models.Index(fields=['sender_type'], name='voidforger__sender__89e15a_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalvoidforgerchatmessage',
            index=models.Index(fields=['sent_at'], name='voidforger__sent_at_0acd66_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalvoidforgerchatmessage',
            index=models.Index(fields=['multimodal_voidforger_chat', 'sender_type'], name='voidforger__multimo_96227d_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalvoidforgerchatmessage',
            index=models.Index(fields=['multimodal_voidforger_chat', 'sent_at'], name='voidforger__multimo_b9a02f_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalvoidforgerchatmessage',
            index=models.Index(fields=['sender_type', 'sent_at'], name='voidforger__sender__8b70c8_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalvoidforgerchatmessage',
            index=models.Index(fields=['multimodal_voidforger_chat', 'sender_type', 'sent_at'], name='voidforger__multimo_7da74c_idx'),
        ),
    ]
