# Generated by Django 5.0.8 on 2024-11-15 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voidforger', '0004_multimodalvoidforgerchat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoidForgerActionMemoryVectorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('raw_data_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('vector_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voidforger_action_memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voidforger.voidforgeractionmemorylog')),
            ],
            options={
                'verbose_name': 'VoidForger Action Memory Vector Data',
                'verbose_name_plural': 'VoidForger Action Memory Vector Data',
                'indexes': [models.Index(fields=['voidforger_action_memory'], name='voidforger__voidfor_73e7cd_idx'), models.Index(fields=['created_at'], name='voidforger__created_3aaee2_idx'), models.Index(fields=['updated_at'], name='voidforger__updated_d74388_idx')],
            },
        ),
        migrations.CreateModel(
            name='VoidForgerAutoExecutionMemoryVectorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('raw_data_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('vector_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voidforger_auto_execution_memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voidforger.voidforgertoggleautoexecutionlog')),
            ],
            options={
                'verbose_name': 'VoidForger Auto Execution Memory Vector Data',
                'verbose_name_plural': 'VoidForger Auto Execution Memory Vector Data',
                'indexes': [models.Index(fields=['voidforger_auto_execution_memory'], name='voidforger__voidfor_103cd7_idx'), models.Index(fields=['created_at'], name='voidforger__created_cf6d78_idx'), models.Index(fields=['updated_at'], name='voidforger__updated_4ea523_idx')],
            },
        ),
        migrations.CreateModel(
            name='VoidForgerOldChatMessagesVectorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('raw_data_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('vector_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voidforger_chat_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voidforger.multimodalvoidforgerchatmessage')),
            ],
            options={
                'verbose_name': 'VoidForger Old Chat Messages Vector Data',
                'verbose_name_plural': 'VoidForger Old Chat Messages Vector Datas',
                'indexes': [models.Index(fields=['voidforger_chat_message'], name='voidforger__voidfor_2cd9c6_idx'), models.Index(fields=['created_at'], name='voidforger__created_10b363_idx'), models.Index(fields=['updated_at'], name='voidforger__updated_5197f0_idx')],
            },
        ),
    ]
