# Generated by Django 5.0.8 on 2024-11-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voidforger', '0005_voidforgeractionmemoryvectordata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voidforgertoggleautoexecutionlog',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
