# Generated by Django 5.0.8 on 2024-11-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voidforger', '0006_alter_voidforgertoggleautoexecutionlog_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voidforgertoggleautoexecutionlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
