# Generated by Django 5.0.8 on 2024-11-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voidforger', '0007_alter_voidforgertoggleautoexecutionlog_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='voidforger',
            name='auto_run_current_cycle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voidforger',
            name='maximum_actions_per_cycle',
            field=models.IntegerField(default=10),
        ),
    ]
