# Generated by Django 5.0.8 on 2024-11-16 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voidforger', '0008_voidforger_auto_run_current_cycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voidforgeractionmemoryvectordata',
            name='voidforger_action_memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voidforger.voidforgeractionmemorylog', unique=True),
        ),
        migrations.AlterField(
            model_name='voidforgerautoexecutionmemoryvectordata',
            name='voidforger_auto_execution_memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voidforger.voidforgertoggleautoexecutionlog', unique=True),
        ),
        migrations.AlterField(
            model_name='voidforgeroldchatmessagesvectordata',
            name='voidforger_chat_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voidforger.multimodalvoidforgerchatmessage', unique=True),
        ),
    ]
