# Generated by Django 5.0.8 on 2024-11-16 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voidforger', '0010_alter_voidforgeractionmemoryvectordata_voidforger_action_memory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voidforgerautoexecutionmemoryvectordata',
            name='voidforger_auto_execution_memory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voidforger.voidforgertoggleautoexecutionlog'),
        ),
    ]
