# Generated by Django 5.0.8 on 2024-11-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voidforger', '0012_alter_voidforgertoggleautoexecutionlog_responsible_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimodalvoidforgerchat',
            name='chat_source',
            field=models.CharField(choices=[('app', 'Application'), ('api', 'API'), ('scheduled', 'Scheduled'), ('orchestration', 'Orchestration'), ('drafting', 'Drafting'), ('formica', 'Formica'), ('slider', 'Slider')], default='app', max_length=100),
        ),
    ]
