# Generated by Django 5.0.8 on 2024-11-16 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voidforger', '0013_multimodalvoidforgerchat_chat_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voidforgeractionmemoryvectordata',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='voidforgeractionmemoryvectordata',
            name='voidforger__voidfor_73e7cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='voidforgeractionmemoryvectordata',
            name='voidforger__created_3aaee2_idx',
        ),
        migrations.RemoveIndex(
            model_name='voidforgeractionmemoryvectordata',
            name='voidforger__updated_d74388_idx',
        ),
        migrations.AlterField(
            model_name='voidforgeractionmemoryvectordata',
            name='voidforger_action_memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voidforger_action_memory_vector_data', to='voidforger.voidforgeractionmemorylog'),
        ),
        migrations.AlterField(
            model_name='voidforgerautoexecutionmemoryvectordata',
            name='voidforger_auto_execution_memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voidforger_auto_execution_memory_vector_data', to='voidforger.voidforgertoggleautoexecutionlog'),
        ),
        migrations.AlterField(
            model_name='voidforgeroldchatmessagesvectordata',
            name='voidforger_chat_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voidforger_chat_message_vector_data', to='voidforger.multimodalvoidforgerchatmessage'),
        ),
    ]
