# Generated by Django 5.0.8 on 2024-11-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voidforger', '0014_alter_voidforgeractionmemoryvectordata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voidforgeractionmemorylog',
            name='action_type',
            field=models.CharField(choices=[('natural_language_response', 'Natural Language Response'), ('tool_order', 'Tool Order'), ('intermediary', 'Intermediary')], max_length=255),
        ),
    ]
