# Generated by Django 5.0.8 on 2024-11-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voidforger', '0016_alter_voidforgeractionmemorylog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voidforgeractionmemorylog',
            name='action_type',
            field=models.CharField(choices=[('natural_language_response', 'Natural Language Response'), ('intermediary_agent_command', 'Intermediary Agent Command'), ('action_log_search_attempt', 'Action Log Search Attempt'), ('auto_execution_log_search_attempt', 'Auto Execution Log Search Attempt'), ('old_chat_messages_search_attempt', 'Old Chat Messages Search Attempt'), ('intermediary_agent_search_attempt', 'Intermediary Agent Search Attempt')], max_length=255),
        ),
    ]
