# Generated by Django 5.0.8 on 2024-11-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voidforger', '0017_alter_voidforgeractionmemorylog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='voidforger',
            name='last_auto_execution_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voidforger',
            name='last_auto_execution_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
