# Generated by Django 5.0.8 on 2024-11-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voidforger', '0018_voidforger_last_auto_execution_ended_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voidforgeractionmemoryvectordata',
            options={'verbose_name': 'VoidForger Action Memory Vector Data', 'verbose_name_plural': 'VoidForger Action Memory Vector Data'},
        ),
        migrations.AlterField(
            model_name='voidforger',
            name='maximum_actions_per_cycle',
            field=models.IntegerField(default=5),
        ),
        migrations.AddIndex(
            model_name='voidforgeractionmemoryvectordata',
            index=models.Index(fields=['voidforger_action_memory'], name='voidforger__voidfor_73e7cd_idx'),
        ),
        migrations.AddIndex(
            model_name='voidforgeractionmemoryvectordata',
            index=models.Index(fields=['created_at'], name='voidforger__created_3aaee2_idx'),
        ),
        migrations.AddIndex(
            model_name='voidforgeractionmemoryvectordata',
            index=models.Index(fields=['updated_at'], name='voidforger__updated_d74388_idx'),
        ),
    ]
