# Generated by Django 5.0.8 on 2024-12-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voidforger', '0021_alter_voidforger_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimodalvoidforgerchatmessage',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
