# Generated by Django 5.0.8 on 2024-12-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voidforger', '0022_multimodalvoidforgerchatmessage_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimodalvoidforgerchatmessage',
            name='sender_type',
            field=models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('DEVELOPER', 'Developer'), ('TOOL', 'Tool')], max_length=100),
        ),
    ]
