# Generated by Django 5.0.8 on 2024-12-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voidforger', '0023_alter_multimodalvoidforgerchatmessage_sender_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimodalvoidforgerchatmessage',
            name='sender_type',
            field=models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'System'), ('TOOL', 'Tool')], max_length=100),
        ),
    ]
