# Generated by Django 5.0.8 on 2024-10-20 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainWalletConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain_type', models.CharField(choices=[('ethereum', 'Ethereum')], max_length=100)),
                ('nickname', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('wallet_address', models.CharField(max_length=16000)),
                ('wallet_private_key', models.CharField(max_length=16000)),
                ('wallet_balance', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('balance_last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_wallet_connections_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'verbose_name': 'Blockchain Wallet Connection',
                'verbose_name_plural': 'Blockchain Wallet Connections',
                'indexes': [models.Index(fields=['organization', 'blockchain_type', 'nickname'], name='smart_contr_organiz_21c571_idx'), models.Index(fields=['wallet_address'], name='smart_contr_wallet__b0b42b_idx'), models.Index(fields=['created_by_user'], name='smart_contr_created_d3120e_idx'), models.Index(fields=['created_at'], name='smart_contr_created_86232a_idx'), models.Index(fields=['updated_at'], name='smart_contr_updated_abed8a_idx')],
            },
        ),
    ]
