# Generated by Django 5.0.8 on 2024-10-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contracts', '0002_blockchainsmartcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainsmartcontract',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blockchainsmartcontract',
            name='nickname',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
