# Generated by Django 5.0.8 on 2024-10-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contracts', '0003_blockchainsmartcontract_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainsmartcontract',
            name='contract_content_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
