# Generated by Django 5.0.8 on 2024-10-21 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contracts', '0004_blockchainsmartcontract_contract_content_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchainsmartcontract',
            name='contract_content_text',
        ),
    ]
