# Generated by Django 5.0.8 on 2024-10-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contracts', '0005_remove_blockchainsmartcontract_contract_content_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainsmartcontract',
            name='maximum_gas_limit',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AddField(
            model_name='blockchainsmartcontract',
            name='maximum_gas_price_gwei',
            field=models.IntegerField(default=20),
        ),
    ]
