# Generated by Django 5.0.8 on 2024-10-21 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contracts', '0006_blockchainsmartcontract_maximum_gas_limit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockchainsmartcontract',
            old_name='maximum_gas_price_gwei',
            new_name='gas_price_gwei',
        ),
    ]
