# Generated by Django 5.0.8 on 2024-10-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contracts', '0007_rename_maximum_gas_price_gwei_blockchainsmartcontract_gas_price_gwei'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchainsmartcontract',
            name='deployed',
        ),
        migrations.AddField(
            model_name='blockchainsmartcontract',
            name='deployment_status',
            field=models.CharField(choices=[('not-generated', 'Not Generated'), ('generated-unsigned', 'Generated Unsigned'), ('transaction-staged', 'Transaction Staged'), ('waiting-for-mining', 'Waiting for Mining'), ('deployed', 'Deployed'), ('failed', 'Failed')], default='not-generated', max_length=1000),
        ),
    ]
