# Generated by Django 5.0.8 on 2024-10-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contracts', '0008_remove_blockchainsmartcontract_deployed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainsmartcontract',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blockchainsmartcontract',
            name='tx_receipt_raw',
            field=models.TextField(blank=True, null=True),
        ),
    ]
