# Generated by Django 5.0.8 on 2024-10-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contracts', '0009_blockchainsmartcontract_tx_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainsmartcontract',
            name='offchain_contract_seed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
