# Generated by Django 5.0.8 on 2024-10-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contracts', '0010_blockchainsmartcontract_offchain_contract_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainsmartcontract',
            name='generated_solidity_code_natural_language',
            field=models.TextField(blank=True, null=True),
        ),
    ]
