# Generated by Django 5.0.8 on 2024-10-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contracts', '0011_blockchainsmartcontract_generated_solidity_code_natural_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainsmartcontract',
            name='post_gen_clauses',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='blockchainsmartcontract',
            name='post_gen_functions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='blockchainsmartcontract',
            name='post_gen_parties',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='blockchainsmartcontract',
            name='post_gen_protocol_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blockchainsmartcontract',
            name='post_gen_topic',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blockchainsmartcontract',
            name='pot_gen_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
