# Generated by Django 5.0.8 on 2024-10-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contracts', '0012_blockchainsmartcontract_post_gen_clauses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainsmartcontract',
            name='post_gen_clauses',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='blockchainsmartcontract',
            name='post_gen_functions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='blockchainsmartcontract',
            name='post_gen_parties',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
