# Generated by Django 5.0.8 on 2024-10-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contracts', '0013_alter_blockchainsmartcontract_post_gen_clauses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainsmartcontract',
            name='contract_args',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
