# Generated by Django 5.0.8 on 2024-10-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contracts', '0014_blockchainsmartcontract_contract_args'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainsmartcontract',
            name='contract_args',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
