# Generated by Django 5.0.8 on 2024-10-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contracts', '0015_alter_blockchainsmartcontract_contract_args'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainsmartcontract',
            name='contract_abi',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
