# Generated by Django 5.0.8 on 2024-11-13 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0007_alter_assistant_context_overflow_strategy'),
        ('smart_contracts', '0016_blockchainsmartcontract_contract_abi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartContractAssistantConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('smart_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_contracts.blockchainsmartcontract')),
            ],
            options={
                'verbose_name': 'Smart Contract Assistant Connection',
                'verbose_name_plural': 'Smart Contract Assistant Connections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['smart_contract', 'assistant'], name='smart_contr_smart_c_fb81b6_idx'), models.Index(fields=['assistant', 'smart_contract'], name='smart_contr_assista_1ec0e3_idx')],
                'unique_together': {('smart_contract', 'assistant')},
            },
        ),
    ]
