# Generated by Django 5.0.8 on 2024-11-14 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_contracts', '0017_smartcontractassistantconnection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmartContractAssistantConnection',
        ),
    ]
