# Generated by Django 5.0.8 on 2024-12-01 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_organization_name'),
        ('smart_contracts', '0018_delete_smartcontractassistantconnection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blockchainsmartcontract',
            unique_together={('wallet', 'nickname')},
        ),
        migrations.AlterUniqueTogether(
            name='blockchainwalletconnection',
            unique_together={('organization', 'wallet_address')},
        ),
    ]
