#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Jupi.tr™
#  File: 0001_initial.py
#  Last Modified: 2024-09-25 17:51:06
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 01:36:42
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@jupi.tr.
#

# Generated by Django 5.1.1 on 2024-09-25 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='message_tem_user_id_ca4f74_idx'), models.Index(fields=['organization'], name='message_tem_organiz_1d2366_idx'), models.Index(fields=['template_text'], name='message_tem_templat_75a063_idx'), models.Index(fields=['created_at'], name='message_tem_created_883d7c_idx'), models.Index(fields=['updated_at'], name='message_tem_updated_9aa330_idx'), models.Index(fields=['user', 'organization'], name='message_tem_user_id_f54675_idx'), models.Index(fields=['user', 'template_text'], name='message_tem_user_id_64363b_idx'), models.Index(fields=['user', 'created_at'], name='message_tem_user_id_e9ef3b_idx'), models.Index(fields=['user', 'updated_at'], name='message_tem_user_id_a7c0d4_idx'), models.Index(fields=['organization', 'template_text'], name='message_tem_organiz_bfaddd_idx'), models.Index(fields=['organization', 'created_at'], name='message_tem_organiz_bd39c8_idx'), models.Index(fields=['organization', 'updated_at'], name='message_tem_organiz_270ea7_idx'), models.Index(fields=['template_text', 'created_at'], name='message_tem_templat_aa5487_idx'), models.Index(fields=['template_text', 'updated_at'], name='message_tem_templat_c2890c_idx'), models.Index(fields=['created_at', 'updated_at'], name='message_tem_created_c357fc_idx'), models.Index(fields=['user', 'organization', 'template_text'], name='message_tem_user_id_cd7d4c_idx'), models.Index(fields=['user', 'organization', 'created_at'], name='message_tem_user_id_561813_idx'), models.Index(fields=['user', 'organization', 'updated_at'], name='message_tem_user_id_19929d_idx'), models.Index(fields=['user', 'template_text', 'created_at'], name='message_tem_user_id_8c981b_idx'), models.Index(fields=['user', 'template_text', 'updated_at'], name='message_tem_user_id_b29dcc_idx'), models.Index(fields=['organization', 'template_text', 'created_at'], name='message_tem_organiz_1c02d0_idx'), models.Index(fields=['organization', 'template_text', 'updated_at'], name='message_tem_organiz_40c164_idx'), models.Index(fields=['template_text', 'created_at', 'updated_at'], name='message_tem_templat_434ca2_idx'), models.Index(fields=['user', 'organization', 'template_text', 'created_at'], name='message_tem_user_id_221dfa_idx'), models.Index(fields=['user', 'organization', 'template_text', 'updated_at'], name='message_tem_user_id_7cfc02_idx'), models.Index(fields=['user', 'organization', 'created_at', 'updated_at'], name='message_tem_user_id_2ba447_idx'), models.Index(fields=['user', 'template_text', 'created_at', 'updated_at'], name='message_tem_user_id_d80b11_idx'), models.Index(fields=['organization', 'template_text', 'created_at', 'updated_at'], name='message_tem_organiz_78f3fc_idx'), models.Index(fields=['user', 'organization', 'template_text', 'created_at', 'updated_at'], name='message_tem_user_id_ea9c71_idx')],
            },
        ),
    ]
