# Generated by Django 5.0.6 on 2024-08-02 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'organization', 'created_at'], name='message_tem_user_id_561813_idx'), models.Index(fields=['user', 'organization'], name='message_tem_user_id_f54675_idx'), models.Index(fields=['user', 'created_at'], name='message_tem_user_id_e9ef3b_idx'), models.Index(fields=['organization', 'created_at'], name='message_tem_organiz_bd39c8_idx'), models.Index(fields=['template_text'], name='message_tem_templat_75a063_idx'), models.Index(fields=['user', 'organization', 'template_text'], name='message_tem_user_id_cd7d4c_idx'), models.Index(fields=['user', 'template_text'], name='message_tem_user_id_64363b_idx'), models.Index(fields=['organization', 'template_text'], name='message_tem_organiz_bfaddd_idx')],
            },
        ),
    ]
