# Generated by Django 5.0.6 on 2024-07-16 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_templates', '0001_initial'),
        ('organization', '0506_alter_organization_organization_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagetemplate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Message Template', 'verbose_name_plural': 'Message Templates'},
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['user', 'organization', 'created_at'], name='message_tem_user_id_561813_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['user', 'organization'], name='message_tem_user_id_f54675_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['user', 'created_at'], name='message_tem_user_id_e9ef3b_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['organization', 'created_at'], name='message_tem_organiz_bd39c8_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['template_text'], name='message_tem_templat_75a063_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['user', 'organization', 'template_text'], name='message_tem_user_id_cd7d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['user', 'template_text'], name='message_tem_user_id_64363b_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['organization', 'template_text'], name='message_tem_organiz_bfaddd_idx'),
        ),
    ]
