# Generated by Django 5.1.1 on 2024-09-23 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceBrowserConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('browser_type', models.CharField(choices=[('google', 'Google')], max_length=100)),
                ('data_selectivity', models.FloatField(default=0.5)),
                ('whitelisted_extensions', models.JSONField(blank=True, default=list, null=True)),
                ('blacklisted_extensions', models.JSONField(blank=True, default=list, null=True)),
                ('reading_abilities', models.JSONField(blank=True, default=list, null=True)),
                ('minimum_investigation_sites', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Source Browser Connection',
                'verbose_name_plural': 'Data Source Browser Connections',
            },
        ),
        migrations.CreateModel(
            name='DataSourceBrowserBrowsingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=1000)),
                ('context_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('html_content', models.TextField(blank=True, null=True)),
                ('context_content', models.TextField(blank=True, null=True)),
                ('log_content', models.TextField(blank=True, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='datasource_browser_screenshots/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='datasource_browsers.datasourcebrowserconnection')),
            ],
            options={
                'verbose_name': 'Data Source Browser Browsing Log',
                'verbose_name_plural': 'Data Source Browser Browsing Logs',
            },
        ),
    ]
