# Generated by Django 5.0.6 on 2024-07-30 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0577_alter_assistant_assistant_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceBrowserConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('browser_type', models.CharField(choices=[('google', 'Google')], max_length=100)),
                ('data_selectivity', models.FloatField(default=0.5)),
                ('whitelisted_extensions', models.TextField(blank=True, null=True)),
                ('blacklisted_extensions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
            ],
        ),
    ]
