# Generated by Django 5.0.8 on 2024-12-01 22:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0013_alter_assistantoldchatmessagesvectordata_unique_together'),
        ('datasource_browsers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datasourcebrowserconnection',
            unique_together={('assistant', 'name')},
        ),
        migrations.AddIndex(
            model_name='datasourcebrowserconnection',
            index=models.Index(fields=['assistant', 'name', 'browser_type', 'created_at'], name='datasource__assista_513d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='datasourcebrowserconnection',
            index=models.Index(fields=['assistant', 'name', 'browser_type', 'created_at', 'updated_at'], name='datasource__assista_9461f7_idx'),
        ),
        migrations.AddIndex(
            model_name='datasourcebrowserconnection',
            index=models.Index(fields=['assistant', 'name', 'browser_type', 'created_at', 'created_by_user'], name='datasource__assista_61e9bf_idx'),
        ),
    ]
