# Generated by Django 5.0.6 on 2024-07-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_browsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasourcebrowserconnection',
            options={'verbose_name': 'Data Source Browser Connection', 'verbose_name_plural': 'Data Source Browser Connections'},
        ),
    ]
