# Generated by Django 5.0.8 on 2024-12-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_browsers', '0002_alter_datasourcebrowserconnection_unique_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='datasourcebrowserbrowsinglog',
            index=models.Index(fields=['connection', 'action', 'created_at'], name='datasource__connect_cd4ebe_idx'),
        ),
        migrations.AddIndex(
            model_name='datasourcebrowserbrowsinglog',
            index=models.Index(fields=['connection', 'action', 'created_at', 'context_url'], name='datasource__connect_7930dd_idx'),
        ),
        migrations.AddIndex(
            model_name='datasourcebrowserbrowsinglog',
            index=models.Index(fields=['connection', 'action', 'created_at', 'context_url', 'html_content'], name='datasource__connect_ed0b9d_idx'),
        ),
        migrations.AddIndex(
            model_name='datasourcebrowserbrowsinglog',
            index=models.Index(fields=['connection', 'action', 'created_at', 'context_url', 'html_content', 'context_content'], name='datasource__connect_ddafd2_idx'),
        ),
    ]
