# Generated by Django 5.0.6 on 2024-07-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_browsers', '0002_alter_datasourcebrowserconnection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcebrowserconnection',
            name='reading_abilities',
            field=models.JSONField(default=dict),
        ),
    ]
