# Generated by Django 5.0.6 on 2024-07-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_browsers', '0004_alter_datasourcebrowserconnection_reading_abilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcebrowserconnection',
            name='reading_abilities',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
