# Generated by Django 5.0.6 on 2024-07-30 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_browsers', '0005_alter_datasourcebrowserconnection_reading_abilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcebrowserconnection',
            name='browser_type',
            field=models.CharField(choices=[('google', 'Google'), ('bing', 'Bing')], max_length=100),
        ),
        migrations.CreateModel(
            name='DataSourceBrowserBrowsingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=1000)),
                ('html_content', models.TextField(blank=True, null=True)),
                ('log_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource_browsers.datasourcebrowserconnection')),
            ],
            options={
                'verbose_name': 'Data Source Browser Browsing Log',
                'verbose_name_plural': 'Data Source Browser Browsing Logs',
            },
        ),
    ]
