# Generated by Django 5.0.6 on 2024-07-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_browsers', '0006_alter_datasourcebrowserconnection_browser_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcebrowserbrowsinglog',
            name='context_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
