# Generated by Django 5.0.6 on 2024-07-30 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_browsers', '0007_datasourcebrowserbrowsinglog_context_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcebrowserconnection',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datasourcebrowserconnection',
            name='browser_type',
            field=models.CharField(choices=[('google', 'Google')], max_length=100),
        ),
    ]
