# Generated by Django 5.0.6 on 2024-07-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_browsers', '0008_datasourcebrowserconnection_created_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcebrowserconnection',
            name='minimum_investigation_sites',
            field=models.IntegerField(default=2),
        ),
    ]
