# Generated by Django 5.0.6 on 2024-07-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_browsers', '0009_datasourcebrowserconnection_minimum_investigation_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcebrowserconnection',
            name='blacklisted_extensions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='datasourcebrowserconnection',
            name='whitelisted_extensions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
