# Generated by Django 5.0.6 on 2024-07-30 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_browsers', '0010_alter_datasourcebrowserconnection_blacklisted_extensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcebrowserbrowsinglog',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='datasource_browsers.datasourcebrowserconnection'),
        ),
    ]
