# Generated by Django 5.0.6 on 2024-07-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_browsers', '0011_alter_datasourcebrowserbrowsinglog_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcebrowserbrowsinglog',
            name='context_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
