# Generated by Django 5.0.6 on 2024-08-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_browsers', '0012_datasourcebrowserbrowsinglog_context_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcebrowserbrowsinglog',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='datasource_browser_screenshots/%Y/%m/%d'),
        ),
    ]
