# Generated by Django 5.1 on 2024-08-15 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(choices=[('user-specific', 'User-Specific'), ('assistant-specific', 'Assistant-Specific')], default='user-specific', max_length=50)),
                ('memory_text_content', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Memory',
                'verbose_name_plural': 'Memories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assistant', 'user', 'created_at'], name='memories_as_assista_121224_idx'), models.Index(fields=['assistant', 'user'], name='memories_as_assista_019b7e_idx'), models.Index(fields=['assistant', 'created_at'], name='memories_as_assista_75a9e4_idx'), models.Index(fields=['user', 'created_at'], name='memories_as_user_id_d05861_idx')],
            },
        ),
    ]
