# Generated by Django 5.0.8 on 2024-10-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantmemory',
            name='memory_type',
            field=models.CharField(choices=[('user-specific', 'User-Specific'), ('assistant-specific', 'Assistant-Specific'), ('organization-specific', 'Organization-Specific')], default='user-specific', max_length=50),
        ),
    ]
