# Generated by Django 5.0.6 on 2024-07-07 22:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0124_alter_assistant_assistant_image'),
        ('memories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmemory',
            name='assistant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant'),
        ),
        migrations.AddField(
            model_name='assistantmemory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistantmemory',
            name='memory_text_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='assistantmemory',
            name='memory_type',
            field=models.CharField(choices=[('user-specific', 'User-Specific'), ('assistant-specific', 'Assistant-Specific')], default='user-specific', max_length=50),
        ),
        migrations.AlterField(
            model_name='assistantmemory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
