# Generated by Django 5.0.6 on 2024-07-07 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0125_alter_assistant_assistant_image'),
        ('memories', '0002_assistantmemory_assistant_assistantmemory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantmemory',
            name='assistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant'),
        ),
    ]
