# Generated by Django 5.0.8 on 2024-10-20 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_alter_assistantmemory_memory_type'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmemory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
    ]
