# Generated by Django 5.0.6 on 2024-07-16 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0408_alter_assistant_assistant_image'),
        ('memories', '0003_alter_assistantmemory_assistant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistantmemory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Memory', 'verbose_name_plural': 'Memories'},
        ),
        migrations.AddIndex(
            model_name='assistantmemory',
            index=models.Index(fields=['assistant', 'user', 'created_at'], name='memories_as_assista_121224_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantmemory',
            index=models.Index(fields=['assistant', 'user'], name='memories_as_assista_019b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantmemory',
            index=models.Index(fields=['assistant', 'created_at'], name='memories_as_assista_75a9e4_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantmemory',
            index=models.Index(fields=['user', 'created_at'], name='memories_as_user_id_d05861_idx'),
        ),
    ]
