# Generated by Django 5.0.8 on 2024-10-27 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm_core', '0002_initial'),
        ('projects', '0002_remove_projectitem_assistants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaKanbanBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('llm_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llm_core.llmcore')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectitem')),
            ],
            options={
                'verbose_name': 'Meta Kanban Board',
                'verbose_name_plural': 'Meta Kanban Boards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetaKanbanStatusColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=10000)),
                ('column_description', models.TextField(blank=True, null=True)),
                ('position_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metakanban.metakanbanboard')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta Kanban Status Column',
                'verbose_name_plural': 'Meta Kanban Status Columns',
                'ordering': ['position_id'],
            },
        ),
        migrations.CreateModel(
            name='MetaKanbanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('uncategorized', 'Uncategorized'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='uncategorized', max_length=100)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metakanban.metakanbanboard')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metakanban.metakanbanstatuscolumn')),
            ],
            options={
                'verbose_name': 'Meta Kanban Task',
                'verbose_name_plural': 'Meta Kanban Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetaKanbanComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metakanban.metakanbantask')),
            ],
            options={
                'verbose_name': 'Meta Kanban Comment',
                'verbose_name_plural': 'Meta Kanban Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='metakanbanboard',
            index=models.Index(fields=['created_at'], name='metakanban__created_e1b937_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanboard',
            index=models.Index(fields=['updated_at'], name='metakanban__updated_490a7c_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanboard',
            index=models.Index(fields=['project'], name='metakanban__project_462e7a_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanboard',
            index=models.Index(fields=['llm_model'], name='metakanban__llm_mod_2be920_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanboard',
            index=models.Index(fields=['created_by_user'], name='metakanban__created_661d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanboard',
            index=models.Index(fields=['title'], name='metakanban__title_cfe14d_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanboard',
            index=models.Index(fields=['created_at', 'updated_at'], name='metakanban__created_2e0fce_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanboard',
            index=models.Index(fields=['created_at', 'updated_at', 'project'], name='metakanban__created_f54415_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanboard',
            index=models.Index(fields=['created_at', 'updated_at', 'llm_model'], name='metakanban__created_90ed81_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanboard',
            index=models.Index(fields=['created_at', 'updated_at', 'created_by_user'], name='metakanban__created_54c809_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanboard',
            index=models.Index(fields=['created_at', 'updated_at', 'title'], name='metakanban__created_d95c99_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanboard',
            index=models.Index(fields=['created_at', 'updated_at', 'project', 'llm_model'], name='metakanban__created_2436b5_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanboard',
            index=models.Index(fields=['created_at', 'updated_at', 'project', 'created_by_user'], name='metakanban__created_79b50f_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanboard',
            index=models.Index(fields=['created_at', 'updated_at', 'project', 'title'], name='metakanban__created_0de50d_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanboard',
            index=models.Index(fields=['created_at', 'updated_at', 'llm_model', 'created_by_user'], name='metakanban__created_07f842_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanboard',
            index=models.Index(fields=['created_at', 'updated_at', 'llm_model', 'title'], name='metakanban__created_7cb456_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanboard',
            index=models.Index(fields=['created_at', 'updated_at', 'created_by_user', 'title'], name='metakanban__created_2a0278_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanboard',
            index=models.Index(fields=['created_at', 'updated_at', 'project', 'llm_model', 'created_by_user'], name='metakanban__created_21e76f_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanboard',
            index=models.Index(fields=['created_at', 'updated_at', 'project', 'llm_model', 'title'], name='metakanban__created_f99a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanboard',
            index=models.Index(fields=['created_at', 'updated_at', 'project', 'created_by_user', 'title'], name='metakanban__created_21532d_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanboard',
            index=models.Index(fields=['created_at', 'updated_at', 'llm_model', 'created_by_user', 'title'], name='metakanban__created_b2060b_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanstatuscolumn',
            index=models.Index(fields=['created_at'], name='metakanban__created_577058_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanstatuscolumn',
            index=models.Index(fields=['updated_at'], name='metakanban__updated_68130f_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanstatuscolumn',
            index=models.Index(fields=['created_by_user'], name='metakanban__created_03a58c_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanstatuscolumn',
            index=models.Index(fields=['column_name'], name='metakanban__column__0b3a01_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanstatuscolumn',
            index=models.Index(fields=['created_at', 'updated_at'], name='metakanban__created_ed572c_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanstatuscolumn',
            index=models.Index(fields=['created_at', 'updated_at', 'created_by_user'], name='metakanban__created_a2eefd_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanstatuscolumn',
            index=models.Index(fields=['created_at', 'updated_at', 'column_name'], name='metakanban__created_365b96_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanstatuscolumn',
            index=models.Index(fields=['created_at', 'updated_at', 'column_name', 'created_by_user'], name='metakanban__created_8accde_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbantask',
            index=models.Index(fields=['created_at'], name='metakanban__created_75e743_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbantask',
            index=models.Index(fields=['updated_at'], name='metakanban__updated_2aa5e4_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbantask',
            index=models.Index(fields=['board'], name='metakanban__board_i_3f3a99_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbantask',
            index=models.Index(fields=['status_column'], name='metakanban__status__28f385_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbantask',
            index=models.Index(fields=['created_by_user'], name='metakanban__created_ce4603_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbantask',
            index=models.Index(fields=['title'], name='metakanban__title_61a470_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbantask',
            index=models.Index(fields=['created_at', 'updated_at'], name='metakanban__created_38ba55_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbantask',
            index=models.Index(fields=['created_at', 'updated_at', 'board'], name='metakanban__created_4a852e_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbantask',
            index=models.Index(fields=['created_at', 'updated_at', 'status_column'], name='metakanban__created_272090_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbantask',
            index=models.Index(fields=['created_at', 'updated_at', 'created_by_user'], name='metakanban__created_c3613e_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbantask',
            index=models.Index(fields=['created_at', 'updated_at', 'title'], name='metakanban__created_1ccb1f_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbantask',
            index=models.Index(fields=['created_at', 'updated_at', 'board', 'status_column'], name='metakanban__created_220825_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbantask',
            index=models.Index(fields=['created_at', 'updated_at', 'board', 'created_by_user'], name='metakanban__created_ee5961_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbantask',
            index=models.Index(fields=['created_at', 'updated_at', 'board', 'title'], name='metakanban__created_39e3ca_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbantask',
            index=models.Index(fields=['created_at', 'updated_at', 'status_column', 'created_by_user'], name='metakanban__created_983cea_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbantask',
            index=models.Index(fields=['created_at', 'updated_at', 'status_column', 'title'], name='metakanban__created_a09fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbantask',
            index=models.Index(fields=['created_at', 'updated_at', 'created_by_user', 'title'], name='metakanban__created_5b7346_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbantask',
            index=models.Index(fields=['created_at', 'updated_at', 'board', 'status_column', 'created_by_user'], name='metakanban__created_2340f5_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbantask',
            index=models.Index(fields=['created_at', 'updated_at', 'board', 'status_column', 'title'], name='metakanban__created_a9d7b3_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbantask',
            index=models.Index(fields=['created_at', 'updated_at', 'board', 'created_by_user', 'title'], name='metakanban__created_c1e96a_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbantask',
            index=models.Index(fields=['created_at', 'updated_at', 'status_column', 'created_by_user', 'title'], name='metakanban__created_80b82f_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbancomment',
            index=models.Index(fields=['created_at'], name='metakanban__created_60220a_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbancomment',
            index=models.Index(fields=['updated_at'], name='metakanban__updated_75c5ab_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbancomment',
            index=models.Index(fields=['task'], name='metakanban__task_id_f50fb7_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbancomment',
            index=models.Index(fields=['comment_by_user'], name='metakanban__comment_ae40d5_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbancomment',
            index=models.Index(fields=['created_at', 'updated_at'], name='metakanban__created_085d6a_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbancomment',
            index=models.Index(fields=['created_at', 'updated_at', 'task'], name='metakanban__created_7169c2_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbancomment',
            index=models.Index(fields=['created_at', 'updated_at', 'comment_by_user'], name='metakanban__created_8049a9_idx'),
        ),
    ]
