# Generated by Django 5.0.8 on 2024-10-27 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metakanban', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='metakanbantask',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MetaKanbanChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create_task', 'Create Task'), ('update_task', 'Update Task'), ('delete_task', 'Delete Task'), ('move_task', 'Move Task'), ('assign_task', 'Assign Task'), ('create_column', 'Create Column'), ('update_column', 'Update Column'), ('delete_column', 'Delete Column'), ('column_reorder', 'Reorder Column'), ('create_comment', 'Create Comment'), ('update_comment', 'Update Comment'), ('delete_comment', 'Delete Comment')], max_length=100)),
                ('action_details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metakanban.metakanbanboard')),
                ('change_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_kanban_changes_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta Kanban Change Log',
                'verbose_name_plural': 'Meta Kanban Change Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='metakanban__timesta_ce1687_idx'), models.Index(fields=['board'], name='metakanban__board_i_03ddd9_idx'), models.Index(fields=['action_type'], name='metakanban__action__98da76_idx'), models.Index(fields=['change_by_user'], name='metakanban__change__e82355_idx'), models.Index(fields=['timestamp', 'board'], name='metakanban__timesta_8f32c8_idx'), models.Index(fields=['timestamp', 'action_type'], name='metakanban__timesta_dde63a_idx'), models.Index(fields=['timestamp', 'change_by_user'], name='metakanban__timesta_9d1b16_idx'), models.Index(fields=['timestamp', 'board', 'action_type'], name='metakanban__timesta_b1cd69_idx'), models.Index(fields=['timestamp', 'board', 'change_by_user'], name='metakanban__timesta_ca2835_idx'), models.Index(fields=['timestamp', 'action_type', 'change_by_user'], name='metakanban__timesta_1ea9df_idx'), models.Index(fields=['timestamp', 'board', 'action_type', 'change_by_user'], name='metakanban__timesta_a0d634_idx')],
            },
        ),
    ]
