# Generated by Django 5.0.8 on 2024-10-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metakanban', '0003_alter_metakanbanchangelog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metakanbanchangelog',
            name='action_type',
            field=models.CharField(blank=True, choices=[('create_task', 'Create Task'), ('update_task', 'Update Task'), ('delete_task', 'Delete Task'), ('move_task', 'Move Task'), ('assign_task', 'Assign Task'), ('create_column', 'Create Column'), ('update_column', 'Update Column'), ('delete_column', 'Delete Column'), ('create_comment', 'Create Comment'), ('update_comment', 'Update Comment'), ('delete_comment', 'Delete Comment')], default='update_task', max_length=100, null=True),
        ),
    ]
