# Generated by Django 5.0.8 on 2024-10-27 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metakanban', '0004_alter_metakanbanchangelog_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaKanbanTaskLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=10000)),
                ('label_color', models.CharField(choices=[('#FF0000', 'Red'), ('#FFA500', 'Orange'), ('#FFFF00', 'Yellow'), ('#008000', 'Green'), ('#008080', 'Teal'), ('#0000FF', 'Blue'), ('#000080', 'Navy'), ('#EE82EE', 'Violet'), ('#FFC0CB', 'Pink'), ('#000000', 'Black'), ('#A52A2A', 'Brown'), ('#FFFFFF', 'White'), ('#808080', 'Gray')], default='#000080', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meta Kanban Task Label',
                'verbose_name_plural': 'Meta Kanban Task Labels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='metakanbanchangelog',
            name='metakanban__board_i_03ddd9_idx',
        ),
        migrations.RemoveIndex(
            model_name='metakanbanchangelog',
            name='metakanban__timesta_8f32c8_idx',
        ),
        migrations.RemoveIndex(
            model_name='metakanbanchangelog',
            name='metakanban__timesta_b1cd69_idx',
        ),
        migrations.RemoveIndex(
            model_name='metakanbanchangelog',
            name='metakanban__timesta_ca2835_idx',
        ),
        migrations.RemoveIndex(
            model_name='metakanbanchangelog',
            name='metakanban__timesta_a0d634_idx',
        ),
        migrations.RemoveField(
            model_name='metakanbanchangelog',
            name='board',
        ),
        migrations.RemoveField(
            model_name='metakanbanstatuscolumn',
            name='column_description',
        ),
        migrations.RemoveField(
            model_name='metakanbantask',
            name='assignee',
        ),
        migrations.AddField(
            model_name='metakanbanchangelog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_kanban_change_logs', to='metakanban.metakanbantask'),
        ),
        migrations.AddField(
            model_name='metakanbancomment',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='meta_kanban_comment_files/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='metakanbancomment',
            name='image_attachment',
            field=models.ImageField(blank=True, null=True, upload_to='meta_kanban_comment_images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='metakanbantask',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='metakanban_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metakanbantask',
            name='label',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='metakanbantask',
            name='task_file',
            field=models.FileField(blank=True, null=True, upload_to='metakanban/task_files/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='metakanbantask',
            name='task_image',
            field=models.ImageField(blank=True, null=True, upload_to='metakanban/task_images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='metakanbantask',
            name='task_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metakanbanchangelog',
            name='action_type',
            field=models.CharField(blank=True, choices=[('create_task', 'Create Task'), ('update_task', 'Update Task'), ('delete_task', 'Delete Task'), ('move_task', 'Move Task'), ('assign_task', 'Assign Task'), ('create_comment', 'Create Comment'), ('update_comment', 'Update Comment'), ('delete_comment', 'Delete Comment')], default='update_task', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='metakanbanchangelog',
            index=models.Index(fields=['task'], name='metakanban__task_id_d2b7a6_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanchangelog',
            index=models.Index(fields=['timestamp', 'task'], name='metakanban__timesta_7588b1_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanchangelog',
            index=models.Index(fields=['timestamp', 'task', 'action_type'], name='metakanban__timesta_923c86_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanchangelog',
            index=models.Index(fields=['timestamp', 'task', 'change_by_user'], name='metakanban__timesta_109d86_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanchangelog',
            index=models.Index(fields=['timestamp', 'task', 'action_type', 'change_by_user'], name='metakanban__timesta_b500ae_idx'),
        ),
        migrations.AddField(
            model_name='metakanbantasklabel',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metakanban.metakanbanboard'),
        ),
        migrations.AddField(
            model_name='metakanbantasklabel',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='metakanbantasklabel',
            index=models.Index(fields=['created_at'], name='metakanban__created_23828b_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbantasklabel',
            index=models.Index(fields=['updated_at'], name='metakanban__updated_b8c17c_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbantasklabel',
            index=models.Index(fields=['created_by_user'], name='metakanban__created_083341_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbantasklabel',
            index=models.Index(fields=['label_name'], name='metakanban__label_n_d19b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbantasklabel',
            index=models.Index(fields=['created_at', 'updated_at'], name='metakanban__created_3d5076_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbantasklabel',
            index=models.Index(fields=['created_at', 'updated_at', 'created_by_user'], name='metakanban__created_353266_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbantasklabel',
            index=models.Index(fields=['created_at', 'updated_at', 'label_name'], name='metakanban__created_38d7f4_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbantasklabel',
            index=models.Index(fields=['created_at', 'updated_at', 'label_name', 'created_by_user'], name='metakanban__created_2070f0_idx'),
        ),
    ]
