# Generated by Django 5.0.8 on 2024-10-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metakanban', '0005_metakanbantasklabel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metakanbantask',
            name='priority',
            field=models.CharField(blank=True, choices=[('uncategorized', 'Uncategorized'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='uncategorized', max_length=100, null=True),
        ),
    ]
