# Generated by Django 5.0.8 on 2024-10-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metakanban', '0006_alter_metakanbantask_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metakanbantask',
            name='label',
        ),
        migrations.AddField(
            model_name='metakanbantask',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='metakanban_tasks', to='metakanban.metakanbantasklabel'),
        ),
    ]
