# Generated by Django 5.0.8 on 2024-10-27 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metakanban', '0007_remove_metakanbantask_label_metakanbantask_labels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetaKanbanComment',
        ),
    ]
