# Generated by Django 5.0.8 on 2024-10-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metakanban', '0010_alter_metakanbantask_created_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metakanbanchangelog',
            name='action_type',
            field=models.CharField(blank=True, choices=[('create_task', 'Create Task'), ('update_task', 'Update Task'), ('delete_task', 'Delete Task'), ('move_task', 'Move Task'), ('assign_task', 'Assign Task'), ('create_column', 'Create Column'), ('update_column', 'Update Column'), ('delete_column', 'Delete Column'), ('move_column', 'Move Column'), ('create_label', 'Create Label'), ('update_label', 'Update Label'), ('delete_label', 'Delete Label')], default='update_task', max_length=100, null=True),
        ),
    ]
