# Generated by Django 5.0.8 on 2024-10-28 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metakanban', '0011_alter_metakanbanchangelog_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='metakanbanchangelog',
            name='metakanban__task_id_d2b7a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='metakanbanchangelog',
            name='metakanban__timesta_7588b1_idx',
        ),
        migrations.RemoveIndex(
            model_name='metakanbanchangelog',
            name='metakanban__timesta_923c86_idx',
        ),
        migrations.RemoveIndex(
            model_name='metakanbanchangelog',
            name='metakanban__timesta_109d86_idx',
        ),
        migrations.RemoveIndex(
            model_name='metakanbanchangelog',
            name='metakanban__timesta_b500ae_idx',
        ),
        migrations.RemoveField(
            model_name='metakanbanchangelog',
            name='task',
        ),
        migrations.AddField(
            model_name='metakanbanchangelog',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_kanban_change_logs', to='metakanban.metakanbanboard'),
        ),
        migrations.AddIndex(
            model_name='metakanbanchangelog',
            index=models.Index(fields=['board'], name='metakanban__board_i_03ddd9_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanchangelog',
            index=models.Index(fields=['timestamp', 'board'], name='metakanban__timesta_8f32c8_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanchangelog',
            index=models.Index(fields=['timestamp', 'board', 'action_type'], name='metakanban__timesta_b1cd69_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanchangelog',
            index=models.Index(fields=['timestamp', 'board', 'change_by_user'], name='metakanban__timesta_ca2835_idx'),
        ),
        migrations.AddIndex(
            model_name='metakanbanchangelog',
            index=models.Index(fields=['timestamp', 'board', 'action_type', 'change_by_user'], name='metakanban__timesta_a0d634_idx'),
        ),
    ]
