# Generated by Django 5.0.8 on 2024-10-28 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metakanban', '0012_remove_metakanbanchangelog_metakanban__task_id_d2b7a6_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='metakanbanchangelog',
            name='change_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_kanban_changes_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
