# Generated by Django 5.0.8 on 2024-10-28 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metakanban', '0014_alter_metakanbanstatuscolumn_created_by_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaKanbanMeetingTranscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_transcription_text', models.TextField()),
                ('is_processed_with_ai', models.BooleanField(default=False)),
                ('meeting_transcription_key_takeaways', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metakanban.metakanbanboard')),
            ],
            options={
                'verbose_name': 'Meta Kanban Meeting Transcription',
                'verbose_name_plural': 'Meta Kanban Meeting Transcriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['board', 'is_processed_with_ai'], name='metakanban__board_i_2e6a14_idx'), models.Index(fields=['board', 'is_processed_with_ai', 'created_at'], name='metakanban__board_i_326b5c_idx'), models.Index(fields=['board', 'created_at'], name='metakanban__board_i_34fa3b_idx'), models.Index(fields=['is_processed_with_ai'], name='metakanban__is_proc_dde9c2_idx'), models.Index(fields=['is_processed_with_ai', 'created_at'], name='metakanban__is_proc_4ad143_idx'), models.Index(fields=['created_at'], name='metakanban__created_44f8b4_idx')],
            },
        ),
    ]
