# Generated by Django 5.0.8 on 2024-10-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metakanban', '0015_metakanbanmeetingtranscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='metakanbanboard',
            name='connection_api_key',
            field=models.CharField(default='DJjr5FH-m3SPCpSrnqyTLCnuYCtVYTMKyXRRW0bZmfZ_r3XZoGq_JGDfmIGA_JhPck3hEfDd78dXJJE8HDb_vw', max_length=1000),
        ),
    ]
