# Generated by Django 5.0.8 on 2024-10-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metakanban', '0016_metakanbanboard_connection_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metakanbanboard',
            name='connection_api_key',
            field=models.CharField(default='Q5cGQ_Pnz7CSJjEX7JSbJ4SImxH4idcpuI7axFKIFQFEuJK6M5yHLk7sGVTascw3bVuVccZdl-fkkWKAcxWexw', max_length=1000),
        ),
    ]
