# Generated by Django 5.0.8 on 2024-10-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metakanban', '0017_alter_metakanbanboard_connection_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metakanbanboard',
            name='connection_api_key',
            field=models.CharField(default='ToycmevvI7-6ksRetfw_7HJ4kvU4QO-Rl5tz_7pxzrBh7zAqkjoleMQq2BAteEWMSbpDojVzsWQYpEvBpF87Rg', max_length=1000),
        ),
    ]
