# Generated by Django 5.0.8 on 2024-10-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metakanban', '0018_alter_metakanbanboard_connection_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metakanbanboard',
            name='connection_api_key',
            field=models.CharField(default='yDjOorK-WMPHwXRNzaNpn_bmlm-kv9ZD5znyiRafIG0HwRmr4XNDujopRW7Qc33yD6ri0tP-2MqE1X9NT-v_lw', max_length=1000),
        ),
    ]
