# Generated by Django 5.0.8 on 2024-10-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metakanban', '0019_alter_metakanbanboard_connection_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metakanbanboard',
            name='connection_api_key',
            field=models.CharField(default='lIJ3BLTZf_f8sLUaB387DM6q_6_UNSNZ8xYg7Fld_BrymLr6FjgBHAerTL7SZup_1U9PJvEWI3U6KNlUABpiDQ', max_length=1000),
        ),
    ]
