# Generated by Django 5.0.8 on 2024-10-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metakanban', '0020_alter_metakanbanboard_connection_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metakanbanboard',
            name='connection_api_key',
            field=models.CharField(max_length=1000),
        ),
    ]
