# Generated by Django 5.0.8 on 2024-11-13 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0007_alter_assistant_context_overflow_strategy'),
        ('metakanban', '0021_alter_metakanbanboard_connection_api_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaKanbanAssistantConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('metakanban_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metakanban.metakanbanboard')),
            ],
            options={
                'verbose_name': 'Meta Kanban Assistant Connection',
                'verbose_name_plural': 'Meta Kanban Assistant Connections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['metakanban_board', 'assistant'], name='metakanban__metakan_d07754_idx'), models.Index(fields=['assistant', 'metakanban_board'], name='metakanban__assista_adffaa_idx')],
                'unique_together': {('metakanban_board', 'assistant')},
            },
        ),
    ]
