# Generated by Django 5.0.8 on 2024-12-01 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metakanban', '0022_metakanbanassistantconnection'),
        ('projects', '0002_remove_projectitem_assistants'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metakanbanboard',
            unique_together={('project', 'title')},
        ),
    ]
