# Generated by Django 5.0.8 on 2024-12-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metakanban', '0023_alter_metakanbanboard_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metakanbanstatuscolumn',
            name='column_name',
            field=models.CharField(max_length=10000, unique=True),
        ),
    ]
