# Generated by Django 5.0.8 on 2024-12-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metakanban', '0024_alter_metakanbanstatuscolumn_column_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metakanbantasklabel',
            name='label_name',
            field=models.CharField(max_length=10000, unique=True),
        ),
    ]
