# Generated by Django 5.0.8 on 2024-12-01 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metakanban', '0025_alter_metakanbantasklabel_label_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metakanbantask',
            unique_together={('board', 'title')},
        ),
    ]
