"""
Django settings for web_project project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

from django.conf import settings
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv

from .template import TEMPLATE_CONFIG, THEME_LAYOUT_DIR, THEME_VARIABLES

load_dotenv()  # take environment variables from .env.

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", default='')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", 'True').lower() in ['true', 'yes', '1']


# https://docs.djangoproject.com/en/dev/ref/settings/#allowed-hosts
ALLOWED_HOSTS = ["localhost", "0.0.0.0", "127.0.0.1"]

# Current DJANGO_ENVIRONMENT
ENVIRONMENT = os.environ.get("DJANGO_ENVIRONMENT", default="local")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "apps.theme.dashboards",
    "apps.theme.layouts",
    "apps.theme.front_pages",
    "apps.theme.mail",
    "apps.theme.chat",
    "apps.theme.my_calendar",
    "apps.theme.kanban",
    "apps.theme.ecommerce",
    "apps.theme.academy",
    "apps.theme.logistics",
    "apps.theme.invoice",
    "apps.theme.users",
    "apps.theme.access",
    "apps.theme.pages",
    "apps.theme.authentication",
    "apps.theme.wizard_examples",
    "apps.theme.modal_examples",
    "apps.theme.cards",
    "apps.theme.ui",
    "apps.theme.extended_ui",
    "apps.theme.icons",
    "apps.theme.forms",
    "apps.theme.form_layouts",
    "apps.theme.form_wizard",
    "apps.theme.form_validation",
    "apps.theme.tables",
    "apps.theme.charts",
    "apps.theme.maps",
    "auth.apps.AuthConfig",
    "apps.theme.transactions",
    #############################
    "apps.landing",
    "apps.user_profile_management",
    "apps.user_settings",
    "apps.dashboard",
    "apps.organization",
    "apps.llm_core",
    "apps.llm_transaction",
    "apps.subscription",
    "apps.user_management",
    "apps.user_permissions",
    "apps.assistants",
    "apps.multimodal_chat",
    "apps.memories",
    "apps.starred_messages",
    "apps.message_templates",
    "apps.export_assistants",
    "apps.datasource_sql",
    "apps.datasource_nosql",
    "apps.datasource_knowledge_base",
    #############################
]

MIDDLEWARE = [

    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",

    "web_project.language_middleware.DefaultLanguageMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "config.middleware.SessionTimeoutMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "config.context_processors.language_code",
                "config.context_processors.my_setting",
                "config.context_processors.get_cookie",
                "config.context_processors.environment",
            ],
            "libraries": {
                "theme": "web_project.template_tags.theme",
            },
            "builtins": [
                "django.templatetags.static",
                "web_project.template_tags.theme",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

# Enable i18n and set the list of supported languages
LANGUAGES = [
    ("en", _("English")),
    ("fr", _("French")),
    ("ar", _("Arabic")),
    ("de", _("German")),
    # Add more languages as needed
]

# Set default language
# ! Make sure you have cleared the browser cache after changing the default language
LANGUAGE_CODE = "en"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / "locale",
]
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


STATICFILES_DIRS = [
    BASE_DIR / "src" / "assets",
]

# Default URL on which Django application runs for specific environment
BASE_URL = os.environ.get("BASE_URL", default="http://127.0.0.1:8000")

# Service profit margins and tax rates
__SERVICE_PROFIT_MARGIN = float(os.environ.get("SERVICE_PROFIT_MARGIN", default="2.00"))
__SERVICE_TAX_RATE = float(os.environ.get("SERVICE_TAX_RATE", default="0.18"))


# Salt for encryption
ENCRYPTION_SALT = os.environ.get("ENCRYPTION_SALT", default="")


# Max Assistant exports per organization
MAX_ASSISTANT_EXPORTS_ORGANIZATION = int(os.environ.get("MAX_ASSISTANT_EXPORTS_ORGANIZATION", default="5"))

# Weaviate credentials
WEAVIATE_CLUSTER_URL = os.environ.get("WEAVIATE_CLUSTER_URL", default="")
WEAVIATE_API_KEY = os.environ.get("WEAVIATE_API_KEY", default="")


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Template Settings
# ------------------------------------------------------------------------------

THEME_LAYOUT_DIR = THEME_LAYOUT_DIR
TEMPLATE_CONFIG = TEMPLATE_CONFIG
THEME_VARIABLES = THEME_VARIABLES

# Email Settings
# ------------------------------------------------------------------------------

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "dursun.consulting@gmail.com"
EMAIL_HOST_PASSWORD = "Cosmos12345!"

# Login your mail
# ------------------------------------------------------------------------------
LOGIN_URL = "/app/login/"
LOGOUT_REDIRECT_URL = "/app/login/"


# Session
# ------------------------------------------------------------------------------

SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_SAVE_EVERY_REQUEST = True

SESSION_COOKIE_AGE = 60 * 60 * 24  # 1 day

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5050",
]

EXCLUDED_PAGES = [
    "/",
    "/app/exported_assistants/exported/",
    "/contact-form-submit",
    "/docs",
    "/faq",
    "/app/login",
    "/app/logout",
    "/app/register",
    "/app/verify_email_page",
    "/app/verify_email",
    "/app/send_verification",
    "/app/forgot_password",
    "/app/reset_password",
]

# Your stuff...
# ------------------------------------------------------------------------------

DESIGN_DOCS_ROUTE = 'dev/design/'

# Media Settings
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_FROM_EMAIL = ""

# API version for exporting agents
EXPORT_API_BASE_URL = "app/export_assistants/api/v1/export"

# Celery task manager
LEAN_BASE_URL = BASE_URL.split("://")[-1].split(":")[0]
CELERY_BROKER_URL = f'redis://{LEAN_BASE_URL}:6379/0'
CELERY_RESULT_BACKEND = f'redis://{LEAN_BASE_URL}:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'



