# Generated by Django 5.0.8 on 2024-11-03 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyCourseInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=1000)),
                ('course_instructor_bio', models.TextField()),
                ('course_instructor_image_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Academy Course Instructor',
                'verbose_name_plural': 'Academy Course Instructors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademyCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=1000)),
                ('course_description', models.TextField()),
                ('course_language', models.CharField(max_length=1000)),
                ('course_video_urls', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmd_academy.academycourseinstructor')),
            ],
            options={
                'verbose_name': 'Academy Course',
                'verbose_name_plural': 'Academy Courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademyCourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=1000)),
                ('section_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='bmd_academy.academycourse')),
            ],
            options={
                'verbose_name': 'Academy Course Section',
                'verbose_name_plural': 'Academy Course Sections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademyCourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=1000)),
                ('video_content', models.FileField(upload_to='academy/course_videos/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='bmd_academy.academycoursesection')),
            ],
            options={
                'verbose_name': 'Academy Course Video',
                'verbose_name_plural': 'Academy Course Videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='academycourseinstructor',
            index=models.Index(fields=['full_name', 'created_at'], name='bmd_academy_full_na_65d261_idx'),
        ),
        migrations.AddIndex(
            model_name='academycourse',
            index=models.Index(fields=['course_title', 'course_language', 'created_at'], name='bmd_academy_course__92f1ee_idx'),
        ),
        migrations.AddIndex(
            model_name='academycoursesection',
            index=models.Index(fields=['section_name', 'created_at'], name='bmd_academy_section_1d4017_idx'),
        ),
        migrations.AddIndex(
            model_name='academycoursevideo',
            index=models.Index(fields=['video_title', 'created_at'], name='bmd_academy_video_t_97b577_idx'),
        ),
    ]
