# Generated by Django 5.0.8 on 2024-11-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmd_academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academycoursevideo',
            name='video_thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='academy/course_video_thumbnails/%Y/%m/%d/'),
        ),
    ]
