# Generated by Django 5.0.8 on 2024-11-03 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmd_academy', '0002_academycoursevideo_video_thumbnail_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academycourseinstructor',
            name='course_instructor_image_url',
        ),
    ]
