# Generated by Django 5.0.8 on 2024-11-03 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmd_academy', '0003_remove_academycourseinstructor_course_instructor_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academycourse',
            name='course_video_urls',
        ),
    ]
