# Generated by Django 5.0.8 on 2024-11-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmd_academy', '0004_remove_academycourse_course_video_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academycoursevideo',
            name='video_thumbnail_image',
        ),
        migrations.AddField(
            model_name='academycourse',
            name='course_thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='academy/course_video_thumbnails/%Y/%m/%d/'),
        ),
    ]
