# Generated by Django 5.0.8 on 2024-11-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmd_academy', '0005_remove_academycoursevideo_video_thumbnail_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academycoursevideo',
            name='video_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
