# Generated by Django 5.0.8 on 2024-11-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmd_academy', '0006_academycoursevideo_video_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academycoursevideo',
            name='video_content',
        ),
        migrations.AddField(
            model_name='academycoursevideo',
            name='video_content_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
