# Generated by Django 5.0.8 on 2024-11-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmd_academy', '0007_remove_academycoursevideo_video_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academycourse',
            name='course_thumbnail_image',
        ),
        migrations.AddField(
            model_name='academycourse',
            name='course_thumbnail_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
