# Generated by Django 5.0.8 on 2024-11-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmd_academy', '0008_remove_academycourse_course_thumbnail_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academycourse',
            name='course_slug',
            field=models.SlugField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='academycourse',
            name='course_title',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
