# Generated by Django 5.0.8 on 2024-11-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmd_academy', '0009_academycourse_course_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academycoursesection',
            name='section_slug',
            field=models.SlugField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='academycoursevideo',
            name='video_slug',
            field=models.SlugField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
