# Generated by Django 5.0.8 on 2024-11-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmd_academy', '0010_academycoursesection_section_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academycoursesection',
            name='section_slug',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='academycoursesection',
            unique_together={('course', 'section_name')},
        ),
        migrations.AlterUniqueTogether(
            name='academycoursevideo',
            unique_together={('course_section', 'video_title')},
        ),
    ]
