# Generated by Django 5.0.8 on 2024-11-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmd_academy', '0011_alter_academycoursesection_section_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academycourse',
            name='course_under_construction',
            field=models.BooleanField(default=True),
        ),
    ]
