# Generated by Django 5.0.8 on 2024-11-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmd_academy', '0012_academycourse_course_under_construction'),
    ]

    operations = [
        migrations.AddField(
            model_name='academycourse',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
