# Generated by Django 5.0.6 on 2024-07-01 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('add_organizations', 'Add Organizations'), ('update_organizations', 'Update Organizations'), ('list_organizations', 'List Organizations'), ('delete_organizations', 'Delete Organizations'), ('add_llm_cores', 'Add LLM Cores'), ('update_llm_cores', 'Update LLM Cores'), ('list_llm_cores', 'List LLM Cores'), ('delete_llm_cores', 'Delete LLM Cores'), ('list_transactions', 'List Transactions'), ('add_users', 'Add Users'), ('update_users', 'Update Users'), ('list_users', 'List Users'), ('delete_users', 'Delete Users'), ('modify_user_permissions', 'Modify User Permissions'), ('list_user_permissions', 'List User Permissions'), ('add_assistants', 'Add Assistants'), ('update_assistants', 'Update Assistants'), ('list_assistants', 'List Assistants'), ('delete_assistants', 'Delete Assistants'), ('create_and_use_chats', 'Create and Use Chats'), ('remove_chats', 'Remove Chats'), ('add_assistant_memories', 'Add Assistant Memories'), ('update_assistant_memories', 'Update Assistant Memories'), ('list_assistant_memories', 'List Assistant Memories'), ('delete_assistant_memories', 'Delete Assistant Memories'), ('export_assistant', 'Export Assistant'), ('add_orchestrations', 'Add Orchestrations'), ('update_orchestrations', 'Update Orchestrations'), ('list_orchestrations', 'List Orchestrations'), ('delete_orchestration', 'Delete Orchestrations'), ('add_file_systems', 'Add File Systems'), ('update_file_systems', 'Update File Systems'), ('list_file_systems', 'List File Systems'), ('delete_file_systems', 'Delete File Systems'), ('add_web_browsers', 'Add Web Browsers'), ('update_web_browsers', 'Update Web Browsers'), ('list_web_browsers', 'List Web Browsers'), ('delete_web_browsers', 'Delete Web Browsers'), ('add_sql_databases', 'Add SQL Databases'), ('update_sql_databases', 'Update SQL Databases'), ('list_sql_databases', 'List SQL Databases'), ('delete_sql_databases', 'Delete SQL Databases'), ('add_nosql_databases', 'Add NoSQL Databases'), ('update_nosql_databases', 'Update NoSQL Databases'), ('list_nosql_databases', 'List NoSQL Databases'), ('delete_nosql_databases', 'Delete NoSQL Databases'), ('add_knowledge_bases', 'Add Knowledge Bases'), ('update_knowledge_bases', 'Update Knowledge Bases'), ('list_knowledge_bases', 'List Knowledge Bases'), ('delete_knowledge_bases', 'Delete Knowledge Bases'), ('add_image_storages', 'Add Image Storages'), ('update_image_storages', 'Update Image Storages'), ('list_image_storages', 'List Image Storages'), ('delete_image_storages', 'Delete Image Storages'), ('add_video_storages', 'Add Video Storages'), ('update_video_storages', 'Update Video Storages'), ('list_video_storages', 'List Video Storages'), ('delete_video_storages', 'Delete Video Storages'), ('add_audio_storages', 'Add Audio Storages'), ('update_audio_storages', 'Update Audio Storages'), ('list_audio_storages', 'List Audio Storages'), ('delete_audio_storages', 'Delete Audio Storages'), ('add_functions', 'Add Functions'), ('update_functions', 'Update Functions'), ('list_functions', 'List Functions'), ('delete_functions', 'Delete Functions'), ('add_apis', 'Add APIs'), ('update_apis', 'Update APIs'), ('list_apis', 'List APIs'), ('delete_apis', 'Delete APIs'), ('add_scheduled_jobs', 'Add Scheduled Jobs'), ('update_scheduled_jobs', 'Update Scheduled Jobs'), ('list_scheduled_jobs', 'List Scheduled Jobs'), ('delete_scheduled_jobs', 'Delete Scheduled Jobs'), ('add_triggers', 'Add Triggers'), ('update_triggers', 'Update Triggers'), ('list_triggers', 'List Triggers'), ('delete_triggers', 'Delete Triggers'), ('can_generate_images', 'Can Generate Images'), ('can_generate_audio', 'Can Generate Audio'), ('add_integrations', 'Add Integrations'), ('update_integrations', 'Update Integrations'), ('list_integrations', 'List Integrations'), ('delete_integrations', 'Delete Integrations'), ('add_meta_integrations', 'Add Meta Integrations'), ('update_meta_integrations', 'Update Meta Integrations'), ('list_meta_integrations', 'List Meta Integrations'), ('delete_meta_integrations', 'Delete Meta Integrations')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
