#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Br6.in™
#  File: 0001_initial.py
#  Last Modified: 2024-10-05 01:39:48
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 14:42:44
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@br6.in.
#
#
#

# Generated by Django 5.1.1 on 2024-09-25 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('add_organizations', 'Add Organizations'), ('update_organizations', 'Update Organizations'), ('list_organizations', 'List Organizations'), ('delete_organizations', 'Delete Organizations'), ('add_llm_cores', 'Add LLM Cores'), ('update_llm_cores', 'Update LLM Cores'), ('list_llm_cores', 'List LLM Cores'), ('delete_llm_cores', 'Delete LLM Cores'), ('list_transactions', 'List Transactions'), ('add_users', 'Add Users'), ('update_users', 'Update Users'), ('list_users', 'List Users'), ('delete_users', 'Delete Users'), ('modify_user_permissions', 'Modify User Permissions'), ('list_user_permissions', 'List User Permissions'), ('add_assistants', 'Add Assistants'), ('update_assistants', 'Update Assistants'), ('list_assistants', 'List Assistants'), ('delete_assistants', 'Delete Assistants'), ('create_and_use_chats', 'Create and Use Chats'), ('remove_chats', 'Remove Chats'), ('add_assistant_memories', 'Add Assistant Memories'), ('update_assistant_memories', 'Update Assistant Memories'), ('list_assistant_memories', 'List Assistant Memories'), ('delete_assistant_memories', 'Delete Assistant Memories'), ('add_export_assistant', 'Add Export Assistant'), ('update_export_assistant', 'Update Export Assistant'), ('list_export_assistant', 'List Export Assistant'), ('delete_export_assistant', 'Delete Export Assistant'), ('add_orchestrations', 'Add Orchestrations'), ('update_orchestrations', 'Update Orchestrations'), ('list_orchestrations', 'List Orchestrations'), ('delete_orchestrations', 'Delete Orchestrations'), ('add_file_systems', 'Add File Systems'), ('update_file_systems', 'Update File Systems'), ('list_file_systems', 'List File Systems'), ('delete_file_systems', 'Delete File Systems'), ('add_web_browsers', 'Add Web Browsers'), ('update_web_browsers', 'Update Web Browsers'), ('list_web_browsers', 'List Web Browsers'), ('delete_web_browsers', 'Delete Web Browsers'), ('add_sql_databases', 'Add SQL Databases'), ('update_sql_databases', 'Update SQL Databases'), ('list_sql_databases', 'List SQL Databases'), ('delete_sql_databases', 'Delete SQL Databases'), ('add_nosql_databases', 'Add NoSQL Databases'), ('update_nosql_databases', 'Update NoSQL Databases'), ('list_nosql_databases', 'List NoSQL Databases'), ('delete_nosql_databases', 'Delete NoSQL Databases'), ('add_knowledge_bases', 'Add Knowledge Bases'), ('update_knowledge_bases', 'Update Knowledge Bases'), ('list_knowledge_bases', 'List Knowledge Bases'), ('delete_knowledge_bases', 'Delete Knowledge Bases'), ('add_media_storages', 'Add Media Storages'), ('update_media_storages', 'Update Media Storages'), ('list_media_storages', 'List Media Storages'), ('delete_media_storages', 'Delete Media Storages'), ('add_ml_model_connections', 'Add ML Model Connections'), ('update_ml_model_connections', 'Update ML Model Connections'), ('list_ml_model_connections', 'List ML Model Connections'), ('delete_ml_model_connections', 'Delete ML Model Connections'), ('add_functions', 'Add Functions'), ('update_functions', 'Update Functions'), ('list_functions', 'List Functions'), ('delete_functions', 'Delete Functions'), ('add_apis', 'Add APIs'), ('update_apis', 'Update APIs'), ('list_apis', 'List APIs'), ('delete_apis', 'Delete APIs'), ('add_scripts', 'Add Scripts'), ('update_scripts', 'Update Scripts'), ('list_scripts', 'List Scripts'), ('delete_scripts', 'Delete Scripts'), ('add_scheduled_jobs', 'Add Scheduled Jobs'), ('update_scheduled_jobs', 'Update Scheduled Jobs'), ('list_scheduled_jobs', 'List Scheduled Jobs'), ('delete_scheduled_jobs', 'Delete Scheduled Jobs'), ('add_triggers', 'Add Triggers'), ('update_triggers', 'Update Triggers'), ('list_triggers', 'List Triggers'), ('delete_triggers', 'Delete Triggers'), ('can_generate_images', 'Can Generate Images'), ('can_generate_audio', 'Can Generate Audio'), ('add_integrations', 'Add Integrations'), ('update_integrations', 'Update Integrations'), ('list_integrations', 'List Integrations'), ('delete_integrations', 'Delete Integrations'), ('add_meta_integrations', 'Add Meta Integrations'), ('update_meta_integrations', 'Update Meta Integrations'), ('list_meta_integrations', 'List Meta Integrations'), ('delete_meta_integrations', 'Delete Meta Integrations'), ('add_starred_messages', 'Add Starred Messages'), ('list_starred_messages', 'List Starred Messages'), ('remove_starred_messages', 'Remove Starred Messages'), ('add_template_messages', 'Add Template Messages'), ('list_template_messages', 'List Template Messages'), ('update_template_messages', 'Update Template Messages'), ('remove_template_messages', 'Remove Template Messages')], max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'permission_type'], name='user_permis_user_id_78612f_idx'), models.Index(fields=['user', 'permission_type', 'is_active'], name='user_permis_user_id_bf67dc_idx'), models.Index(fields=['user', 'is_active'], name='user_permis_user_id_40df0b_idx'), models.Index(fields=['permission_type', 'is_active'], name='user_permis_permiss_a45d8a_idx'), models.Index(fields=['permission_type'], name='user_permis_permiss_558933_idx'), models.Index(fields=['is_active'], name='user_permis_is_acti_d1a36c_idx'), models.Index(fields=['created_at'], name='user_permis_created_ace89e_idx'), models.Index(fields=['user', 'created_at'], name='user_permis_user_id_b1e5e4_idx'), models.Index(fields=['permission_type', 'created_at'], name='user_permis_permiss_071603_idx'), models.Index(fields=['user', 'permission_type', 'created_at'], name='user_permis_user_id_17ccb6_idx'), models.Index(fields=['user', 'permission_type', 'is_active', 'created_at'], name='user_permis_user_id_a117be_idx'), models.Index(fields=['user', 'is_active', 'created_at'], name='user_permis_user_id_973e74_idx'), models.Index(fields=['permission_type', 'is_active', 'created_at'], name='user_permis_permiss_40ec3b_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'permission_type'), name='unique_user_permission')],
            },
        ),
    ]
