# Generated by Django 5.0.6 on 2024-07-02 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_permissions', '0003_alter_userpermission_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermission',
            name='user',
        ),
    ]
