# Generated by Django 5.0.8 on 2024-09-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_permissions', '0005_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='role_permissions',
        ),
        migrations.AddField(
            model_name='userrole',
            name='role_permissions',
            field=models.JSONField(default=list),
        ),
    ]
