#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Jupi.tr™
#  File: 0006_remove_userrole_role_permissions_and_more.py
#  Last Modified: 2024-09-29 19:58:36
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 01:36:42
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@jupi.tr.
#

# Generated by Django 5.0.8 on 2024-09-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_permissions', '0005_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='role_permissions',
        ),
        migrations.AddField(
            model_name='userrole',
            name='role_permissions',
            field=models.JSONField(default=list),
        ),
    ]
