# Generated by Django 5.0.6 on 2024-07-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_permissions', '0006_userpermission_unique_user_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
