# Generated by Django 5.0.6 on 2024-07-16 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_permissions', '0013_alter_userpermission_permission_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['user', 'permission_type'], name='user_permis_user_id_78612f_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['user', 'permission_type', 'is_active'], name='user_permis_user_id_bf67dc_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['user', 'is_active'], name='user_permis_user_id_40df0b_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['permission_type', 'is_active'], name='user_permis_permiss_a45d8a_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['permission_type'], name='user_permis_permiss_558933_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['is_active'], name='user_permis_is_acti_d1a36c_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['created_at'], name='user_permis_created_ace89e_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['user', 'created_at'], name='user_permis_user_id_b1e5e4_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['permission_type', 'created_at'], name='user_permis_permiss_071603_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['user', 'permission_type', 'created_at'], name='user_permis_user_id_17ccb6_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['user', 'permission_type', 'is_active', 'created_at'], name='user_permis_user_id_a117be_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['user', 'is_active', 'created_at'], name='user_permis_user_id_973e74_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['permission_type', 'is_active', 'created_at'], name='user_permis_permiss_40ec3b_idx'),
        ),
    ]
