# Generated by Django 5.0.8 on 2024-12-01 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_organization_name'),
        ('user_permissions', '0042_alter_userpermission_permission_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('organization', 'role_name')},
        ),
    ]
