# Generated by Django 5.0.6 on 2024-07-16 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0430_alter_assistant_assistant_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceMediaStorageConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('media_category', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('compressed', 'Compressed'), ('code', 'Code'), ('data', 'Data')], max_length=20)),
                ('directory_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('directory_schema', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
            ],
            options={
                'verbose_name': 'Data Source Media Storage Connection',
                'verbose_name_plural': 'Data Source Media Storage Connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSourceMediaStorageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file_name', models.CharField(max_length=255)),
                ('media_file_size', models.BigIntegerField(blank=True, null=True)),
                ('media_file_type', models.CharField(choices=[('jpg', 'JPEG'), ('png', 'PNG'), ('gif', 'GIF'), ('svg', 'SVG'), ('bmp', 'BMP'), ('tiff', 'TIFF'), ('mp3', 'MP3'), ('wav', 'WAV'), ('flac', 'FLAC'), ('aac', 'AAC'), ('ogg', 'OGG'), ('mp4', 'MP4'), ('avi', 'AVI'), ('mkv', 'MKV'), ('mov', 'MOV'), ('zip', 'ZIP'), ('rar', 'RAR'), ('tar', 'TAR'), ('py', 'Python'), ('js', 'JavaScript'), ('ts', 'TypeScript'), ('php', 'PHP'), ('css', 'CSS'), ('html', 'HTML'), ('java', 'Java'), ('c', 'C'), ('cpp', 'C++'), ('h', 'C-Header'), ('sh', 'Shell'), ('go', 'Go'), ('dart', 'Dart'), ('yml', 'YML'), ('yaml', 'YAML'), ('sql', 'SQL'), ('pkl', 'Pickle')], max_length=10)),
                ('full_file_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='datasource_media_storages.datasourcemediastorageconnection')),
            ],
            options={
                'verbose_name': 'Data Source Media Storage Item',
                'verbose_name_plural': 'Data Source Media Storage Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='datasourcemediastorageconnection',
            index=models.Index(fields=['assistant', 'name'], name='datasource__assista_cd1770_idx'),
        ),
        migrations.AddIndex(
            model_name='datasourcemediastorageconnection',
            index=models.Index(fields=['assistant', 'directory_uri'], name='datasource__assista_cfd765_idx'),
        ),
        migrations.AddIndex(
            model_name='datasourcemediastorageconnection',
            index=models.Index(fields=['assistant', 'created_at'], name='datasource__assista_c1740b_idx'),
        ),
        migrations.AddIndex(
            model_name='datasourcemediastorageitem',
            index=models.Index(fields=['storage_base', 'media_file_name'], name='datasource__storage_4dd7c4_idx'),
        ),
        migrations.AddIndex(
            model_name='datasourcemediastorageitem',
            index=models.Index(fields=['storage_base', 'media_file_type'], name='datasource__storage_b35690_idx'),
        ),
        migrations.AddIndex(
            model_name='datasourcemediastorageitem',
            index=models.Index(fields=['storage_base', 'created_at'], name='datasource__storage_0ba2d6_idx'),
        ),
    ]
