# Generated by Django 5.0.6 on 2024-07-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0431_assistant_storages_base_directory_and_more'),
        ('datasource_media_storages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='datasourcemediastorageconnection',
            name='datasource__assista_cfd765_idx',
        ),
        migrations.RenameField(
            model_name='datasourcemediastorageconnection',
            old_name='directory_uri',
            new_name='directory_full_path',
        ),
        migrations.AddIndex(
            model_name='datasourcemediastorageconnection',
            index=models.Index(fields=['assistant', 'media_category'], name='datasource__assista_f84dcc_idx'),
        ),
        migrations.AddIndex(
            model_name='datasourcemediastorageconnection',
            index=models.Index(fields=['assistant', 'directory_full_path'], name='datasource__assista_66f427_idx'),
        ),
    ]
