# Generated by Django 5.0.8 on 2024-12-01 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0013_alter_assistantoldchatmessagesvectordata_unique_together'),
        ('datasource_media_storages', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datasourcemediastorageconnection',
            unique_together={('assistant', 'name')},
        ),
    ]
