# Generated by Django 5.0.8 on 2024-12-02 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_media_storages', '0002_alter_datasourcemediastorageconnection_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItemVectorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('raw_data_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('vector_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource_media_storages.datasourcemediastorageitem')),
            ],
            options={
                'verbose_name': 'Data Source Media Store Item Vector Data',
                'verbose_name_plural': 'Data Source Media Storage Item Vector Data',
                'indexes': [models.Index(fields=['media_item'], name='datasource__media_i_d5348e_idx'), models.Index(fields=['created_at'], name='datasource__created_af18a3_idx'), models.Index(fields=['updated_at'], name='datasource__updated_425051_idx')],
            },
        ),
    ]
