# Generated by Django 5.0.6 on 2024-07-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_media_storages', '0002_remove_datasourcemediastorageconnection_datasource__assista_cfd765_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcemediastorageitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='datasourcemediastorageitem',
            index=models.Index(fields=['storage_base', 'media_file_size'], name='datasource__storage_9666db_idx'),
        ),
        migrations.AddIndex(
            model_name='datasourcemediastorageitem',
            index=models.Index(fields=['storage_base', 'full_file_path'], name='datasource__storage_5d1aed_idx'),
        ),
        migrations.AddIndex(
            model_name='datasourcemediastorageitem',
            index=models.Index(fields=['storage_base', 'description'], name='datasource__storage_233d5a_idx'),
        ),
    ]
