# Generated by Django 5.0.6 on 2024-07-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_media_storages', '0003_datasourcemediastorageitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcemediastorageitem',
            name='file_bytes',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
