# Generated by Django 5.0.6 on 2024-07-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_media_storages', '0004_datasourcemediastorageitem_file_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcemediastorageconnection',
            name='interpretation_maximum_tokens',
            field=models.IntegerField(default=2048),
        ),
        migrations.AddField(
            model_name='datasourcemediastorageconnection',
            name='interpretation_temperature',
            field=models.FloatField(default=0.25),
        ),
    ]
