# Generated by Django 5.0.6 on 2024-07-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_media_storages', '0005_datasourcemediastorageconnection_interpretation_maximum_tokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcemediastorageitem',
            name='media_file_type',
            field=models.CharField(choices=[('jpg', 'JPEG'), ('png', 'PNG'), ('gif', 'GIF'), ('svg', 'SVG'), ('bmp', 'BMP'), ('tiff', 'TIFF'), ('mp3', 'MP3'), ('wav', 'WAV'), ('flac', 'FLAC'), ('aac', 'AAC'), ('ogg', 'OGG'), ('mp4', 'MP4'), ('avi', 'AVI'), ('mkv', 'MKV'), ('mov', 'MOV'), ('zip', 'ZIP'), ('rar', 'RAR'), ('tar', 'TAR'), ('py', 'Python'), ('js', 'JavaScript'), ('ts', 'TypeScript'), ('php', 'PHP'), ('css', 'CSS'), ('html', 'HTML'), ('java', 'Java'), ('c', 'C'), ('cpp', 'C++'), ('h', 'C-Header'), ('sh', 'Shell'), ('go', 'Go'), ('dart', 'Dart'), ('yml', 'YML'), ('yaml', 'YAML'), ('sql', 'SQL'), ('pkl', 'Pickle'), ('csv', 'CSV'), ('xlsx', 'XLSX'), ('json', 'JSON'), ('xml', 'XML'), ('tsv', 'TSV')], max_length=10),
        ),
    ]
