# Generated by Django 5.0.8 on 2024-12-02 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0014_assistant_is_beamguard_active'),
        ('datasource_file_systems', '0002_alter_datasourcefilesystem_unique_together'),
        ('datasource_nosql', '0004_alter_customnosqlquery_unique_together'),
        ('datasource_sql', '0003_alter_customsqlquery_unique_together'),
        ('organization', '0006_alter_organization_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeamGuardArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=10000, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(choices=[('sql', 'SQL'), ('nosql', 'NoSQL'), ('file_system', 'File System')], max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_assistant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamguard_artifacts', to='assistants.assistant')),
                ('file_system_connection_object', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamguard_artifacts', to='datasource_file_systems.datasourcefilesystem')),
                ('nosql_connection_object', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamguard_artifacts', to='datasource_nosql.nosqldatabaseconnection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beamguard_artifacts', to='organization.organization')),
                ('sql_connection_object', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamguard_artifacts', to='datasource_sql.sqldatabaseconnection')),
            ],
            options={
                'verbose_name': 'BeamGuard Artifact',
                'verbose_name_plural': 'BeamGuard Artifacts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'type'], name='beamguard_b_organiz_af88e4_idx'), models.Index(fields=['organization', 'type', 'created_at'], name='beamguard_b_organiz_25f827_idx'), models.Index(fields=['organization', 'type', 'created_at', 'nickname'], name='beamguard_b_organiz_b07f93_idx')],
            },
        ),
    ]
