# Generated by Django 5.0.8 on 2024-12-02 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0014_assistant_is_beamguard_active'),
        ('beamguard', '0001_initial'),
        ('datasource_file_systems', '0002_alter_datasourcefilesystem_unique_together'),
        ('datasource_nosql', '0004_alter_customnosqlquery_unique_together'),
        ('datasource_sql', '0003_alter_customsqlquery_unique_together'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='beamguardartifact',
            name='beamguard_b_organiz_af88e4_idx',
        ),
        migrations.RemoveIndex(
            model_name='beamguardartifact',
            name='beamguard_b_organiz_25f827_idx',
        ),
        migrations.RemoveIndex(
            model_name='beamguardartifact',
            name='beamguard_b_organiz_b07f93_idx',
        ),
        migrations.RenameField(
            model_name='beamguardartifact',
            old_name='nickname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='beamguardartifact',
            name='created_by_assistant',
        ),
        migrations.RemoveField(
            model_name='beamguardartifact',
            name='organization',
        ),
        migrations.AddField(
            model_name='beamguardartifact',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamguard_artifacts', to='assistants.assistant'),
        ),
        migrations.AddField(
            model_name='beamguardartifact',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beamguardartifact',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='beamguardartifact',
            index=models.Index(fields=['assistant', 'type'], name='beamguard_b_assista_0fb757_idx'),
        ),
        migrations.AddIndex(
            model_name='beamguardartifact',
            index=models.Index(fields=['assistant', 'type', 'created_at'], name='beamguard_b_assista_81c370_idx'),
        ),
        migrations.AddIndex(
            model_name='beamguardartifact',
            index=models.Index(fields=['assistant', 'type', 'created_at', 'name'], name='beamguard_b_assista_8bdb1d_idx'),
        ),
    ]
