# Generated by Django 5.0.8 on 2024-12-02 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamguard', '0002_remove_beamguardartifact_beamguard_b_organiz_af88e4_idx_and_more'),
        ('multimodal_chat', '0005_remove_multimodalchat_context_memory_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='beamguardartifact',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamguard_artifacts', to='multimodal_chat.multimodalchat'),
        ),
    ]
