# Generated by Django 5.0.8 on 2024-12-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamguard', '0003_beamguardartifact_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='beamguardartifact',
            name='raw_query',
            field=models.TextField(blank=True, null=True),
        ),
    ]
