# Generated by Django 5.0.8 on 2024-12-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamguard', '0004_beamguardartifact_raw_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beamguardartifact',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='beamguardartifact',
            name='confirmation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=500),
        ),
    ]
