# Generated by Django 5.0.8 on 2024-12-03 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beamguard', '0005_remove_beamguardartifact_is_confirmed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beamguardartifact',
            old_name='confirmed_at',
            new_name='processed_at',
        ),
    ]
