# Generated by Django 5.0.8 on 2024-12-03 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamguard', '0006_rename_confirmed_at_beamguardartifact_processed_at'),
        ('datasource_file_systems', '0002_alter_datasourcefilesystem_unique_together'),
        ('datasource_nosql', '0004_alter_customnosqlquery_unique_together'),
        ('datasource_sql', '0003_alter_customsqlquery_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beamguardartifact',
            name='file_system_connection_object',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamguard_artifacts', to='datasource_file_systems.datasourcefilesystem'),
        ),
        migrations.AlterField(
            model_name='beamguardartifact',
            name='nosql_connection_object',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamguard_artifacts', to='datasource_nosql.nosqldatabaseconnection'),
        ),
        migrations.AlterField(
            model_name='beamguardartifact',
            name='sql_connection_object',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamguard_artifacts', to='datasource_sql.sqldatabaseconnection'),
        ),
    ]
