# Generated by Django 5.0.8 on 2024-11-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_category', models.CharField(choices=[('computer_vision', 'Computer Vision'), ('generative_ai', 'Generative AI'), ('graph_machine_learning', 'Graph Machine Learning'), ('natural_language_processing', 'Natural Language Processing'), ('miscellaneous', 'Miscellaneous')], default='miscellaneous', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('model_download_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ML Model Integration',
                'verbose_name_plural': 'ML Model Integrations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_category'], name='ml_model_st_model_c_358d70_idx'), models.Index(fields=['created_at'], name='ml_model_st_created_4ea280_idx'), models.Index(fields=['updated_at'], name='ml_model_st_updated_a53ce1_idx')],
            },
        ),
    ]
