# Generated by Django 5.0.8 on 2024-11-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodelintegration',
            name='model_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
