# Generated by Django 5.0.8 on 2024-12-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model_store', '0002_mlmodelintegration_model_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodelintegration',
            name='model_image_url',
        ),
        migrations.AddField(
            model_name='mlmodelintegration',
            name='model_image',
            field=models.ImageField(blank=True, null=True, upload_to='integration_ml_model_images/%Y/%m/%d/'),
        ),
    ]
