# Generated by Django 5.0.8 on 2024-12-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model_store', '0003_remove_mlmodelintegration_model_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodelintegration',
            name='model_category',
            field=models.CharField(choices=[('computer_vision', 'Computer Vision'), ('generative_ai', 'Generative AI'), ('graph_machine_learning', 'Graph Machine Learning'), ('natural_language_processing', 'Natural Language Processing'), ('miscellaneous', 'Miscellaneous'), ('time_series_analysis', 'Time Series Analysis'), ('reinforcement_learning', 'Reinforcement Learning'), ('audio_processing', 'Audio Processing'), ('recommendation_systems', 'Recommendation Systems'), ('tabular_data_learning', 'Tabular Data Learning'), ('3d_data_processing', '3D Data Processing'), ('robotics_and_control', 'Robotics and Control'), ('multimodal_learning', 'Multimodal Learning'), ('biomedical_applications', 'Biomedical Applications'), ('anomaly_detection', 'Anomaly Detection')], default='miscellaneous', max_length=255),
        ),
    ]
