# Generated by Django 5.0.8 on 2024-12-23 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0014_assistant_is_beamguard_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChromeExtensionConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_api_key', models.CharField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chrome_assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Chrome Extension Connection',
                'verbose_name_plural': 'Google Chrome Extension Connections',
                'indexes': [models.Index(fields=['chrome_assistant'], name='browser_ext_chrome__942caf_idx'), models.Index(fields=['owner_user'], name='browser_ext_owner_u_12f9b6_idx'), models.Index(fields=['chrome_assistant', 'owner_user'], name='browser_ext_chrome__fa4258_idx')],
                'unique_together': {('chrome_assistant', 'owner_user')},
            },
        ),
    ]
