# Generated by Django 5.0.8 on 2024-11-09 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0007_alter_assistant_context_overflow_strategy'),
        ('integrations', '0013_alter_assistantintegration_integration_context_overflow_strategy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationVectorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField()),
                ('vector_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration_assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.assistantintegration')),
            ],
            options={
                'verbose_name': 'Integration Vector Data',
                'verbose_name_plural': 'Integration Vector Data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantVectorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField()),
                ('vector_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
            ],
            options={
                'verbose_name': 'Assistant Vector Data',
                'verbose_name_plural': 'Assistant Vector Data',
                'indexes': [models.Index(fields=['assistant'], name='semantor_as_assista_4159b5_idx'), models.Index(fields=['created_at'], name='semantor_as_created_1146b9_idx'), models.Index(fields=['updated_at'], name='semantor_as_updated_59f789_idx')],
            },
        ),
    ]
