# Generated by Django 5.0.8 on 2024-11-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantvectordata',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assistantvectordata',
            name='vector_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='integrationvectordata',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='integrationvectordata',
            name='vector_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
