# Generated by Django 5.0.8 on 2024-11-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantor', '0002_alter_assistantvectordata_raw_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationvectordata',
            name='raw_data_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
