# Generated by Django 5.0.8 on 2024-11-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantor', '0003_integrationvectordata_raw_data_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantvectordata',
            name='raw_data_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
