# Generated by Django 5.0.8 on 2024-11-10 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantor', '0004_assistantvectordata_raw_data_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SemantorConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('maximum_assistant_search_items', models.IntegerField(default=5)),
                ('maximum_integration_search_items', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Semantor Configuration',
                'verbose_name_plural': 'Semantor Configurations',
                'indexes': [models.Index(fields=['user', 'is_active'], name='semantor_se_user_id_c3512a_idx'), models.Index(fields=['user', 'is_active', 'maximum_assistant_search_items'], name='semantor_se_user_id_2144e3_idx'), models.Index(fields=['user', 'is_active', 'maximum_integration_search_items'], name='semantor_se_user_id_dbe74b_idx'), models.Index(fields=['user', 'is_active', 'maximum_assistant_search_items', 'maximum_integration_search_items'], name='semantor_se_user_id_6ad80e_idx')],
            },
        ),
    ]
