# Generated by Django 5.0.8 on 2024-11-10 05:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantor', '0005_semantorconfiguration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='semantorconfiguration',
            name='semantor_se_user_id_c3512a_idx',
        ),
        migrations.RemoveIndex(
            model_name='semantorconfiguration',
            name='semantor_se_user_id_2144e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='semantorconfiguration',
            name='semantor_se_user_id_dbe74b_idx',
        ),
        migrations.RemoveIndex(
            model_name='semantorconfiguration',
            name='semantor_se_user_id_6ad80e_idx',
        ),
        migrations.RenameField(
            model_name='semantorconfiguration',
            old_name='is_active',
            new_name='is_global_network_active',
        ),
        migrations.AddField(
            model_name='semantorconfiguration',
            name='is_local_network_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='semantorconfiguration',
            index=models.Index(fields=['user', 'is_local_network_active', 'is_global_network_active'], name='semantor_se_user_id_cdf617_idx'),
        ),
        migrations.AddIndex(
            model_name='semantorconfiguration',
            index=models.Index(fields=['user', 'is_local_network_active', 'is_global_network_active', 'maximum_assistant_search_items'], name='semantor_se_user_id_aa9907_idx'),
        ),
        migrations.AddIndex(
            model_name='semantorconfiguration',
            index=models.Index(fields=['user', 'is_local_network_active', 'is_global_network_active', 'maximum_integration_search_items'], name='semantor_se_user_id_fccde9_idx'),
        ),
        migrations.AddIndex(
            model_name='semantorconfiguration',
            index=models.Index(fields=['user', 'is_local_network_active', 'is_global_network_active', 'maximum_assistant_search_items', 'maximum_integration_search_items'], name='semantor_se_user_id_ba4a8a_idx'),
        ),
    ]
