# Generated by Django 5.0.8 on 2024-11-16 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leanmod', '0002_initial'),
        ('semantor', '0006_remove_semantorconfiguration_semantor_se_user_id_c3512a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeanModVectorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('raw_data_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('vector_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leanmod_assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leanmod.leanassistant')),
            ],
            options={
                'verbose_name': 'LeanMod Assistant Vector Data',
                'verbose_name_plural': 'LeanMod Assistant Vector Data',
                'indexes': [models.Index(fields=['leanmod_assistant'], name='semantor_le_leanmod_2cd8c1_idx'), models.Index(fields=['created_at'], name='semantor_le_created_0a6fe7_idx'), models.Index(fields=['updated_at'], name='semantor_le_updated_3fd164_idx')],
            },
        ),
    ]
