# Generated by Django 5.0.8 on 2024-11-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantor', '0007_leanmodvectordata'),
    ]

    operations = [
        migrations.AddField(
            model_name='semantorconfiguration',
            name='temporary_data_source_and_tool_access',
            field=models.BooleanField(default=True),
        ),
    ]
