# Generated by Django 5.0.6 on 2024-07-27 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0536_alter_assistant_assistant_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('step_guide', models.JSONField(blank=True, null=True)),
                ('trigger_type', models.CharField(choices=[('interval', 'Interval'), ('chronological', 'Chronological')], default='interval', max_length=255)),
                ('every', models.PositiveIntegerField(blank=True, null=True)),
                ('period', models.CharField(blank=True, choices=[('seconds', 'Seconds'), ('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], max_length=255, null=True)),
                ('cron_datetime_specifier', models.DateTimeField(blank=True, null=True)),
                ('current_run_count', models.PositiveIntegerField(default=0)),
                ('maximum_runs', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_jobs', to='assistants.assistant')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scheduled Job',
                'verbose_name_plural': 'Scheduled Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledJobInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(auto_now=True)),
                ('scheduled_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='mm_scheduled_jobs.scheduledjob')),
            ],
            options={
                'verbose_name': 'Scheduled Job Instance',
                'verbose_name_plural': 'Scheduled Job Instances',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='scheduledjob',
            name='scheduled_job_instances',
            field=models.ManyToManyField(related_name='scheduled_jobs', to='mm_scheduled_jobs.scheduledjobinstance'),
        ),
        migrations.AddIndex(
            model_name='scheduledjobinstance',
            index=models.Index(fields=['scheduled_job', 'status', 'started_at'], name='mm_schedule_schedul_e90319_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjobinstance',
            index=models.Index(fields=['scheduled_job', 'status', 'started_at', 'ended_at'], name='mm_schedule_schedul_008e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjobinstance',
            index=models.Index(fields=['scheduled_job', 'status', 'started_at', 'ended_at', 'id'], name='mm_schedule_schedul_5542ef_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjobinstance',
            index=models.Index(fields=['scheduled_job', 'status', 'started_at', 'ended_at', 'id', 'status'], name='mm_schedule_schedul_b9d6c9_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjob',
            index=models.Index(fields=['name', 'assistant', 'created_by_user', 'created_at'], name='mm_schedule_name_e58ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjob',
            index=models.Index(fields=['created_at'], name='mm_schedule_created_c2219a_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjob',
            index=models.Index(fields=['assistant'], name='mm_schedule_assista_7b121d_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjob',
            index=models.Index(fields=['created_by_user'], name='mm_schedule_created_15dd25_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjob',
            index=models.Index(fields=['assistant', 'created_by_user'], name='mm_schedule_assista_ac7046_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjob',
            index=models.Index(fields=['assistant', 'created_by_user', 'created_at'], name='mm_schedule_assista_13064d_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjob',
            index=models.Index(fields=['assistant', 'created_by_user', 'created_at', 'name'], name='mm_schedule_assista_6e15ea_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjob',
            index=models.Index(fields=['assistant', 'created_by_user', 'created_at', 'name', 'current_run_count'], name='mm_schedule_assista_7be62f_idx'),
        ),
    ]
