# Generated by Django 5.0.8 on 2024-11-14 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_scheduled_jobs', '0001_initial'),
        ('orchestrations', '0002_orchestrationreactantassistantconnection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrchestrationScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('step_guide', models.JSONField(default=list)),
                ('minute', models.CharField(blank=True, max_length=600, null=True)),
                ('hour', models.CharField(blank=True, max_length=240, null=True)),
                ('day_of_week', models.CharField(blank=True, max_length=90, null=True)),
                ('day_of_month', models.CharField(blank=True, max_length=310, null=True)),
                ('month_of_year', models.CharField(blank=True, max_length=120, null=True)),
                ('current_run_count', models.PositiveIntegerField(default=0)),
                ('maximum_runs', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orchestration_scheduled_jobs', to=settings.AUTH_USER_MODEL)),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_jobs', to='orchestrations.maestro')),
            ],
            options={
                'verbose_name': 'Orchestration Scheduled Job',
                'verbose_name_plural': 'Orchestration Scheduled Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrchestrationScheduledJobInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('building', 'Building'), ('initializing_assistant', 'Initializing Assistant'), ('generating', 'Generating'), ('saving_logs', 'Saving Logs'), ('cleaning_up', 'Cleaning Up'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=255)),
                ('logs', models.JSONField(default=list)),
                ('execution_index', models.IntegerField(default=0, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(auto_now=True)),
                ('scheduled_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_job_instances', to='mm_scheduled_jobs.orchestrationscheduledjob')),
            ],
            options={
                'verbose_name': 'Orchestration Scheduled Job Instance',
                'verbose_name_plural': 'Orchestration Scheduled Job Instances',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='orchestrationscheduledjob',
            index=models.Index(fields=['name', 'maestro', 'created_by_user', 'created_at'], name='mm_schedule_name_506119_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationscheduledjob',
            index=models.Index(fields=['created_at'], name='mm_schedule_created_7065cf_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationscheduledjob',
            index=models.Index(fields=['maestro'], name='mm_schedule_maestro_7b3b49_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationscheduledjob',
            index=models.Index(fields=['created_by_user'], name='mm_schedule_created_8f492d_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationscheduledjob',
            index=models.Index(fields=['maestro', 'created_by_user'], name='mm_schedule_maestro_0c76b6_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationscheduledjob',
            index=models.Index(fields=['maestro', 'created_by_user', 'created_at'], name='mm_schedule_maestro_3c5c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationscheduledjob',
            index=models.Index(fields=['maestro', 'created_by_user', 'created_at', 'name'], name='mm_schedule_maestro_cf395d_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationscheduledjob',
            index=models.Index(fields=['maestro', 'created_by_user', 'created_at', 'name', 'current_run_count'], name='mm_schedule_maestro_88e47e_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationscheduledjobinstance',
            index=models.Index(fields=['scheduled_job', 'status', 'started_at'], name='mm_schedule_schedul_b66acd_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationscheduledjobinstance',
            index=models.Index(fields=['scheduled_job', 'status', 'started_at', 'ended_at'], name='mm_schedule_schedul_c4e4eb_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationscheduledjobinstance',
            index=models.Index(fields=['scheduled_job', 'status', 'started_at', 'ended_at', 'id'], name='mm_schedule_schedul_4cc011_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationscheduledjobinstance',
            index=models.Index(fields=['scheduled_job', 'status', 'started_at', 'ended_at', 'id', 'status'], name='mm_schedule_schedul_efe00c_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationscheduledjobinstance',
            index=models.Index(fields=['scheduled_job', 'status', 'started_at', 'ended_at', 'id', 'status', 'logs'], name='mm_schedule_schedul_45ceea_idx'),
        ),
    ]
