# Generated by Django 5.0.6 on 2024-07-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm_scheduled_jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledjob',
            old_name='cron_datetime_specifier',
            new_name='cron_run_at',
        ),
    ]
