# Generated by Django 5.0.8 on 2024-12-01 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm_scheduled_jobs', '0002_orchestrationscheduledjob_and_more'),
        ('orchestrations', '0002_orchestrationreactantassistantconnection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orchestrationscheduledjob',
            unique_together={('maestro', 'name')},
        ),
    ]
