# Generated by Django 5.0.6 on 2024-07-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_scheduled_jobs', '0002_rename_cron_datetime_specifier_scheduledjob_cron_run_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledjobinstance',
            name='logs',
            field=models.JSONField(default=list),
        ),
        migrations.AddIndex(
            model_name='scheduledjobinstance',
            index=models.Index(fields=['scheduled_job', 'status', 'started_at', 'ended_at', 'id', 'status', 'logs'], name='mm_schedule_schedul_e23ad0_idx'),
        ),
    ]
