# Generated by Django 5.0.8 on 2024-12-01 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0013_alter_assistantoldchatmessagesvectordata_unique_together'),
        ('mm_scheduled_jobs', '0003_alter_orchestrationscheduledjob_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduledjob',
            unique_together={('assistant', 'name')},
        ),
    ]
