# Generated by Django 5.0.6 on 2024-07-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_scheduled_jobs', '0003_scheduledjobinstance_logs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledjob',
            name='cron_run_at',
        ),
        migrations.AddField(
            model_name='scheduledjob',
            name='day_of_month',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='scheduledjob',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='scheduledjob',
            name='hour',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='scheduledjob',
            name='minute',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='scheduledjob',
            name='month_of_year',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
