# Generated by Django 5.0.6 on 2024-07-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_scheduled_jobs', '0004_remove_scheduledjob_cron_run_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledjob',
            name='every',
        ),
        migrations.RemoveField(
            model_name='scheduledjob',
            name='period',
        ),
        migrations.RemoveField(
            model_name='scheduledjob',
            name='trigger_type',
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='step_guide',
            field=models.JSONField(default=list),
        ),
    ]
