# Generated by Django 5.0.8 on 2024-12-07 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leanmod', '0008_alter_leanassistant_unique_together'),
        ('mm_scheduled_jobs', '0004_alter_scheduledjob_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeanModScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('step_guide', models.JSONField(default=list)),
                ('minute', models.CharField(blank=True, max_length=600, null=True)),
                ('hour', models.CharField(blank=True, max_length=240, null=True)),
                ('day_of_week', models.CharField(blank=True, max_length=90, null=True)),
                ('day_of_month', models.CharField(blank=True, max_length=310, null=True)),
                ('month_of_year', models.CharField(blank=True, max_length=120, null=True)),
                ('current_run_count', models.PositiveIntegerField(default=0)),
                ('maximum_runs', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leanmod_scheduled_jobs', to=settings.AUTH_USER_MODEL)),
                ('leanmod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_jobs', to='leanmod.leanassistant')),
            ],
            options={
                'verbose_name': 'LeanMod Scheduled Job',
                'verbose_name_plural': 'LeanMod Scheduled Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeanModScheduledJobInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('building', 'Building'), ('initializing_assistant', 'Initializing Assistant'), ('generating', 'Generating'), ('saving_logs', 'Saving Logs'), ('cleaning_up', 'Cleaning Up'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=255)),
                ('logs', models.JSONField(default=list)),
                ('execution_index', models.IntegerField(default=0, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(auto_now=True)),
                ('scheduled_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_job_instances', to='mm_scheduled_jobs.leanmodscheduledjob')),
            ],
            options={
                'verbose_name': 'LeanMod Scheduled Job Instance',
                'verbose_name_plural': 'LeanMod Scheduled Job Instances',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='leanmodscheduledjob',
            index=models.Index(fields=['name', 'leanmod', 'created_by_user', 'created_at'], name='mm_schedule_name_04546b_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodscheduledjob',
            index=models.Index(fields=['created_at'], name='mm_schedule_created_606378_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodscheduledjob',
            index=models.Index(fields=['leanmod'], name='mm_schedule_leanmod_a31686_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodscheduledjob',
            index=models.Index(fields=['created_by_user'], name='mm_schedule_created_c2307f_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodscheduledjob',
            index=models.Index(fields=['leanmod', 'created_by_user'], name='mm_schedule_leanmod_30874c_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodscheduledjob',
            index=models.Index(fields=['leanmod', 'created_by_user', 'created_at'], name='mm_schedule_leanmod_25c095_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodscheduledjob',
            index=models.Index(fields=['leanmod', 'created_by_user', 'created_at', 'name'], name='mm_schedule_leanmod_6ae6c9_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodscheduledjob',
            index=models.Index(fields=['leanmod', 'created_by_user', 'created_at', 'name', 'current_run_count'], name='mm_schedule_leanmod_ecc341_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leanmodscheduledjob',
            unique_together={('leanmod', 'name')},
        ),
        migrations.AddIndex(
            model_name='leanmodscheduledjobinstance',
            index=models.Index(fields=['scheduled_job', 'status', 'started_at'], name='mm_schedule_schedul_98f9c5_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodscheduledjobinstance',
            index=models.Index(fields=['scheduled_job', 'status', 'started_at', 'ended_at'], name='mm_schedule_schedul_f983af_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodscheduledjobinstance',
            index=models.Index(fields=['scheduled_job', 'status', 'started_at', 'ended_at', 'id'], name='mm_schedule_schedul_9e46af_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodscheduledjobinstance',
            index=models.Index(fields=['scheduled_job', 'status', 'started_at', 'ended_at', 'id', 'status'], name='mm_schedule_schedul_6b261b_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodscheduledjobinstance',
            index=models.Index(fields=['scheduled_job', 'status', 'started_at', 'ended_at', 'id', 'status', 'logs'], name='mm_schedule_schedul_b35227_idx'),
        ),
    ]
