# Generated by Django 5.0.6 on 2024-07-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_scheduled_jobs', '0005_remove_scheduledjob_every_remove_scheduledjob_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledjob',
            name='day_of_month',
            field=models.CharField(blank=True, max_length=310, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='hour',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='minute',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='month_of_year',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
