# Generated by Django 5.0.6 on 2024-07-28 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_scheduled_jobs', '0006_alter_scheduledjob_day_of_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledjobinstance',
            name='scheduled_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='mm_scheduled_jobs.scheduledjob'),
        ),
        migrations.AlterField(
            model_name='scheduledjobinstance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('building', 'Building'), ('initializing_assistant', 'Initializing Assistant'), ('generating', 'Generating'), ('saving_logs', 'Saving Logs'), ('cleaning_up', 'Cleaning Up'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=255),
        ),
    ]
