# Generated by Django 5.0.6 on 2024-07-28 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_scheduled_jobs', '0007_alter_scheduledjobinstance_scheduled_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledjobinstance',
            name='scheduled_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='mm_scheduled_jobs.scheduledjob'),
        ),
    ]
