# Generated by Django 5.0.6 on 2024-07-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_scheduled_jobs', '0008_alter_scheduledjobinstance_scheduled_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledjobinstance',
            name='execution_index',
            field=models.IntegerField(default=0),
        ),
    ]
