# Generated by Django 5.0.6 on 2024-07-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_scheduled_jobs', '0009_scheduledjobinstance_execution_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledjobinstance',
            name='execution_index',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
