# Generated by Django 5.1.1 on 2024-09-23 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('script_content', models.TextField(blank=True)),
                ('script_step_guide', models.JSONField(blank=True, default=list)),
                ('script_picture', models.ImageField(blank=True, null=True, upload_to='custom_scripts/%YYYY/%mm/%dd/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Script',
                'verbose_name_plural': 'Custom Scripts',
            },
        ),
        migrations.CreateModel(
            name='CustomScriptReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_source', models.CharField(blank=True, default='internal', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('custom_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm_scripts.customscript')),
            ],
            options={
                'verbose_name': 'Custom Script Reference',
                'verbose_name_plural': 'Custom Script References',
            },
        ),
        migrations.AddField(
            model_name='customscript',
            name='custom_script_references',
            field=models.ManyToManyField(blank=True, to='mm_scripts.customscriptreference'),
        ),
        migrations.AddIndex(
            model_name='customscriptreference',
            index=models.Index(fields=['custom_script', 'assistant'], name='mm_scripts__custom__afa5e7_idx'),
        ),
        migrations.AddIndex(
            model_name='customscriptreference',
            index=models.Index(fields=['assistant', 'custom_script', 'created_by_user'], name='mm_scripts__assista_9b48e6_idx'),
        ),
        migrations.AddIndex(
            model_name='customscriptreference',
            index=models.Index(fields=['created_at'], name='mm_scripts__created_93eeb6_idx'),
        ),
        migrations.AddIndex(
            model_name='customscriptreference',
            index=models.Index(fields=['assistant'], name='mm_scripts__assista_23a799_idx'),
        ),
        migrations.AddIndex(
            model_name='customscriptreference',
            index=models.Index(fields=['custom_script'], name='mm_scripts__custom__b0b470_idx'),
        ),
        migrations.AddIndex(
            model_name='customscriptreference',
            index=models.Index(fields=['created_by_user'], name='mm_scripts__created_6c5ac3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customscriptreference',
            unique_together={('custom_script', 'assistant')},
        ),
        migrations.AddIndex(
            model_name='customscript',
            index=models.Index(fields=['name'], name='mm_scripts__name_4bdd63_idx'),
        ),
        migrations.AddIndex(
            model_name='customscript',
            index=models.Index(fields=['created_by_user'], name='mm_scripts__created_026e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='customscript',
            index=models.Index(fields=['created_at'], name='mm_scripts__created_77d4f9_idx'),
        ),
        migrations.AddIndex(
            model_name='customscript',
            index=models.Index(fields=['updated_at'], name='mm_scripts__updated_3d5554_idx'),
        ),
        migrations.AddIndex(
            model_name='customscript',
            index=models.Index(fields=['is_public'], name='mm_scripts__is_publ_8c5402_idx'),
        ),
        migrations.AddIndex(
            model_name='customscript',
            index=models.Index(fields=['is_featured'], name='mm_scripts__is_feat_6b3db1_idx'),
        ),
        migrations.AddIndex(
            model_name='customscript',
            index=models.Index(fields=['name', 'is_public'], name='mm_scripts__name_aa56f4_idx'),
        ),
    ]
