# Generated by Django 5.0.8 on 2024-12-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_scripts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customscript',
            name='name',
            field=models.CharField(max_length=10000, unique=True),
        ),
    ]
