# Generated by Django 5.0.6 on 2024-07-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_scripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customscript',
            name='script_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customscript',
            name='script_step_guide',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='customscript',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
