# Generated by Django 5.0.8 on 2024-10-14 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm_core', '0002_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftingFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'verbose_name': 'Drafting Folder',
                'verbose_name_plural': 'Drafting Folders',
            },
        ),
        migrations.CreateModel(
            name='DraftingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=4000)),
                ('document_content_json_quill', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafting_document_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafting_document_last_updated_by_user', to=settings.AUTH_USER_MODEL)),
                ('llm_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llm_core.llmcore')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('document_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drafting.draftingfolder')),
            ],
            options={
                'verbose_name': 'Drafting Document',
                'verbose_name_plural': 'Drafting Documents',
            },
        ),
        migrations.AddIndex(
            model_name='draftingfolder',
            index=models.Index(fields=['organization'], name='drafting_dr_organiz_b98e40_idx'),
        ),
        migrations.AddIndex(
            model_name='draftingfolder',
            index=models.Index(fields=['organization', 'name'], name='drafting_dr_organiz_bb601e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='draftingfolder',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='draftingdocument',
            index=models.Index(fields=['organization'], name='drafting_dr_organiz_f299a0_idx'),
        ),
        migrations.AddIndex(
            model_name='draftingdocument',
            index=models.Index(fields=['organization', 'document_folder'], name='drafting_dr_organiz_7e7221_idx'),
        ),
        migrations.AddIndex(
            model_name='draftingdocument',
            index=models.Index(fields=['organization', 'llm_model'], name='drafting_dr_organiz_0e3a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='draftingdocument',
            index=models.Index(fields=['organization', 'llm_model', 'document_folder'], name='drafting_dr_organiz_770dcd_idx'),
        ),
        migrations.AddIndex(
            model_name='draftingdocument',
            index=models.Index(fields=['organization', 'document_folder', 'document_title'], name='drafting_dr_organiz_e39dde_idx'),
        ),
        migrations.AddIndex(
            model_name='draftingdocument',
            index=models.Index(fields=['organization', 'llm_model', 'document_folder', 'document_title'], name='drafting_dr_organiz_a3de84_idx'),
        ),
    ]
