# Generated by Django 5.0.8 on 2024-10-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftingdocument',
            name='document_content_json_quill',
            field=models.TextField(blank=True, null=True),
        ),
    ]
