# Generated by Django 5.0.8 on 2024-10-14 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0004_assistant_multi_step_reasoning_capability_choice'),
        ('drafting', '0002_alter_draftingdocument_document_content_json_quill'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='draftingdocument',
            name='drafting_dr_organiz_0e3a0f_idx',
        ),
        migrations.RemoveIndex(
            model_name='draftingdocument',
            name='drafting_dr_organiz_770dcd_idx',
        ),
        migrations.RemoveIndex(
            model_name='draftingdocument',
            name='drafting_dr_organiz_a3de84_idx',
        ),
        migrations.RemoveField(
            model_name='draftingdocument',
            name='llm_model',
        ),
        migrations.AddField(
            model_name='draftingdocument',
            name='copilot_assistant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant'),
        ),
        migrations.AddIndex(
            model_name='draftingdocument',
            index=models.Index(fields=['organization', 'copilot_assistant'], name='drafting_dr_organiz_29636f_idx'),
        ),
        migrations.AddIndex(
            model_name='draftingdocument',
            index=models.Index(fields=['organization', 'copilot_assistant', 'document_folder'], name='drafting_dr_organiz_d08baa_idx'),
        ),
        migrations.AddIndex(
            model_name='draftingdocument',
            index=models.Index(fields=['organization', 'copilot_assistant', 'document_folder', 'document_title'], name='drafting_dr_organiz_fc2f58_idx'),
        ),
    ]
