# Generated by Django 5.0.8 on 2024-10-14 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0004_assistant_multi_step_reasoning_capability_choice'),
        ('drafting', '0003_remove_draftingdocument_drafting_dr_organiz_0e3a0f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftingdocument',
            name='copilot_assistant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant'),
        ),
    ]
