# Generated by Django 5.0.8 on 2024-10-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0004_alter_draftingdocument_copilot_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftingdocument',
            name='context_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftingdocument',
            name='target_audience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftingdocument',
            name='tone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftingfolder',
            name='meta_context_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
