# Generated by Django 5.0.8 on 2024-10-31 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0006_alter_assistant_project_items'),
        ('drafting', '0005_draftingdocument_context_instructions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftingGoogleAppsConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_api_key', models.CharField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drafting_assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Drafting Google Apps Connection',
                'verbose_name_plural': 'Drafting Google Apps Connections',
                'indexes': [models.Index(fields=['drafting_assistant'], name='drafting_dr_draftin_e78328_idx'), models.Index(fields=['owner_user'], name='drafting_dr_owner_u_888405_idx'), models.Index(fields=['drafting_assistant', 'owner_user'], name='drafting_dr_draftin_435b34_idx')],
                'unique_together': {('drafting_assistant', 'owner_user')},
            },
        ),
    ]
