# Generated by Django 5.0.8 on 2024-12-01 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0006_draftinggoogleappsconnection'),
        ('organization', '0005_alter_organization_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='draftingdocument',
            unique_together={('organization', 'document_folder', 'document_title')},
        ),
    ]
