# Generated by Django 5.0.8 on 2024-10-31 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0006_alter_assistant_project_items'),
        ('organization', '0002_organization_description_organization_mission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetosFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('meta_context_instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'verbose_name': 'Sheetos Folder',
                'verbose_name_plural': 'Sheetos Folders',
            },
        ),
        migrations.CreateModel(
            name='SheetosDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=4000)),
                ('document_content_json_quill', models.TextField(blank=True, null=True)),
                ('context_instructions', models.TextField(blank=True, null=True)),
                ('target_audience', models.TextField(blank=True, null=True)),
                ('tone', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copilot_assistant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheetos_document_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheetos_document_last_updated_by_user', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('document_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetos.sheetosfolder')),
            ],
            options={
                'verbose_name': 'Sheetos Document',
                'verbose_name_plural': 'Sheetos Documents',
            },
        ),
        migrations.CreateModel(
            name='SheetosGoogleAppsConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_api_key', models.CharField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sheetos_assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
            ],
            options={
                'verbose_name': 'Sheetos Google Apps Connection',
                'verbose_name_plural': 'Sheetos Google Apps Connections',
            },
        ),
        migrations.AddIndex(
            model_name='sheetosfolder',
            index=models.Index(fields=['organization'], name='sheetos_she_organiz_c601c3_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetosfolder',
            index=models.Index(fields=['organization', 'name'], name='sheetos_she_organiz_840289_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sheetosfolder',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='sheetosdocument',
            index=models.Index(fields=['organization'], name='sheetos_she_organiz_468ae8_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetosdocument',
            index=models.Index(fields=['organization', 'document_folder'], name='sheetos_she_organiz_dba2e8_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetosdocument',
            index=models.Index(fields=['organization', 'copilot_assistant'], name='sheetos_she_organiz_aa897f_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetosdocument',
            index=models.Index(fields=['organization', 'copilot_assistant', 'document_folder'], name='sheetos_she_organiz_fabd30_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetosdocument',
            index=models.Index(fields=['organization', 'document_folder', 'document_title'], name='sheetos_she_organiz_935505_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetosdocument',
            index=models.Index(fields=['organization', 'copilot_assistant', 'document_folder', 'document_title'], name='sheetos_she_organiz_f9f7bf_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetosgoogleappsconnection',
            index=models.Index(fields=['sheetos_assistant'], name='sheetos_she_sheetos_9c6e76_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetosgoogleappsconnection',
            index=models.Index(fields=['owner_user'], name='sheetos_she_owner_u_60c6df_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetosgoogleappsconnection',
            index=models.Index(fields=['sheetos_assistant', 'owner_user'], name='sheetos_she_sheetos_e9e24a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sheetosgoogleappsconnection',
            unique_together={('sheetos_assistant', 'owner_user')},
        ),
    ]
