# Generated by Django 5.0.8 on 2024-12-01 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_organization_name'),
        ('sheetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sheetosdocument',
            unique_together={('organization', 'document_folder', 'document_title')},
        ),
    ]
