### POST request to get API response from an agent ( the endpoint might be invalid, so the request will fail)

POST http://localhost:8000/app/export_leanmods/api/v1/export/2/TestOrganization/9/TestLeanAssistant1/gpt4o/2024/9/23/4527879919451489
Content-Type: application/json
Authorization: Bearer bimod/2/TestOrganization/9/TestLeanAssistant1/gpt4o/31fb37c753e9fba31681083af2fb0eb13c51a2ff737b6353647823f0f858c3e3

    {
      "chat_history": [
        {
          "role": "user",
          "content": "How are you?"
        }
      ]
    }

### end of request
