### POST request to get API response from an agent ( the endpoint might be invalid, so the request will fail)

POST http://127.0.0.1:8000/app/export_assistants/api/v1/export/11/MySmartFarm/1/HelpfulAssistant/gpt4o/2024/7/20/0614796371619611
Content-Type: application/json
Authorization: Bearer bimod/11/MySmartFarm/1/HelpfulAssistant/gpt4o/b536eea085de3f7e7d4961073f7c376688565cae4b29cffc362947ea66be1f0f

    {
      "chat_history": [
        {
          "role": "user",
          "content": "What do you see in this image.",
          "image_uris": [
            "media/generated/images/6e1a7cb2-7733-4e45-a2f0-ab522a4b1ca7_77fc31dd-9383-4641-a68c-5ad5e612f8bf.png"
          ]
        }
      ]
    }

### end of request
