### POST request to get API response from an agent ( the endpoint might be invalid, so the request will fail)

POST http://localhost:8000/app/export_assistants/api/v1/export/1/SampleOrg/1/MainAssistant/gpt4o/2024/8/25/7295855584340019
Content-Type: application/json
Authorization: Bearer bimod/1/SampleOrg/1/MainAssistant/gpt4o/7ff174388d93b7f69b68bcaad997a312e19e6a66d860170aa275409a3c41d0f2

    {
      "chat_history": [
        {
          "role": "user",
          "content": "How are you?"
        }
      ]
    }

### end of request
