
POST http://127.0.0.1:8000/app/mm_triggered_jobs/api/v1/webhook/1/2/
Content-Type: application/json

    {
      "sample_payload": {
        "test_key_1": "test_value_1",
        "test_key_2": "test_value_2"
      },
      "sample_payload_2": {
        "test_key_3": "test_value_3",
        "test_key_4": "test_value_4",
        "test_key_5": [
            "test_value_5",
            "test_value_6"
        ],
        "test_key_6": {
            "test_key_7": "test_value_7",
            "test_key_8": "test_value_8"
        }
      }
    }

### end of request
