#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Bimod.io™
#  File: execute_metatempo_query_tool_prompt.py
#  Last Modified: 2024-11-13 05:16:34
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-11-13 05:16:34
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@Bimod.io.
#
from apps.core.tool_calls.utils import ToolCallDescriptorNames


def build_tool_prompt__execute_metatempo_query():
    response_prompt = f"""

            ### **TOOL**: MetaTempo Query Execution

            - The MetaTempo Query Execution Tool is a tool you can use to retrieve insights from the AI assistant managing
            the MetaTempo AI-Assisted Tempo Tracking. MetaTempo is a tool that allows projects and teams to track the
            overall performance, status, and efficiency by allowing regular data to be retrieved from team member's computers
            and using that, provides insights and suggestions to the team leaders and managers. It is able to assign activity
            scores, tracking the related tasks members are working on, and creating daily reports as well as broader general/overall
            reports. When you are communicating with a MetaTempo assistant using this tool, the tracker assistant will
            return responses about current statuses to you in natural language so you can answer user's questions about
            the MetaTempo tracking tool as well as understanding the interpretations and reports generated by the assistant.
            You can try to reach any of the specified MetaTempo board connections that is defined within your
            "MetaTempo <> Assistant Connections" section.

            - The format for the dictionary you will output to use MetaTempo Query Execution Tool is as follows:

            '''
                {{
                    "tool": "{ToolCallDescriptorNames.EXECUTE_METATEMPO_QUERY}",
                    "parameters": {{
                        "connection_id": "...",
                        "action": "...",  # Must be either "QUERY" or "REPORT"
                        "query": "...",
                        }}
                    }}
            '''

            ---

            #### **DO NOT WRITE: ** 'json' anywhere in your dictionary or next to "'''" elements.

            #### **INSTRUCTIONS:** The "connection_id" will be the ID of MetaTempo <> Assistant Connection object
            you are referring to for executing your query, and "query" will be the query you are investigating in natural
            language for the MetaTempo assistant to answer.

            To use this tool, you need to provide following fields 'VERY CAREFULLY':

            - [1] The "action" field must be either "QUERY" or "REPORT". If you choose "QUERY", the assistant will
            return the results of the query you are asking for. If you choose "REPORT", the assistant will generate and return
            an overall report of the MetaTempo tracker you are referring to. For example; you can ask "QUERY" to get the
            information about the recent activities of the team members or "REPORT" to generate a general report about the
            overall status.

                **NOTE:** "REPORT" mode will ignore the "query" field, while "QUERY" mode will use it to retrieve the
                information from the MetaTempo Tracker you are referring to.

            - [2] The "query" field must be the query you are investigating in natural language for the MetaTempo assistant
            to answer. This query will be used to retrieve the information from the MetaTempo Tracker you are referring to. For
            example; you can ask "How well the team X is working on project Y in the recent days?" or "What are the most common
            applications and tasks the team is working on?" or "What can you say about the overall activity scores of the
            team members?".

            #### **NOTE**: The system will provide you the results of search in the next 'assistant' message.
            This message will have the output of the agent you are communicating with to understand and query MetaTempo
            insights. You are expected to take in this response, and use it to provide an answer to the user.

            ---

        """
    return response_prompt

