# Generated by Django 5.0.6 on 2024-08-12 23:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'slug'], name='blog_app_bl_name_70f6f1_idx'), models.Index(fields=['name'], name='blog_app_bl_name_cd97e1_idx'), models.Index(fields=['slug'], name='blog_app_bl_slug_9876c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(related_name='posts', to='blog_app.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogSEOMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=300)),
                ('meta_description', models.CharField(blank=True, max_length=1000)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_meta', to='blog_app.blogpost')),
            ],
            options={
                'verbose_name': 'Blog SEO Meta',
                'verbose_name_plural': 'Blog SEO Meta',
                'ordering': ['post'],
            },
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['title', 'slug'], name='blog_app_bl_title_beba11_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['title', 'status'], name='blog_app_bl_title_00e0ad_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['title', 'status', 'published_at'], name='blog_app_bl_title_bbea9d_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['title', 'status', 'created_at'], name='blog_app_bl_title_fe3b74_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['title', 'status', 'updated_at'], name='blog_app_bl_title_6d7042_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['title', 'status', 'published_at', 'created_at'], name='blog_app_bl_title_8637ac_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['title', 'status', 'published_at', 'updated_at'], name='blog_app_bl_title_380d66_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['title', 'status', 'created_at', 'updated_at'], name='blog_app_bl_title_cb386e_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['title', 'status', 'created_at', 'published_at'], name='blog_app_bl_title_1affe6_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['title', 'status', 'updated_at', 'published_at'], name='blog_app_bl_title_56e0b2_idx'),
        ),
        migrations.AddIndex(
            model_name='blogseometa',
            index=models.Index(fields=['post'], name='blog_app_bl_post_id_3f8dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='blogseometa',
            index=models.Index(fields=['meta_title'], name='blog_app_bl_meta_ti_5ac93f_idx'),
        ),
        migrations.AddIndex(
            model_name='blogseometa',
            index=models.Index(fields=['meta_description'], name='blog_app_bl_meta_de_e32856_idx'),
        ),
        migrations.AddIndex(
            model_name='blogseometa',
            index=models.Index(fields=['meta_keywords'], name='blog_app_bl_meta_ke_eef817_idx'),
        ),
        migrations.AddIndex(
            model_name='blogseometa',
            index=models.Index(fields=['post', 'meta_title'], name='blog_app_bl_post_id_241988_idx'),
        ),
        migrations.AddIndex(
            model_name='blogseometa',
            index=models.Index(fields=['post', 'meta_description'], name='blog_app_bl_post_id_070278_idx'),
        ),
        migrations.AddIndex(
            model_name='blogseometa',
            index=models.Index(fields=['post', 'meta_keywords'], name='blog_app_bl_post_id_f4fe8f_idx'),
        ),
    ]
