# Generated by Django 5.0.6 on 2024-08-13 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='categories',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
