# Generated by Django 5.0.6 on 2024-08-13 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_remove_blogpost_categories_delete_blogcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='excerpt',
        ),
    ]
