# Generated by Django 5.0.6 on 2024-08-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_remove_blogpost_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_post_images/%Y/%m/%d/'),
        ),
    ]
