# Generated by Django 5.0.6 on 2024-08-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_blogpost_thumbnail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Tag',
                'verbose_name_plural': 'Blog Tags',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='blog_app_bl_name_018f62_idx'), models.Index(fields=['slug'], name='blog_app_bl_slug_d565b1_idx'), models.Index(fields=['created_at'], name='blog_app_bl_created_602029_idx'), models.Index(fields=['updated_at'], name='blog_app_bl_updated_841b05_idx')],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog_app.blogtag'),
        ),
    ]
