# Generated by Django 5.0.6 on 2024-07-11 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0232_alter_assistant_assistant_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomNoSQLQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('query', models.JSONField()),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom NoSQL Query',
                'verbose_name_plural': 'Custom NoSQL Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoSQLDatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbms_type', models.CharField(choices=[('mongodb', 'MongoDB')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('host', models.CharField(max_length=1000)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('connection_string', models.CharField(blank=True, max_length=5000, null=True)),
                ('is_read_only', models.BooleanField(default=True)),
                ('schema_data_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nosql_database_connections', to='assistants.assistant')),
                ('created_by_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nosql_database_connections', to=settings.AUTH_USER_MODEL)),
                ('custom_queries', models.ManyToManyField(blank=True, to='datasource_nosql.customnosqlquery')),
            ],
            options={
                'verbose_name': 'NoSQL Database Connection',
                'verbose_name_plural': 'NoSQL Database Connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customnosqlquery',
            name='database_connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='datasource_nosql.nosqldatabaseconnection'),
        ),
    ]
