# Generated by Django 5.0.8 on 2024-10-12 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0004_assistant_multi_step_reasoning_capability_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoSQLDatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nosql_db_type', models.CharField(choices=[('couchbase', 'Couchbase')], max_length=500)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('host', models.CharField(max_length=255)),
                ('bucket_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('one_time_retrieval_instance_limit', models.IntegerField(default=100)),
                ('one_time_retrieval_token_limit', models.IntegerField(default=10000)),
                ('is_read_only', models.BooleanField(default=True)),
                ('schema_data_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nosql_database_connections', to='assistants.assistant')),
                ('created_by_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nosql_database_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NoSQL Database Connection',
                'verbose_name_plural': 'NoSQL Database Connections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assistant', 'nosql_db_type', 'name'], name='datasource__assista_53ee03_idx'), models.Index(fields=['assistant', 'nosql_db_type', 'created_at'], name='datasource__assista_2e6be0_idx'), models.Index(fields=['assistant', 'nosql_db_type', 'updated_at'], name='datasource__assista_b92a66_idx'), models.Index(fields=['assistant', 'nosql_db_type', 'name', 'created_at'], name='datasource__assista_429e58_idx'), models.Index(fields=['assistant', 'nosql_db_type', 'name', 'updated_at'], name='datasource__assista_1c23a9_idx')],
            },
        ),
    ]
