# Generated by Django 5.1 on 2024-08-30 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomNoSQLQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('query', models.TextField()),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom NoSQL Query',
                'verbose_name_plural': 'Custom NoSQL Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoSQLDatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbms_type', models.CharField(choices=[('mongodb', 'MongoDB')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('host', models.CharField(max_length=1000)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('db_name', models.CharField(blank=True, max_length=255, null=True)),
                ('connection_string', models.CharField(blank=True, max_length=5000, null=True)),
                ('is_read_only', models.BooleanField(default=True)),
                ('schema_data_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nosql_database_connections', to='assistants.assistant')),
                ('created_by_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nosql_database_connections', to=settings.AUTH_USER_MODEL)),
                ('custom_queries', models.ManyToManyField(blank=True, to='datasource_nosql.customnosqlquery')),
            ],
            options={
                'verbose_name': 'NoSQL Database Connection',
                'verbose_name_plural': 'NoSQL Database Connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customnosqlquery',
            name='database_connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='datasource_nosql.nosqldatabaseconnection'),
        ),
        migrations.AddIndex(
            model_name='nosqldatabaseconnection',
            index=models.Index(fields=['assistant', 'dbms_type', 'name'], name='datasource__assista_d99b40_idx'),
        ),
        migrations.AddIndex(
            model_name='nosqldatabaseconnection',
            index=models.Index(fields=['assistant', 'dbms_type', 'created_at'], name='datasource__assista_7a7bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='nosqldatabaseconnection',
            index=models.Index(fields=['assistant', 'dbms_type', 'updated_at'], name='datasource__assista_e5f66b_idx'),
        ),
        migrations.AddIndex(
            model_name='nosqldatabaseconnection',
            index=models.Index(fields=['assistant', 'dbms_type', 'name', 'created_at'], name='datasource__assista_f481e2_idx'),
        ),
        migrations.AddIndex(
            model_name='nosqldatabaseconnection',
            index=models.Index(fields=['assistant', 'dbms_type', 'name', 'updated_at'], name='datasource__assista_fc5d68_idx'),
        ),
        migrations.AddIndex(
            model_name='customnosqlquery',
            index=models.Index(fields=['database_connection', 'name'], name='datasource__databas_02412a_idx'),
        ),
        migrations.AddIndex(
            model_name='customnosqlquery',
            index=models.Index(fields=['database_connection', 'created_at'], name='datasource__databas_4a9995_idx'),
        ),
        migrations.AddIndex(
            model_name='customnosqlquery',
            index=models.Index(fields=['database_connection', 'updated_at'], name='datasource__databas_e27469_idx'),
        ),
        migrations.AddIndex(
            model_name='customnosqlquery',
            index=models.Index(fields=['database_connection', 'name', 'created_at'], name='datasource__databas_36b832_idx'),
        ),
        migrations.AddIndex(
            model_name='customnosqlquery',
            index=models.Index(fields=['database_connection', 'name', 'updated_at'], name='datasource__databas_905eb9_idx'),
        ),
    ]
