# Generated by Django 5.0.8 on 2024-10-12 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_nosql', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomNoSQLQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('nosql_query', models.TextField()),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_queries', to='datasource_nosql.nosqldatabaseconnection')),
            ],
            options={
                'verbose_name': 'Custom NoSQL Query',
                'verbose_name_plural': 'Custom NoSQL Queries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['database_connection', 'name'], name='datasource__databas_02412a_idx'), models.Index(fields=['database_connection', 'created_at'], name='datasource__databas_4a9995_idx'), models.Index(fields=['database_connection', 'updated_at'], name='datasource__databas_e27469_idx'), models.Index(fields=['database_connection', 'name', 'created_at'], name='datasource__databas_36b832_idx'), models.Index(fields=['database_connection', 'name', 'updated_at'], name='datasource__databas_905eb9_idx')],
            },
        ),
    ]
