# Generated by Django 5.0.6 on 2024-07-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_nosql', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nosqldatabaseconnection',
            name='db_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
