# Generated by Django 5.0.6 on 2024-07-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_nosql', '0002_nosqldatabaseconnection_db_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customnosqlquery',
            name='query',
            field=models.TextField(),
        ),
    ]
