# Generated by Django 5.0.8 on 2024-12-01 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0013_alter_assistantoldchatmessagesvectordata_unique_together'),
        ('datasource_nosql', '0002_customnosqlquery'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nosqldatabaseconnection',
            unique_together={('assistant', 'host', 'bucket_name')},
        ),
    ]
