# Generated by Django 5.0.6 on 2024-07-16 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0402_alter_assistant_assistant_image'),
        ('datasource_nosql', '0003_alter_customnosqlquery_query'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customnosqlquery',
            index=models.Index(fields=['database_connection', 'name'], name='datasource__databas_02412a_idx'),
        ),
        migrations.AddIndex(
            model_name='customnosqlquery',
            index=models.Index(fields=['database_connection', 'created_at'], name='datasource__databas_4a9995_idx'),
        ),
        migrations.AddIndex(
            model_name='customnosqlquery',
            index=models.Index(fields=['database_connection', 'updated_at'], name='datasource__databas_e27469_idx'),
        ),
        migrations.AddIndex(
            model_name='customnosqlquery',
            index=models.Index(fields=['database_connection', 'name', 'created_at'], name='datasource__databas_36b832_idx'),
        ),
        migrations.AddIndex(
            model_name='customnosqlquery',
            index=models.Index(fields=['database_connection', 'name', 'updated_at'], name='datasource__databas_905eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='nosqldatabaseconnection',
            index=models.Index(fields=['assistant', 'dbms_type', 'name'], name='datasource__assista_d99b40_idx'),
        ),
        migrations.AddIndex(
            model_name='nosqldatabaseconnection',
            index=models.Index(fields=['assistant', 'dbms_type', 'created_at'], name='datasource__assista_7a7bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='nosqldatabaseconnection',
            index=models.Index(fields=['assistant', 'dbms_type', 'updated_at'], name='datasource__assista_e5f66b_idx'),
        ),
        migrations.AddIndex(
            model_name='nosqldatabaseconnection',
            index=models.Index(fields=['assistant', 'dbms_type', 'name', 'created_at'], name='datasource__assista_f481e2_idx'),
        ),
        migrations.AddIndex(
            model_name='nosqldatabaseconnection',
            index=models.Index(fields=['assistant', 'dbms_type', 'name', 'updated_at'], name='datasource__assista_fc5d68_idx'),
        ),
    ]
