# Generated by Django 5.0.8 on 2024-12-01 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_nosql', '0003_alter_nosqldatabaseconnection_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customnosqlquery',
            unique_together={('database_connection', 'name')},
        ),
    ]
