# Generated by Django 5.0.8 on 2024-12-04 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_nosql', '0004_alter_customnosqlquery_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoSQLSchemaChunkVectorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('raw_data_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('vector_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nosql_database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource_nosql.nosqldatabaseconnection')),
            ],
            options={
                'verbose_name': 'NoSQL Schema Chunk Vector Data',
                'verbose_name_plural': 'NoSQL Schema Chunk Vector Data',
                'indexes': [models.Index(fields=['nosql_database'], name='datasource__nosql_d_1aae4e_idx'), models.Index(fields=['created_at'], name='datasource__created_959b63_idx'), models.Index(fields=['updated_at'], name='datasource__updated_cf87ca_idx')],
            },
        ),
    ]
