# Generated by Django 5.0.8 on 2024-12-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_nosql', '0005_nosqlschemachunkvectordata'),
    ]

    operations = [
        migrations.AddField(
            model_name='nosqldatabaseconnection',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nosqldatabaseconnection',
            name='nosql_db_type',
            field=models.CharField(choices=[('couchbase', 'Couchbase'), ('mongoDB', 'MongoDB')], max_length=500),
        ),
    ]
