# Generated by Django 5.0.8 on 2024-12-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_nosql', '0006_nosqldatabaseconnection_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosqldatabaseconnection',
            name='nosql_db_type',
            field=models.CharField(choices=[('couchbase', 'Couchbase'), ('mongoDB', 'MongoDB'), ('redis', 'Redis'), ('elasticSearch', 'ElasticSearch'), ('neo4j', 'Neo4j')], max_length=500),
        ),
    ]
