# Generated by Django 5.0.8 on 2024-12-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_nosql', '0007_alter_nosqldatabaseconnection_nosql_db_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosqldatabaseconnection',
            name='bucket_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nosqldatabaseconnection',
            name='nosql_db_type',
            field=models.CharField(choices=[('couchbase', 'Couchbase'), ('mongoDB', 'MongoDB'), ('redis', 'Redis'), ('elasticSearch', 'ElasticSearch'), ('neo4j', 'Neo4j'), ('pinecone', 'Pinecone'), ('weaviate', 'Weaviate')], max_length=500),
        ),
    ]
