# Generated by Django 5.0.8 on 2024-12-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_nosql', '0008_alter_nosqldatabaseconnection_bucket_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosqldatabaseconnection',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nosqldatabaseconnection',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
