# Generated by Django 5.0.8 on 2024-12-18 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0014_assistant_is_beamguard_active'),
        ('datasource_nosql', '0009_alter_nosqldatabaseconnection_password_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nosqldatabaseconnection',
            unique_together={('assistant', 'name')},
        ),
    ]
