# Generated by Django 5.0.8 on 2024-12-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_nosql', '0010_alter_nosqldatabaseconnection_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosqldatabaseconnection',
            name='nosql_db_type',
            field=models.CharField(choices=[('couchbase', 'Couchbase'), ('mongoDB', 'MongoDB'), ('redis', 'Redis'), ('elasticSearch', 'ElasticSearch'), ('neo4j', 'Neo4j'), ('weaviate', 'Weaviate')], max_length=500),
        ),
    ]
