# Generated by Django 5.1.1 on 2024-09-24 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orchestrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportOrchestrationAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('request_limit_per_hour', models.IntegerField(default=1000)),
                ('is_online', models.BooleanField(default=True)),
                ('custom_api_key', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('endpoint', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_orchestrations_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('orchestrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrations.maestro')),
            ],
            options={
                'verbose_name': 'Export Orchestration API',
                'verbose_name_plural': 'Export Orchestration APIs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrchestratorRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('export_orchestration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='export_orchestrations.exportorchestrationapi')),
            ],
            options={
                'verbose_name': 'Request Orchestration Log',
                'verbose_name_plural': 'Request Orchestration Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='exportorchestrationapi',
            index=models.Index(fields=['orchestrator'], name='export_orch_orchest_8712f6_idx'),
        ),
        migrations.AddIndex(
            model_name='exportorchestrationapi',
            index=models.Index(fields=['created_by_user'], name='export_orch_created_1bb8eb_idx'),
        ),
        migrations.AddIndex(
            model_name='exportorchestrationapi',
            index=models.Index(fields=['created_at'], name='export_orch_created_897a6a_idx'),
        ),
        migrations.AddIndex(
            model_name='exportorchestrationapi',
            index=models.Index(fields=['updated_at'], name='export_orch_updated_5ebace_idx'),
        ),
        migrations.AddIndex(
            model_name='exportorchestrationapi',
            index=models.Index(fields=['orchestrator', 'created_at'], name='export_orch_orchest_7cd3cd_idx'),
        ),
        migrations.AddIndex(
            model_name='exportorchestrationapi',
            index=models.Index(fields=['orchestrator', 'updated_at'], name='export_orch_orchest_35c4b5_idx'),
        ),
        migrations.AddIndex(
            model_name='exportorchestrationapi',
            index=models.Index(fields=['orchestrator', 'created_by_user'], name='export_orch_orchest_c64d9f_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestratorrequestlog',
            index=models.Index(fields=['export_orchestration'], name='export_orch_export__f2937e_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestratorrequestlog',
            index=models.Index(fields=['timestamp'], name='export_orch_timesta_dcd6ba_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestratorrequestlog',
            index=models.Index(fields=['export_orchestration', 'timestamp'], name='export_orch_export__cd5062_idx'),
        ),
    ]
