#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Jupi.tr™
#  File: 0002_initial.py
#  Last Modified: 2024-09-25 17:51:06
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 01:36:44
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@jupi.tr.
#

# Generated by Django 5.1.1 on 2024-09-25 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('export_orchestrations', '0001_initial'),
        ('orchestrations', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportorchestrationapi',
            name='orchestrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exported_orchestrations', to='orchestrations.maestro'),
        ),
        migrations.AddField(
            model_name='exportorchestrationapi',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exported_orchestrations', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='orchestratorrequestlog',
            name='export_orchestration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='export_orchestrations.exportorchestrationapi'),
        ),
        migrations.AddIndex(
            model_name='exportorchestrationapi',
            index=models.Index(fields=['orchestrator'], name='export_orch_orchest_8712f6_idx'),
        ),
        migrations.AddIndex(
            model_name='exportorchestrationapi',
            index=models.Index(fields=['created_by_user'], name='export_orch_created_1bb8eb_idx'),
        ),
        migrations.AddIndex(
            model_name='exportorchestrationapi',
            index=models.Index(fields=['created_at'], name='export_orch_created_897a6a_idx'),
        ),
        migrations.AddIndex(
            model_name='exportorchestrationapi',
            index=models.Index(fields=['updated_at'], name='export_orch_updated_5ebace_idx'),
        ),
        migrations.AddIndex(
            model_name='exportorchestrationapi',
            index=models.Index(fields=['orchestrator', 'created_at'], name='export_orch_orchest_7cd3cd_idx'),
        ),
        migrations.AddIndex(
            model_name='exportorchestrationapi',
            index=models.Index(fields=['orchestrator', 'updated_at'], name='export_orch_orchest_35c4b5_idx'),
        ),
        migrations.AddIndex(
            model_name='exportorchestrationapi',
            index=models.Index(fields=['orchestrator', 'created_by_user'], name='export_orch_orchest_c64d9f_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestratorrequestlog',
            index=models.Index(fields=['export_orchestration'], name='export_orch_export__f2937e_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestratorrequestlog',
            index=models.Index(fields=['timestamp'], name='export_orch_timesta_dcd6ba_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestratorrequestlog',
            index=models.Index(fields=['export_orchestration', 'timestamp'], name='export_orch_export__cd5062_idx'),
        ),
    ]
