# Generated by Django 5.0.8 on 2024-12-01 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export_orchestrations', '0002_initial'),
        ('orchestrations', '0002_orchestrationreactantassistantconnection'),
        ('organization', '0005_alter_organization_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exportorchestrationapi',
            unique_together={('organization', 'orchestrator', 'is_public')},
        ),
    ]
