# Generated by Django 5.0.8 on 2024-11-06 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0013_alter_assistantintegration_integration_context_overflow_strategy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaIntegrationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=1000)),
                ('category_description', models.TextField(blank=True, null=True)),
                ('category_image_url', models.URLField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('category_slug', models.SlugField(blank=True, max_length=1000, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meta Integration Category',
                'verbose_name_plural': 'Meta Integration Categories',
                'indexes': [models.Index(fields=['category_name'], name='meta_integr_categor_28f20c_idx')],
                'unique_together': {('category_name',)},
            },
        ),
        migrations.CreateModel(
            name='MetaIntegrationTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.JSONField(blank=True, null=True)),
                ('meta_integration_management_type', models.CharField(choices=[('expert_networks_and_lean_assistant', 'Expert Networks & Lean Assistant'), ('orchestration_maestro_and_lean_assistant', 'Orchestration Maestro & Lean Assistant')], default='expert_networks_and_lean_assistant', max_length=1000)),
                ('meta_integration_name', models.CharField(max_length=1000)),
                ('meta_integration_description', models.TextField(blank=True, null=True)),
                ('meta_integration_team_image', models.ImageField(blank=True, null=True, upload_to='meta_integration_team_images/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration_assistants', models.ManyToManyField(blank=True, related_name='meta_integration_teams', to='integrations.assistantintegration')),
                ('meta_integration_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta_integrations.metaintegrationcategory')),
            ],
            options={
                'verbose_name': 'Meta Integration Team',
                'verbose_name_plural': 'Meta Integration Teams',
                'indexes': [models.Index(fields=['meta_integration_name'], name='meta_integr_meta_in_cf095e_idx'), models.Index(fields=['meta_integration_management_type'], name='meta_integr_meta_in_c15c1d_idx'), models.Index(fields=['meta_integration_category'], name='meta_integr_meta_in_ed95e2_idx'), models.Index(fields=['tags'], name='meta_integr_tags_30aa02_idx'), models.Index(fields=['created_at'], name='meta_integr_created_cdb0ff_idx'), models.Index(fields=['updated_at'], name='meta_integr_updated_b88378_idx')],
            },
        ),
    ]
