# Generated by Django 5.0.8 on 2024-11-06 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta_integrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='metaintegrationteam',
            name='meta_integr_meta_in_c15c1d_idx',
        ),
        migrations.RemoveField(
            model_name='metaintegrationteam',
            name='meta_integration_management_type',
        ),
    ]
