# Generated by Django 5.0.8 on 2024-12-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_integrations', '0002_remove_metaintegrationteam_meta_integr_meta_in_c15c1d_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metaintegrationcategory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='metaintegrationcategory',
            name='category_name',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
