# Generated by Django 5.0.8 on 2024-12-01 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta_integrations', '0003_alter_metaintegrationcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metaintegrationteam',
            unique_together={('meta_integration_category', 'meta_integration_name')},
        ),
    ]
