# Generated by Django 5.0.6 on 2024-08-02 18:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_permissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('bonus_percentage_referrer', models.IntegerField(default=50)),
                ('bonus_percentage_referee', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('current_referrals', models.IntegerField(default=0)),
                ('max_referral_limit', models.IntegerField(default=0)),
                ('datetime_limit', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_on_card', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=16)),
                ('card_expiration_month', models.CharField(max_length=2)),
                ('card_expiration_year', models.CharField(max_length=2)),
                ('card_cvc', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Card',
                'verbose_name_plural': 'Credit Cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('email_token', models.CharField(blank=True, max_length=100, null=True)),
                ('forget_password_token', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=60, null=True)),
                ('birthdate', models.DateField(default=django.utils.timezone.now)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='/profile_pictures/default.png', max_length=1000, upload_to='profile_pictures/%Y/%m/%d/3o1skM3InzGpDXV1')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by_user', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_created_by_users', to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(blank=True, related_name='user_permissions', to='user_permissions.userpermission')),
                ('sub_users', models.ManyToManyField(blank=True, related_name='sub_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('referral_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_code', to='accounts.promocode')),
                ('credit_cards', models.ManyToManyField(blank=True, related_name='user_credit_cards', to='accounts.usercreditcard')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['code'], name='accounts_pr_code_d73dcd_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['is_active'], name='accounts_pr_is_acti_5db432_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['created_at'], name='accounts_pr_created_305448_idx'),
        ),
        migrations.AddIndex(
            model_name='usercreditcard',
            index=models.Index(fields=['user', 'name_on_card', 'card_number', 'created_at'], name='accounts_us_user_id_765ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='usercreditcard',
            index=models.Index(fields=['user', 'name_on_card', 'card_number', 'card_expiration_month', 'card_expiration_year', 'card_cvc', 'created_at'], name='accounts_us_user_id_318068_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='accounts_pr_user_id_97e401_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['email'], name='accounts_pr_email_08cbb0_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user', 'email'], name='accounts_pr_user_id_d70b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user', 'email', 'is_verified'], name='accounts_pr_user_id_cfeda2_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user', 'email', 'is_verified', 'created_at'], name='accounts_pr_user_id_7cb391_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['first_name', 'last_name'], name='accounts_pr_first_n_61792f_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['first_name', 'last_name', 'created_at'], name='accounts_pr_first_n_1ecd65_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['phone_number'], name='accounts_pr_phone_n_c27a97_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['phone_number', 'created_at'], name='accounts_pr_phone_n_dbfa14_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['address'], name='accounts_pr_address_08d395_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['address', 'created_at'], name='accounts_pr_address_83743e_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['city'], name='accounts_pr_city_79ec1d_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['city', 'created_at'], name='accounts_pr_city_3cef42_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['country'], name='accounts_pr_country_13da80_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['country', 'created_at'], name='accounts_pr_country_de9a70_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['postal_code'], name='accounts_pr_postal__cfa89a_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['postal_code', 'created_at'], name='accounts_pr_postal__9c22a5_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_active'], name='accounts_pr_is_acti_d3fcf1_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_active', 'created_at'], name='accounts_pr_is_acti_5b5fc5_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['created_by_user'], name='accounts_pr_created_5befe7_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['created_by_user', 'created_at'], name='accounts_pr_created_bd8f4d_idx'),
        ),
    ]
