# Generated by Django 5.0.8 on 2024-09-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreditcard',
            name='automated_data_backups',
            field=models.BooleanField(default=False),
        ),
    ]
