# Generated by Django 5.1 on 2024-08-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/profile_pictures/default.png', max_length=1000, upload_to='profile_pictures/%Y/%m/%d/0Sqfi4I6L6VOdsqi'),
        ),
    ]
