#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Br6.in™
#  File: 0003_remove_usercreditcard_automated_data_backups_and_more.py
#  Last Modified: 2024-09-30 16:47:04
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 15:45:58
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@br6.in.
#

# Generated by Django 5.0.8 on 2024-09-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usercreditcard_automated_data_backups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercreditcard',
            name='automated_data_backups',
        ),
        migrations.AddField(
            model_name='profile',
            name='automated_data_backups',
            field=models.BooleanField(default=False),
        ),
    ]
