# Generated by Django 5.0.8 on 2024-09-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usercreditcard_automated_data_backups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercreditcard',
            name='automated_data_backups',
        ),
        migrations.AddField(
            model_name='profile',
            name='automated_data_backups',
            field=models.BooleanField(default=False),
        ),
    ]
