# Generated by Django 5.0.8 on 2024-10-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_usercreditcard_automated_data_backups_and_more'),
        ('notifications', '0007_remove_notificationitem_notificatio_user_id_828485_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='notifications.notificationitem'),
        ),
    ]
