# Generated by Django 5.0.8 on 2024-10-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_notifications'),
        ('notifications', '0008_remove_notificationitem_notificatio_created_000e21_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='notifications',
            field=models.ManyToManyField(default=list, related_name='notifications', to='notifications.notificationitem'),
        ),
    ]
