# Generated by Django 5.0.8 on 2024-10-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_notifications'),
        ('notifications', '0010_remove_notificationitem_notificatio_notific_bad5d1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='notifications',
            field=models.ManyToManyField(blank=True, default=list, null=True, related_name='notifications', to='notifications.notificationitem'),
        ),
    ]
