# Generated by Django 5.0.8 on 2024-09-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_free_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_highest_ever_forum_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/profile_pictures/default.png', max_length=1000, upload_to='profile_pictures/%Y/%m/%d/te1H2ogml1EAEG5X'),
        ),
    ]
