# Generated by Django 5.0.8 on 2024-09-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_user_highest_ever_forum_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_accredited_by_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/profile_pictures/default.png', max_length=1000, upload_to='profile_pictures/%Y/%m/%d/3CVHiVhp6tgiIz4b'),
        ),
    ]
