# Generated by Django 5.0.8 on 2024-10-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accreditation_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
