# Generated by Django 5.0.8 on 2024-10-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_accreditation_email_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BimodEmailAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject_raw', models.CharField(max_length=255)),
                ('title_raw', models.CharField(max_length=255)),
                ('body_raw', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bimod Email Announcement',
                'verbose_name_plural': 'Bimod Email Announcements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='accounts_bi_created_31265f_idx'), models.Index(fields=['title_raw'], name='accounts_bi_title_r_c81126_idx'), models.Index(fields=['email_subject_raw'], name='accounts_bi_email_s_140b65_idx')],
            },
        ),
    ]
