# Generated by Django 5.0.8 on 2024-10-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_bimodemailannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='metatempo_tracking_auth_key',
            field=models.CharField(default='FWTt6pA5FIKtd5XLR5iuGbj96ezqUI7A1V8NRqLWGmehkmRnRTfwN02vmYM0V1meBhPjWW5MgiPd5C_f7bOX-g', max_length=100),
        ),
    ]
