# Generated by Django 5.0.8 on 2024-10-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_metatempo_tracking_auth_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='metatempo_tracking_auth_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
