# Generated by Django 5.0.8 on 2025-01-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_metatempo_tracking_auth_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_api_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
