# Generated by Django 5.0.6 on 2024-08-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_profile_free_credits_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_forum_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_forum_rank',
            field=models.CharField(choices=[('unranked', 'Unranked'), ('wood', 'Wood'), ('iron', 'Iron'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('master', 'Master'), ('grandmaster', 'Grandmaster')], default='unranked', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_forum_role',
            field=models.CharField(choices=[('bimod', 'Bimod'), ('client_admin', 'Client Admin'), ('client_user', 'Client User')], default='client_user', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/profile_pictures/default.png', max_length=1000, upload_to='profile_pictures/%Y/%m/%d/TLPMtAS1nIHcLxuK'),
        ),
    ]
