# Generated by Django 5.0.6 on 2024-07-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_profile_created_by_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='profile_pictures/%Y/%m/%d/GLLxtbb0oUiRLdx9'),
        ),
    ]
