# Generated by Django 5.0.6 on 2024-07-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='profile_pictures/%Y/%m/%d/2qJQ2Ai56eacVpTg'),
        ),
    ]
