# Generated by Django 5.0.6 on 2024-07-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_alter_profile_profile_picture'),
        ('user_permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_permissions',
            field=models.ManyToManyField(related_name='profiles', to='user_permissions.userpermission'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='profile_pictures/%Y/%m/%d/ve8ISPhjVgPPmkNM'),
        ),
    ]
