# Generated by Django 5.0.6 on 2024-07-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_rename_user_permissions_profile_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='profile_pictures/%Y/%m/%d/RqhRPuCgmmZP4Upy'),
        ),
    ]
