# Generated by Django 5.0.6 on 2024-07-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_remove_profile_permissions_and_more'),
        ('user_permissions', '0003_alter_userpermission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='permissions',
            field=models.ManyToManyField(related_name='profiles', to='user_permissions.userpermission'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='profile_pictures/%Y/%m/%d/p0zh2ed5GZPdxMFX'),
        ),
    ]
