# Generated by Django 5.0.6 on 2024-07-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0081_alter_profile_profile_picture'),
        ('user_permissions', '0005_userpermission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='user_permissions', to='user_permissions.userpermission'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='profile_pictures/%Y/%m/%d/GNqdC9j8bPik1ImX'),
        ),
    ]
