# Generated by Django 5.0.6 on 2024-07-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0190_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='img/avatars/0.png', max_length=1000, upload_to='profile_pictures/%Y/%m/%d/Jmo5RnSEcZZUGT8k'),
        ),
    ]
