# Generated by Django 5.0.6 on 2024-07-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0356_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/profile_pictures/default.png', max_length=1000, upload_to='profile_pictures/%Y/%m/%d/o2jEhIe8VQ1iz0Hu'),
        ),
    ]
