# Generated by Django 5.0.6 on 2024-07-16 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0512_alter_profile_profile_picture'),
        ('user_permissions', '0014_userpermission_user_permis_user_id_78612f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/profile_pictures/default.png', max_length=1000, upload_to='profile_pictures/%Y/%m/%d/L69bBvEBpuxD6Bce'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='accounts_pr_user_id_97e401_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['email'], name='accounts_pr_email_08cbb0_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user', 'email'], name='accounts_pr_user_id_d70b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user', 'email', 'is_verified'], name='accounts_pr_user_id_cfeda2_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user', 'email', 'is_verified', 'created_at'], name='accounts_pr_user_id_7cb391_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['first_name', 'last_name'], name='accounts_pr_first_n_61792f_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['first_name', 'last_name', 'created_at'], name='accounts_pr_first_n_1ecd65_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['phone_number'], name='accounts_pr_phone_n_c27a97_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['phone_number', 'created_at'], name='accounts_pr_phone_n_dbfa14_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['address'], name='accounts_pr_address_08d395_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['address', 'created_at'], name='accounts_pr_address_83743e_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['city'], name='accounts_pr_city_79ec1d_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['city', 'created_at'], name='accounts_pr_city_3cef42_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['country'], name='accounts_pr_country_13da80_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['country', 'created_at'], name='accounts_pr_country_de9a70_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['postal_code'], name='accounts_pr_postal__cfa89a_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['postal_code', 'created_at'], name='accounts_pr_postal__9c22a5_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_active'], name='accounts_pr_is_acti_d3fcf1_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_active', 'created_at'], name='accounts_pr_is_acti_5b5fc5_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['created_by_user'], name='accounts_pr_created_5befe7_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['created_by_user', 'created_at'], name='accounts_pr_created_bd8f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='usercreditcard',
            index=models.Index(fields=['user', 'name_on_card', 'card_number', 'created_at'], name='accounts_us_user_id_765ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='usercreditcard',
            index=models.Index(fields=['user', 'name_on_card', 'card_number', 'card_expiration_month', 'card_expiration_year', 'card_cvc', 'created_at'], name='accounts_us_user_id_318068_idx'),
        ),
    ]
