# Generated by Django 5.0.6 on 2024-07-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0513_alter_profile_options_alter_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/profile_pictures/default.png', max_length=1000, upload_to='profile_pictures/%Y/%m/%d/DTDbhgi0TE9F2mC0'),
        ),
    ]
