# Generated by Django 5.0.6 on 2024-07-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0550_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/profile_pictures/default.png', max_length=1000, upload_to='profile_pictures/%Y/%m/%d/RZo3u88e6B201xRM'),
        ),
    ]
