# Generated by Django 5.0.6 on 2024-07-30 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0670_alter_profile_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/profile_pictures/default.png', max_length=1000, upload_to='profile_pictures/%Y/%m/%d/o4tjszItgdynzu3z'),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('bonus_percentage', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('referral_limit', models.IntegerField(default=0)),
                ('datetime_limit', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='accounts_pr_code_d73dcd_idx'), models.Index(fields=['is_active'], name='accounts_pr_is_acti_5db432_idx'), models.Index(fields=['created_at'], name='accounts_pr_created_305448_idx')],
            },
        ),
    ]
