# Generated by Django 5.0.6 on 2024-07-30 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0671_alter_profile_profile_picture_promocode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='bonus_percentage',
            new_name='current_referrals',
        ),
        migrations.RenameField(
            model_name='promocode',
            old_name='referral_limit',
            new_name='max_referral_limit',
        ),
        migrations.AddField(
            model_name='profile',
            name='referral_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_code', to='accounts.promocode'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='bonus_percentage_referee',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='promocode',
            name='bonus_percentage_referrer',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/profile_pictures/default.png', max_length=1000, upload_to='profile_pictures/%Y/%m/%d/Tmfv5gCsKUXjDxNn'),
        ),
    ]
