#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Jupi.tr™
#  File: 0001_initial.py
#  Last Modified: 2024-09-25 17:51:06
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 01:36:45
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@jupi.tr.
#

# Generated by Django 5.1.1 on 2024-09-25 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceFileSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_type', models.CharField(choices=[('linux', 'Linux'), ('macos', 'MacOS')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('host_url', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=22)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('file_directory_tree', models.TextField(blank=True, null=True)),
                ('os_read_limit_tokens', models.IntegerField(default=10000)),
                ('is_read_only', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_source_file_systems', to='assistants.assistant')),
                ('created_by_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_source_file_systems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Source File System',
                'verbose_name_plural': 'Data Source File Systems',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assistant', 'os_type', 'name'], name='datasource__assista_45414e_idx'), models.Index(fields=['assistant', 'os_type', 'created_at'], name='datasource__assista_fddddf_idx'), models.Index(fields=['assistant', 'os_type', 'updated_at'], name='datasource__assista_085e9c_idx'), models.Index(fields=['assistant', 'os_type', 'name', 'created_at'], name='datasource__assista_f995c1_idx'), models.Index(fields=['assistant', 'os_type', 'name', 'updated_at'], name='datasource__assista_903bea_idx')],
            },
        ),
    ]
