# Generated by Django 5.0.6 on 2024-07-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_file_systems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcefilesystem',
            name='os_type',
            field=models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows'), ('macos', 'MacOS')], max_length=50),
        ),
    ]
