# Generated by Django 5.0.6 on 2024-07-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_file_systems', '0002_alter_datasourcefilesystem_os_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcefilesystem',
            name='ssh_connection_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datasourcefilesystem',
            name='port',
            field=models.IntegerField(default=22),
        ),
    ]
