# Generated by Django 5.0.8 on 2024-12-04 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_file_systems', '0002_alter_datasourcefilesystem_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSystemDirectorySchemaChunkVectorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('raw_data_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('vector_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource_file_systems.datasourcefilesystem')),
            ],
            options={
                'verbose_name': 'File System Directory Schema Chunk Vector Data',
                'verbose_name_plural': 'File System Directory Schema Chunk Vector Data',
                'indexes': [models.Index(fields=['file_system'], name='datasource__file_sy_139ab6_idx'), models.Index(fields=['created_at'], name='datasource__created_1a7bf9_idx'), models.Index(fields=['updated_at'], name='datasource__updated_11f6b5_idx')],
            },
        ),
    ]
