# Generated by Django 5.0.8 on 2024-12-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_file_systems', '0003_filesystemdirectoryschemachunkvectordata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcefilesystem',
            name='file_directory_tree',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
