# Generated by Django 5.0.6 on 2024-07-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_file_systems', '0003_datasourcefilesystem_ssh_connection_uri_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasourcefilesystem',
            name='ssh_connection_uri',
        ),
        migrations.AlterField(
            model_name='datasourcefilesystem',
            name='os_type',
            field=models.CharField(choices=[('linux', 'Linux'), ('macos', 'MacOS')], max_length=50),
        ),
    ]
