#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Br6.in™
#  File: 0001_initial.py
#  Last Modified: 2024-10-05 01:39:47
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 14:42:39
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@br6.in.
#
#
#

# Generated by Django 5.0.8 on 2024-10-01 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm_core', '0002_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainstormingIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_title', models.CharField(max_length=1000)),
                ('idea_description', models.TextField()),
                ('depth_level', models.IntegerField(default=1)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Brainstorming Idea',
                'verbose_name_plural': 'Brainstorming Ideas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrainstormingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=1000)),
                ('topic_definition', models.TextField()),
                ('constraints', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('llm_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llm_core.llmcore')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'verbose_name': 'Brainstorming Session',
                'verbose_name_plural': 'Brainstorming Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrainstormingLevelSynthesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth_level', models.IntegerField()),
                ('synthesis_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ideas', models.ManyToManyField(to='brainstorms.brainstormingidea')),
                ('brainstorming_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brainstorms.brainstormingsession')),
            ],
            options={
                'verbose_name': 'Brainstorming Level Synthesis',
                'verbose_name_plural': 'Brainstorming Level Syntheses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='brainstormingidea',
            name='brainstorming_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brainstorms.brainstormingsession'),
        ),
        migrations.CreateModel(
            name='BrainstormingCompleteSynthesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synthesis_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('brainstorming_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brainstorms.brainstormingsession')),
            ],
            options={
                'verbose_name': 'Brainstorming Complete Synthesis',
                'verbose_name_plural': 'Brainstorming Complete Syntheses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='brainstormingsession',
            index=models.Index(fields=['organization'], name='brainstorms_organiz_7aaa36_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingsession',
            index=models.Index(fields=['llm_model'], name='brainstorms_llm_mod_92e493_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingsession',
            index=models.Index(fields=['created_by_user'], name='brainstorms_created_4398b4_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingsession',
            index=models.Index(fields=['session_name'], name='brainstorms_session_98405d_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingsession',
            index=models.Index(fields=['created_at'], name='brainstorms_created_464552_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingsession',
            index=models.Index(fields=['updated_at'], name='brainstorms_updated_334918_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingsession',
            index=models.Index(fields=['organization', 'llm_model'], name='brainstorms_organiz_9377d4_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingsession',
            index=models.Index(fields=['organization', 'session_name'], name='brainstorms_organiz_d390eb_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingsession',
            index=models.Index(fields=['llm_model', 'session_name'], name='brainstorms_llm_mod_0ce76f_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingsession',
            index=models.Index(fields=['organization', 'llm_model', 'created_by_user'], name='brainstorms_organiz_6f87f4_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingsession',
            index=models.Index(fields=['organization', 'llm_model', 'created_at'], name='brainstorms_organiz_85e54e_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingsession',
            index=models.Index(fields=['organization', 'llm_model', 'updated_at'], name='brainstorms_organiz_228714_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingsession',
            index=models.Index(fields=['organization', 'llm_model', 'session_name'], name='brainstorms_organiz_ea4f25_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingsession',
            index=models.Index(fields=['organization', 'llm_model', 'created_by_user', 'session_name'], name='brainstorms_organiz_a8e035_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingsession',
            index=models.Index(fields=['organization', 'llm_model', 'created_by_user', 'created_at'], name='brainstorms_organiz_402a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingsession',
            index=models.Index(fields=['organization', 'llm_model', 'created_by_user', 'updated_at'], name='brainstorms_organiz_308a38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='brainstormingsession',
            unique_together={('organization', 'llm_model', 'session_name')},
        ),
        migrations.AddIndex(
            model_name='brainstorminglevelsynthesis',
            index=models.Index(fields=['brainstorming_session'], name='brainstorms_brainst_fac987_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstorminglevelsynthesis',
            index=models.Index(fields=['created_by_user'], name='brainstorms_created_42f582_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstorminglevelsynthesis',
            index=models.Index(fields=['depth_level'], name='brainstorms_depth_l_8b4630_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstorminglevelsynthesis',
            index=models.Index(fields=['created_at'], name='brainstorms_created_03a85b_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstorminglevelsynthesis',
            index=models.Index(fields=['updated_at'], name='brainstorms_updated_ff86c5_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstorminglevelsynthesis',
            index=models.Index(fields=['brainstorming_session', 'depth_level'], name='brainstorms_brainst_ddd3e1_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstorminglevelsynthesis',
            index=models.Index(fields=['brainstorming_session', 'created_by_user'], name='brainstorms_brainst_28e3d7_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstorminglevelsynthesis',
            index=models.Index(fields=['brainstorming_session', 'created_at'], name='brainstorms_brainst_e82b55_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstorminglevelsynthesis',
            index=models.Index(fields=['brainstorming_session', 'updated_at'], name='brainstorms_brainst_1c221b_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstorminglevelsynthesis',
            index=models.Index(fields=['brainstorming_session', 'depth_level', 'created_by_user'], name='brainstorms_brainst_0efb86_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstorminglevelsynthesis',
            index=models.Index(fields=['brainstorming_session', 'depth_level', 'created_at'], name='brainstorms_brainst_b4f832_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstorminglevelsynthesis',
            index=models.Index(fields=['brainstorming_session', 'depth_level', 'updated_at'], name='brainstorms_brainst_3fc575_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='brainstorminglevelsynthesis',
            unique_together={('brainstorming_session', 'depth_level')},
        ),
        migrations.AddIndex(
            model_name='brainstormingidea',
            index=models.Index(fields=['brainstorming_session'], name='brainstorms_brainst_c99b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingidea',
            index=models.Index(fields=['created_by_user'], name='brainstorms_created_593759_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingidea',
            index=models.Index(fields=['idea_title'], name='brainstorms_idea_ti_360b8d_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingidea',
            index=models.Index(fields=['created_at'], name='brainstorms_created_8e8c33_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingidea',
            index=models.Index(fields=['updated_at'], name='brainstorms_updated_902d31_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingidea',
            index=models.Index(fields=['brainstorming_session', 'idea_title'], name='brainstorms_brainst_c8abe4_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingidea',
            index=models.Index(fields=['brainstorming_session', 'created_by_user'], name='brainstorms_brainst_b44c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingidea',
            index=models.Index(fields=['brainstorming_session', 'created_at'], name='brainstorms_brainst_7f6121_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingidea',
            index=models.Index(fields=['brainstorming_session', 'updated_at'], name='brainstorms_brainst_5f0670_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingidea',
            index=models.Index(fields=['brainstorming_session', 'idea_title', 'created_by_user'], name='brainstorms_brainst_ef947a_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingidea',
            index=models.Index(fields=['brainstorming_session', 'idea_title', 'created_at'], name='brainstorms_brainst_32faa5_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingidea',
            index=models.Index(fields=['brainstorming_session', 'idea_title', 'updated_at'], name='brainstorms_brainst_1e9ed3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='brainstormingidea',
            unique_together={('brainstorming_session', 'idea_title', 'depth_level')},
        ),
        migrations.AddIndex(
            model_name='brainstormingcompletesynthesis',
            index=models.Index(fields=['brainstorming_session'], name='brainstorms_brainst_5a8a40_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingcompletesynthesis',
            index=models.Index(fields=['created_by_user'], name='brainstorms_created_966e41_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingcompletesynthesis',
            index=models.Index(fields=['created_at'], name='brainstorms_created_740ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingcompletesynthesis',
            index=models.Index(fields=['updated_at'], name='brainstorms_updated_7c0ab9_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingcompletesynthesis',
            index=models.Index(fields=['brainstorming_session', 'created_by_user'], name='brainstorms_brainst_b3841c_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingcompletesynthesis',
            index=models.Index(fields=['brainstorming_session', 'created_at'], name='brainstorms_brainst_c71513_idx'),
        ),
        migrations.AddIndex(
            model_name='brainstormingcompletesynthesis',
            index=models.Index(fields=['brainstorming_session', 'updated_at'], name='brainstorms_brainst_5cd49c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='brainstormingcompletesynthesis',
            unique_together={('brainstorming_session',)},
        ),
    ]
