# Generated by Django 5.0.8 on 2024-10-01 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainstorms', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brainstormingidea',
            unique_together={('brainstorming_session', 'idea_description', 'depth_level')},
        ),
    ]
