#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Jupi.tr™
#  File: 0002_alter_brainstormingidea_unique_together.py
#  Last Modified: 2024-10-01 14:26:47
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 01:36:37
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@jupi.tr.
#

# Generated by Django 5.0.8 on 2024-10-01 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainstorms', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brainstormingidea',
            unique_together={('brainstorming_session', 'idea_description', 'depth_level')},
        ),
    ]
