# Generated by Django 5.0.8 on 2024-12-01 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainstorms', '0002_alter_brainstormingidea_unique_together'),
        ('organization', '0005_alter_organization_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brainstormingsession',
            unique_together={('organization', 'session_name')},
        ),
    ]
