# Generated by Django 5.0.8 on 2024-12-01 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainstorms', '0003_alter_brainstormingsession_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brainstormingcompletesynthesis',
            unique_together=set(),
        ),
    ]
