# Generated by Django 5.0.8 on 2024-12-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcewebsitestorageitem',
            name='n_chunks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasourcewebsitestorageitem',
            name='status_completion',
            field=models.IntegerField(default=0),
        ),
    ]
