# Generated by Django 5.0.8 on 2024-12-07 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_website', '0002_datasourcewebsitestorageitem_n_chunks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasourcewebsitestorageitem',
            old_name='status_completion',
            new_name='status_completion_percentage',
        ),
    ]
