# Generated by Django 5.0.8 on 2024-12-07 23:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_website', '0003_rename_status_completion_datasourcewebsitestorageitem_status_completion_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='datasourcewebsitestorageitem',
            name='datasource__indexin_6767ba_idx',
        ),
        migrations.RemoveIndex(
            model_name='datasourcewebsitestorageitem',
            name='datasource__website_eb754c_idx',
        ),
        migrations.RenameField(
            model_name='datasourcewebsitestorageitem',
            old_name='indexing_methodology',
            new_name='crawling_methodology',
        ),
        migrations.AddIndex(
            model_name='datasourcewebsitestorageitem',
            index=models.Index(fields=['crawling_methodology'], name='datasource__crawlin_b0760d_idx'),
        ),
        migrations.AddIndex(
            model_name='datasourcewebsitestorageitem',
            index=models.Index(fields=['website_url', 'crawling_methodology'], name='datasource__website_80693f_idx'),
        ),
    ]
