# Generated by Django 5.0.8 on 2024-12-09 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasource_website', '0004_remove_datasourcewebsitestorageitem_datasource__indexin_6767ba_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasourcewebsitestorageitem',
            old_name='status_completion_percentage',
            new_name='n_chunks_indexed_status',
        ),
    ]
