# Generated by Django 5.0.8 on 2024-12-01 22:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forumlike',
            unique_together={('user', 'comment')},
        ),
    ]
