# Generated by Django 5.0.8 on 2024-12-01 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_forum', '0002_alter_forumlike_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forumthread',
            unique_together={('category', 'title')},
        ),
    ]
