# Generated by Django 5.0.6 on 2024-08-12 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_forum', '0002_forumlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='verified_comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_post', to='community_forum.forumcomment'),
        ),
    ]
