# Generated by Django 5.1 on 2024-08-15 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportAssistantAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('request_limit_per_hour', models.IntegerField(default=1000)),
                ('is_online', models.BooleanField(default=True)),
                ('custom_api_key', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('endpoint', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_assistants_created_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Export Assistant API',
                'verbose_name_plural': 'Export Assistant APIs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('export_assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='export_assistants.exportassistantapi')),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='exportassistantapi',
            index=models.Index(fields=['assistant'], name='export_assi_assista_c017f5_idx'),
        ),
        migrations.AddIndex(
            model_name='exportassistantapi',
            index=models.Index(fields=['created_by_user'], name='export_assi_created_c3d1a1_idx'),
        ),
        migrations.AddIndex(
            model_name='exportassistantapi',
            index=models.Index(fields=['created_at'], name='export_assi_created_fc2c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='exportassistantapi',
            index=models.Index(fields=['updated_at'], name='export_assi_updated_4473f3_idx'),
        ),
        migrations.AddIndex(
            model_name='exportassistantapi',
            index=models.Index(fields=['assistant', 'created_at'], name='export_assi_assista_7a9d81_idx'),
        ),
        migrations.AddIndex(
            model_name='exportassistantapi',
            index=models.Index(fields=['assistant', 'updated_at'], name='export_assi_assista_3f2c49_idx'),
        ),
        migrations.AddIndex(
            model_name='exportassistantapi',
            index=models.Index(fields=['assistant', 'created_by_user'], name='export_assi_assista_b1860c_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['export_assistant'], name='export_assi_export__127ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['timestamp'], name='export_assi_timesta_8b9c92_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['export_assistant', 'timestamp'], name='export_assi_export__da0e87_idx'),
        ),
    ]
