# Generated by Django 5.0.6 on 2024-07-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_assistants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportassistantapi',
            options={'ordering': ['-created_at'], 'verbose_name': 'Export Assistant API', 'verbose_name_plural': 'Export Assistant APIs'},
        ),
        migrations.AlterField(
            model_name='exportassistantapi',
            name='custom_api_key',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
