# Generated by Django 5.1.1 on 2024-09-25 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('export_assistants', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportassistantapi',
            name='organization',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exported_assistants', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='export_assistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='export_assistants.exportassistantapi'),
        ),
        migrations.AddIndex(
            model_name='exportassistantapi',
            index=models.Index(fields=['assistant'], name='export_assi_assista_c017f5_idx'),
        ),
        migrations.AddIndex(
            model_name='exportassistantapi',
            index=models.Index(fields=['created_by_user'], name='export_assi_created_c3d1a1_idx'),
        ),
        migrations.AddIndex(
            model_name='exportassistantapi',
            index=models.Index(fields=['created_at'], name='export_assi_created_fc2c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='exportassistantapi',
            index=models.Index(fields=['updated_at'], name='export_assi_updated_4473f3_idx'),
        ),
        migrations.AddIndex(
            model_name='exportassistantapi',
            index=models.Index(fields=['assistant', 'created_at'], name='export_assi_assista_7a9d81_idx'),
        ),
        migrations.AddIndex(
            model_name='exportassistantapi',
            index=models.Index(fields=['assistant', 'updated_at'], name='export_assi_assista_3f2c49_idx'),
        ),
        migrations.AddIndex(
            model_name='exportassistantapi',
            index=models.Index(fields=['assistant', 'created_by_user'], name='export_assi_assista_b1860c_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['export_assistant'], name='export_assi_export__127ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['timestamp'], name='export_assi_timesta_8b9c92_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['export_assistant', 'timestamp'], name='export_assi_export__da0e87_idx'),
        ),
    ]
