# Generated by Django 5.0.8 on 2024-12-01 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0013_alter_assistantoldchatmessagesvectordata_unique_together'),
        ('export_assistants', '0002_initial'),
        ('organization', '0005_alter_organization_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exportassistantapi',
            unique_together={('organization', 'assistant', 'is_public')},
        ),
    ]
