# Generated by Django 5.0.6 on 2024-07-08 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_assistants', '0002_alter_exportassistantapi_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportassistantapi',
            name='endpoint',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('export_assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='export_assistants.exportassistantapi')),
            ],
        ),
    ]
