# Generated by Django 5.0.6 on 2024-07-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_assistants', '0003_exportassistantapi_endpoint_requestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportassistantapi',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
    ]
