# Generated by Django 5.0.6 on 2024-07-16 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0406_alter_assistant_assistant_image'),
        ('export_assistants', '0004_exportassistantapi_is_online'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Request Log', 'verbose_name_plural': 'Request Logs'},
        ),
        migrations.AddIndex(
            model_name='exportassistantapi',
            index=models.Index(fields=['assistant'], name='export_assi_assista_c017f5_idx'),
        ),
        migrations.AddIndex(
            model_name='exportassistantapi',
            index=models.Index(fields=['created_by_user'], name='export_assi_created_c3d1a1_idx'),
        ),
        migrations.AddIndex(
            model_name='exportassistantapi',
            index=models.Index(fields=['created_at'], name='export_assi_created_fc2c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='exportassistantapi',
            index=models.Index(fields=['updated_at'], name='export_assi_updated_4473f3_idx'),
        ),
        migrations.AddIndex(
            model_name='exportassistantapi',
            index=models.Index(fields=['assistant', 'created_at'], name='export_assi_assista_7a9d81_idx'),
        ),
        migrations.AddIndex(
            model_name='exportassistantapi',
            index=models.Index(fields=['assistant', 'updated_at'], name='export_assi_assista_3f2c49_idx'),
        ),
        migrations.AddIndex(
            model_name='exportassistantapi',
            index=models.Index(fields=['assistant', 'created_by_user'], name='export_assi_assista_b1860c_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['export_assistant'], name='export_assi_export__127ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['timestamp'], name='export_assi_timesta_8b9c92_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['export_assistant', 'timestamp'], name='export_assi_export__da0e87_idx'),
        ),
    ]
