

MOCK_STREAM_STRATEGIST = [
    # For the STRATEGIST legion node
    "🟢Strategist: I'm currently idle, awaiting new orders or scheduled/triggered operations.",
    "🔵Strategist: Chatting with an assistant to discuss data sources.",
    "🟢Strategist: I am triggered by API request, fetching data from the financial data source.",
    "🟢Strategist: Working on quantitative data, and gathering insights for potential strategies.",
    "🔵Strategist: Chatting with an assistant to decide on which data sources to use.",
    "🟢Strategist: Thinking and generating a potential strategy.",
    "🟢Strategist: Browsing online for strategy ideas.",
    "🔵Strategist: Chatting with an assistant to discuss about what could be the next strategy.",
    "🟢Strategist: Reviewing the performance of existing strategies from the online data sources.",
    "🔵Strategist: Chatting with an assistant to discuss the latest financial news.",
    "🟢Strategist: Researching latest financial news and trends.",
    "🟢Strategist: Reading the latest financial reports and publications.",
    "🟢Strategist: Checking internal database resources for potential strategies.",
    "🟡Strategist: Chatting with orchestrators to discuss the updates.",
    "🔴Strategist: Detected a minor issue, currently resolving it.",
    "🔴Strategist: Diagnostic checks on the system for any anomalies.",
    "🟢Strategist: Coordinating assistant workers on tasks.",
    "🔵Strategist: Engaging in a training session for strategies.",
    "🟢Strategist: Analyzing current activities to adjust our approach.",
    "🟡Strategist: Awaiting confirmation on the latest strategy implementation plans.",
    "🔴Strategist: Addressing discrepancies in data interpretation.",
    "🟢Strategist: Integrating algorithm updates into the strategy.",
    "🟢Strategist: Conducting historical trading strategy review for insights.",
    "🔵Strategist: Consulting worker assistants on financial modeling techniques.",
    "🟡Strategist: Monitoring market activities for our strategies.",
    "🟢Strategist: Updating strategy parameters based on market conditions.",
    "🔴Strategist: Resolving conflicts in strategic direction of the portfolio.",
    "🟢Strategist: Reviewing industry white papers to stay ahead in the market.",
    "🔵Strategist: Searching out potential economic policy changes.",
    "🟢Strategist: Scanning through patent databases for relevant fin-tech updates.",
]

MOCK_STREAM_BACKTESTING = [
    # For the BACKTESTING legion node
    "🟢Backtesting: I am idle, waiting for new models to test.",
    "🔵Backtesting: Configuring parameters for a next backtest.",
    "🟢Backtesting: Running backtests on a new trading algorithm.",
    "🟢Backtesting: Analyzing results from model tests.",
    "🔵Backtesting: Updating risk assessment parameters based on backtests.",
    "🟢Backtesting: Validating model accuracy based on historical data.",
    "🟢Backtesting: Refining models to improve precision.",
    "🟢Backtesting: Checking for overfitting in the latest strategy models.",
    "🔵Backtesting: Gathering historical data for my backtest.",
    "🟢Backtesting: Preparing analysis report on backtesting results.",
    "🟢Backtesting: Testing scenarios to assess robustness of our model.",
    "🟢Backtesting: Applying a Monte Carlo simulation.",
    "🔴Backtesting: Encountered errors in the simulation software, addressing now.",
    "🔴Backtesting: Debugging issues found in the latest backtest scripts.",
    "🟢Backtesting: Re-running backtests after adjusting for market anomalies.",
    "🟢Backtesting: Comparing performance of the models against benchmarks.",
    "🟢Backtesting: Enhancing data quality.",
    "🟢Backtesting: Scaling up computing resources.",
    "🔴Backtesting: Resolving data integrity issues in historical financial records.",
    "🟢Backtesting: Reviewing alternative data sources.",
    "🟢Backtesting: Conducting stress tests under different economic scenarios.",
    "🟡Backtesting: Finalizing enhancements to backtesting platform.",
    "🔵Backtesting: Training orchestration members on using advanced backtesting tools.",
    "🟢Backtesting: Performing regression tests on newly updated trading models.",
    "🔵Backtesting: Revising backtest strategies to incorporate real-time market feeds.",
]

MOCK_STREAM_TRADER = [
    # For the TRADER legion node
    "🟢Trader: I am idle, waiting for market opening.",
    "🔵Trader: Analyzing pre-market data and adjusting trading strategies.",
    "🟢Trader: Executing trades based on automated algorithms.",
    "🟢Trader: Monitoring live market feeds.",
    "🟢Trader: Reviewing the effectiveness of recently implemented trades.",
    "🟢Trader: Optimizing trading algorithms.",
    "🔵Trader: Consulting with risk management orchestration node.",
    "🔵Trader: Adjusting positions in response to unexpected market news.",
    "🟢Trader: Studying market trends.",
    "🟡Trader: Taking a pause.",
    "🔴Trader: Investigating discrepancies in trade execution reports.",
    "🔴Trader: Troubleshooting issues with trading platform.",
    "🟢Trader: Comparing trading performance against market benchmarks.",
    "🔵Trader: Strategizing with the worker assistants on leveraging economic event impacts.",
    "🟢Trader: Backtesting new trading strategies with historical data.",
    "🟡Trader: Updating trading journal with logs of the recent sessions.",
    "🔴Trader: Addressing a critical error in risk management algorithms.",
    "🟡Trader: Reviewing and adjusting stop-loss orders.",
    "🔵Trader: Analyzing competitor trading patterns for strategic insights.",
    "🟢Trader: Searching through alternative datasets to gain an edge in trading.",
    "🔵Trader: Briefing the orchestration nodes on potential policy changes affecting markets.",
]

MOCK_STREAM_RISK_MANAGER = [
    # For the RISK MANAGER legion node
    "🟢Risk Manager: I'm currently idle.",
    "🟢Risk Manager: Monitoring overall risk exposure across portfolios.",
    "🔵Risk Manager: Analyzing market fluctuations and their impact on risk levels.",
    "🟢Risk Manager: Reviewing compliance with internal and external risk regulations.",
    "🟢Risk Manager: Updating risk models to incorporate latest market data.",
    "🔵Risk Manager: Conducting a stress test on active positions.",
    "🟢Risk Manager: Preparing risk assessment report.",
    "🟢Risk Manager: Consulting with trader orchestrator to align risk thresholds with market strategies.",
    "🔵Risk Manager: Evaluating the efficacy of risk mitigation tools.",
    "🟢Risk Manager: Developing new risk metrics for emerging market segments.",
    "🟢Risk Manager: Conducting scenario analysis to predict potential future losses.",
    "🟢Risk Manager: Revising risk appetite in light of current economic indicators.",
    "🟡Risk Manager: Pausing new trades to evaluate current situation.",
    "🔴Risk Manager: Resolving discrepancies found in risk reporting data.",
    "🟢Risk Manager: Training worker assistants on advanced risk management techniques.",
    "🔵Risk Manager: Assessing counterparty risks for new contracts.",
    "🟢Risk Manager: Monitoring real-time alerts for limit breaches.",
    "🟡Risk Manager: Verifying model predictions with actual outcomes for calibration.",
    "🟢Risk Manager: Updating hedge strategies.",
    "🟢Risk Manager: Analyzing the current impact of new technology adoption on operational risk.",
    "🟢Risk Manager: Active surveillance on liquidity risk.",
    "🔵Risk Manager: Briefing orchestration nodes on strategic risk considerations for current investments.",
]

MOCK_STREAM_PORTFOLIO_MANAGER = [
    # For the PORTFOLIO MANAGER legion node
    "🟢Portfolio Manager: Reviewing daily portfolio performance and making adjustments as necessary.",
    "🔵Portfolio Manager: Conducting asset allocation review based on current market conditions.",
    "🟢Portfolio Manager: Identifying new investment opportunities.",
    "🟢Portfolio Manager: Analyzing recent portfolio risk metrics; re-balancing to maintain target allocations.",
    "🟢Portfolio Manager: Monitoring geopolitical events.",
    "🟢Portfolio Manager: Checking for currency exposure and considering hedge options.",
    "🟡Portfolio Manager: Pausing new investments for assessment.",
    "🟢Portfolio Manager: Reviewing historical performance data to refine investment models.",
    "🟢Portfolio Manager: Researching for innovative fintech solutions to enhance portfolio management.",
    "🔵Portfolio Manager: Discussing with risk manager node about optimizing risk-return profiles.",
    "🟢Portfolio Manager: Organizing training for the orchestration team on new financial analysis tools.",
    "🟡Portfolio Manager: Preparing documentation for upcoming audits.",
    "🔵Portfolio Manager: Researching online discussions on global economic trends and their impact on investments.",
]

MOCK_TRADING_ACTIVITY = [
    "🟢LONG order placed for ",
    "🔴SHORT order placed for ",
    "🔵CLOSE order placed for ",
    "🟡HOLD / No action attempted. Active surveillance is ongoing.",
]

MOCK_TRADING_SYMBOL = [
    "ETH. ",
    "BTC. ",
    "SOL. ",
    "BNB. ",
    "XRP. ",
]

MOCK_LEVERAGE = [
    "Transaction leverage is set for 'X1'.",
    "Transaction leverage is set for 'X2'.",
    "Transaction leverage is set for 'X3.",
    "Transaction leverage is set for 'X4.",
    "Transaction leverage is set for 'X5.",
    "Transaction leverage is set for 'X6.",
    "Transaction leverage is set for 'X8.",
    "Transaction leverage is set for 'X10.",
    "Transaction leverage is set for 'X20.",
    "Transaction leverage is set for 'X50.",
]
