# Generated by Django 5.1 on 2024-08-15 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggeredJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('step_guide', models.JSONField(default=list)),
                ('trigger_source', models.CharField(blank=True, max_length=2000, null=True)),
                ('event_type', models.CharField(blank=True, max_length=4000, null=True)),
                ('endpoint_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('current_run_count', models.PositiveIntegerField(default=0)),
                ('maximum_runs', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_jobs', to=settings.AUTH_USER_MODEL)),
                ('trigger_assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_jobs', to='assistants.assistant')),
            ],
            options={
                'verbose_name': 'Triggered Job',
                'verbose_name_plural': 'Triggered Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TriggeredJobInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('building', 'Building'), ('initializing_assistant', 'Initializing Assistant'), ('generating', 'Generating'), ('saving_logs', 'Saving Logs'), ('cleaning_up', 'Cleaning Up'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=255)),
                ('webhook_payload', models.JSONField(default=dict)),
                ('logs', models.JSONField(default=list)),
                ('execution_index', models.IntegerField(default=0, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(auto_now=True)),
                ('triggered_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='mm_triggered_jobs.triggeredjob')),
            ],
            options={
                'verbose_name': 'Triggered Job Instance',
                'verbose_name_plural': 'Triggered Job Instances',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='triggeredjob',
            name='triggered_job_instances',
            field=models.ManyToManyField(blank=True, related_name='scheduled_jobs', to='mm_triggered_jobs.triggeredjobinstance'),
        ),
        migrations.AddIndex(
            model_name='triggeredjobinstance',
            index=models.Index(fields=['triggered_job', 'status', 'started_at'], name='mm_triggere_trigger_1ca3c4_idx'),
        ),
        migrations.AddIndex(
            model_name='triggeredjobinstance',
            index=models.Index(fields=['triggered_job', 'status', 'started_at', 'ended_at'], name='mm_triggere_trigger_3f2e30_idx'),
        ),
        migrations.AddIndex(
            model_name='triggeredjobinstance',
            index=models.Index(fields=['triggered_job', 'status', 'started_at', 'ended_at', 'id'], name='mm_triggere_trigger_303d71_idx'),
        ),
        migrations.AddIndex(
            model_name='triggeredjobinstance',
            index=models.Index(fields=['triggered_job', 'status', 'started_at', 'ended_at', 'id', 'status'], name='mm_triggere_trigger_5179d8_idx'),
        ),
        migrations.AddIndex(
            model_name='triggeredjobinstance',
            index=models.Index(fields=['triggered_job', 'status', 'started_at', 'ended_at', 'id', 'status', 'logs'], name='mm_triggere_trigger_d29250_idx'),
        ),
        migrations.AddIndex(
            model_name='triggeredjobinstance',
            index=models.Index(fields=['triggered_job', 'status', 'started_at', 'ended_at', 'id', 'status', 'logs', 'webhook_payload'], name='mm_triggere_trigger_9329c6_idx'),
        ),
        migrations.AddIndex(
            model_name='triggeredjob',
            index=models.Index(fields=['name', 'trigger_assistant', 'created_by_user', 'created_at'], name='mm_triggere_name_7bd5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='triggeredjob',
            index=models.Index(fields=['created_at'], name='mm_triggere_created_f0b0ad_idx'),
        ),
        migrations.AddIndex(
            model_name='triggeredjob',
            index=models.Index(fields=['trigger_assistant'], name='mm_triggere_trigger_e3078f_idx'),
        ),
        migrations.AddIndex(
            model_name='triggeredjob',
            index=models.Index(fields=['created_by_user'], name='mm_triggere_created_d49752_idx'),
        ),
        migrations.AddIndex(
            model_name='triggeredjob',
            index=models.Index(fields=['trigger_assistant', 'created_by_user'], name='mm_triggere_trigger_5a5454_idx'),
        ),
        migrations.AddIndex(
            model_name='triggeredjob',
            index=models.Index(fields=['trigger_assistant', 'created_by_user', 'created_at'], name='mm_triggere_trigger_cdf898_idx'),
        ),
        migrations.AddIndex(
            model_name='triggeredjob',
            index=models.Index(fields=['trigger_assistant', 'created_by_user', 'created_at', 'name'], name='mm_triggere_trigger_1f1e90_idx'),
        ),
        migrations.AddIndex(
            model_name='triggeredjob',
            index=models.Index(fields=['trigger_assistant', 'created_by_user', 'created_at', 'name', 'current_run_count'], name='mm_triggere_trigger_6dac79_idx'),
        ),
    ]
