# Generated by Django 5.0.8 on 2024-11-14 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_triggered_jobs', '0001_initial'),
        ('orchestrations', '0002_orchestrationreactantassistantconnection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrchestrationTriggeredJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('step_guide', models.JSONField(default=list)),
                ('trigger_source', models.CharField(blank=True, max_length=2000, null=True)),
                ('event_type', models.CharField(blank=True, max_length=4000, null=True)),
                ('endpoint_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('current_run_count', models.PositiveIntegerField(default=0)),
                ('maximum_runs', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orchestration_triggered_jobs', to=settings.AUTH_USER_MODEL)),
                ('trigger_maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_jobs', to='orchestrations.maestro')),
            ],
            options={
                'verbose_name': 'Orchestration Triggered Job',
                'verbose_name_plural': 'Orchestration Triggered Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrchestrationTriggeredJobInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('building', 'Building'), ('initializing_assistant', 'Initializing Assistant'), ('generating', 'Generating'), ('saving_logs', 'Saving Logs'), ('cleaning_up', 'Cleaning Up'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=255)),
                ('webhook_payload', models.JSONField(default=dict)),
                ('logs', models.JSONField(default=list)),
                ('execution_index', models.IntegerField(default=0, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(auto_now=True)),
                ('triggered_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_job_instances', to='mm_triggered_jobs.orchestrationtriggeredjob')),
            ],
            options={
                'verbose_name': 'Orchestration Triggered Job Instance',
                'verbose_name_plural': 'Orchestration Triggered Job Instances',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='orchestrationtriggeredjob',
            index=models.Index(fields=['name', 'trigger_maestro', 'created_by_user', 'created_at'], name='mm_triggere_name_9dc315_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationtriggeredjob',
            index=models.Index(fields=['created_at'], name='mm_triggere_created_135545_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationtriggeredjob',
            index=models.Index(fields=['trigger_maestro'], name='mm_triggere_trigger_953264_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationtriggeredjob',
            index=models.Index(fields=['created_by_user'], name='mm_triggere_created_d7553b_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationtriggeredjob',
            index=models.Index(fields=['trigger_maestro', 'created_by_user'], name='mm_triggere_trigger_bd31a4_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationtriggeredjob',
            index=models.Index(fields=['trigger_maestro', 'created_by_user', 'created_at'], name='mm_triggere_trigger_87b9ba_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationtriggeredjob',
            index=models.Index(fields=['trigger_maestro', 'created_by_user', 'created_at', 'name'], name='mm_triggere_trigger_301aca_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationtriggeredjob',
            index=models.Index(fields=['trigger_maestro', 'created_by_user', 'created_at', 'name', 'current_run_count'], name='mm_triggere_trigger_1eec4c_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationtriggeredjobinstance',
            index=models.Index(fields=['triggered_job', 'status', 'started_at'], name='mm_triggere_trigger_b36553_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationtriggeredjobinstance',
            index=models.Index(fields=['triggered_job', 'status', 'started_at', 'ended_at'], name='mm_triggere_trigger_9ef10f_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationtriggeredjobinstance',
            index=models.Index(fields=['triggered_job', 'status', 'started_at', 'ended_at', 'id'], name='mm_triggere_trigger_1f36fd_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationtriggeredjobinstance',
            index=models.Index(fields=['triggered_job', 'status', 'started_at', 'ended_at', 'id', 'status'], name='mm_triggere_trigger_219bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationtriggeredjobinstance',
            index=models.Index(fields=['triggered_job', 'status', 'started_at', 'ended_at', 'id', 'status', 'logs'], name='mm_triggere_trigger_ced12c_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationtriggeredjobinstance',
            index=models.Index(fields=['triggered_job', 'status', 'started_at', 'ended_at', 'id', 'status', 'logs', 'webhook_payload'], name='mm_triggere_trigger_4cb2f0_idx'),
        ),
    ]
