# Generated by Django 5.0.6 on 2024-07-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_triggered_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggeredjob',
            name='event_type',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
