# Generated by Django 5.0.8 on 2024-12-01 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0013_alter_assistantoldchatmessagesvectordata_unique_together'),
        ('mm_triggered_jobs', '0002_orchestrationtriggeredjob_and_more'),
        ('orchestrations', '0002_orchestrationreactantassistantconnection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orchestrationtriggeredjob',
            unique_together={('trigger_maestro', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='triggeredjob',
            unique_together={('trigger_assistant', 'name')},
        ),
    ]
