# Generated by Django 5.0.6 on 2024-07-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_triggered_jobs', '0002_triggeredjob_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triggeredjob',
            name='triggered_job_instances',
            field=models.ManyToManyField(blank=True, null=True, related_name='scheduled_jobs', to='mm_triggered_jobs.triggeredjobinstance'),
        ),
    ]
