# Generated by Django 5.0.8 on 2024-12-07 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leanmod', '0008_alter_leanassistant_unique_together'),
        ('mm_triggered_jobs', '0003_alter_orchestrationtriggeredjob_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeanModTriggeredJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('step_guide', models.JSONField(default=list)),
                ('trigger_source', models.CharField(blank=True, max_length=2000, null=True)),
                ('event_type', models.CharField(blank=True, max_length=4000, null=True)),
                ('endpoint_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('current_run_count', models.PositiveIntegerField(default=0)),
                ('maximum_runs', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leanmod_triggered_jobs', to=settings.AUTH_USER_MODEL)),
                ('trigger_leanmod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_jobs', to='leanmod.leanassistant')),
            ],
            options={
                'verbose_name': 'LeanMod Triggered Job',
                'verbose_name_plural': 'LeanMod Triggered Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeanModTriggeredJobInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('building', 'Building'), ('initializing_assistant', 'Initializing Assistant'), ('generating', 'Generating'), ('saving_logs', 'Saving Logs'), ('cleaning_up', 'Cleaning Up'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=255)),
                ('webhook_payload', models.JSONField(default=dict)),
                ('logs', models.JSONField(default=list)),
                ('execution_index', models.IntegerField(default=0, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(auto_now=True)),
                ('triggered_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_job_instances', to='mm_triggered_jobs.leanmodtriggeredjob')),
            ],
            options={
                'verbose_name': 'LeanMod Triggered Job Instance',
                'verbose_name_plural': 'LeanMod Triggered Job Instances',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='leanmodtriggeredjob',
            index=models.Index(fields=['name', 'trigger_leanmod', 'created_by_user', 'created_at'], name='mm_triggere_name_c5b8eb_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodtriggeredjob',
            index=models.Index(fields=['created_at'], name='mm_triggere_created_fe9385_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodtriggeredjob',
            index=models.Index(fields=['trigger_leanmod'], name='mm_triggere_trigger_4b93d6_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodtriggeredjob',
            index=models.Index(fields=['created_by_user'], name='mm_triggere_created_1637d2_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodtriggeredjob',
            index=models.Index(fields=['trigger_leanmod', 'created_by_user'], name='mm_triggere_trigger_9899f3_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodtriggeredjob',
            index=models.Index(fields=['trigger_leanmod', 'created_by_user', 'created_at'], name='mm_triggere_trigger_ecd0d6_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodtriggeredjob',
            index=models.Index(fields=['trigger_leanmod', 'created_by_user', 'created_at', 'name'], name='mm_triggere_trigger_114e83_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodtriggeredjob',
            index=models.Index(fields=['trigger_leanmod', 'created_by_user', 'created_at', 'name', 'current_run_count'], name='mm_triggere_trigger_d503d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leanmodtriggeredjob',
            unique_together={('trigger_leanmod', 'name')},
        ),
        migrations.AddIndex(
            model_name='leanmodtriggeredjobinstance',
            index=models.Index(fields=['triggered_job', 'status', 'started_at'], name='mm_triggere_trigger_d7c0be_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodtriggeredjobinstance',
            index=models.Index(fields=['triggered_job', 'status', 'started_at', 'ended_at'], name='mm_triggere_trigger_36e413_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodtriggeredjobinstance',
            index=models.Index(fields=['triggered_job', 'status', 'started_at', 'ended_at', 'id'], name='mm_triggere_trigger_71d456_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodtriggeredjobinstance',
            index=models.Index(fields=['triggered_job', 'status', 'started_at', 'ended_at', 'id', 'status'], name='mm_triggere_trigger_49955c_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodtriggeredjobinstance',
            index=models.Index(fields=['triggered_job', 'status', 'started_at', 'ended_at', 'id', 'status', 'logs'], name='mm_triggere_trigger_92e735_idx'),
        ),
        migrations.AddIndex(
            model_name='leanmodtriggeredjobinstance',
            index=models.Index(fields=['triggered_job', 'status', 'started_at', 'ended_at', 'id', 'status', 'logs', 'webhook_payload'], name='mm_triggere_trigger_2e65b9_idx'),
        ),
    ]
