# Generated by Django 5.0.8 on 2024-09-05 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0009_alter_organization_organization_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NERIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('language', models.CharField(choices=[('en', 'English')], default='en', max_length=2)),
                ('encrypt_persons', models.BooleanField(default=False)),
                ('encrypt_orgs', models.BooleanField(default=False)),
                ('encrypt_nationality_religion_political', models.BooleanField(default=False)),
                ('encrypt_facilities', models.BooleanField(default=False)),
                ('encrypt_countries_cities_states', models.BooleanField(default=False)),
                ('encrypt_locations', models.BooleanField(default=False)),
                ('encrypt_products', models.BooleanField(default=False)),
                ('encrypt_events', models.BooleanField(default=False)),
                ('encrypt_artworks', models.BooleanField(default=False)),
                ('encrypt_laws', models.BooleanField(default=False)),
                ('encrypt_languages', models.BooleanField(default=False)),
                ('encrypt_dates', models.BooleanField(default=False)),
                ('encrypt_times', models.BooleanField(default=False)),
                ('encrypt_percentages', models.BooleanField(default=False)),
                ('encrypt_money', models.BooleanField(default=False)),
                ('encrypt_quantities', models.BooleanField(default=False)),
                ('encrypt_ordinal_numbers', models.BooleanField(default=False)),
                ('encrypt_cardinal_numbers', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nerintegrations_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'verbose_name': 'NER Integration',
                'verbose_name_plural': 'NER Integrations',
                'indexes': [models.Index(fields=['organization'], name='data_securi_organiz_85e81f_idx'), models.Index(fields=['language'], name='data_securi_languag_070792_idx'), models.Index(fields=['created_by_user'], name='data_securi_created_5f7d10_idx'), models.Index(fields=['created_at'], name='data_securi_created_bb5098_idx'), models.Index(fields=['updated_at'], name='data_securi_updated_971480_idx'), models.Index(fields=['name'], name='data_securi_name_ab2018_idx'), models.Index(fields=['organization', 'language'], name='data_securi_organiz_d553bb_idx'), models.Index(fields=['organization', 'created_by_user'], name='data_securi_organiz_c5d43b_idx'), models.Index(fields=['organization', 'created_at'], name='data_securi_organiz_b1607a_idx'), models.Index(fields=['organization', 'updated_at'], name='data_securi_organiz_4f9d61_idx'), models.Index(fields=['organization', 'name'], name='data_securi_organiz_0f0110_idx'), models.Index(fields=['organization', 'language', 'created_by_user'], name='data_securi_organiz_c29351_idx'), models.Index(fields=['organization', 'language', 'created_at'], name='data_securi_organiz_b96c5c_idx'), models.Index(fields=['organization', 'language', 'updated_at'], name='data_securi_organiz_6e0e72_idx'), models.Index(fields=['organization', 'language', 'name'], name='data_securi_organiz_509a39_idx'), models.Index(fields=['organization', 'created_by_user', 'created_at'], name='data_securi_organiz_485ee6_idx'), models.Index(fields=['organization', 'created_by_user', 'updated_at'], name='data_securi_organiz_fcd444_idx'), models.Index(fields=['organization', 'created_by_user', 'name'], name='data_securi_organiz_101b6c_idx'), models.Index(fields=['organization', 'created_at', 'updated_at'], name='data_securi_organiz_843e9d_idx'), models.Index(fields=['organization', 'created_at', 'name'], name='data_securi_organiz_f4831e_idx')],
            },
        ),
    ]
