#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Bimod.io™
#  File: 0001_initial.py
#  Last Modified: 2024-10-05 01:39:47
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 14:42:40
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@Bimod.io.
#
#
#

# Generated by Django 5.1.1 on 2024-09-25 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NERIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('language', models.CharField(choices=[('en', 'English')], default='en', max_length=2)),
                ('encrypt_persons', models.BooleanField(default=False)),
                ('encrypt_orgs', models.BooleanField(default=False)),
                ('encrypt_nationality_religion_political', models.BooleanField(default=False)),
                ('encrypt_facilities', models.BooleanField(default=False)),
                ('encrypt_countries_cities_states', models.BooleanField(default=False)),
                ('encrypt_locations', models.BooleanField(default=False)),
                ('encrypt_products', models.BooleanField(default=False)),
                ('encrypt_events', models.BooleanField(default=False)),
                ('encrypt_artworks', models.BooleanField(default=False)),
                ('encrypt_laws', models.BooleanField(default=False)),
                ('encrypt_languages', models.BooleanField(default=False)),
                ('encrypt_dates', models.BooleanField(default=False)),
                ('encrypt_times', models.BooleanField(default=False)),
                ('encrypt_percentages', models.BooleanField(default=False)),
                ('encrypt_money', models.BooleanField(default=False)),
                ('encrypt_quantities', models.BooleanField(default=False)),
                ('encrypt_ordinal_numbers', models.BooleanField(default=False)),
                ('encrypt_cardinal_numbers', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nerintegrations_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NER Integration',
                'verbose_name_plural': 'NER Integrations',
            },
        ),
    ]
