#  Copyright (c) 2024 BMD™ Autonomous Holdings. All rights reserved.
#
#  Project: Jupi.tr™
#  File: 0002_initial.py
#  Last Modified: 2024-09-25 17:51:06
#  Author: Ege Dogan Dursun (Co-Founder & Chief Executive Officer / CEO @ BMD™ Autonomous Holdings)
#  Created: 2024-10-05 01:36:38
#
#  This software is proprietary and confidential. Unauthorized copying,
#  distribution, modification, or use of this software, whether for
#  commercial, academic, or any other purpose, is strictly prohibited
#  without the prior express written permission of BMD™ Autonomous
#  Holdings.
#
#   For permission inquiries, please contact: admin@jupi.tr.
#

# Generated by Django 5.1.1 on 2024-09-25 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_security', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nerintegration',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddIndex(
            model_name='nerintegration',
            index=models.Index(fields=['organization'], name='data_securi_organiz_85e81f_idx'),
        ),
        migrations.AddIndex(
            model_name='nerintegration',
            index=models.Index(fields=['language'], name='data_securi_languag_070792_idx'),
        ),
        migrations.AddIndex(
            model_name='nerintegration',
            index=models.Index(fields=['created_by_user'], name='data_securi_created_5f7d10_idx'),
        ),
        migrations.AddIndex(
            model_name='nerintegration',
            index=models.Index(fields=['created_at'], name='data_securi_created_bb5098_idx'),
        ),
        migrations.AddIndex(
            model_name='nerintegration',
            index=models.Index(fields=['updated_at'], name='data_securi_updated_971480_idx'),
        ),
        migrations.AddIndex(
            model_name='nerintegration',
            index=models.Index(fields=['name'], name='data_securi_name_ab2018_idx'),
        ),
        migrations.AddIndex(
            model_name='nerintegration',
            index=models.Index(fields=['organization', 'language'], name='data_securi_organiz_d553bb_idx'),
        ),
        migrations.AddIndex(
            model_name='nerintegration',
            index=models.Index(fields=['organization', 'created_by_user'], name='data_securi_organiz_c5d43b_idx'),
        ),
        migrations.AddIndex(
            model_name='nerintegration',
            index=models.Index(fields=['organization', 'created_at'], name='data_securi_organiz_b1607a_idx'),
        ),
        migrations.AddIndex(
            model_name='nerintegration',
            index=models.Index(fields=['organization', 'updated_at'], name='data_securi_organiz_4f9d61_idx'),
        ),
        migrations.AddIndex(
            model_name='nerintegration',
            index=models.Index(fields=['organization', 'name'], name='data_securi_organiz_0f0110_idx'),
        ),
        migrations.AddIndex(
            model_name='nerintegration',
            index=models.Index(fields=['organization', 'language', 'created_by_user'], name='data_securi_organiz_c29351_idx'),
        ),
        migrations.AddIndex(
            model_name='nerintegration',
            index=models.Index(fields=['organization', 'language', 'created_at'], name='data_securi_organiz_b96c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='nerintegration',
            index=models.Index(fields=['organization', 'language', 'updated_at'], name='data_securi_organiz_6e0e72_idx'),
        ),
        migrations.AddIndex(
            model_name='nerintegration',
            index=models.Index(fields=['organization', 'language', 'name'], name='data_securi_organiz_509a39_idx'),
        ),
        migrations.AddIndex(
            model_name='nerintegration',
            index=models.Index(fields=['organization', 'created_by_user', 'created_at'], name='data_securi_organiz_485ee6_idx'),
        ),
        migrations.AddIndex(
            model_name='nerintegration',
            index=models.Index(fields=['organization', 'created_by_user', 'updated_at'], name='data_securi_organiz_fcd444_idx'),
        ),
        migrations.AddIndex(
            model_name='nerintegration',
            index=models.Index(fields=['organization', 'created_by_user', 'name'], name='data_securi_organiz_101b6c_idx'),
        ),
        migrations.AddIndex(
            model_name='nerintegration',
            index=models.Index(fields=['organization', 'created_at', 'updated_at'], name='data_securi_organiz_843e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='nerintegration',
            index=models.Index(fields=['organization', 'created_at', 'name'], name='data_securi_organiz_f4831e_idx'),
        ),
    ]
