# Generated by Django 5.0.8 on 2024-12-01 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_security', '0002_initial'),
        ('organization', '0005_alter_organization_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nerintegration',
            unique_together={('organization', 'name')},
        ),
    ]
