# Generated by Django 5.0.6 on 2024-06-29 23:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AddField(
            model_name='subscription',
            name='allow_audio_gen_and_analysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='allow_audio_storage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='allow_image_gen_and_analysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='allow_image_storage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='allow_long_term_memory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='allow_video_storage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='balance_discount_rate',
            field=models.FloatField(choices=[('free', 0.0), ('starter', 0.1), ('grower', 0.15), ('enterprise', 0.2)], default=0.0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_by_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_updated_by_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='updated_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_api',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_documents',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_file_systems',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_functions',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_integrations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_knowledge_bases',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_meta_integrations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_number_of_assistants',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_number_of_chats',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_number_of_llm_cores',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_number_of_users',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_orchestrations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_providers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_scheduled_jobs',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_sql_databases',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_triggers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_web_browsers',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscription',
            name='renewal_day_of_month',
            field=models.IntegerField(default=29),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'free'), ('starter', 'starter'), ('grower', 'grower'), ('enterprise', 'enterprise')], default='free', max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='card_expiration_month',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='card_expiration_year',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
