# Generated by Django 5.0.6 on 2024-06-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='balance_discount_rate',
            new_name='subscription_balance_discount_rate',
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_cost',
            field=models.FloatField(choices=[('free', 0), ('starter', 1000), ('grower', 5000), ('enterprise', 10000)], default=0.0),
        ),
    ]
