# Generated by Django 5.0.6 on 2024-06-29 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_rename_balance_discount_rate_subscription_subscription_balance_discount_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='next_renewal_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 29, 23, 33, 59, 954809, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_status',
            field=models.CharField(choices=[('free_starter', 'free_starter'), ('active', 'active'), ('missed_payment', 'missed_payment'), ('cancelled', 'cancelled'), ('on_trial', 'on_trial')], default='free_starter', max_length=100),
        ),
    ]
