# Generated by Django 5.0.6 on 2024-06-29 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subscription_next_renewal_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='name_on_card',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='next_renewal_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 29, 23, 39, 5, 594186, tzinfo=datetime.timezone.utc)),
        ),
    ]
