# Generated by Django 5.0.6 on 2024-06-29 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_subscription_name_on_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='next_renewal_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 29, 23, 53, 22, 230401, tzinfo=datetime.timezone.utc)),
        ),
    ]
