# Generated by Django 5.0.6 on 2024-06-30 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_alter_subscription_allow_image_storage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='card_cvc',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='card_expiration_month',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='card_expiration_year',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name_on_card',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='next_renewal_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 21, 11, 51, 328884, tzinfo=datetime.timezone.utc)),
        ),
    ]
