# Generated by Django 5.0.6 on 2024-07-01 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_alter_subscription_card_cvc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='card_number',
            field=models.CharField(max_length=19),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='next_renewal_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 17, 34, 9, 820717, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='renewal_day_of_month',
            field=models.IntegerField(default=1),
        ),
    ]
