# Generated by Django 5.0.6 on 2024-07-01 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_alter_subscription_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='next_renewal_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 17, 46, 13, 952758, tzinfo=datetime.timezone.utc)),
        ),
    ]
