# Generated by Django 5.0.6 on 2024-07-01 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_alter_subscription_next_renewal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='next_renewal_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 18, 28, 53, 11401, tzinfo=datetime.timezone.utc)),
        ),
    ]
