# Generated by Django 5.0.6 on 2024-07-01 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0015_alter_subscription_next_renewal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='next_renewal_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 20, 51, 28, 105860, tzinfo=datetime.timezone.utc)),
        ),
    ]
