# Generated by Django 5.0.6 on 2024-07-01 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0019_alter_subscription_next_renewal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='next_renewal_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 21, 9, 9, 715589, tzinfo=datetime.timezone.utc)),
        ),
    ]
