# Generated by Django 5.0.6 on 2024-07-01 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0022_alter_subscription_next_renewal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='next_renewal_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 23, 11, 35, 591029, tzinfo=datetime.timezone.utc)),
        ),
    ]
