# Generated by Django 5.0.6 on 2024-07-02 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0030_alter_subscription_next_renewal_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='next_renewal_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 1, 0, 6, 35, 443237, tzinfo=datetime.timezone.utc)),
        ),
    ]
