# Generated by Django 5.0.6 on 2024-07-03 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0125_alter_subscription_next_renewal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='next_renewal_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 13, 4, 4, 914879, tzinfo=datetime.timezone.utc)),
        ),
    ]
