# Generated by Django 5.0.6 on 2024-07-04 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0139_alter_subscription_next_renewal_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='next_renewal_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 3, 0, 49, 38, 746775, tzinfo=datetime.timezone.utc)),
        ),
    ]
