# Generated by Django 5.0.6 on 2024-07-04 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0147_alter_subscription_next_renewal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='next_renewal_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 3, 22, 54, 51, 339312, tzinfo=datetime.timezone.utc)),
        ),
    ]
