# Generated by Django 5.0.6 on 2024-07-05 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0152_alter_subscription_next_renewal_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='next_renewal_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 12, 22, 26, 33124, tzinfo=datetime.timezone.utc)),
        ),
    ]
