# Generated by Django 5.0.6 on 2024-07-05 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0209_alter_profile_profile_picture'),
        ('subscription', '0171_remove_subscription_allow_audio_gen_and_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='credit_card',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.usercreditcard'),
        ),
    ]
