# Generated by Django 5.0.6 on 2024-07-05 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0210_profile_subscription_alter_profile_profile_picture'),
        ('subscription', '0172_alter_subscription_credit_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.usercreditcard'),
        ),
    ]
