# Generated by Django 5.0.6 on 2024-07-05 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0211_alter_profile_profile_picture'),
        ('subscription', '0173_alter_subscription_credit_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='credit_card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.usercreditcard'),
        ),
    ]
