# Generated by Django 5.0.6 on 2024-07-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0213_remove_profile_subscription_and_more'),
        ('subscription', '0174_alter_subscription_credit_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
