name: Deploy to Development Server

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Debug SSH Agent
      run: ssh-add -l

    - name: Test SSH Connection
      run: ssh -vvv -o "StrictHostKeyChecking=no" root@185.170.198.44 "echo 'SSH connection successful'"

    - name: Deploy to Development Server
      run: |
        ssh -o "StrictHostKeyChecking=no" root@185.170.198.44 << 'EOF'
          cd /root/var/www/bimod_dev/bimod-app
          chmod +x deploy-dev.sh
          bash deploy-dev.sh main
        EOF
