# Generated by Django 5.0.8 on 2024-10-20 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_fa_icon', models.CharField(choices=[('fa fa-bell', 'fa fa-bell'), ('fa fa-bullseye', 'fa fa-bullseye'), ('fa fa-comment', 'fa fa-comment'), ('fa fa-envelope', 'fa fa-envelope'), ('fa fa-exclamation-triangle', 'fa fa-exclamation-triangle'), ('fa fa-info-circle', 'fa fa-info-circle'), ('fa fa-list', 'fa fa-list'), ('fa fa-paper-plane', 'fa fa-paper-plane'), ('fa fa-question-circle', 'fa fa-question-circle')], default='fa fa-bell', max_length=1000)),
                ('notification_title', models.CharField(max_length=1000)),
                ('notification_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Item',
                'verbose_name_plural': 'Notification Items',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user'], name='notificatio_user_id_828485_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_27a12f_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_54751d_idx')],
            },
        ),
    ]
