# Generated by Django 5.0.8 on 2024-10-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationitem',
            name='notification_title',
        ),
        migrations.AddField(
            model_name='notificationitem',
            name='notification_title_category',
            field=models.CharField(choices=[('bimod-team', 'Bimod Team'), ('internal', 'Internal'), ('info', 'Information'), ('alert', 'Alert'), ('warning', 'Warning'), ('error', 'System Error')], default='info', max_length=1000),
        ),
    ]
