# Generated by Django 5.0.8 on 2024-10-20 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notificationitem_notification_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notificationitem',
            name='notificatio_user_id_27a12f_idx',
        ),
        migrations.RemoveField(
            model_name='notificationitem',
            name='is_read',
        ),
        migrations.AddField(
            model_name='notificationitem',
            name='readers',
            field=models.ManyToManyField(blank=True, related_name='read_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationitem',
            name='notification_fa_icon',
            field=models.CharField(choices=[('fa fa-bell', 'fa fa-bell'), ('fa fa-bullseye', 'fa fa-bullseye'), ('fa fa-comment', 'fa fa-comment'), ('fa fa-envelope', 'fa fa-envelope'), ('fa fa-exclamation-triangle', 'fa fa-exclamation-triangle'), ('fa fa-info-circle', 'fa fa-info-circle'), ('fa fa-list', 'fa fa-list'), ('fa fa-paper-plane', 'fa fa-paper-plane'), ('fa fa-question-circle', 'fa fa-question-circle'), ('fa fa-building', 'fa fa-building')], default='fa fa-bell', max_length=1000),
        ),
        migrations.AlterField(
            model_name='notificationitem',
            name='notification_title_category',
            field=models.CharField(choices=[('bimod-team', 'Bimod Team'), ('internal', 'Internal Notification'), ('info', 'Information'), ('alert', 'Alert'), ('warning', 'Warning'), ('error', 'System Error')], default='info', max_length=1000),
        ),
    ]
