# Generated by Django 5.0.8 on 2024-10-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationitem_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationitem',
            name='bimod_admin_notification',
            field=models.BooleanField(default=False),
        ),
    ]
