# Generated by Django 5.0.8 on 2024-10-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notificationitem_bimod_admin_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationitem',
            name='notification_fa_icon_color',
            field=models.CharField(blank=True, default='btn-primary', max_length=1000),
        ),
    ]
