# Generated by Django 5.0.8 on 2024-10-20 23:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notificationitem_notification_fa_icon_color'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notificationitem',
            name='notificatio_user_id_828485_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationitem',
            name='notificatio_user_id_54751d_idx',
        ),
        migrations.RenameField(
            model_name='notificationitem',
            old_name='user',
            new_name='created_by_user',
        ),
        migrations.AddIndex(
            model_name='notificationitem',
            index=models.Index(fields=['created_by_user'], name='notificatio_created_000e21_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationitem',
            index=models.Index(fields=['created_by_user', 'created_at'], name='notificatio_created_7c4817_idx'),
        ),
    ]
