# Generated by Django 5.0.8 on 2024-10-20 23:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_remove_notificationitem_notificatio_user_id_828485_idx_and_more'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notificationitem',
            name='notificatio_created_000e21_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationitem',
            name='notificatio_created_7c4817_idx',
        ),
        migrations.RemoveField(
            model_name='notificationitem',
            name='created_by_user',
        ),
        migrations.AddIndex(
            model_name='notificationitem',
            index=models.Index(fields=['created_at'], name='notificatio_created_a0505f_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationitem',
            index=models.Index(fields=['notification_title_category', 'created_at'], name='notificatio_notific_b98d7e_idx'),
        ),
    ]
