# Generated by Django 5.0.8 on 2024-10-21 00:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_remove_notificationitem_notificatio_created_000e21_idx_and_more'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationitem',
            name='bimod_admin_notification',
        ),
        migrations.AddField(
            model_name='notificationitem',
            name='notification_sender_type',
            field=models.CharField(choices=[('bimod-team', 'Bimod Team'), ('system', 'System')], default='bimod-team', max_length=1000),
        ),
        migrations.AlterField(
            model_name='notificationitem',
            name='notification_title_category',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('info', 'Information'), ('warning', 'Warning'), ('error', 'System Error'), ('alert', 'Alert')], default='info', max_length=1000),
        ),
        migrations.AddIndex(
            model_name='notificationitem',
            index=models.Index(fields=['organization', 'created_at'], name='notificatio_organiz_eb8cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationitem',
            index=models.Index(fields=['notification_sender_type', 'created_at'], name='notificatio_notific_ed128d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationitem',
            index=models.Index(fields=['notification_fa_icon', 'created_at'], name='notificatio_notific_666cd2_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationitem',
            index=models.Index(fields=['notification_fa_icon_color', 'created_at'], name='notificatio_notific_bad5d1_idx'),
        ),
    ]
