# Generated by Django 5.0.8 on 2024-10-21 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_remove_notificationitem_bimod_admin_notification_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notificationitem',
            name='notificatio_notific_bad5d1_idx',
        ),
        migrations.RemoveField(
            model_name='notificationitem',
            name='notification_fa_icon_color',
        ),
    ]
