# Generated by Django 5.0.8 on 2024-11-03 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_remove_notificationitem_notificatio_notific_bad5d1_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationitem',
            name='notification_sender_type',
            field=models.CharField(choices=[('bimod-team', 'Bimod Team'), ('welcome', 'Welcome'), ('system', 'System')], default='bimod-team', max_length=1000),
        ),
    ]
