# Generated by Django 5.0.8 on 2024-10-11 08:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=6)),
                ('model_name', models.CharField(max_length=10000)),
                ('object_id', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['object_id'], name='audit_logs__object__9d0929_idx'), models.Index(fields=['model_name'], name='audit_logs__model_n_65fc30_idx'), models.Index(fields=['timestamp'], name='audit_logs__timesta_aec53a_idx'), models.Index(fields=['user'], name='audit_logs__user_id_a5e0ec_idx'), models.Index(fields=['action'], name='audit_logs__action_235999_idx'), models.Index(fields=['model_name', 'object_id'], name='audit_logs__model_n_e500d9_idx'), models.Index(fields=['model_name', 'object_id', 'action'], name='audit_logs__model_n_329263_idx'), models.Index(fields=['model_name', 'object_id', 'timestamp'], name='audit_logs__model_n_406363_idx'), models.Index(fields=['model_name', 'object_id', 'user'], name='audit_logs__model_n_4da1ec_idx'), models.Index(fields=['model_name', 'object_id', 'action', 'timestamp'], name='audit_logs__model_n_6dcfe2_idx'), models.Index(fields=['model_name', 'object_id', 'action', 'user'], name='audit_logs__model_n_44fb86_idx'), models.Index(fields=['model_name', 'object_id', 'action', 'timestamp', 'user'], name='audit_logs__model_n_962ff6_idx')],
            },
        ),
    ]
