# Generated by Django 5.0.8 on 2024-11-02 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0006_alter_assistant_project_items'),
        ('organization', '0003_alter_organization_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('meta_context_instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'verbose_name': 'Slider Folder',
                'verbose_name_plural': 'Slider Folders',
            },
        ),
        migrations.CreateModel(
            name='SliderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=4000)),
                ('document_content_json_quill', models.TextField(blank=True, null=True)),
                ('context_instructions', models.TextField(blank=True, null=True)),
                ('target_audience', models.TextField(blank=True, null=True)),
                ('tone', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copilot_assistant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_document_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_document_last_updated_by_user', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('document_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slider.sliderfolder')),
            ],
            options={
                'verbose_name': 'Slider Document',
                'verbose_name_plural': 'Slider Documents',
            },
        ),
        migrations.CreateModel(
            name='SliderGoogleAppsConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_api_key', models.CharField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('slider_assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
            ],
            options={
                'verbose_name': 'Slider Google Apps Connection',
                'verbose_name_plural': 'Slider Google Apps Connections',
            },
        ),
        migrations.AddIndex(
            model_name='sliderfolder',
            index=models.Index(fields=['organization'], name='slider_slid_organiz_e0b042_idx'),
        ),
        migrations.AddIndex(
            model_name='sliderfolder',
            index=models.Index(fields=['organization', 'name'], name='slider_slid_organiz_563cda_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sliderfolder',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='sliderdocument',
            index=models.Index(fields=['organization'], name='slider_slid_organiz_1f8c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='sliderdocument',
            index=models.Index(fields=['organization', 'document_folder'], name='slider_slid_organiz_687b38_idx'),
        ),
        migrations.AddIndex(
            model_name='sliderdocument',
            index=models.Index(fields=['organization', 'copilot_assistant'], name='slider_slid_organiz_486fd5_idx'),
        ),
        migrations.AddIndex(
            model_name='sliderdocument',
            index=models.Index(fields=['organization', 'copilot_assistant', 'document_folder'], name='slider_slid_organiz_bc8fcd_idx'),
        ),
        migrations.AddIndex(
            model_name='sliderdocument',
            index=models.Index(fields=['organization', 'document_folder', 'document_title'], name='slider_slid_organiz_0dd83e_idx'),
        ),
        migrations.AddIndex(
            model_name='sliderdocument',
            index=models.Index(fields=['organization', 'copilot_assistant', 'document_folder', 'document_title'], name='slider_slid_organiz_bfc172_idx'),
        ),
        migrations.AddIndex(
            model_name='slidergoogleappsconnection',
            index=models.Index(fields=['slider_assistant'], name='slider_slid_slider__f5eb4c_idx'),
        ),
        migrations.AddIndex(
            model_name='slidergoogleappsconnection',
            index=models.Index(fields=['owner_user'], name='slider_slid_owner_u_ae9b26_idx'),
        ),
        migrations.AddIndex(
            model_name='slidergoogleappsconnection',
            index=models.Index(fields=['slider_assistant', 'owner_user'], name='slider_slid_slider__b8efa7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='slidergoogleappsconnection',
            unique_together={('slider_assistant', 'owner_user')},
        ),
    ]
