# Generated by Django 5.0.8 on 2024-12-10 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_alter_sliderdocument_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sliderfolder',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sliderfolder',
            name='created_by_user',
        ),
        migrations.RemoveField(
            model_name='sliderfolder',
            name='organization',
        ),
        migrations.DeleteModel(
            name='SliderDocument',
        ),
        migrations.DeleteModel(
            name='SliderFolder',
        ),
    ]
